### PR TITLE
[R] replace uses of T and F with TRUE and FALSE

### PR DESCRIPTION
**Pull request by jameslamb**
This pull request proposes replacing uses of  `T` and `F` in R code with `TRUE`  and  `FALSE`. `T` and  `F` are dangerous because they are only aliases and can be overwritten.

```r
TRUE <- 4
# Error in TRUE <- 4 : invalid (do_set) left-hand side to assignment

T <- 4
T
# [1] 4
```

Thanks for your time and consideration!

### CODE REVIEW

**Comment by hcho3** [comment]
Is `T` a synonym (alias) of `TRUE` in R?

**Comment by jameslamb** [comment]
> Is `T` a synonym (alias) of `TRUE` in R?

It is! But the difference (like in that code sample) is that `T` can be overridden and  `TRUE` cannot. So all this code changed in this this PR looks like it is working, but it could behave in an unexpected way in the future if someone adds a patch that creates any variable named `T`.

**Comment by jameslamb** [comment]
We use `{lintr}` in `LightGBM` to catch such issues (and many others): https://github.com/microsoft/LightGBM/blob/d42f43132df63ae64783d3bc4f6366dd325116af/.ci/lint_r_code.R#L53

I'd be happy to propose a pull request that adds similar linting in `xgboost` CI if it interests you.

Alternatively, you or other maintainers could run it manually to look for things, like this from the root of the repo:

```shell
Rscript lint_r_code.R $(pwd)
```

**Comment by hcho3** [comment]
@jameslamb Thanks for your explanation. Here is the current list of R linters we use: https://github.com/dmlc/xgboost/blob/master/R-package/tests/testthat/test_lint.R. You should add `T_and_F_symbol_linter` in that list.

**Comment by hcho3** [comment]
Hmm looks like R lint hasn't been enabled:
https://github.com/dmlc/xgboost/blob/1d22a9be1cdeb53dfa9322c92541bc50e82f3c43/R-package/tests/testthat/test_lint.R#L26

Let's try enabling it and see what happens.

**Comment by jameslamb** [comment]
> Hmm looks like R lint hasn't been enabled:
> https://github.com/dmlc/xgboost/blob/1d22a9be1cdeb53dfa9322c92541bc50e82f3c43/R-package/tests/testthat/test_lint.R#L26
> 
> Let's try enabling it and see what happens.

Sure, I just pushed https://github.com/dmlc/xgboost/pull/5778/commits/600185a0b071da53ff9a03c9659d02a80f5e2000 which uncomments it and adds the `T_and_F_symbol_linter`. Could you point me to which CI build it should be running in?


It looks like that `test_lint.R` was added in 2015. A lot of new linters have been added since then, which might be worth considering. Some of those are not just style things but can find actual code-correctness issues such as the one in this PR. Maybe we should move this discussion off this narrowly-scoped PR and into an issue?

**Comment by terrytangyuan** [comment]
@jameslamb Thanks James! We should definitely revamp the code style and hopefully uncomment most of those linters.

**Comment by hcho3** [comment]
It seems like all lint checks are passing: https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-5778/2/pipeline/221#step-246-log-364.

I agree that we should create a new issue to add more lint checks for R in the future.

**Comment by jameslamb** [comment]
> It seems like all lint checks are passing: https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-5778/2/pipeline/221#step-246-log-364, where all testthat tests are run.
> 
> I agree that we should create a new issue to add more lint checks for R in the future.

@hcho3 that log isn't evidence that they're passing, since the linting code has `skip`s and I'm not sure if any of them are being triggered.

https://github.com/dmlc/xgboost/blob/1d22a9be1cdeb53dfa9322c92541bc50e82f3c43/R-package/tests/testthat/test_lint.R#L3-L5

**Comment by jameslamb** [comment]
> I agree that we should create a new issue to add more lint checks for R in the future.

opened #5779

**Comment by hcho3** [comment]
I removed the skip statements except `skip_on_cran()`. Let's see if lint check passes.

**Pull request merged**
