### PR TITLE
More thorough unit testing for R package

### PR DESCRIPTION
**Pull request by terrytangyuan**
Let's see if this passes Travis...

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Okay. This passed checks. @hetong007 Could you merge? Thanks.

**Comment by hetong007** [comment]
Thank you, they look good. Can you please also add your name to the list of contributors?

**Comment by terrytangyuan** [comment]
@hetong007  Thanks. Done.

**Comment by hetong007** [comment]
Merged.

**Pull request merged**
