### PR TITLE
[dask] Accept other inputs for prediction.

### PR DESCRIPTION
**Pull request by trivialfis**
* Returns a series when input is dataframe.

Related: https://github.com/dmlc/xgboost/issues/5425

### CODE REVIEW

**Comment by rnyak** [comment]
@RAMitchell I see that that these changes were merged. I have a follow up question related: [#5425](https://github.com/dmlc/xgboost/issues/5425) issue that I created.

I installed the latest nightly build, and ran:
```
pip install xgboost-1.1.0_SNAPSHOT+6601a641d756a2769fcd85e25817506490c40861-py2.py3-none-manylinux1_x86_64.whl 
```
This code still returns `prediction = xgb.dask.predict(client, output, dtrain)` the `prediction` as  `dask.array.core.Array` not as  `dask_cudf.Series`.

**Comment by trivialfis** [comment]
It outputs a series when input to predict is a dataframe.

**Comment by trivialfis** [comment]
Right now it's a dask series.  dask cudf doesn't support dropping dimension with map partition, will check back at 0.13

**Comment by rnyak** [comment]
@trivialfis  Thanks. yes, I can get a `dask.dataframe.core.Series` from `xgb.dask.predict(client, output, X_test)`. From here, I'd like to calculate RMSE, but cannot do it with two `dask.dataframe.core.Series`.  

example code:
```
prediction = xgb.dask.predict(client, output, X_test)
true= Y_test['true_output']
type(true), type(prediction)
(dask.dataframe.core.Series, dask.dataframe.core.Series)

#calculate squared error
squared_error=(prediction -true)**2
squared_error.compute()
0   NaN
1   NaN
5   NaN
6   NaN
```

If I convert `dask.dataframe.core.Series` to  `dask.array.core.Array` then, I can calculate the squared error.  Is that the recommended way?

**Comment by trivialfis** [comment]
That's weird, let me take a look.

**Pull request merged**
