### PR TITLE
[jvm-packages] remove default parameters

### PR DESCRIPTION
**Pull request by wbo4958**
This PR is to remove the most booster default parameters, which will be defaulted by xgboost native.

### CODE REVIEW

**Comment by wbo4958** [comment]
@trivialfis could you help to check the python test CI?

**Comment by trivialfis** [comment]
Please ignore it for now. The hypothesis package is updated and caught the error where xgboost failed to parse some parameters in double precision.

**Review by trivialfis — COMMENTED** [review]
Could you please set this parameter to true https://github.com/dmlc/xgboost/blob/755d9d460924ab0afdf287d6ff3a01ae701a657a/include/xgboost/generic_parameters.h#L39 and check if there's any warning during training? If not then you can pass it from the scala package to enable the validation.

**Comment by wbo4958** [comment]
> Could you please set this parameter to true
> 
> https://github.com/dmlc/xgboost/blob/755d9d460924ab0afdf287d6ff3a01ae701a657a/include/xgboost/generic_parameters.h#L39
> 
> and check if there's any warning during training? If there is no warning then you can pass it from the scala package to enable the validation.

Yeah, there are some WARNINGs,

``` console
Parameters: { "allow_non_zero_for_missing", "dmlc_worker_connect_retry", "features_col", "handle_invalid", "label_col", "missing", "num_early_stopping_rounds", "num_round", "num_workers", "prediction_col", "probability_col", "rabit_ring_reduce_threshold", "rabit_timeout", "raw_prediction_col", "silent", "tracker_conf", "train_test_ratio", "tree_limit", "use_external_memory" } might not be used.
```

Most parameters unused are coming from the JVM parameter default values, and we should delete these parameters before passing into native. I also have filed an item (AKA an followup) to unify these parameters.

**Comment by trivialfis** [comment]
Hmm, rabit timeout is useful.

**Review by trivialfis — APPROVED** [review]

**Comment by trivialfis** [comment]
> Hmm, rabit timeout is useful.

I take it back. It's not useful for XGBoost training, this should be removed after rabit initialization.

**Comment by trivialfis** [comment]
@wbo4958 Could you please rebase the branch to master?

**Pull request merged**
