### PR TITLE
[jvm-packages] Open public methods for load/save spark models with plain input/output streams

### PR DESCRIPTION
**Pull request by nikolay-karpow**
It's useful to be able to store/load a model not only as a hadoop file. Also, if we allow to load a model without SparkContext, we a free to use such a model for local predictions without connecting to a spark cluster at all.

### CODE REVIEW

**Comment by CodingCat** [comment]
I may miss something here, what's the motivation of this PR?

1. if you can save and load in local file system, and predict with spark.XGBoostModel, you still need to connect with spark, as you XGBoostModel.transform is calling Spark's DF related stuffs

2. if you can save and load in local file system and predict with spark.XGBoostModel.booster, this PR has no difference with spark.XGBoostModel.booster.saveModel and scala.XGBoostModel.load()

**Comment by nikolay-karpow** [comment]
I want to do the following:

1. Train a model on spark. 
Here I use `ml.dmlc.xgboost4j.scala.spark.XGBoost.trainWithRDD` which gives me an instance of `ml.dmlc.xgboost4j.scala.spark.XGBoostModel `

2. Use this model for predict on spark.
I use ml.dmlc.xgboost4j.scala.spark.XGBoostModel.predict

3. Save the model on disk.

4. Load the saved model by a different instance of the same application and do local predicts on it, without connecting to spark. For local predicts I use `ml.dmlc.xgboost4j.scala.spark.XGBoostModel.booster().predict`

It looks to me, there is no way to do it unless I use Java serialization in order to save/load XGBoostModel. As it's risky from the backward compatibility perspective, I suggest to add a possibility to use plain streams for save/load `ml.dmlc.xgboost4j.scala.spark.XGBoostModel`. 

Do I miss something? Is there a simple way to achieve that without xgboost code changes?

**Comment by CodingCat** [comment]
> Load the saved model by a different instance of the same application and do local predicts on it, without connecting to spark. For local predicts I use ml.dmlc.xgboost4j.scala.spark.XGBoostModel.booster().predict

It seems that you are not going to connect with not only Spark but also distributed file system. To avoid involving Spark, you can do what you're doing now, booster().predict; to avoid distributed file system, why `saveAsHadoopFile(file:///localpath)` is not working?

> It looks to me, there is no way to do it unless I use Java serialization in order to save/load XGBoostModel. As it's risky from the backward compatibility perspective, I suggest to add a possibility to use plain streams for save/load ml.dmlc.xgboost4j.scala.spark.XGBoostModel.

why Java serialization has problems of backward compatibility while this API does not have it?

**Comment by nikolay-karpow** [comment]
> It seems that you are not going to connect with not only Spark but also distributed file system. To avoid involving Spark, you can do what you're doing now, booster().predict; to avoid distributed file system, why saveAsHadoopFile("file:///localpath") is not working?

I have to pass SparkContext into loadModelFromHadoopFile, that's why... If I create SparkContext instance, I connect to the cluster. 

> why Java serialization has problems of backward compatibility while this API does not have it?
Because with Java Serialization in case of XGBoostModel class changes I might not be able to load a model, saved with older version of XGBoost. I assume, API is kinda more stable.

**Comment by CodingCat** [comment]
> I have to pass SparkContext into loadModelFromHadoopFile, that's why... If I create SparkContext instance, I connect to the cluster.

so, my question is, in Spark's package, why we have to create a API for non-spark usage? 

> Because with Java Serialization in case of XGBoostModel class changes I might not be able to load a model, saved with older version of XGBoost. I assume, API is kinda more stable.

I am kind of confused...I thought by Java Serialization, you refer to single-machine version XGBoost's serialization

Looks like you refer to the real Java Ser/DeSer system? if so, my question here is, why save/load methods in the Booster of scala package (i.e. single-machine version) does not work for you

**Comment by nikolay-karpow** [comment]
> so, my question is, in Spark's package, why we have to create a API for non-spark usage?

Well... If we are talking about API, then why a model can be saved to FS only?) Why cannot I save it into a database, into whatever else? These methods don't need spark at all, they just take hadoop config from SparkContext, so InputStream/OutputStream is more universal...

> Looks like you refer to the real Java Ser/DeSer system? if so, my question here is, why save/load methods in the Booster of scala package (i.e. single-machine version) does not work for you

Yes, I do refer to the real Java serialization. I'm not sure, I understand you about single-machine version... You mean, to train a model on spark, then take a booster from it and save only booster?

**Comment by CodingCat** [comment]
> Well... If we are talking about API, then why a model can be saved to FS only?)

yes, you can, but as the design of a `spark` package, we do not want to leak the API to other usages, everything should be around a `spark application`

> You mean, to train a model on spark, then take a booster from it and save only the booster?

because you eventually only want to call model.booster.predict, which does not utilize any additional information provided by xgboost4j-spark (i.e. all additional information saved by spark package is useless), save that is enough for you (see https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j/src/main/java/ml/dmlc/xgboost4j/java/Booster.java#L323)

**Comment by nikolay-karpow** [comment]
@CodingCat Well... Yes, it looks like it should work for me, even though it's rather inconvenient and I still think, better have more general approach in the API... Thanks for explanation.

**Comment by CodingCat** [comment]
@fathersson I have explained clearly, we do support prediction without SparkContext, through<b> XGBoost Java/Scala package</b> NOT <b>XGBoost Spark package</b>

with spark package, everything should be around spark 

if you want to turn around to pure XGBoost save/load without spark, the only thing you need to do is

```scala
xgboostModel.booster.save
```

the only "overhead" here is `.booster`

since we have a java/scala package <b> AS THE BASE OF SPARK PACKAGE</b>, we should not blur their boundary

**Comment by fathersson** [comment]
@CodingCat thank you, it's very useful. 
We will reconsider our approach.

**Pull request closed without merging**
