### PR TITLE
[WIP] Use model slicing for copy.

### PR DESCRIPTION
**Pull request by trivialfis**
Related: https://github.com/dmlc/xgboost/issues/7138 https://github.com/dmlc/xgboost/issues/6697

Avoid serializing into JSON during copy.  By default, XGBoost makes a copy after training for releasing memory.  This PR optimizes the copy function to use model slicing instead of serialization.  This helps when creating many large models using scikit-learn grid search.

### CODE REVIEW

**Comment by trivialfis** [comment]
@ShvetsKS I have removed the JSON serialization during training for tree model in this PR, can we close https://github.com/dmlc/xgboost/issues/6697 if we were able to merge it?

**Comment by ShvetsKS** [comment]
@trivialfis seems degradation was fixed!
master: 14.8s vs use-slice-for-copy: 13.1s
I think we can close  #6697, thanks a lot!

**Comment by trivialfis** [comment]
Great news.  I need to split up this PR and implement an actual copy function so the code can look a bit nicer.  Will follow up on Monday.

**Comment by trivialfis** [comment]
Some fixes are here: https://github.com/dmlc/xgboost/pull/7149 will start working on the copy function.

**Comment by trivialfis** [comment]
Closed by https://github.com/dmlc/xgboost/pull/7545 .

**Pull request closed without merging**
