### PR TITLE
training continuation

### PR DESCRIPTION
**Pull request by Far0n**
Yields training continuation of stored xgb-model file or python 'Booster' instance returned by *xgb.train()*

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@Far0n Conflicts with the recent merge of your other PR. Could you rebase when that build is finished?

**Comment by Far0n** [comment]
yes, I'll do so

**Comment by terrytangyuan** [comment]
@Far0n Thanks. Also, could you add unit test for this? They are in the tests folder in root directory.

**Comment by Far0n** [comment]
@terrytangyuan Sure. Are there any special demands for xgb's unit tests?

**Comment by terrytangyuan** [comment]
Thanks. Just make sure the new code is covered within the shortest time as possible.

**Comment by Far0n** [comment]
- bugfix added to set correct "best_iteration" after training continuation
- "best_iteration" is now set to ntree-1 if early stopping is not used to avoid "No such attribute Excpetion" when using bst.best_iteration for ntree_limit in xgb.predict()

**Comment by Far0n** [comment]
redo this one 2 ?

**Comment by terrytangyuan** [comment]
It's up to you. Make sure have clearer commit messages.

**Comment by Far0n** [comment]
kk, let me clean up all of my PR's

**Pull request closed without merging**
