### PR TITLE
Fix prediction from loaded pickle.

### PR DESCRIPTION
**Pull request by trivialfis**
Fix https://github.com/dmlc/xgboost/issues/4513 .

@pseudotensor @sh1ng

### CODE REVIEW

**Comment by trivialfis** [comment]
The test is adopted from https://github.com/h2oai/h2o4gpu/blob/master/tests/python/open_data/gbm/test_gpu_prediction_pickledmodel.py#L189-L222

**Comment by trivialfis** [comment]
@hcho3 I ended up removing the const from predict method.  One way to keep the const is to make train_param a pointer even in Learner, but that might not be really useful.

**Comment by pseudotensor** [comment]
Thanks @trivialfis !

**Comment by pseudotensor** [comment]
FYI, the idea is we typically build a model on the GPU, then for scoring the system could be arbitrarily different, with more or less GPUs or even none.  And, even if have GPUs when scoring, we still want to be able to choose to use only CPU.

**Comment by trivialfis** [comment]
@pseudotensor See last part of tests/python-gpu/test_pickling.py in this PR.  I tested switching to cpu.

**Comment by pseudotensor** [comment]
Yes, I saw thanks.  I was just explaining the diversity of what we would like to do in case context helps.

**Comment by trivialfis** [comment]
Aha, got it.

**Comment by pseudotensor** [comment]
merge?

**Pull request merged**
