### PR TITLE
[jvm-packages] Add BigDenseMatrix

### PR DESCRIPTION
**Pull request by honzasterba**
* ability to create DMatrix with bigger than Integer.MAX_VALUE size arrays
* uses sun.misc.Unsafe

original author @michalkurka

### CODE REVIEW

**Comment by CodingCat** [comment]
thanks! I will review it shortly, really busy in a lot of stuffs recently

**Comment by honzasterba** [comment]
@CodingCat thanks for taking the time, please let me know if this is generally acceptable and I will then work on fixing the CI errors

**Comment by honzasterba** [comment]
hi @CodingCat, I have found some time and rebased this on top of master, please take a look

**Comment by hcho3** [comment]
@CodingCat @trams Are you guys okay with the use of `sun.misc.Unsafe`, presumably to speed up serialization?

**Comment by sperlingxx** [comment]
LGTM

**Pull request merged**
