### PR TITLE
Support FreeBSD

### PR DESCRIPTION
**Pull request by hcho3**
* `exp10` is a GNU extension and is missing on FreeBSD. Add `__FreeBSD__` guard to disable use of `exp10`. In the long run, we may want to add a feature testing for `exp10` to the build system.
* `std::chrono::duration_cast<...>.count()` implementation returns `long long` type, which `JsonInteger` does not accept. Explicitly cast the result into `int64_t`.

Depends on https://github.com/dmlc/rabit/pull/133.

Closes https://github.com/dmlc/xgboost/issues/5117.

### CODE REVIEW

**Comment by trivialfis** [comment]
>  In the long run, we may want to add a feature testing for exp10 to the build system.

I have an implementation using lookup table.  Will start splitting up the optimized JSON PR after this release.

**Comment by hcho3** [comment]
> I have an implementation using lookup table. Will start splitting up the optimized JSON PR after this release.

Awesome!

**Comment by hcho3** [comment]
For now, I'm leaving out the rabit update from this PR. I will file a separate PR for updating rabit.

**Comment by trivialfis** [comment]
There are a handful of BSDs out there, we may want to use `__linux__` instead.

**Pull request merged**
