### PR TITLE
[CI] Upgrade cuDF and RMM to 0.19 nightly

### PR DESCRIPTION
**Pull request by hcho3**
Might help fix https://github.com/rapidsai/cudf/issues/7722

### CODE REVIEW

**Comment by hcho3** [comment]
@trivialfis I'm reverting #6818 to check whether the crash still occurs with the latest cuDF.

**Comment by trivialfis** [comment]
Hmm .. a new error trace.

**Comment by trivialfis** [comment]
Did it just fix itself?  -, -?

**Comment by trivialfis** [comment]
Don't merge, I need to revert the commit and try again.

**Comment by hcho3** [comment]
We ran out of CI budget. Please try again in an hour.

**Comment by trivialfis** [comment]
@hcho3 I think it somehow has fixed itself, even without upgrading: https://github.com/dmlc/xgboost/pull/6858 .  It's not determined yet since I didn't run memcheck on that PR.  But for this one, the error seems to be gone.

**Comment by pseudotensor** [comment]
I recommend hunting it down, unlikely magically goes away :)

**Comment by trivialfis** [comment]
Yeah ..  the difficulty is it's not reproducible on CI.  It's very unlikely that we can debug in on Jenkins.

**Comment by trivialfis** [comment]
@hcho3 @pseudotensor The issue is addressed.

**Pull request closed without merging**
