### PR TITLE
Fix race condition in interaction constraint.

### PR DESCRIPTION
**Pull request by trivialfis**
* Split up the kernel to sync write.

* QueryNode is no-longer used in Query, but kept for testing.

### CODE REVIEW

**Comment by trivialfis** [comment]
@rongou, @sriramch Please help testing, I can't reproduce the error on my machine.

**Comment by sriramch** [comment]
@trivialfis looks good. i haven't done extended testing - just made sure that unit tests pass, as i'm blocked on #4554

**Comment by rongou** [comment]
@trivialfis tests passed for me as well.

**Comment by trivialfis** [comment]
@sriramch @rongou Great! Thanks for the help.  Feel free to reach me for any further issues.

**Pull request merged**
