### PR TITLE
Fixing parsing of model dump text file in R

### PR DESCRIPTION
**Pull request by chrissly31415**
Fixed parsing of negative reals, integers and scientific notation which
can occur in the model dump.

### CODE REVIEW

**Comment by tqchen** [comment]
@pommedeterresautee  can you make a review on this?

**Comment by pommedeterresautee** [comment]
@tqchen Yeah I planed it for tomorrow (can t before)

**Comment by pommedeterresautee** [comment]
Works for me

**Comment by tqchen** [comment]
thanks! this is now merged

**Pull request merged**
