### PR TITLE
Add PredictLeaf in learner to get predicted leaf indices and scores.

### PR DESCRIPTION
**Pull request by byzhang**

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks for contributing, is there any reason that you want to get the leaf score besides the indices?

**Comment by byzhang** [comment]
Tianqi, I want to compare the weights learned by boosting vs by logistic regression or other additive models.

**Comment by tqchen** [comment]
You can probably do it with the model_dump, which is available in python and cli as well.

**Comment by byzhang** [comment]
xgboost dump does have the leaf scores, but it's less efficient to parse the information from the dumped models. And it might be silently broken by a dump format change.

**Comment by tqchen** [comment]
The information is indeed used by the feature importance and other places. So it is likely to be consistent.  

If what was wanted was the model information, maybe consider a more robust serialization format, e.g. support dump into json, which might take a bit more effort but could also benefit others who want to read the model. Would you like to take a stab?

Thanks!

**Comment by byzhang** [comment]
It sounds interesting. Can you open an issue for it? We can summarize what
kind of information need to be serialize first. Then I may be able to
squeeze some time later this week for it. (But 'm open for another quick
gun on it) :)

Thanks,
-B

**Comment by tqchen** [comment]
Please open an issue here https://github.com/dmlc/xgboost/issues :) I will close this PR for now.

Thanks!

**Pull request closed without merging**
