### PR TITLE
improve OS X build instruction

### PR DESCRIPTION
**Pull request by fyears**

### CODE REVIEW

**Comment by fyears** [comment]
hold on ... some unexpected error...

**Comment by fyears** [comment]
Yeah, it should work. I am now reopening it.

**Comment by tqchen** [comment]
one question, is clang-omp available by default? It would be great people still get non omp version compiled when it is not available

**Comment by fyears** [comment]
Answer: No. clang-omp is provided by third party.

To clearfy, the shipped clang in os x does not support openmp. But you should be able to get no-openmp xgboost using default clang.

And if you want to use openmp, you HAVE TO use third-party clang  / self-compiled clang / third-party gcc / self-compiled gcc, as well as the openmp runtime library. And I think it is most convenient to use homebrew, a package manager on os x, to download clang-omp and libiomp.

**Comment by fyears** [comment]
One more thing: no gcc is provided in os x by default. gcc and g++ are set to be aliases as clang and clang++ by default

So... if you think it better to "keep everything default" (so no openmp on os x), you can just ignore my makefile chang suggestion.

**Comment by tqchen** [comment]
I mean, it is great to have instruction on openmp, the only thing we want to make sure is that when no_omp=1 was set, everything compiled in default way by using https://github.com/dmlc/xgboost/blob/master/build.sh

**Comment by fyears** [comment]
Then, you could remove my changes in Makefile.

**Comment by tqchen** [comment]
@fyears I think the instructions is good and it should be merged in. Can you update the PR to remove the changes in makefile? Thanks

**Pull request closed without merging**
