### PR TITLE
Scikit-Learn Wrapper For XGBoost

### PR DESCRIPTION
**Pull request by nerdcha**
Thanks for your feedback, Tianqi. A clean fork fixed the readme issue, and the code is now catching import errors if the user doesn't have sklearn installed.

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks! It is now merged into master

**Comment by nerdcha** [comment]
Erm, did you mean to close without merging?

**Comment by tqchen** [comment]
My bad, it is not merged

**Comment by adamwlev** [comment]
Hi @nerdcha,
if I do
```
clf = XGBClassifier()
clf.fit(X,y)
clf.fit(X_2,y_2)
```
is that second `.fit` call supposed to refit the boosted from scratch or start with the existing booster and fit more estimators?

Thanks!
Adam

**Pull request merged**
