### PR TITLE
[CI] Migrate CI pipelines from Jenkins to BuildKite

### PR DESCRIPTION
**Pull request by hcho3**
I have been personally maintaining our Jenkins CI server (https://xgboost-ci.net/) since April 2018. While the CI pipeline has been a great asset to the XGBoost project, it suffered from a few glaring problems:

* Security issues necessitate frequent system updates, and some plug-ins would unexpectedly fail. The plug-in oriented architecture of Jenkins makes it brittle
* The Jenkins server involves lots of manual configuration via its GUI
* Many cloud components (EC2 machine images, Lambdas, Jenkins server software) were manually set up by me; no reproducible provision; no ability to debug the setup process
* Most importantly, **I am the only person who knows how to manage the server. It's hard to delegate**, since most portion of the Jenkins setup was done manually by me.

To address the issues, I am migrating our CI pipeline to BuildKite. [BuildKite](https://buildkite.com/) is a SaaS (Software as a Service) that orchestrates cloud machines to host CI pipelines. Benefits include:

* Minimal pricing overhead over what we already spend on AWS. They only charge $9/month per each admin user we add on BuildKite control panel. The funding will still come from our Open Collective account.
* Reduced maintenance burden as we no longer have to run a server 24/7
* Infrastructure as Code. Using CloudFormation, we automate the provision of various cloud resources. No more manual configuration or setup.
As a result, someone else who decides to take over the management of the CI pipeline will have easier time understanding the system.
* YAML configuration file to define the pipeline; those who are familiar with GH Action will feel right at home.
* Many open-source projects use it: LLVM, CUDA.jl, Horovod.

### CODE REVIEW

**Review by trivialfis — COMMENTED** [review]
Thank you for the great work on the CI!  Now that we are trying to move toward a more automated system, could you please add some documents to give a brief introduction on how things work and how others should maintain it? Another question, is there any github integration like a status icon?

**Comment by hcho3** [comment]
> is there any github integration like a status icon?

Yes, you'll see an icon on the `master` branch already. Pull requests don't have an icon yet because we haven't merged this PR yet. For now, I created a separate feature branch to test BuildKite: https://github.com/dmlc/xgboost/tree/use_buildkite

**Comment by hcho3** [comment]
> could you please add some documents to give a brief introduction on how things work and how others should maintain it?

Yes, let me write documentation this week.

**Comment by hcho3** [comment]
Screenshot 2022-09-06 170221

Now every test job will require a manual approval prior to running. This will significantly reduce our CI expenses.

**Comment by hcho3** [comment]
Build status:
* https://buildkite.com/xgboost/xgboost-ci/builds/56
* https://buildkite.com/xgboost/xgboost-ci-windows/builds/52

**Comment by hcho3** [comment]
Merging this for now. I will closely monitor the CI for next 3 days (until Sep 10). If everything goes well, I will remove Jenkins

**Pull request merged**
