### PR TITLE
[R] configure backtrace and fopen64

### LINKED ISSUE #8595: [R] compilation failure with missing libexecinfo on Alpine Linux 3.17
Related to #5232.

Alpine Linux >= 3.17 [no longer provides libexecinfo](https://gitlab.alpinelinux.org/alpine/aports/-/commit/50795a14dee639ce2dcc836e2b2baca9bad4a1b1).
Without that, installation of the xgboost R package 1.6.0.1 from CRAN fails as follows:

```
* installing *source* package 'xgboost' ...
** package 'xgboost' successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking Backtrace lib... 
checking for backtrace in -lexecinfo... no
checking endian... 
configure: creating ./config.status
config.status: creating src/Makevars
** libs
Makevars:17: -DXGBOOST_STRICT_R_MODE=1
Makevars:17: -DDMLC_LOG_BEFORE_THROW=0
Makevars:17: -DDMLC_ENABLE_STD_THREAD=1
Makevars:17: -DDMLC_DISABLE_STDIN=1
Makevars:17: -DDMLC_LOG_CUSTOMIZE=1
Makevars:17: -DXGBOOST_CUSTOMIZE_LOGGER=1
Makevars:17: -DRABIT_CUSTOMIZE_MSG_
g++ -std=gnu++14 -I"/usr/include/R" -DNDEBUG -I./include -I./dmlc-core/include -I./rabit/include -I. -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_ENABLE_STD_THREAD=1 -DDMLC_DISABLE_STDIN=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1 -DRABIT_CUSTOMIZE_MSG_  -O2 -fomit-frame-pointer  -fopenmp -DDMLC_CMAKE_LITTLE_ENDIAN=1 -pthread -fvisibility=hidden -fpic  -O2 -fomit-frame-pointer -D__MUSL__ -flto -c xgboost_R.cc -o xgboost_R.o
In file included from ./dmlc-core/include/dmlc/././base.h:336,
                 from ./dmlc-core/include/dmlc/./logging.h:16,
                 from ./dmlc-core/include/dmlc/common.h:14,
                 from xgboost_R.cc:4:
./dmlc-core/include/dmlc/build_config_default.h:27:29: fatal error: execinfo.h: No such file or directory
   27 |     #define DMLC_EXECINFO_H <execinfo.h>
      |                             ^
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:176: xgboost_R.o] Error 1
ERROR: compilation failed for package 'xgboost'
* removing '/tmp/lib/xgboost'
```

A rather minimal Dockerfile to reproduce is

```Dockerfile
FROM alpine:3.17
ENV TZ=UTC
RUN apk add --no-cache R R-dev R-doc g++
RUN R -s -e 'install.packages("xgboost", repos = "https://cloud.R-project.org/")'
```

FWIW, I have worked around this problem in my own build of R (in which I set `CXXFLAGS += -D__MUSL__`) by patching the CRAN package as follows:

```diff
--- orig/src/dmlc-core/include/dmlc/build_config_default.h
+++ patched/src/dmlc-core/include/dmlc/build_config_default.h
@@ -18,6 +18,7 @@
 
 /* default logic for stack trace */
 #if (defined(__GNUC__) && !defined(__MINGW32__)\
+     && !defined(__MUSL__)\
      && !defined(__sun) && !defined(__SVR4)\
      && !(defined __MINGW64__) && !(defined __ANDROID__))\
      && !defined(__CYGWIN__) && !defined(__EMSCRIPTEN__)\
```

However, this is no general solution as [`__MUSL__` is not defined by default in musl](<https://www.openwall.com/lists/musl/2013/03/29/13>).

### PR DESCRIPTION
**Pull request by bastistician**
Fixes #8595.

This adds `-DDMLC_LOG_STACK_TRACE=0` and `-DDMLC_USE_FOPEN64=0` to the `XGB_RFLAGS` pre-processor flags in case the respective features are missing.

- I added `AC_MSG_NOTICE` messages for consistency with how endian detection is recorded in the log.
- I ran `autoreconf` using the same version (2.71) as used previously to keep the `configure` diff small, but for a clearer picture see the changes in the `configure.ac` source file.
- For testing, I created the R source package directory using `python3 tests/ci_build/test_r_package.py --task=pack` and installed that on both Ubuntu and Alpine Linux.

Installation now gives the following output on my Ubuntu 22.04 and Alpine Linux 3.20 systems, respectively:

<details><summary>Ubuntu 22.04</summary>

```
configure: Checking if/where backtrace is available
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ -std=gnu++17 accepts -g... yes
checking for g++ -std=gnu++17 option to enable C++11 features... none needed
checking for backtrace in -lexecinfo... no
checking for backtrace... yes
configure: Checking whether fopen64 is available
checking for fopen64... yes
configure: Endian detection
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
configure: Checking system endianness as USE_LITTLE_ENDIAN is unset
checking whether byte ordering is bigendian... no
using little endian
configure: creating ./config.status
config.status: creating src/Makevars
config.status: creating config.h
** libs
Makevars:20: -DXGBOOST_STRICT_R_MODE=1
Makevars:20: -DDMLC_LOG_BEFORE_THROW=0
Makevars:20: -DDMLC_ENABLE_STD_THREAD=1
Makevars:20: -DDMLC_DISABLE_STDIN=1
Makevars:20: -DDMLC_LOG_CUSTOMIZE=1
using C compiler: 'gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0'
using C++ compiler: 'g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0'
using C++17
[...]
```
</details>

<details><summary>Alpine Linux v3.20</summary>

```
configure: Checking if/where backtrace is available
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ -std=gnu++17 accepts -g... yes
checking for g++ -std=gnu++17 option to enable C++11 features... none needed
checking for backtrace in -lexecinfo... no
checking for backtrace... no
configure: Checking whether fopen64 is available
checking for fopen64... no
configure: Endian detection
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
configure: Checking system endianness as USE_LITTLE_ENDIAN is unset
checking whether byte ordering is bigendian... no
using little endian
configure: creating ./config.status
config.status: creating src/Makevars
config.status: creating config.h
** libs
Makevars:20: -DDMLC_LOG_STACK_TRACE=0
Makevars:20: -DDMLC_USE_FOPEN64=0
Makevars:20: -DXGBOOST_STRICT_R_MODE=1
Makevars:20: -DDMLC_LOG_BEFORE_THROW=0
Makevars:20: -DDMLC_ENABLE_STD_THREAD=1
Makevars:20: -DDMLC_DISABLE_STDIN=1
Makevars:20: -DDMLC_LOG_CUSTOMIZE=1
using C compiler: 'gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309'
using C++ compiler: 'g++ (Alpine 13.2.1_git20240309) 13.2.1 20240309'
using C++17
[...]
```
</details>

### CODE REVIEW

**Comment by trivialfis** [comment]
cc @jameslamb

**Comment by trivialfis** [comment]
I have manually checked the compilation is working:
``` dockerfile
FROM alpine:latest

RUN apk add R R-dev git g++

RUN \
    R -e 'install.packages(c("Matrix", "jsonlite", "data.table"), repos="https://mirror.las.iastate.edu/CRAN/", Ncpus = parallel::detectCores())'


RUN \
    mkdir ws && cd ws && \
    git clone --recursive https://github.com/bastistician/xgboost.git && \
    cd xgboost && git checkout musl-compatible

RUN \
    cd ws/xgboost/R-package && \
    MAKEFLAGS=-j$(nproc) R CMD INSTALL .

```

Haven't run any test yet due to failure to install `testthat` (`ps` compilation error).

**Review by trivialfis — APPROVED** [review]

**Comment by jameslamb** [comment]
Thanks for the `@`. I know this was already merged, but I just reviewed (and double-checked how these flags affect `dmlc-core`)... these changes look good to me.

**Comment by bastistician** [comment]
A new patch release of 'xgboost' was recently published on CRAN, but it lacked this fix.
Thus, on Alpine Linux, `install.packages("xgboost")` still fails, **also blocking >100 revdeps**.

@trivialfis : Could you please release a version that includes this fix or is otherwise compatible with Alpine Linux. Only 28 of ~22300 CRAN packages currently fail to compile on Alpine Linux and 'xgboost' is one of them (that with most reverse dependencies).

**Comment by trivialfis** [comment]
Thank you for raising this, I opened a new issue to keep track of it: https://github.com/dmlc/xgboost/issues/11414 . I will work on it.

**Pull request merged**
