### PR TITLE
Support gpu shader

### PR DESCRIPTION
**Pull request by wbo4958**

### CODE REVIEW

**Comment by wbo4958** [comment]
@trivialfis, Could you help merge it. Thx

**Comment by trivialfis** [comment]
Could you please provide a brief description for the PR?

**Comment by wbo4958** [comment]
This PR is to put xgboost4j/xgboost4j-spark/xgboost4j-spark-gpu to a uber jar xgboost-spark-gpu, So with this PR, users can use one single xgboost-spark-gpu instead of using the previous 3 jars.

**Comment by wbo4958** [comment]
@trivialfis would you help merge this PR, Thx.

**Pull request closed without merging**
