### PR TITLE
Force tree order in JSON.

### PR DESCRIPTION
**Pull request by trivialfis**
It's not a bug.  Right now the order is implicitly enforced, this PR makes it explicit.  Marked as blocking because with explicit behaviour, we can be sure there's no chance for mistake.

* Put in omp parallel.  On large number of trees this is about 20% faster, not very impressive so I can revert it if needed.

### CODE REVIEW

**Comment by trivialfis** [comment]
@hcho3 I can remove the blocking tag if you think it's risky.

**Comment by hcho3** [comment]
@trivialfis Is the `Json` class tested for concurrent accesses? I'm a bit concerned about the use of OpenMP here. We could remove OpenMP from this PR to reduce the risk.

**Comment by trivialfis** [comment]
>  Is the Json class tested for concurrent accesses

No.  But each JSON object is created as a local variable to the thread (inside for loop).

> We could remove OpenMP from this PR to reduce the risk.

Sounds good.  Let me remove it.

**Comment by trivialfis** [comment]
@hcho3 OMP loop is removed.

**Pull request merged**
