### PR TITLE
Update Rabit

### PR DESCRIPTION
**Pull request by hcho3**
Pulls in the following additions:
* **Fix hung training (dmlc/rabit#132)**
* Expose AllGather primitive (dmlc/rabit#113, dmlc/rabit#129)
* Fix CMake variable (dmlc/rabit#126)
* Allow duplicated bootstrap AllReduce overwrite previous results (dmlc/rabit#128)
* Fix build on FreeBSD (dmlc/rabit#133)

### CODE REVIEW

**Comment by trivialfis** [comment]
@hcho3 Can we branch out after this PR?

**Comment by hcho3** [comment]
@trivialfis Do you mean release candidate?

**Comment by trivialfis** [comment]
Yup.  A release branch.

**Comment by hcho3** [comment]
Sure, I'll do that after this PR and #5236 are merged.

**Pull request merged**
