### PR TITLE
Force colored output for ninja build.

### PR DESCRIPTION
**Pull request by trivialfis**

### CODE REVIEW

**Comment by hcho3** [comment]
@trivialfis Shall we enable this in our CI?

**Comment by trivialfis** [comment]
@hcho3 Not sure, can the text console handle colored output?  If not then it will be printing ansi code.

**Comment by hcho3** [comment]
@trivialfis Yes, Jenkins should be able to handle ANSI colors:
https://github.com/dmlc/xgboost/blob/071e10c1d1c492d4ee28e0c8a8e1a5206225f4ca/Jenkinsfile#L27-L33

**Comment by hcho3** [comment]
Hmm no idea why it doesn't work in Jenkins. For now let me revert my last commit.

**Comment by trivialfis** [comment]
@hcho3 Maybe jenkins is stripping out the color code?

**Comment by trivialfis** [comment]
I'm fine with Jenkins not having colored output.

**Pull request merged**
