### PR TITLE
[R] Throw explicit error when using categorical features in functions which don't support them

### PR DESCRIPTION
**Pull request by david-cortes**
ref https://github.com/dmlc/xgboost/issues/9810
ref https://github.com/dmlc/xgboost/issues/9925

This PR adds an explicit error message when trying to call `xgb.model.dt.tree` and functions that depend on it (currently `xgb.plot.multi.trees`) on a model that has categorical features, as it fails to extract the splits from those.

It doesn't actually fix the issue - i.e. this PR doesn't fix the functions to make them work with categorical data - but instead just makes the error message understandable.

Should ideally be reverted once there is a C-level function to produce tables from trees with proper support for categorical splits.

### CODE REVIEW

**Review by trivialfis — APPROVED** [review]
Will merge once the CI is green.

**Comment by david-cortes** [comment]
On second thought, I'm thinking it better to remove the `text` argument for trees-to-table:
* Once a C-level function to get the table is added, it'd work from a booster object only instead of text dumps, so better to have the breaking change now before a CRAN release.
* Having this `text` argument doesn't allow throwing an informative error when the model has categorical features.

**Comment by trivialfis** [comment]
> Once a C-level function to get the table is added

It might take a while, though. I'm working on storing the `factor` in the booster, as there are complaints about this being a foot gun.

**Comment by trivialfis** [comment]
Could you please help resolve the conflicts?

**Comment by david-cortes** [comment]
> Could you please help resolve the conflicts?

Solved.

**Review by trivialfis — APPROVED** [review]

**Pull request merged**
