### PR TITLE
Adding some new function in the Exsocket class

### PR DESCRIPTION
**Pull request by momomuchu**

### CODE REVIEW

**Review by trivialfis — COMMENTED** [review]
May I ask what's the motivation for doing so? We usually don't include code that's not used by existing xgboost interfaces.

**Comment by momomuchu** [comment]
sorry, i'm just trying to contribute maybe i shouldn't have ?

**Comment by momomuchu** [comment]
I didn't very know how to contribute so i just put it some addons function, that wont impact the code in general.

**Comment by trivialfis** [comment]
We appreciate that you are willing to contribute to the XGBoost project. Unfortunately, we cannot accept the pull request as it is, since it is not clear how it's useful for other users of XGBoost. If you are willing, there are other ways to contribute:
* Report bugs on the issue tracker
* Submit a fix for an existing bug
* Review PRs that you are interested in.
* Some issues on GitHub are marked as `good first issue`. You may consider them first.
* If you want to add a new feature, please first post an issue on GitHub so that we can discuss the details.

**Pull request closed without merging**
