### PR TITLE
Document current limitation in number of features

### PR DESCRIPTION
**Pull request by hcho3**
See discussion at #3884. The `num_feature` variable uses 32-bit integer, which causes XGBoost to fail for datasets with more than 2147483647 features. For now, print a better error message.

### CODE REVIEW

**Comment by hcho3** [comment]
@trivialfis FYI

**Comment by trivialfis** [comment]
@hcho3 What's preventing using int64_t currently?

**Comment by hcho3** [comment]
@trivialfis XGBoost saves the trained model as binary dump. So you can't easily add or change fields without breaking backward compatibility. As an aside, someone told me today that the use of binary dump is causing endian-compatibility issue as well (model created by little-endian machine doesn't load on big-endian machine).

**Comment by khotilov** [comment]
@trivialfis Since dense structures are currently used in many places to index features, using such large indices would be consuming 2Gb times N of memory.

**Pull request merged**
