### PR TITLE
Disable HT for DMatrix creation

### PR DESCRIPTION
**Pull request by ShvetsKS**
Recently introduced `OmpSetNumThreads` function brings up to 2x slowdown on HW with enabled Hyper-threading.

DMatrix create time| master, s | this PR, s | Speedup
-- | -- | -- | --
mortgage | 11.67 | 5.68 | 2.05
higgs | 0.96 | 0.51 | 1.88
msrank | 4.36 | 3.53 | 1.23

It significantly affects inference stage as was mentioned in https://github.com/dmlc/xgboost/issues/6283.

Reason: there is still overheads on memory allocation\initialization (`InitBudget`, `InitStorage`) so there is no gain from usage HT here.

### CODE REVIEW

**Review by trivialfis — COMMENTED** [review]
So the default setting doesn't account for HT?  Also, please don't change the file permission.

**Comment by ShvetsKS** [comment]
> So the default setting doesn't account for HT? Also, please don't change the file permission.

@trivialfis by default `nthreads == -1` for DMatrix create, and `omp_get_num_procs` returns 2x of hardware threads with enabled HT. So it has negative impact on time of DMatrix creation always. That's why I reverted initial behavior (before introduction `OmpSetNumThreads` function) for DMatrix.

Files permissions were reverted.

**Comment by ShvetsKS** [comment]
All tests were passed for previous commit 4320275
Current run failed due to exceeded budget

**Comment by ShvetsKS** [comment]
@trivialfis would it be better to wait refreshed budget to see all passed tests again?

**Comment by trivialfis** [comment]
Yup.  Will merge once all tests pass.

**Review by trivialfis — APPROVED** [review]

**Pull request merged**
