### PR TITLE
adding support for comments in SVM file

### PR DESCRIPTION
**Pull request by antonymayi**
the original libsvm tools [unofficially](http://www.csie.ntu.edu.tw/~cjlin/libsvm/faq.html#f306) allow comments in the SVM datafile. making simple change to align with this behavior.

### CODE REVIEW

**Comment by xmueller** [comment]
+1 for this, would spare me from stripping gigs of SVM data before processing with xgboost.

**Comment by terrytangyuan** [comment]
@tqchen Could you check this?

**Comment by tqchen** [comment]
sorry for the delayed reply. Thanks for the contribution.

I am working on an on-going refactor that will re-use the parser in https://github.com/dmlc/dmlc-core
It would be great if you can send a pr there, so it could be future compatible, and benefit other dmlc projects.

**Comment by fanfannothing** [comment]
nice

**Pull request closed without merging**
