### PR TITLE
cpu_predictor has_categorical error

### PR DESCRIPTION
**Pull request by gklab**

### CODE REVIEW

**Review by trivialfis — APPROVED** [review]
Thank you for the fix!

**Comment by gklab** [comment]
The code can be simplified here.

**Comment by gklab** [comment]
@trivialfis

**Comment by trivialfis** [comment]
Hi, can we revert the simplification and keep the fix?

**Comment by gklab** [comment]
yes

**Comment by gklab** [comment]
> Hi, can we revert the simplification and keep the fix?

OK. May I ask what is the original intention of not simplifying this code?

**Comment by gklab** [comment]
> Hi, can we revert the simplification and keep the fix?

Interesting, I had no idea that my simplification of this code would cause so many validations to fail.

**Comment by gklab** [comment]
> Hi, can we revert the simplification and keep the fix?

Oh, I'm a rookie in C++, I don't know that template parameters should use constants

**Review by trivialfis — APPROVED** [review]
Nice fix, thank you!

**Pull request merged**
