### PR TITLE
Saving multiple versions of xgb models

### PR DESCRIPTION
**Pull request by glr72**
Hi, 

the small change below allows to save more than 1 version of the model (in the main xgb.train.R it is always overwritten).

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@glr72 Thanks but some people might want to only save 1 version though. It would be better if, instead, you can add a parameter `max_to_keep` for the maximum number of recent models to keep. The idea is that people want to save only several versions of the recent models. I am open to other ideas though.

**Comment by glr72** [comment]
hi terrytangyuan,

I implemented your proposal. You have parameter max_to_keep (default = 0), which works as you suggested.

**Comment by terrytangyuan** [comment]
@glr72 Thank you. Could you squash your commits into one and add yourself to CONTRIBUTORS?

**Comment by glr72** [comment]
Hi terrytangyuan, 
sure. Can you please teach me how to do it? Thanks

**Comment by terrytangyuan** [comment]
There are many ways to do this but here's one that's on top of my mind and you can just copy and paste. 
```
git reset --soft HEAD~5 # move head to 5 commits before and keep the changes
git add -A # add all the changes to stage
git commit -m "Added max_to_keep parameter" # commit message
git push --force origin master # do a force push to your master branch since you are changing commit history
```
 For your reference, you should look into how to use `git rebase` from command line or use it in sourceTree (http://blogs.atlassian.com/2014/06/interactive-rebase-sourcetree/).  Let me know if you have any questions.

**Comment by glr72** [comment]
Ok I did it. There's a problem with the CONTRIBUTOR file but it looks to be not relevant.

**Comment by terrytangyuan** [comment]
Good job! Looks like it has conflicts with CONTRIBUTORS. Could you resolve it or do a
```
git reset --hard HEAD~1
git push --hard origin master
```
and I'll add you there myself. 

Thanks!

**Comment by glr72** [comment]
commands executed (actually --forcec and not --hard)

Thanks again

**Comment by terrytangyuan** [comment]
@glr72 I don't see any changes though. Mind trying it again?

**Comment by tqchen** [comment]
closing this PR for now and refer to https://github.com/dmlc/xgboost/issues/892 for new guidelines with respect to adding these related features

**Pull request closed without merging**
