### PR TITLE
[jvm-packages] Set up dependabot

### PR DESCRIPTION
**Pull request by hcho3**
This may help us keep dependencies up to date.

### CODE REVIEW

**Comment by wbo4958** [comment]
@hcho3 what does dependabot do?

**Comment by hcho3** [comment]
@wbo4958 It automatically generates pull requests to update the dependencies.

**Review by trivialfis — APPROVED** [review]

**Comment by trivialfis** [comment]
I thought github have that by default?

**Comment by hcho3** [comment]
> I thought github have that by default?

Not quite. We need to opt into it by creating the config file.

Let's give it a try and see if the bot works as intended.

**Comment by hcho3** [comment]
Looks like I made a mistake in the `ignore` specification. I will create a new pull request to follow up.

**Pull request merged**
