### PR TITLE
Reorder includes.

### PR DESCRIPTION
**Pull request by trivialfis**
@hcho3 

Address recent update of cpplint.

### CODE REVIEW

**Comment by hcho3** [comment]
@trivialfis It is actually possible to disable the header ordering check. Let us discuss the merits of keeping the check or not. You seemed to want to remove it, and I am interesting to hearing your opinion on this topic.

**Comment by trivialfis** [comment]
@hcho3 I'm fine with both options, XGBoost doesn't rely on header macros too much so ordering might not be a real issue.  Also should we consider dmlc and rabit headers as system headers (indicated by `-isystem` instead of `-I`)?  But on the other hand having organized headers is nice.

**Comment by trivialfis** [comment]
I'm confused, the CI result is different from https://github.com/dmlc/xgboost/pull/5612

**Comment by hcho3** [comment]
I've purged the Docker cache, so that the build env is built from scratch.

**Comment by trivialfis** [comment]
Thanks!  Will continue the PR tomorrow.

**Comment by hcho3** [comment]
You have other things on your plate. If you want, I can take over this PR.

**Pull request merged**
