### PR TITLE
[DIST] Enable multiple thread  make rabit and xgboost threadsafe

### PR DESCRIPTION
**Pull request by tqchen**
…e thread-safe by using thread local variables.

### CODE REVIEW

**Comment by tqchen** [comment]
cc @CodingCat   see newest version of https://github.com/tqchen/xgboost/blob/master/jvm-packages/xgboost4j-demo/src/main/java/ml/dmlc/xgboost4j/demo/DistTrain.java

**Comment by tqchen** [comment]
- Currently the copy of libxgboost4j library and tracker.py is by create_jni.sh
- We will want to use pom and maven to handle these automatically in the future

**Comment by tqchen** [comment]
@CodingCat  it seems to me that the interface Booster is not necessary. As we will only have one version of Booster each, for scala and java.

**Comment by tqchen** [comment]
please also help review the serializable commit https://github.com/tqchen/xgboost/commit/0df2ed80c8184fe3a7603a97d4ff82f24685497d I feel I did it right.

**Comment by CodingCat** [comment]
@tqchen I made some changes to the current implementation, mainly for adding some trackable logging statements. and removed the FileUtil, as that static function is only used by NativeLibLoader

**Pull request merged**
