### PR TITLE
support auc evaluation when the dataset only contains pos or neg samples

### PR DESCRIPTION
**Pull request by sharkdtu**
If running xgboost on yarn, sometimes  an execption with the message "dataset only contains pos or neg samples" will be threw during auc evaluating. That is because, when running xgboost on yarn, sample data will be split into multipile small splits for workers, some small splits may only contains pos or neg samples actually. 
For example, if the sample data is as follows:
```
0.0  1:0 2:1
0.0  0:0 2:1
1.0  1:0 2:0
1.0  1:0 2:0
```
if running xgboost on yarn with 2 workers, the data will be split into two splits like this:
```
0.0  1:0 2:1
0.0  0:0 2:1
```
```
1.0  1:0 2:0
1.0  1:0 2:0
```

to avoid throwing an error, add a pos sample and a neg sample respectively, and it will have little impact on the auc evaluation

### CODE REVIEW

**Comment by tqchen** [comment]
Maybe we can do a special check on the end and return a special value, when the dataset is all pos or neg?

**Comment by sharkdtu** [comment]
a special check on the end and return a special value may not help.  when the dataset of a worker is all pos or neg, the contribution to the auc metric is different from the dataset distribution. how can we determine a special value?

**Comment by tqchen** [comment]
For example, use similar statistics like you defined by having one positive and negative example in both end. But only applys when the special case occurs

**Comment by tqchen** [comment]
I am closing this for now, mainly because the codebase is shifting toward this new refactored version ttps://github.com/dmlc/xgboost/tree/brick/ , which will  be merged soon.

Would be great if you can push a fix with respect to that. As I mentioned in last post, it would be nice to make the result consistent with old auc eval as long as pos example occurs and output special value when they do not

**Comment by sharkdtu** [comment]
ok, I think approximately estimate auc using mean is not accurate when running xgboost  in distributed way. It is just suitable for the data which is uniform on each worker. May be we should think about changing to another way.

**Comment by wenmin-wu** [comment]
@sharkdtu 
I want to know how to get the training auc info while running xgboost on yarn, in my settings, I can just see the training-error info. Thanks!

**Comment by sharkdtu** [comment]
@wenmin-wu add `eval_metric = "auc" ` in your config file

**Comment by wenmin-wu** [comment]
@sharkdtu have you meet the `org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.hdfs.server.namenode.LeaseExpiredException): No lease on /tmp/mushroom.final.model (inode 73759781): File does not exist. Holder DFSClient_NONMAPREDUCE_-1617396307_1 does not have any open files.` during the final model saving period

**Pull request closed without merging**
