### PR TITLE
[jvm-packages] Fixed java.nio.BufferUnderFlow issue in Scala Rabit tracker.

### PR DESCRIPTION
**Pull request by xydrolase**
This pull request attempts to address the issue #1925 reported by @geoHeil. If the Rabit tracker sends fragmented TCP packets for tracker command "print", the Rabit handler may attempt to decode the message prematurely, causing buffer underflow. See added unit test.

### CODE REVIEW

**Comment by CodingCat** [comment]
@tqchen , it seems that I cannot merge due to the low coverage of test cases in the project?

**Comment by CodingCat** [comment]
@tqchen , still unable to merge patches? 

image

**Comment by tqchen** [comment]
seems was because there used to be a check to require branch to be up to date. I removed that constraint, can you try again?

**Comment by CodingCat** [comment]
yeah, it is working now...thanks

**Comment by CodingCat** [comment]
merged, thanks @xydrolase

**Pull request merged**
