### PR TITLE
[WIP] [jvm-packages] move dmatrix building into rabit env

### PR DESCRIPTION
**Pull request by wbo4958**
DMatrix needs to communicate with other partitions to make sure the
number of features is consistent.

### CODE REVIEW

**Comment by wbo4958** [comment]
For now, there are some unit tests failing. one is feature size checking in DMatrix, the other one is rabit  timeout issue. Hi @trivialfis can you help on these issues?

**Comment by RAMitchell** [comment]
Is it possible that the number of DMatrix objects on each worker becomes different? Or the creation of these objects is not synchronised across workers for some reason?

**Comment by trivialfis** [comment]
Let me add a DMatrix check.

**Comment by RAMitchell** [comment]
We merged a more moderate solution in #5581 given that there might be complications with this approach.

**Comment by wbo4958** [comment]
Thx Rory, Closed this since #5581 has been merged.

**Pull request closed without merging**
