### PR TITLE
add test cases for Scala API

### PR DESCRIPTION
**Pull request by CodingCat**
add test cases for Scala API

### CODE REVIEW

**Comment by CodingCat** [comment]
@tqchen , mind have a review?

**Comment by CodingCat** [comment]
I will add the examples of Scala in another PR

**Comment by CodingCat** [comment]
I added default values for Scala API, the remaining issue is that Java does not support default values, we need to override again and again....I'm considering adding a configuration layer in XGBoost jvm package, but it might be an overkill for just around 10 configuration entries, @tqchen , your thoughts

**Comment by tqchen** [comment]
I guess we are fine for java package for now then. Current API is good to serve most purposes

**Comment by CodingCat** [comment]
ok, then, I guess the PR is ready to go as long as Travis agrees....

**Comment by CodingCat** [comment]
Done @tqchen

**Pull request merged**
