### PR TITLE
[GPU-Plugin] Fix test command

### PR DESCRIPTION
**Pull request by ysh329**
Due to the `test` filename changed to `tests`, the test command should be changed also.
from
```Python
python -m nose test/python/
```
to
```Python
python -m nose tests/python/
```

### CODE REVIEW

**Comment by pseudotensor** [comment]
Erroneous PR, directory is still test.  Maybe confusion with xgboost/tests directory.

**Comment by ysh329** [comment]
@pseudotensor 
```Shell
root@c7ced51f77a2:/xgboost# ls
CMakeLists.txt     Makefile   amalgamation  build_plugin  doc           lib             rabit      xgb.model.dart
CONTRIBUTORS.md    NEWS.md    appveyor.yml  cub           dtest.buffer  make            src        xgboost
ISSUE_TEMPLATE.md  R-package  build         demo          include       plugin          tests
LICENSE            README.md  build.sh      dmlc-core     jvm-packages  python-package  xgb.model
root@c7ced51f77a2:/xgboost# python -m nose test/python/
E
======================================================================
ERROR: Failure: OSError (No such file /xgboost/test/python)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/failure.py", line 42, in runTest
    raise self.exc_class(self.exc_val)
OSError: No such file /xgboost/test/python

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
root@c7ced51f77a2:/xgboost# python -m nose tests/python/                                                                               
[01:33:57] 6513x127 matrix with 143286 entries loaded from demo/data/agaricus.txt.train
[01:33:57] 1611x127 matrix with 35442 entries loaded from demo/data/agaricus.txt.test
[01:33:57] 1611x127 matrix with 35442 entries loaded from dtest.buffer
.[01:33:57] 6513x127 matrix with 143286 entries loaded from demo/data/agaricus.txt.train
```

**Comment by RAMitchell** [comment]
The gpu plugin readme refers to plugin/updater_gpu/test/python.

**Comment by ysh329** [comment]
@RAMitchell oops, thanks. :smile:

**Pull request closed without merging**
