### PR TITLE
[CI] Automatically build GPU-enabled R package for Windows

### PR DESCRIPTION
**Pull request by hcho3**
Follow up with https://github.com/dmlc/xgboost/pull/6827 by building the binary R package for Windows too. This will greatly simplify using GPUs with the R package on Windows.

Users will now be able to install XGBoost with the following simple commands:
```
# Install dependencies
R -q -e "install.packages(c('data.table', 'magrittr', 'jsonlite', 'remotes'))"
# Install XGBoost
R CMD INSTALL ./xgboost.tar.gz
```
and they will be able to use the GPU algorithm (as long as the machine has a working GPU).

I re-built the image of the Windows CI worker as part of this PR, in order to install R.

### CODE REVIEW

**Comment by hcho3** [comment]
Will re-run tests after #7186 is merged.

**Comment by hcho3** [comment]
Log for successful building of the binary R package: https://xgboost-ci.net/blue/organizations/jenkins/xgboost-win64/detail/PR-7185/2/pipeline/45

**Review by trivialfis — APPROVED** [review]

**Comment by trivialfis** [comment]
I missed that sm_86 is not supported on cuda 11.0.  Will open a new PR for fixing that.

**Comment by trivialfis** [comment]
https://github.com/dmlc/xgboost/pull/7187

**Comment by trivialfis** [comment]
@hcho3 The R package build seems to be failing: https://xgboost-ci.net/blue/organizations/jenkins/xgboost-win64/detail/master/937/pipeline .

**Comment by hcho3** [comment]
@trivialfis That's odd. It was working in this PR: https://xgboost-ci.net/blue/organizations/jenkins/xgboost-win64/detail/PR-7185/2/pipeline/45. Let me take a look. I wonder it could be some macro crash?

**Comment by hcho3** [comment]
@trivialfis Actually, in https://xgboost-ci.net/blue/organizations/jenkins/xgboost-win64/detail/master/937/pipeline/, the main build is failing, not the R package.

**Comment by hcho3** [comment]
Diagnosis: the `build/` directory didn't get cleaned up properly from the last invocation of `build-rpkg-win64-cuda10.1`, so `build-win64-cuda10.1` task gets the `build` directory with `R_LIB=ON` configuration. We need to ensure the build directory gets cleaned up properly.

**Comment by aegerton** [comment]
Thanks @hcho3 for the suggestion.  I tried the `1.5.0 version` as requested, but received a very similar error message as before;-

```
install.packages("C:/Users/aeger/Downloads/xgboost_r_gpu_win64_1.5.0.tar.gz", repos = NULL, type = "source")
Installing package into ‘D:/OneDrive/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package 'xgboost' ...
** using staged installation
      0 [main] sh 1788 C:\rtools40\usr\bin\sh.exe: *** fatal error - error while loading shared libraries: /usr/local/cuda/lib64/libnvblas.so: cannot open shared object file: No such file or directory
    411 [main] sh 1788 cygwin_exception::open_stackdumpfile: Dumping stack trace to sh.exe.stackdump
ERROR: configuration failed for package 'xgboost'
* removing 'D:/OneDrive/Documents/R/win-library/4.1/xgboost'
Warning in install.packages :
  installation of package ‘C:/Users/aeger/Downloads/xgboost_r_gpu_win64_1.5.0.tar.gz’ had non-zero exit status
```
Sorry to be a pain!  Any other ideas, please?

**Pull request merged**
