### PR TITLE
Unify set index data.

### PR DESCRIPTION
**Pull request by trivialfis**

### CODE REVIEW

**Comment by trivialfis** [comment]
@ShvetsKS

**Comment by trivialfis** [comment]
@hcho3 @RAMitchell @SmirnovEgorRu Please help reviewing.

**Review by RAMitchell — COMMENTED** [review]
The reorganisation looks good. Does the lambda get compiled inline? The difference between a function call and inlining could be large here.

**Comment by trivialfis** [comment]
@RAMitchell  I believe so, examining it with gdb:

```
(gdb) print get_offset
$2 = {__offsets = 0x555555ca1630}
(gdb) disassemble get_offset
Value can't be converted to integer.
```

**Pull request merged**
