### PR TITLE
[jvm-packages] improve prediction performance of XGBoostClassifier/XGBoostRegressor

### PR DESCRIPTION
**Pull request by sperlingxx**
1. Skip score predictions if they are unnecessary.

2. Store internal prediction results(rawPrediction, probability, predLeaf, predContrib) with Array instead of transforming them into Iterable.

### CODE REVIEW

**Comment by sperlingxx** [comment]
@CodingCat  Can you help to review this PR?

**Comment by CodingCat** [comment]
I will review this shortly, busy in other business

**Comment by CodingCat** [comment]
is this PR necessary now?

**Comment by sperlingxx** [comment]
@CodingCat  I'll close it.

**Pull request closed without merging**
