### PR TITLE
[BLOCKING] Adding JVM doc build to Jenkins CI

### PR DESCRIPTION
**Pull request by hcho3**
Use Jenkins CI to build JVM doc on the fly. Since the CI already knows which branch I'm in (or which PR I'm in), versioning is easy.

### CODE REVIEW

**Comment by hcho3** [comment]
@CodingCat

**Comment by CodingCat** [comment]
LGTM

**Comment by CodingCat** [comment]
thanks for the help!

**Comment by CodingCat** [comment]
some tests were stuck.....is it relevant?

**Comment by hcho3** [comment]
@CodingCat Travis is being flaky for some reason. I don't think it's relevant.

**Comment by hcho3** [comment]
Once the javadoc tarballs arrive safely to my S3 bucket, I can modify `conf.py` so that they get added to ReadTheDocs.

**Comment by hcho3** [comment]
@CodingCat Is there any way to not build native lib when building docs?

**Comment by hcho3** [comment]
@RAMitchell Can you take a look at the change I made to Jenkinsfile? Does it look reasonable to you?

**Comment by hcho3** [comment]
We'll release 0.80 once this is merged.

**Pull request merged**
