### PR TITLE
add a test for cpu predictor using external memory

### PR DESCRIPTION
**Pull request by rongou**
@RAMitchell @hcho3

### CODE REVIEW

**Comment by RAMitchell** [comment]
Is there a way we can test external memory without so much data? I feel like this type of test is much slower than it really needs to be.

**Comment by rongou** [comment]
@RAMitchell hmm with the current APIs it seems quite hard to test external memory without the large data. Let me know if you have any ideas. The test runs around 800 ms on my machine, seems inline with some the existing tests.

**Comment by rongou** [comment]
@RAMitchell @hcho3 ok, made some minimal api changes to allow testing on smaller external memory pages. The test now runs in a few milliseconds. Please take another look.

**Comment by RAMitchell** [comment]
Looks good, and this is a much more sustainable way to write tests for external memory. I will wait to see if anyone else has comments before merging.

**Pull request merged**
