### PR TITLE
 Release patch release 1.3.2

### PR DESCRIPTION
**Pull request by trivialfis**

### CODE REVIEW

**Comment by trivialfis** [comment]
Oh, no, I meant to push the tag.

**Comment by hcho3** [comment]
You should push the tag only after the PR is merged.

**Comment by hcho3** [comment]
For now, let's monitor the CI. We can always repair the 1.3.0 branch if something blows up.

**Comment by trivialfis** [comment]
Yup, I tried to push a revert commit to my local branch, somehow github is not updating.

**Comment by trivialfis** [comment]
All passed, log for appvayor is here: https://ci.appveyor.com/project/tqchen/xgboost/builds/37239902  .  I will push a tag.

**Pull request merged**
