### PR TITLE
Work around a segfault observed in SparsePage::Push()

### PR DESCRIPTION
**Pull request by hcho3**
Work around #7156, by removing `resize()` of the thread-local vector inside the OpenMP block.

### CODE REVIEW

**Review by trivialfis — COMMENTED** [review]
Could you please explain why is this an issue?  Is opencv  changing some setting in number of threads?

**Comment by hcho3** [comment]
@trivialfis I don't know yet. I filed this PR to document a workaround I happened to find.

**Comment by trivialfis** [comment]
Asking because we are using thread local vector in many places. I'm worrying this might happen in other places.

**Comment by trivialfis** [comment]
But Looks good to me, as long as the tests can pass.

**Comment by hcho3** [comment]
@trivialfis It turns out that it's sufficient to avoid `resize()` of the thread-local vector inside the OpenMP block. (I'm removing the reduction clause because MSVC doesn't support it for the `max` operator.)

We may want to scan the code for all other occurrences of thread-local vectors and see if we are resizing them inside the OpenMP block.

**Comment by hcho3** [comment]
One possibility is that an empty vector could have an optimized representation that differs from the representation of an non-empty vector. So calling `max_columns_vector[tid].resize()` may cause re-allocation of `max_columns_vector` (due to the change of representation) and thus lead to the mutation of the shared object.

**Comment by trivialfis** [comment]
Hmm ... might not be necessary, we don't know the cause, let's don't make too many changes based on guesses.

**Comment by trivialfis** [comment]
> max_columns_vector[tid].resize() may cause re-allocation of max_columns_vector (due to the change of representation)

It can be small vector optimization, but that's thread local right?  It can not change its parent container.

**Comment by hcho3** [comment]
@trivialfis FYI this PR will also fix the R tests on GitHub Actions.

**Review by trivialfis — APPROVED** [review]

**Pull request merged**
