### PR TITLE
[jvm-packages][spark]Preserve num classes

### PR DESCRIPTION
**Pull request by CodingCat**
@mengdong please check if this resolves the issues

### CODE REVIEW

**Comment by CodingCat** [comment]
@mengdong , I found that there are some issues when passing num_class to the booster when num_class = 2...I still need to evaluate whether it is the same case when num_class is larger than 2

**Comment by CodingCat** [comment]
multi classes OK, but there is really a problem when you pass num_class = 2

**Comment by mengdong** [comment]
I think this works for multi-class, when num_class = 2 is not important as people only use num_class for multi-class task, however, there are trivial problems like how to handle the probabilities and predicted label for multi-class learning task.

**Comment by CodingCat** [comment]
@mengdong I think it is fine for label and prediction col name as long as you only use in cv

for threshold...I do not think MLLIB support to define it in CV

**Comment by CodingCat** [comment]
I will merge it for now, and please let me know if you find other problems

**Comment by ronlut** [comment]
@CodingCat 
I'm getting a `value 0 for Parameter num_class should be greater equal to 1` when trying to train on a binary data (num_class=2).
Setting `num_class=2` using `set_params()` looks like it solves the problem, but is it the solution?

**Pull request merged**
