### PR TITLE
Catch all standard exceptions in C API.

### PR DESCRIPTION
**Pull request by trivialfis**
Related: https://github.com/dmlc/xgboost/issues/6217

### CODE REVIEW

**Comment by trivialfis** [comment]
It seems on CI environment the exception is not thrown.

**Comment by hcho3** [comment]
@trivialfis Maybe CI containers have an aggressive OOM killer that kills rouge processes allocating huge memory? I suggest that you write a unit test that explicitly throws a standard exception.

**Comment by hcho3** [comment]
See http://coldattic.info/post/40/. Linux kernel can send SIGKILL to a process that goes over a memory limit.

**Comment by trivialfis** [comment]
> I suggest that you write a unit test that explicitly throws a standard exception.

That might be the best option for this PR.  But it defeats the purpose of catching these kind of exception: to avoid abort.  See linked issue.

Actually this is interesting to me, as now the behavior contradicts the C++, see Exceptions in: https://en.cppreference.com/w/cpp/memory/allocator/allocate

**Comment by trivialfis** [comment]
Might be a fixed bug in the std library as I can pass the test instantly with gcc 9.

**Comment by hcho3** [comment]
@trivialfis Linux over-commits memory requests by default, and when memory runs out, the kernels starts killing processes. So catching `std::bad_alloc` might not prevent process abortion. See https://stackoverflow.com/a/51676578.

**Comment by trivialfis** [comment]
@hcho3 Can you review?  I think the PR is still useful as it does work on my platform. ;-) Besides, as we are now compiling Python package with cxx symbols hidden, so any exception will turn into an abort when reaching the C API.  This PR can capture these exceptions and provide a way to output some error messages (borderline but still better than abort).

**Review by hcho3 — APPROVED** [review]

**Pull request merged**
