### PR TITLE
[jvm-packages] Minor improvements to the CMake build

### PR DESCRIPTION
**Pull request by superbobry**
See individual commit messages for details.

### CODE REVIEW

**Comment by RAMitchell** [comment]
FYI you can add travis/appveyor to your fork easily.

**Comment by superbobry** [comment]
Thanks for the tip! The other reason is that this way people also know what's being worked on.

**Comment by superbobry** [comment]
I think this is good to merge.

**Comment by CodingCat** [comment]
would you mind resolving the conflicts?

**Pull request merged**
