### PR TITLE
In mknfold init random seed only if the seed parameter is sent by the…

### PR DESCRIPTION
**Pull request by mircean**
… caller

### CODE REVIEW

**Comment by terrytangyuan** [comment]
This will change the default behavior. Is there a reason why you are changing this? It's an internal function.

**Comment by mircean** [comment]
The code as is sets the random seed to 0 on each call. Thus one cannot call cv multiple times and average the results (so the seed is not a factor) because the cv will produce the same result
In general, all methods must have a way for the caller to avoid setting the random seed

**Comment by terrytangyuan** [comment]
okay. Could you fix the tests?

**Comment by mircean** [comment]
Not sure why the tests failed – I looked but I couldn’t figure it out. I’ll have to spend more time to understand the test errors

**Pull request closed without merging**
