### PR TITLE
Release version 0.72

### PR DESCRIPTION
**Pull request by hcho3**
As discussed in #3252, let us release version 0.72 on June 1, 2018.

Here are couple things that will occur:
* On **May 31, 2018, 10:00 AM Pacific Time**, there will be code freeze for release 0.72.
  - All pull requests (PRs) that are merged to `master` prior to May 31, 2018 will be part of release 0.72.
  - A new branch `release_0.72` has been created. On May 31, I will re-base the branch on top of the last commit of that day.
  - PRs that are not merged by May 31 will not be part of release 0.72 (except for a few reasons as outlined [here](https://github.com/dmlc/xgboost/issues/3252#issuecomment-382597377)).
* On **June 1, 2018, 10:00 AM Pacific Time**, I will create a new tag `0.72` to mark the latest release. I plan to write a release note for 0.72 in `NEWS.md`.
* On **June 1, 2018**, I will submit a tarball for 0.72 release to PyPI (Python Package Index).

### CODE REVIEW

**Comment by RAMitchell** [comment]
Can we also upload the GPU binary wheel in this release?

**Comment by hcho3** [comment]
@RAMitchell Yes, we can submit binary wheels to PyPI, as well as the GitHub release section. Are the GPU wheels also usable for CPU-only machines? (That's what you seem to say in [here](https://github.com/dmlc/xgboost/issues/3322#issuecomment-389727564).)

**Comment by RAMitchell** [comment]
@hcho3 Yes I believe so. I am testing this on Jenkins by running the GPU compiled wheels in a container without cuda. You should be able to easily grab one of the wheels off Jenkins and try it on your own machine.

**Comment by CodingCat** [comment]
we are going to have a major changes on xgboost4j-spark, are we open to make it as 0.8 (include some breaking changes) ?

**Comment by CodingCat** [comment]
the code are currently in spark_dev_do_not_delete branch

**Comment by CodingCat** [comment]
nvm, we will put the code in the next release

**Comment by hcho3** [comment]
@CodingCat Okay, let's shoot for releasing 0.80 for the next release date (August 1, 2018).

**Comment by hcho3** [comment]
I will merge this PR as soon as the tests pass.

**Comment by hcho3** [comment]
@RAMitchell I'd like to do some test runs on the GPU binary wheel before I upload it to PyPI. Does a binary built with CUDA 9.1 runs on machines with older CUDA toolkits?

**Comment by RAMitchell** [comment]
@hcho3 I think it should depend on drivers not the toolkit. In any case some gpu support should be better than none. We should announce it as experimental for gpus. The cpu only code should be unaffected regardless.

**Pull request merged**
