### PR TITLE
Compress fatbins

### PR DESCRIPTION
**Pull request by ajschmidt8**
This PR contains some cherry-picked commits from the `rapidsai` fork. The changes include:

- Adding some `CMake` changes to compress fatbins

### CODE REVIEW

**Comment by trivialfis** [comment]
> Updating the CXX & CUDA standard

I'm afraid that's problematic for a minor version release (next release is 1.6).  We are not ready for an upgrade to the entire toolchain yet.

@hcho3 @RAMitchell

**Review by trivialfis — COMMENTED** [review]
Aside from the cxx version upgrade, the change looks good to me.

**Comment by ajschmidt8** [comment]
No problem. I will remove the commit that updates the toolchain.

**Comment by ajschmidt8** [comment]
Done

**Review by trivialfis — APPROVED** [review]
Thanks for the PR

**Pull request merged**
