### PR TITLE
More Pandas dtypes and more flexible variable naming

### PR DESCRIPTION
**Pull request by JohanManders**
- Pandas DataFrame supports more dtypes than 'int64', 'float64' and 'bool', therefor added a bunch of extra dtypes for the data variable.
- From now on the label variable can be a Pandas DataFrame with the same dtypes as the data variable or it can be a numpy.ndarray
- If the label is a Pandas DataFrame, it will be converted to float.
- If no feature_types is set, the data dtypes will be converted to 'int', 'float' or 'i' (bool).
- ~~If data is Pandas DataFrame, feature_names passed through will be ignored and overwritten by the column names of the Pandas DataFrame.~~
- The feature_names may contain every character except [, ] or <
- List of possible dtypes: 
 - 'int8', 'int16', 'int32', 'int64'
 - 'uint8', 'uint16', 'uint32', 'uint64'
 - 'float16', 'float32', 'float64'
 - 'bool'

An example to test various changes:
```python
import xgboost as xgb
import pandas as pd

col_1 = [76.1, 44, 20.4, 42, 74, 73, 6, 57, 59.224, 26, 64, 28, 99, 90.8, 40, 77, 14, 2, 97, 33]
col_2 = [62, 31, 51, 19, 1.4, 80, 74, 15.22, 42, 26, 29.7, 95, 2, 99, 12.87, 58, 30, 68, 92, 45]
col_3 = [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0]
target = [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0]

# X and y both DataFrames.
# X uses column names with an underscore
X = pd.DataFrame({'COL_1':col_1,
                  'COL_2':col_2,
                  'COL_3':col_3})
y = pd.DataFrame({'TARGET':target})

# Testing different types
# All three can be 'int8', 'float16', 'uint32' etc.
X['COL_1'] = X['COL_1'].astype('uint8')
X['COL_2'] = X['COL_2'].astype('float32')
X['COL_3'] = X['COL_3'].astype('bool')

# Testing a vary strange column name
strange_column_name = 'v3Ry_$t@ng3 N@m3'
X.rename(columns={'COL_1':strange_column_name}, inplace=True)

X_train = X[0:15]
X_test = X[15:20]

# Can be a numpy.ndarray when using y_train = y[0:15].values
y_train = y[0:15]

param_dist = {'objective':'binary:logistic', 'n_estimators':2}

clf = xgb.XGBModel(**param_dist)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(y_pred)
```

### CODE REVIEW

**Comment by JohanManders** [comment]
@tqchen I have a few questions about the two errors I get when using test_basic.py on the new code:

- The first error is because you could now use all characters, except [ ] and <. Are you alright with that and should I change the test_basic.py file?
- The second error is that the feature_types that are coming back, are not 'int', 'q', 'i'. To try to be consistent, I changed all 'q' and all 'i' to 'int'. Is there a reason to also want to use 'q' and 'i' in Python?

```
======================================================================
FAIL: test_dmatrix_init (__main__.TestBasic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\python\xgboost-master\tests\python\test_basic.py", line 47, in test_dmatrix_init
    feature_names=['a', 'b', 'c', 'd', 'e=1'])
AssertionError: ValueError not raised
```
And
```
======================================================================
FAIL: test_pandas (__main__.TestBasic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\python\xgboost-master\tests\python\test_basic.py", line 104, in test_pandas
    assert dm.feature_types == ['int', 'q', 'i']
AssertionError
```

Thanks!

**Comment by tqchen** [comment]
I think the major reason of using q, i is to be consistent with c++ side's feature name specification. I think we can use the more intuitive names, as long as things are consistent, and translation is done properly

**Comment by JohanManders** [comment]
- This code: ```mapper = {'int64': 'int', 'float64': 'q', 'bool': 'i'}``` converts a 'float64' to a 'q', which is a 'long long' in C and an 'integer' in Python (and apparently a '__int64' on Windows). I think a float should stay a float, don't you?

- And the 'bool' converts to an 'i', which is an 'int' in C and Python. Why not use 'int' like the 'int64'? I think it will keep the variable types consistent in Python if we only use 'int' and 'float'.

**Comment by tqchen** [comment]
Yes, I think we can go with int and float and bool

Note that the c++ side accepts only i, q and int. for now.  c.f. https://github.com/dmlc/xgboost/tree/master/demo/binary_classification#dump-model

So some of these conversions may have to be with c++ side. Either do the conversion on python side, or change the defs of c++ side later

**Comment by JohanManders** [comment]
It is up to you. If you would commit the changes all types of **int and bool** become **int**, all types of **float** become **float**. As far as I can tell it runs fine with all the changes.

The dump-model seems to work fine and dumps a nice model with the Pandas column names:
```python
import xgboost as xgb
import pandas as pd

col_1 = [76.1, 44, 20.4, 42, 74, 73, 6, 57, 59.224, 26, 64, 28, 99, 90.8, 40, 77, 14, 2, 97, 33]
col_2 = [62, 31, 51, 19, 1.4, 80, 74, 15.22, 42, 26, 29.7, 95, 2, 99, 12.87, 58, 30, 68, 92, 45]
target = [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0]

X = pd.DataFrame({'COL_1':col_1,
                  'COL_2':col_2})
y = pd.DataFrame({'TARGET':target})

X['COL_1'] = X['COL_1'].astype('float32')
X['COL_2'] = X['COL_2'].astype('int16')

X_train = X[0:15]
X_test = X[15:20]

y_train = y[0:15]

dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test)

param = {'max_depth':2, 'eta':1, 'silent':1, 'objective':'binary:logistic' }
num_round = 2

bst = xgb.train(param, dtrain, num_round)

bst.dump_model('dump.nice.txt')
```
Content 'dump.nice.txt':
```
booster[0]:
0:[COL_1<4.5] yes=1,no=2,missing=1
	1:leaf=0
	2:[COL_1<4.5] yes=3,no=4,missing=3
		3:leaf=0
		4:leaf=0.315789
booster[1]:
0:[COL_1<4.5] yes=1,no=2,missing=1
	1:leaf=0
	2:[COL_1<4.5] yes=3,no=4,missing=3
		3:leaf=0
		4:leaf=0.0698864
```

**Comment by tqchen** [comment]
The change of c++ side might affect some other packages such as R, so we want to do it more carefully.  I think we can switch the names in python side first, and remaps them when calling into the dump API. Can you do that?

**Comment by JohanManders** [comment]
Sorry, I don't know what you are asking... Without changing anything on the c++ side, it seems to work fine with the changes I made.

- I have not changed anything to the dump_model and the get_dump functions, they work perfectly as they are, also (even better) when using a pandas DataFrame.
- The changes I made to the _maybe_from_pandas function changes all the 'q' and 'i' references to 'int' and 'float'.
- The only line that still has a reference to 'q' is: ```ftype = from_pystr_to_cstr(['q'] * flen)``` on line 940 of the core.py file. I think this needs to stay this way to convert a list of Python str to C pointer.

On my side one question remains, should the test_basic.py file be edited? If so by me or you?

**Comment by sinhrks** [comment]
@JohanManders  "i" is not for "int", it's "indicator variable" likely to be ``bool``. From my understanding, feature type only for specifying output dump string format, irrelevant from actual data types. You can see my gist how each feature type affect to the output (node label).

https://gist.github.com/sinhrks/cc9a88f74074fc296e12#file-add_featuretypes-ipynb

This closes #534.

**Comment by JohanManders** [comment]
@sinhrks Thanks for testing that!

Based on your tests, it seems that ```i``` is used for ```bool```, ```int``` can be used for ```int``` and both ```q``` and ```float``` can be used for a ```float```. Too bad the c++ side doesn't recognize ```bool```, but ```int``` and ```float``` work fine.

I have changed my code.

**Comment by tqchen** [comment]
I would like to check update status on this. Can you make the changes such that the current testcase pass? Or update the testcases if it is proposed new behavior?

**Comment by JohanManders** [comment]
@tqchen I have updated the testcases so that a float can stay a float and = is a legal character for a feature_name, but < is not.

I double checked everything and I think these changes are an improvement.

**Comment by terrytangyuan** [comment]
@JohanManders Can you rebase to resolve some conflicts and try again so that the errors are more obvious?

**Comment by JohanManders** [comment]
@terrytangyuan I thought it was easier to make the adjustments to my master branch (https://github.com/JohanManders/xgboost), because this branch keeps having errors. Could you close this pull request and make a new pull request from my master branch? Let me know what you think.

**Comment by terrytangyuan** [comment]
Yeah feel free to work on your own forked repo and open a new PR whenever it's ready.

**Comment by JohanManders** [comment]
Opened a new PR with the changes: https://github.com/dmlc/xgboost/pull/597
Thanks @terrytangyuan!

**Pull request closed without merging**
