### PR TITLE
[WIP] build xgboost4j with docker

### PR DESCRIPTION
**Pull request by CodingCat**
As the first step to publish xgboost4j to maven, we need some cross-build environment...

At this moment, we focus on providing the Linux version

### CODE REVIEW

**Comment by superbobry** [comment]
FYI I have a working Mac/Linux/Windows build in [criteo-forks/xgboost-jars](https://github.com/criteo-forks/xgboost4j-jars). It doesn't use Docker and relies on Travis and Appveyor environments instead.

Which configuration you plan to provide for the JARs? HDFS/S3/Azure/OpenMP?

**Comment by CodingCat** [comment]
you mean the version of HDFS, and if it supports S3/OpenMP, and how about Azure?

**Comment by superbobry** [comment]
Yep, sorry for bad wording. The question is what feature set do you intend to provide for the "official" JAR.

A minor sidenote: the earlist version of glibc we can get on Travis is 2.15. This could be an issue for older clusters using CentOS6 (and similarly dated distributions). A possible workaround is to bundle glibc of the appropriate version in the JAR and extract it if necessary. Do you think that might be good enough for a PR?

**Comment by CodingCat** [comment]
@superbobry, that would be nice if you can file a PR

regarding the feature set, I think let's first release Spark 2.0.x and Spark 2.1...for OpenMP, I think we would like to include it since users can always `turn it off` by setting `nthread` as 1; for HDFS, I do not think we need to depend on a particular version, right?

for glibc, yes, I would like to include it in our native libraries, just like what rocksdb does

**Comment by CodingCat** [comment]
close it as @superbobry  is actively working on it

**Pull request closed without merging**
