### PR TITLE
[CI] Migrate linters to GitHub Actions

### PR DESCRIPTION
**Pull request by hcho3**
Tracking issue: #5891 

I am moving three linting steps from Jenkins to GitHub Actions: `lint`, `sphinx`, and `doxygen`.

Also, reduce workload of R tests by half, since GitHub Actions has a usage cap per organization and we don't want to get our jobs throttled.

~TODO. Figure out how to run clang-tidy in GitHub Actions.~

### CODE REVIEW

**Comment by hcho3** [comment]
Maybe we should keep the clang-tidy check in Jenkins. Right now, it takes 8 minutes to run the check, and that's with a c5n.4xlarge EC2 instance (16 virtual cores). If we migrate clang-tidy to GitHub Actions, it will take a long time because GitHub Actions allocates only 2 virtual cores for each job.

**Review by trivialfis — APPROVED** [review]

**Comment by trivialfis** [comment]
Minor issue, does it make sense to merge tidy into build step?

**Comment by hcho3** [comment]
@trivialfis Done.

**Comment by trivialfis** [comment]
Thanks!  Looks good to me.

**Pull request merged**
