### PR TITLE
Avoid including `c_api.h` in header files.

### PR DESCRIPTION
**Pull request by trivialfis**

### CODE REVIEW

**Comment by hcho3** [comment]
The name of this pull request is a bit confusing, since we are moving `#include <xgboost/c_api.h>` from headers to sources, not removing them. I'm assuming this is to speed up builds?

**Comment by hcho3** [comment]
In the future, we may want to use pre-compiled headers to speed up builds. [CMake supports it.](https://cmake.org/cmake/help/v3.16/command/target_precompile_headers.html)

**Comment by trivialfis** [comment]
> The name of this pull request is a bit confusing

@hcho3 Yup, let me change it.

> In the future, we may want to use pre-compiled headers to speed up builds

That's mostly for external libraries right?  If you cache your own header it will be slower.  Also nvcc doesn't seem to support it.

**Comment by hcho3** [comment]
> Also nvcc doesn't seem to support it.

Darn, I was about to suggest PCH for Cub and Thrust :(

**Pull request merged**
