### PR TITLE
[jvm-packages] XGBoost4j Windows fixes

### PR DESCRIPTION
**Pull request by Craigacp**
This pull request fixes issue #1491. It switches `bst_ulong` over to `uint64_t`
from `unsigned long` which is a consistent size on all supported 64-bit
platforms. There are small changes to the Makefile and create_jni.bat files to
cope with the different file locations. The JNI wrapper itself has several types
changed over to `jint` from `int`, and a few casts. It also adds an ifdef for
MacOS as there Java defines `jlong` to be `long int`, and gcc defines `int64_t`
to be `long long int`, which despite both of them being 64-bit integers are
different types. I tested this against the Java & Scala unit tests, and also
that the Python & R libraries built and imported successfully on Windows (7 and
10, MingW64 gcc 5.3), Linux (Ubuntu 16.04 and RHEL7) and MacOS (10.11 with
Macports GCC 5.3).

The correct build procedure on Windows for the JVM packages is now to run
"mingw32-make jvm" before running the maven build inside jvm-packages. This
still has issues if the JAVA_HOME path has spaces in it, so make sure these are
escaped or the path doesn't have spaces.

This pull request doesn't currently update any documentation, but I'm happy to
do that as necessary.

### CODE REVIEW

**Comment by CodingCat** [comment]
@Craigacp thanks for the PR, I will give a review tomorrow

BTW, would you mind rebasing with master branch?

**Comment by CodingCat** [comment]
it seems that the Travis test haven't been triggered correctly, would you mind sync with the master branch to trigger that?

**Comment by Craigacp** [comment]
Sure. It'll take me a couple of days, I'm away from my Windows build environment at the moment, and the changes to XGDMatrixCreateFromCSR look like the kind of thing I'll need to rebuild to test.

**Comment by Craigacp** [comment]
After rebasing this is now pull request #1639, because my GitHub skills are a bit rusty.

**Pull request closed without merging**
