### PR TITLE
Release version 0.80

### PR DESCRIPTION
**Pull request by hcho3**
This is part of regular bi-monthly release cycle of core lib (#3252).

Code freeze: The 0.80 release will include all commits up to **August 9, 2018**.
Release Date: **August 10, 2018**.

TODOs
- [x] Merge #3532
- [x] Merge #3535 
- [x] Merge #3546 
- [x] Merge #3563: to correct my prior mistake
- [x] Merge #3567: include JVM doc build script in the Jenkins CI
- [x] Write release notes

### CODE REVIEW

**Comment by hcho3** [comment]
@CodingCat I have a favor to ask: can you write a summary of what's new in 0.80? I noticed that JVM packages have been re-factored significantly. Can you describe your design decisions?

**Comment by CodingCat** [comment]
@hcho3 , sure, will send it to you today

**Comment by CodingCat** [comment]
@hcho3 

# New Features in XGBoost4J-Spark 0.8

To consolidate the APIs and improve the user experience, we refactored the design of XGBoost4J-Spark in 0.8 in a significant manner:

* consolidated APIs: we removed the APIs like transformLeaf() in 0.8- versions, and users can control behaviors like output leaf prediction results by setting corresponding column names. With this approach, it is much easier to integrate XGBoost models into a Spark ML pipeline.
* better user experience: we refactored the parameters relevant modules in XGBoost4J-Spark to provide both camel-case (Spark ML style) and underscore (XGBoost style) parameters 

More details can be found in [XGBoost4J-Spark 0.8 Tutorial](https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html) and [XGBoost4J-Spark API Docs](https://xgboost.readthedocs.io/en/latest/jvm/scaladocs/xgboost4j-spark/index.html#package)

**Comment by hcho3** [comment]
@CodingCat Thanks! When you say "0.8- versions", do you mean all previous versions?

**Comment by CodingCat** [comment]
Yes

**Comment by hcho3** [comment]
Also, the removal of `trainWithDataframe()` / `trainWithRDD()` is part of API consolidation?

**Comment by hcho3** [comment]
To consolidate the APIs and improve the user experience, we refactored the design of XGBoost4J-Spark in 0.8 in a significant manner:

* Consolidated APIs: It is now much easier to integrate XGBoost models into a Spark ML pipeline. 
Users can control behaviors like output leaf prediction results by setting corresponding column names. Training is now more consistent with other Estimators in Spark MLLIB: there is now one single method `fit()` to train decision trees.

* Better user experience: we refactored the parameters relevant modules in XGBoost4J-Spark to provide both camel-case (Spark ML style) and underscore (XGBoost style) parameters

**Comment by hcho3** [comment]
Now re-basing `release_0.80` against the current `master`. The 0.80 release has now been finalized. I'll write a release note tonight.

**Pull request merged**
