### PR TITLE
Polishing API + wording in function description #Rstat

### PR DESCRIPTION
**Pull request by pommedeterresautee**

### CODE REVIEW

**Comment by pommedeterresautee** [comment]
@tqchen I have an error on some Python code.
I don t touch Python part. Any idea?

**Comment by pommedeterresautee** [comment]
https://travis-ci.org/dmlc/xgboost/jobs/93959908

**Comment by tqchen** [comment]
Seems due to python part convention break @terrytangyuan

**Comment by tqchen** [comment]
@pommedeterresautee Feel free to merge in this one as long as other tests pass

**Comment by terrytangyuan** [comment]
I haven't got a chance to look into it yet but it seems like @pommedeterresautee didn't touch any python code. @pommedeterresautee Feel free to comment out the link task in travis and merge this for now.

**Comment by pommedeterresautee** [comment]
@terrytangyuan Is that ok if I let Travis like that. I just merge? 
If tests fail, it needs to be reminded, don t you think?

**Comment by terrytangyuan** [comment]
Sure but it just will look bad for visitors. It's only minor issue. I've disabled py lint test on master. Feel free to merge when you are ready.

**Comment by pommedeterresautee** [comment]
Thanks @terrytangyuan , got my green mark!

**Pull request merged**
