### PR TITLE
Hide symbols in CI build + hide symbols for C and CUDA

### PR DESCRIPTION
**Pull request by trivialfis**
Recently I ran into an issue where `cub::DeviceRadixSort` runs into a cuda invalid value error when used with cuDF.  I believe it's due to mixed C++ symbols exported from both libraries.  ~This might also be the cause of https://github.com/rapidsai/cudf/issues/7722~.  This PR enables "hidden" visibility for all c++ symbols by default on our CI build.

### CODE REVIEW

**Comment by trivialfis** [comment]
@hcho3 Now I'm thinking maybe we set it to default in CMake option?

**Review by hcho3 — APPROVED** [review]

**Comment by trivialfis** [comment]
@hcho3 Could you confirm that this will change our nightly build?

**Comment by hcho3** [comment]
@trivialfis The nightly build already uses `-DHIDE_CXX_SYMBOLS=ON`. Setting `C_VISIBILITY_PRESET` and `CUDA_VISIBILITY_PRESET` will help.

**Comment by trivialfis** [comment]
Thanks @hcho3 !

**Pull request merged**
