### PR TITLE
Serialize expand entry for allgather.

### PR DESCRIPTION
**Pull request by trivialfis**

### CODE REVIEW

**Comment by trivialfis** [comment]
cc @rongou

**Review by rongou — COMMENTED** [review]
Overall looks good, but aren't you worried about the size blowup with JSON? Especially with federated learning when the data may need to be shipped over relatively slow internet connections.

**Comment by trivialfis** [comment]
If the performance becomes a problem, we can shrink the size of the JSON object to plain binary by removing object key strings and packing everything into an array, XGB can work with binary JSON.

**Comment by trivialfis** [comment]
On the other hand, I think GPU cat is ot yet supported, correct me if I'm wrong. I couldn't find the synchronization for GPU cat bits.

**Comment by rongou** [comment]
> If the performance becomes a problem, we can shrink the size of the JSON object to plain binary by removing object key strings and packing everything into an array, XGB can work with binary JSON.

Fair enough.

> On the other hand, I think GPU cat is ot yet supported, correct me if I'm wrong. I couldn't find the synchronization for GPU cat bits.

I'm not sure. We do have some tests for category features, maybe they are not exhaustive enough.

**Review by rongou — APPROVED** [review]

**Pull request merged**
