### PR TITLE
Performance optimizations for Intel CPUs

### PR DESCRIPTION
**Pull request by SmirnovEgorRu**
In this [issue](https://github.com/hcho3/xgboost-fast-hist-perf-lab/issues/15) some performance optimizations for multi-core CPUs were offered.
I prepared these as a pull-request. Also, I added SW prefetching, which helps to improve performance additionally.
It was tested for HIGGS data set (1m x 28) in comparison with [Intel® DAAL](https://github.com/intel/daal).

|   | Intel® DAAL | Current XGBoost  | Proposed changes |
|---|---|---|---|
| Time, ms |  1344 | 8600 | 4238 |

HW: Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz (2 sockets, 14 cores per socket).

Parameters: 
"objective": "binary:hinge", "max_depth": "6", "eta": "0.3", "min_child_weight": "0" (DAAL's analog: minObservationsInLeafNode=0), "tree_method", "hist", "n_estimators": "50"

Accuracy before and after my changes - the same: 72.306801.

Some additional optimizations can be done: e.g. parallelization by nodes, optimization of "ApplySplit" functions.

### CODE REVIEW

**Comment by hcho3** [comment]
Thanks a lot for assembling this pull request. I will review it and make fixes to pass CI tests.

In the longer run, we can also tweak compiler flags to take advantage of latest features of Intel CPUs. Not all of these flags can be merged into the master CMake build due to compatibility reasons, but we can make a special pre-built binary distribution for AWS C5 instances (which has AVX512).

**Comment by hcho3** [comment]
@RAMitchell I recall you mentioning some failure cases that was triggered by using single-precision float for the accumulator variable. Can you share some examples?

**Comment by RAMitchell** [comment]
Looks like it may be okay after some experimentation with large datasets. I am not sure how I reached the previous conclusion.

|                                 | ('YearPredictionMSD', 'Time(s)') | ('YearPredictionMSD', 'Train RMSE') | ('YearPredictionMSD', 'Test RMSE') | ('Synthetic', 'Time(s)') | ('Synthetic', 'Train RMSE') | ('Synthetic', 'Test RMSE') | ('Higgs', 'Time(s)') | ('Higgs', 'Train Accuracy') | ('Higgs', 'Test Accuracy') | ('Cover Type', 'Time(s)') | ('Cover Type', 'Train Accuracy') | ('Cover Type', 'Test Accuracy') | ('Bosch', 'Time(s)') | ('Bosch', 'Train Accuracy') |
|---------------------------------|----------------------------------|-------------------------------------|------------------------------------|--------------------------|-----------------------------|----------------------------|----------------------|-----------------------------|----------------------------|---------------------------|----------------------------------|---------------------------------|----------------------|-----------------------------|
| xgb-gpu-hist (single precision) | 18.9042                          | 7.80142                             | 8.88601                            | 23.2389                  | 13.369                      | 13.5223                    | 18.9742              | 0.750733                    | 0.747206                   | 64.3457                   | 0.909576                         | 0.892335                        | 12.8371              | 0.995123                    |
| xgb-gpu-hist (double precision) | 18.8883                          | 7.79193                             | 8.88281                            | 24.439                   | 13.3822                     | 13.5334                    | 23.429               | 0.750603                    | 0.747163                   | 67.2516                   | 0.908491                         | 0.891793                        | 12.0918              | 0.995085                    |

**Comment by trivialfis** [comment]
@RAMitchell The change happens within    CPU histogram, if one change GradStat to float some tests should fail.

**Comment by SmirnovEgorRu** [comment]
@hcho3 can we use different types of GHistEntry for GPU and CPU?
Now I'm collecting data for case with double precision for GHistEntry. I will send result soon.

**Comment by SmirnovEgorRu** [comment]
Also, I measured for case when GHistEntry contains doubles (as in source code) instead of floats:

||Intel® DAAL | Current XGBoost | Proposed changes (float) | Proposed changes (double) |
|--|-- |--|--|--|
|Time, ms | 1344 | 8600 | 4238| 4455|

Performance gain from usage of float is not significant, so it doubles can be used here.

**Comment by hcho3** [comment]
@SmirnovEgorRu I don't think GHistEntry is parameterized, so currently, no. We'll merge it once the tests pass.

**Comment by hcho3** [comment]
@SmirnovEgorRu Let me know if you need help passing the CI.

**Comment by SmirnovEgorRu** [comment]
@hcho3, looks like it is passed now.
Can we commit it?

**Comment by SmirnovEgorRu** [comment]
@hcho3, yes, you can update, of course.
Do I need to do something here from my side?

**Comment by hcho3** [comment]
@SmirnovEgorRu Make sure to check on "Allow Edits from Maintainers"

**Comment by Denisevi4** [comment]
> Looks like it may be okay after some experimentation with large datasets. I am not sure how I reached the previous conclusion.
> 
> ('YearPredictionMSD', 'Time(s)')	('YearPredictionMSD', 'Train RMSE')	('YearPredictionMSD', 'Test RMSE')	('Synthetic', 'Time(s)')	('Synthetic', 'Train RMSE')	('Synthetic', 'Test RMSE')	('Higgs', 'Time(s)')	('Higgs', 'Train Accuracy')	('Higgs', 'Test Accuracy')	('Cover Type', 'Time(s)')	('Cover Type', 'Train Accuracy')	('Cover Type', 'Test Accuracy')	('Bosch', 'Time(s)')	('Bosch', 'Train Accuracy')
> xgb-gpu-hist (single precision)	18.9042	7.80142	8.88601	23.2389	13.369	13.5223	18.9742	0.750733	0.747206	64.3457	0.909576	0.892335	12.8371	0.995123
> xgb-gpu-hist (double precision)	18.8883	7.79193	8.88281	24.439	13.3822	13.5334	23.429	0.750603	0.747163	67.2516	0.908491	0.891793	12.0918	0.995085

@RAMitchell May I ask how do you run gpu hist with double precision? Thanks

**Comment by SmirnovEgorRu** [comment]
@hcho3 any news here?
Can I help here? With defines or something else.

**Comment by hcho3** [comment]
@trivialfis FYI, this is another reason why we should prefer CMake over Makefile, since CMake lets us explicitly test the existence of specific compiler intrinsics such as `_mm_prefetch` and `__builtin_prefetch`. With Makefile, we'll have to be overly conservative when adopting compiler intrinsics because we can't test their existence.

**Comment by hcho3** [comment]
@trivialfis Can you take a look at this PR to see if it can be made compatible with your PR #3825?

**Comment by trivialfis** [comment]
@hcho3 Please ignore  #3825 and go ahead finishing this PR.  I will take care of the remaining rebase.  After all this one is more important I think.

**Comment by SmirnovEgorRu** [comment]
@hcho3  @trivialfis Do we need to do smt new to push it?

**Comment by hcho3** [comment]
@SmirnovEgorRu I went ahead and merged the pull request. I will follow up with some unit tests later.

**Comment by Laurae2** [comment]
@SmirnovEgorRu @hcho3 I'll get a look at benchmarking pre-post this PR on my 72 thread server (Dual Xeon 6154).

Will be using a2dc929 (pre) and 5f151c5 (post).

**Pull request merged**
