### PR TITLE
Fix test_gpu_coordinate.

### LINKED ISSUE #3961: linear test doesn't really use GPU
https://github.com/dmlc/xgboost/blob/master/tests/python-gpu/test_gpu_linear.py#L19

This sets the updater to coord_descent, and I notice when doing tests on bigger data that the GPU has memory allocated but usage is very low during the test.  However, if I set updater to gpu_coord_descent, then the GPU memory is allocated *and* the usage is at least 30% or so for the otherwise identical run.

@RAMitchell

### PR DESCRIPTION
**Pull request by trivialfis**
* Use `gpu_coord_descent` in test.
* Reduce number of running rounds.

closes #3961 .

### CODE REVIEW

**Comment by trivialfis** [comment]
It's really a good time to look at memory usage now.  The odds of passing Travis Python test at the first time is so low ...

**Comment by trivialfis** [comment]
@hcho3 Hi, could you please help getting some hints on why MGPU tests got stuck on Jenkins?  I tried many times and it keep stopping at `test_gpu_updaters.py::TestGPU::test_gpu_hist_mgpu`.  The tests runs perfectly on my end.
Thanks.

**Comment by trivialfis** [comment]
@hcho3 I think I might found a memory access bug in gpu coordinate, please don't look into this for now.

**Comment by trivialfis** [comment]
@hcho3 Jenkins' down?

**Comment by hcho3** [comment]
@trivialfis I restarted the test.

**Comment by trivialfis** [comment]
@hcho3 Thanks!

**Comment by trivialfis** [comment]
Sign ..  Now the appveyor ...

**Pull request merged**
