### PR TITLE
[Python] Accept numpy generators as `random_state`

### PR DESCRIPTION
**Pull request by david-cortes**
This PR modifies the scikit-learn interface to accept numpy generators as possible inputs for `random_state`. Generators are now the recommended mechanism for drawing random numbers in numpy, while the previous `RandomState` is deprecated. Lots of other software like SciPy have moved towards the new `Generator` class and allow passing a `random_state` as either `int`/`RandomState`/`Generator` ([example](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.random.html)).

### CODE REVIEW

**Review by trivialfis — APPROVED** [review]
Thank you for the work on rng!

**Comment by trivialfis** [comment]
Hi, could you please help take a look into the CI errors? Feel free to ping me if there's anything I can help.

**Comment by david-cortes** [comment]
> Hi, could you please help take a look into the CI errors? Feel free to ping me if there's anything I can help.

This is the message I managed to find:
> XFAIL tests/python/test_with_modin.py::TestModin::test_modin

The PR didn't touch anything that would deal with modin so don't know the reason for the failure.

**Comment by trivialfis** [comment]
> This is the message I managed to find:

Hmm, not sure where did you see the modin error. Here are the ones I see on github action:

https://github.com/dmlc/xgboost/actions/runs/6719062791/job/18259950760?pr=9743
https://github.com/dmlc/xgboost/actions/runs/6719062791/job/18259951139?pr=9743
https://github.com/dmlc/xgboost/actions/runs/6719062791/job/18259950609?pr=9743

**Comment by david-cortes** [comment]
Thanks for the hints. Fixed now.

**Pull request merged**
