### PR TITLE
[jvm-packages] Change the phase of exec maven plugin

### PR DESCRIPTION
**Pull request by CodingCat**
@hcho3 this would avoid compiling native libs for doc generation

### CODE REVIEW

**Comment by hcho3** [comment]
Thanks!

**Comment by hcho3** [comment]
So the native lib would be compiled for `mvn package` or `mvn compile` but not `mvn scala:doc`?

**Comment by CodingCat** [comment]
Exactly

**Comment by hcho3** [comment]
I still have to `mvn install` before `mvn scala:doc` because XGBoost4J-Spark depends on XGBoost4J and the former tries to locate the latter from the local Maven repository. Anyway out of this?

**Comment by CodingCat** [comment]
ah, I know why it works in my side, because I once installed the package locally

I don't have a good solution for now....

**Comment by hcho3** [comment]
@CodingCat It's not a show stopper, so I'll go ahead and merge the current PR as is. Closing this PR for now.

**Pull request closed without merging**
