### PR TITLE
revert shallow submodule for cub

### PR DESCRIPTION
**Pull request by khotilov**
per discussion in #2572

### CODE REVIEW

**Comment by RAMitchell** [comment]
Any reason not to merge this yet?

**Comment by khotilov** [comment]
@RAMitchell I'm on vacation, travelling... could you please add an approval review (github tells me that it's required to merge on the phone)

**Comment by earthling4** [comment]
Same here

**Comment by khotilov** [comment]
@RAMitchell there seems to be some reshuffling happening in the cub repo (maybe they are addressing the NVlabs/cub/issues/94 issue that you've raised?). There's no more f3937a96fdec78a73446aaaa114c112ff31f5503 commit which the cub submodule is currently tied to, but it seems like it has been replaced with d5d70e26f6cc247dcf93ddaece555d4b792e579c a day or so ago NVlabs/cub/pull/92 , and the size of a checked out cub repo is right now 25M. I'll push a PR to update the hash reference for cub.

**Comment by khotilov** [comment]
However, when comparing *using github* the two commits that I've mentioned above, there are lots of differences: https://github.com/NVlabs/cub/compare/f3937a96fdec78a73446aaaa114c112ff31f5503...d5d70e26f6cc247dcf93ddaece555d4b792e579c
So, I am now not sure what was happening in that repo... If you find that d5d70e2 is safe to use, could you please update the reference?

**Comment by RAMitchell** [comment]
I have updated the reference to the latest so git clone recursive now works. There is still a problem however with compiling the GPU version due to a change in cub that looks like a mistake.

**Comment by earthling4** [comment]
2017-08-13 20:32:05Z | Cloning into 'cub'...
-- | --
2017-08-13 20:32:05Z | fatal: reference is not a tree: f3937a96fdec78a73446aaaa114c112ff31f5503

**Comment by earthling4** [comment]
It still doesn't work for me

**Comment by lichangW** [comment]
it still doesn't work for me

**Pull request merged**
