### PR TITLE
added code for instance based weighing for rank objectives

### PR DESCRIPTION
**Pull request by ngoyal2707**
This PR uses sample_weights per list instance for all the ranking objectives. This is somewhat important for some use cases where in production systems we want to give more weights for some sample instance compared to other. (In this case, sample instance is query entire document set).

Testing Done:
1) Used python wrapper to train on weighted loss and evaluate on weighted loss. Performs much better than just training on unweighted loss.
usage:
`train_data_xgboost.set_weight(train_pairs_weight)`

The weights need to be normalized externally as per current implementation as following:
```
train_pairs_weight /= train_pairs_weight.sum()
train_pairs_weight *= train_pairs_weight.shape[0]
```
which is essentially doing:
w_i = w_i*N / (sum (w_i))

If you think I should do the normalization inside the source code, let me know, I can easily change the PR with that.  

EDIT:
This PR should resolve both of following issues:
https://github.com/dmlc/xgboost/issues/2460
https://github.com/dmlc/xgboost/issues/2561

### CODE REVIEW

**Comment by ngoyal2707** [comment]
Hey @hcho3 , @tqchen : wonder if you guys can take a look at this and give your opinions.

**Comment by ngoyal2707** [comment]
@hcho3 Thanks for looking into the PR, as per your comments I have added changes with:

1) Put weight normalization inside the rank_obj.cc, so there's no need of externally normalize them.
2) Added tests showing that putting weights works with "rank:pairwise" objective.

Questions:
1) Is there any alternative to looping over whole dataset serially to find sum_weights inside GetGradients as it seems like it should be done only once, although I saw that other objectives were following the same  https://github.com/dmlc/xgboost/blob/master/src/objective/regression_obj.cc#L219 , so guess it's not too slow? 


Side Note:
1) I think there's a small bug (or weirdness) with the implementation of how rank_obj.cc creates pairs. It can technically create same pair twice as the way [loop](https://github.com/dmlc/xgboost/blob/master/src/objective/rank_obj.cc#L77) is written, it never checks for pair already added. I don't think it will make much difference, but do you think it is intentional vs needs to be corrected?

**Comment by ngoyal2707** [comment]
@hcho3 your changes of doing weight normalization looks good to me. Can you please merge them to master now?

**Comment by hcho3** [comment]
@ngoyal2707 I ended up removing my latest change. The normalization factor would need to be re-computed whenever the objective function object is re-used for a different dataset, and I could not find a good way to detect the change of dataset. For now, I think we should just compute the normalization factor to be on the safe side.

**Comment by ngoyal2707** [comment]
@hcho3 I see, good point, sorry I didn't catch that. 
Can you please merge my original request then? I can look into the if I can move that to constructor as follow up refactor.

**Comment by hcho3** [comment]
@ngoyal2707 Yes, I will merge it once all tests pass.

**Comment by ejalonas** [comment]
One dumb question @ngoyal2707, can you clarify the structure of the `train_pairs_weight` in your initial example? Are those weights based on a group of results, or on each result within a group (e.g. if I have DMatrix with 5 groups of 10 results a piece for pairwise ranking, when I go to set the weights, is the structure of it an array of 5 floats (weighting per group), and array of 50 entries (weighting each result) or an array of len 5 where each entry is an array of len 10 (weighting each result again).

**Comment by ngoyal2707** [comment]
Hey @ejalonas , In my implementation `train_pairs_weight` is  at group level. So for your example of `5` groups of `10` results each, you will need to give `5` weights. 

If you want individual instance based weight, you can use `rank:ndcg` objective with giving magnitude of `label` as your weights, although `ndcg` scaling from magnitude of `label` to `weight` is not linear.
Currently "rank:pairwise" objective ignores magnitude of `label.

**Comment by ejalonas** [comment]
Thanks @ngoyal2707 ! I really appreciate your clarification and contribution to this repo.

**Comment by sunlei198911** [comment]
@ngoyal2707 r  which release version will begin to support the group weight?

**Pull request merged**
