### PR TITLE
[python-package] ctypes2numpy supports more dtypes

### PR DESCRIPTION
**Pull request by sperlingxx**

### CODE REVIEW

**Comment by trivialfis** [comment]
Is XGBoost returning these types from C APIs?

**Comment by sperlingxx** [comment]
@trivialfis  So far, there isn't. I want to make it more generally, so it can be used as a general util.

**Comment by trivialfis** [comment]
I will merge it when there's an actual use case.  Otherwise XGBoost returning one of added types is considered as a bug.  Also I have been trying to narrow the range of used types, dynamically casting types is dangerous and expensive.

**Comment by sperlingxx** [comment]
@trivialfis  Fine, I closed this.

**Comment by trivialfis** [comment]
@sperlingxx Thanks for the effort.

**Pull request closed without merging**
