### PR TITLE
Add device memory usage profiling.

### PR DESCRIPTION
**Pull request by trivialfis**
This is another small step toward optimizing memory usage of gpu_hist method.  There might be a better way to handle the backtrace information instead of printing everything.  Suggestions are welcomed.

### CODE REVIEW

**Comment by hcho3** [comment]
@trivialfis I'm curious, what is the benefit of building a custom monitor as supposed to using `nvprof`?

**Comment by trivialfis** [comment]
@hcho3 It's really strange that I am able to find all the really detailed information by using nvprof , but memory usage.

**Comment by hcho3** [comment]
@trivialfis So `nvprof` doesn't give you memory usage information?

**Comment by trivialfis** [comment]
@hcho3 As far as I know, it doesn't.

**Comment by hcho3** [comment]
@trivialfis That's interesting. I now see why you are working on this pull request.

**Comment by trivialfis** [comment]
Some early results for fun.  Generated with `python ./tests/benchmark/benchmark_tree.py --columns=640 --iterations=256`.  Only "GB" level results are copied.

I tried 1200 columns, but combined with swap is still not enough memory for generating the dataset.  After getting this sorted out, I will give _epsilon_ dataset a try, see if we can shrink down some memory usage for datasets like this.

Don't go nuts with the offsets from backtrace,  I'm really having a hard time to get reliable backtrace. Even in the same compilation unit, some functions require -rdynamic while others don't.  On Fedora I could demangle the filename automatically while on Ubuntu I can't even make `addr2line` work correctly.

Any suggestions are welcomed.

> 
> Pointer: 0x7f530024dbec
> 
> Peak: 1.193956 GB
> 
> XGBoosterUpdateOneIter+0x48
> dmlc::StackTrace[abi:cxx11]()+0x53
> ffi_call_unix64+0x4c
> xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*)+0x220
> xgboost::common::DeviceMemoryStat::Allocate(void*, unsigned long)+0xab
> xgboost::gbm::GBTree::CommitModel(std::vector<std::vector<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> >, std::allocator<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> > > >, std::allocator<std::vector<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> >, std::allocator<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> > > > > >&&)+0x2d0
> xgboost::gbm::GBTree::DoBoost(xgboost::DMatrix*, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::ObjFunction*)+0x85b
> xgboost::predictor::DeviceMatrix::DeviceMatrix(xgboost::DMatrix*, int, bool)+0x16a
> xgboost::predictor::GPUPredictor::DevicePredictInternal(xgboost::DMatrix*, xgboost::HostDeviceVector<float>*, xgboost::gbm::GBTreeModel const&, unsigned long, unsigned long)+0xef0
> xgboost::predictor::GPUPredictor::UpdatePredictionCache(xgboost::gbm::GBTreeModel const&, std::vector<std::unique_ptr<xgboost::TreeUpdater, std::default_delete<xgboost::TreeUpdater> >, std::allocator<std::unique_ptr<xgboost::TreeUpdater, std::default_delete<xgboost::TreeUpdater> > > >*, int)+0xad
> 
> 
> Pointer: 0x7faa499dabec
> 
> Peak: 1.193956 GB
> 
> XGBoosterUpdateOneIter+0x48
> dmlc::StackTrace[abi:cxx11]()+0x53
> ffi_call_unix64+0x4c
> xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*)+0x220
> xgboost::common::DeviceMemoryStat::Allocate(void*, unsigned long)+0xab
> xgboost::gbm::GBTree::CommitModel(std::vector<std::vector<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> >, std::allocator<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> > > >, std::allocator<std::vector<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> >, std::allocator<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> > > > > >&&)+0x2d0
> xgboost::gbm::GBTree::DoBoost(xgboost::DMatrix*, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::ObjFunction*)+0x85b
> xgboost::predictor::DeviceMatrix::DeviceMatrix(xgboost::DMatrix*, int, bool)+0x16a
> xgboost::predictor::GPUPredictor::DevicePredictInternal(xgboost::DMatrix*, xgboost::HostDeviceVector<float>*, xgboost::gbm::GBTreeModel const&, unsigned long, unsigned long)+0xef0
> xgboost::predictor::GPUPredictor::UpdatePredictionCache(xgboost::gbm::GBTreeModel const&, std::vector<std::unique_ptr<xgboost::TreeUpdater, std::default_delete<xgboost::TreeUpdater> >, std::allocator<std::unique_ptr<xgboost::TreeUpdater, std::default_delete<xgboost::TreeUpdater> > > >*, int)+0xad
> 
> 
> Pointer: 0x7f289f51cbec
> 
> Peak: 1.193956 GB
> 
> XGBoosterUpdateOneIter+0x48
> dmlc::StackTrace[abi:cxx11]()+0x53
> ffi_call_unix64+0x4c
> xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*)+0x220
> xgboost::common::DeviceMemoryStat::Allocate(void*, unsigned long)+0xab
> xgboost::gbm::GBTree::CommitModel(std::vector<std::vector<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> >, std::allocator<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> > > >, std::allocator<std::vector<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> >, std::allocator<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> > > > > >&&)+0x2d0
> xgboost::gbm::GBTree::DoBoost(xgboost::DMatrix*, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::ObjFunction*)+0x85b
> xgboost::predictor::DeviceMatrix::DeviceMatrix(xgboost::DMatrix*, int, bool)+0x16a
> xgboost::predictor::GPUPredictor::DevicePredictInternal(xgboost::DMatrix*, xgboost::HostDeviceVector<float>*, xgboost::gbm::GBTreeModel const&, unsigned long, unsigned long)+0xef0
> xgboost::predictor::GPUPredictor::UpdatePredictionCache(xgboost::gbm::GBTreeModel const&, std::vector<std::unique_ptr<xgboost::TreeUpdater, std::default_delete<xgboost::TreeUpdater> >, std::allocator<std::unique_ptr<xgboost::TreeUpdater, std::default_delete<xgboost::TreeUpdater> > > >*, int)+0xad

**Comment by trivialfis** [comment]
@hcho3 Hi, do you have any insight on how to force the linking in make file?  Currently the R test failed with:

> dlopen(/Users/travis/build/dmlc/xgboost/xgboost/xgboost.Rcheck/xgboost/libs/xgboost.so, 6): Symbol not found: __ZN7xgboost6common34__dmlc_registry_file_tag_monitor__Ev

One way to solve it is inlining everything, but that will bring a huge burden for compilation, since the printing messages of `Monitor` and `DeviceMemStat` are changed frequently.  An added period mark would force a recompilation of the whole project.

An odd thing I notice is that there are two "_" prefixed to the missing symbol, while there should be only one of it.  If it's something in the makefile I'm missing please let me know.  Otherwise I have to inline all these functions before finishing this PR.  Thanks!

**Comment by trivialfis** [comment]
@hcho3 Thanks! You just save my day.

**Comment by trivialfis** [comment]
Initial result from my simple testing with epsilon dataset (500000 x 2000 dense), with:
```
params = {'n_gpus': -1, 'debug_verbose': 5,
          'tree_method': 'gpu_hist',
          'objective': 'binary:logistic'}
num_boost_round = 256
```

> Device memory usage summary: ===========
> Peak usage: 9.177299 GB.
> Number of allocations: 72 times.

And the biggest memory consumer seems to be the single GPU predictor, which also causes extremely imbalanced memory usage across all GPUs.  Here is the obtained traces for GPU predictor:

```
Pointer: 0x7fedde000000
Peak usage: 5.963445 GB
Traces:
  XGBoosterUpdateOneIter+0x48
  dmlc::StackTrace[abi:cxx11]()+0x53
  ffi_call_unix64+0x4c
  xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*)+0x220
  xgboost::common::DeviceMemoryStat::Allocate(void*, unsigned long)+0x1ec
  xgboost::gbm::GBTree::CommitModel(std::vector<std::vector<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> >, std::allocator<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> > > >, std::allocator<std::vector<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> >, std::allocator<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> > > > > >&&)+0x2d0
  xgboost::gbm::GBTree::DoBoost(xgboost::DMatrix*, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::ObjFunction*)+0x85b
  xgboost::predictor::DeviceMatrix::DeviceMatrix(xgboost::DMatrix*, int, bool)+0x16f
  xgboost::predictor::GPUPredictor::DevicePredictInternal(xgboost::DMatrix*, xgboost::HostDeviceVector<float>*, xgboost::gbm::GBTreeModel const&, unsigned long, unsigned long)+0xef0
  xgboost::predictor::GPUPredictor::UpdatePredictionCache(xgboost::gbm::GBTreeModel const&, std::vector<std::unique_ptr<xgboost::TreeUpdater, std::default_delete<xgboost::TreeUpdater> >, std::allocator<std::unique_ptr<xgboost::TreeUpdater, std::default_delete<xgboost::TreeUpdater> > > >*, int)+0xad
```
We should try it again after #3738 is merged.

**Comment by trivialfis** [comment]
New profiling result with multigpu predictor in place:
[usage.txt](https://github.com/dmlc/xgboost/files/2513050/usage.txt)

**Comment by hcho3** [comment]
@trivialfis Okay, maybe we can come back to it after merging other re-factor PRs.

**Comment by trivialfis** [comment]
@RAMitchell @hcho3  Good news.  The large memory usage from `GPUPredictor::UpdatePredictionCache` in previous profiling is mainly due to I put too much data in `evals={}`.  I don't know why these datasets have caches, but for simple training without evals_set, the memory usage is quite modest.

**Comment by trivialfis** [comment]
Closing for now.

**Pull request closed without merging**
