### PR TITLE
add cmake install target

### PR DESCRIPTION
**Pull request by henrique**
```
henrique@ubuntu:~/dev/xgboost/build$ sudo make install
[ 10%] Built target rabit
[ 28%] Built target dmlccore
[ 96%] Built target objxgboost
[ 98%] Built target libxgboost
[100%] Built target xgboost
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /usr/local/bin/xgboost
-- Installing: /usr/local/lib/libxgboost.so
-- Installing: /usr/local/include/xgboost
-- Installing: /usr/local/include/xgboost/base.h
-- Installing: /usr/local/include/xgboost/c_api.h
-- Installing: /usr/local/include/xgboost/data.h
-- Installing: /usr/local/include/xgboost/feature_map.h
-- Installing: /usr/local/include/xgboost/gbm.h
-- Installing: /usr/local/include/xgboost/learner.h
-- Installing: /usr/local/include/xgboost/logging.h
-- Installing: /usr/local/include/xgboost/metric.h
-- Installing: /usr/local/include/xgboost/objective.h
-- Installing: /usr/local/include/xgboost/tree_model.h
-- Installing: /usr/local/include/xgboost/tree_updater.h
-- Installing: /usr/local/include/rabit
-- Installing: /usr/local/include/rabit/c_api.h
-- Installing: /usr/local/include/rabit/internal
-- Installing: /usr/local/include/rabit/internal/engine.h
-- Installing: /usr/local/include/rabit/internal/io.h
-- Installing: /usr/local/include/rabit/internal/rabit-inl.h
-- Installing: /usr/local/include/rabit/internal/timer.h
-- Installing: /usr/local/include/rabit/internal/utils.h
-- Installing: /usr/local/include/rabit/rabit.h
-- Installing: /usr/local/include/rabit/serializable.h
-- Installing: /usr/local/include/dmlc
-- Installing: /usr/local/include/dmlc/any.h
-- Installing: /usr/local/include/dmlc/array_view.h
-- Installing: /usr/local/include/dmlc/base.h
-- Installing: /usr/local/include/dmlc/common.h
-- Installing: /usr/local/include/dmlc/concurrency.h
-- Installing: /usr/local/include/dmlc/config.h
-- Installing: /usr/local/include/dmlc/data.h
-- Installing: /usr/local/include/dmlc/input_split_shuffle.h
-- Installing: /usr/local/include/dmlc/io.h
-- Installing: /usr/local/include/dmlc/json.h
-- Installing: /usr/local/include/dmlc/logging.h
-- Installing: /usr/local/include/dmlc/lua.h
-- Installing: /usr/local/include/dmlc/memory.h
-- Installing: /usr/local/include/dmlc/memory_io.h
-- Installing: /usr/local/include/dmlc/omp.h
-- Installing: /usr/local/include/dmlc/optional.h
-- Installing: /usr/local/include/dmlc/parameter.h
-- Installing: /usr/local/include/dmlc/recordio.h
-- Installing: /usr/local/include/dmlc/registry.h
-- Installing: /usr/local/include/dmlc/serializer.h
-- Installing: /usr/local/include/dmlc/threadediter.h
-- Installing: /usr/local/include/dmlc/thread_local.h
-- Installing: /usr/local/include/dmlc/timer.h
-- Installing: /usr/local/include/dmlc/type_traits.h
```

### CODE REVIEW

**Comment by henrique** [comment]
Would anyone mind having a quick look at this?
Simple patch but it'd make installation standard and much easier...
Cheers

**Comment by RAMitchell** [comment]
Thanks for the PR. A few questions:

How would I use this if I wanted to install the python, JVM or R packages? Would it conflict with a previous installation of any of these packages as currently documented? What happens if I do this on Windows?

**Comment by henrique** [comment]
This simple PR is just the standard installation for shared libraries and headers (C/C++), all it does is copy these files to /usr/local/ as listed in the initial comment, so it shouldn't interfere if any of the other installations.
About Windows, sorry I don't have a working cmake on windows to test it. It seems a bit useless on Winodws unless you properly set CMAKE_INSTALL_PREFIX : https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html
Moreover, I'd think you could get rid of the current xgboost/Makefile and do the test+coverage in cmake as well, but that would be a different PR...

**Comment by RAMitchell** [comment]
While this is a good idea I think we should address it later when we have more of an idea what's happening with cmake.

I don't want to further fragment the XGBoost build/installation process, especially without documentation.

**Pull request closed without merging**
