### PR TITLE
python cv bugfixing (eval metrics)

### PR DESCRIPTION
**Pull request by Far0n**
- fixed bug if both eval_metrics xgb-param and metrics param of cv function have been set
- cv early stopping output looks now like the one of xgb.train

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@Far0n Could you add some test for the two fixes?

**Comment by Far0n** [comment]
@terrytangyuan sure, done.

**Comment by Far0n** [comment]
.. sry my ide reformatted "test_basic.py". hope this is okay?!

**Comment by terrytangyuan** [comment]
LTGM. Thanks!

**Pull request merged**
