### PR TITLE
Fix R CRAN failures.

### PR DESCRIPTION
**Pull request by trivialfis**
Related: https://github.com/dmlc/xgboost/issues/7260#issuecomment-962985358

* Remove hist builder dtor.
I did not reproduce the warning using clang-14, might be missing some flags in my config or it's just a bug in clang-12 used by CRAN test.  Anyway, this is a cleanup that removes unnecessary code.
* Initialize some variables.

### CODE REVIEW

**Comment by hetong007** [comment]
Thanks. May I suggest to hold this PR until we see all the checks for 1.5.0.1 on this page: https://cran.r-project.org/web/checks/check_results_xgboost.html. It might take a few days, and we have until Nov 22nd to patch.

**Review by hcho3 — APPROVED** [review]

**Comment by hetong007** [comment]
There are additional issues with valgrind: https://www.stats.ox.ac.uk/pub/bdr/memtests/valgrind/xgboost/00check.log:

- An R test failure: `Failure (test_helpers.R:231:11): xgb-attribute numeric precision`
- Some leaks in the end of the check log.

I didn't remember CRAN ever complains about it, but if it is fixable on our side maybe we can also try?

**Comment by trivialfis** [comment]
> An R test failure: Failure (test_helpers.R:231:11): xgb-attribute numeric precision

That's just testing the `as.numeric` in R.  XGBoost is not involved.  Will relax the test.  A longer-term solution might be using JSON instead.

> at 0x1E1906EF: xgboost::data::SimpleDMatrix::GetGradientIndex(xgboost::BatchParam const&) (packages/tests-vg/xgboost/src/amalgamation/../src/data/simple_dmatrix.cc:94)

Probably the `gpu_id`, which is not used in that context.  Will fix.

> 0x1E21680E: xgboost::DMatrix* xgboost::DMatrix::Create<xgboost::data::DenseAdapter>(xgboost::data::DenseAdapter*, float, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (packages/tests-vg/xgboost/src/amalgamation/../src/data/data.cc:828)

This should be released by R by calling `XGDMatrixFree_R`.  Not sure why it isn't called.

>   ==2937178==    by 0x1E148116: XGDMatrixCreateFromCSC_R (packages/tests-vg/xgboost/src/xgboost_R.cc:137)

Leak in libgomp?  Not sure if there's anything we can do.


> XGDMatrixSetInfo_R (packages/tests-vg/xgboost/src/xgboost_R.cc:203)

std::vector should manage the memory as RAII.  Not sure if there's anything we can do.

**Comment by trivialfis** [comment]
Ran valgrind with `Rscript testthat.R`.  No error or warning from valgrind.

**Review by hcho3 — APPROVED** [review]

**Comment by trivialfis** [comment]
@hcho3 Do you think we can free some budget for running valgrind with gtest on CI once we remove CUDA10?

**Comment by hcho3** [comment]
@trivialfis We can just use GitHub Actions for this?

**Comment by trivialfis** [comment]
But then we will skip all GPU code path.

**Comment by hcho3** [comment]
@trivialfis I don't think CRAN tests are run for any GPU code path

**Comment by trivialfis** [comment]
> running valgrind with gtest

I want to run valgrind with c++ tests.  But there are some warnings whenever GPU code is executed, so we might just limit it to CPU only for now:
```
==304308== Warning: noted but unhandled ioctl 0x19 with no size/direction hints.
==304308==    This could cause spurious value errors to appear.
==304308==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==304308== Warning: set address range perms: large range [0x10006000000, 0x10106000000) (noaccess)
==304308== Warning: noted but unhandled ioctl 0x49 with no size/direction hints.
==304308==    This could cause spurious value errors to appear.
==304308==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==304308== Warning: noted but unhandled ioctl 0x21 with no size/direction hints.
==304308==    This could cause spurious value errors to appear.
==304308==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==304308== Warning: noted but unhandled ioctl 0x1b with no size/direction hints.
==304308==    This could cause spurious value errors to appear.
==304308==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==304308== Warning: noted but unhandled ioctl 0x44 with no size/direction hints.
==304308==    This could cause spurious value errors to appear.
==304308==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
```

**Comment by trivialfis** [comment]
I think this PR should contain all the fixes in XGBoost.

**Comment by trivialfis** [comment]
@hetong007 I looked into the 2 memory leak reports, first one is from libgomp, the second one is from the `std::vector` implementation in GCC.  I don't know how to fix them and so far haven't been able to reproduce them using my own setup.  Any chance we can continue the submission?

**Comment by trivialfis** [comment]
Got it.  Thanks for guiding the release.

**Comment by hetong007** [comment]
I see most CRAN results are available with no new issue. I'm merging this PR.

**Comment by trivialfis** [comment]
Thanks, I will backport it and bump the version

**Comment by hetong007** [comment]
Seems CRAN checks are all finished. Please instruct when to submit (before 22nd).

**Comment by trivialfis** [comment]
I will run through all the tests again today

**Comment by trivialfis** [comment]
@hetong007 Let me know if there's anything else I can do to help.

**Comment by hetong007** [comment]
It is undergoing checks by the CRAN team. Will update here.

**Comment by hetong007** [comment]
On CRAN now. From the [status page](https://cran.r-project.org/web/checks/check_results_xgboost.html) I see the column with `r-devel-linux-x86_64-fedora-clang` has its previous WARN fixed. Appreciated!

**Comment by trivialfis** [comment]
Excellent!

**Pull request merged**
