### PR TITLE
XGBoost Tutorial for Beginners

### PR DESCRIPTION
**Pull request by mjbahmani**

### CODE REVIEW

**Comment by CodingCat** [comment]
@hcho3 where we should put this type of things?

**Comment by trivialfis** [comment]
Is it me or it's github renderer?  The format is completely screwed up ...

**Comment by hcho3** [comment]
@trivialfis The notebook renders fine on my machine.

**Comment by CodingCat** [comment]
while this notebook is not ready for merging, it reminds me that notebook-formed tutorial might be a good idea for further customer engagement

**Comment by hcho3** [comment]
@CodingCat Agreed. For a good example of notebook collection, see [Amazon SageMaker Examples repository](https://github.com/awslabs/amazon-sagemaker-examples).

**Comment by hcho3** [comment]
Closing for now

**Pull request closed without merging**
