### PR TITLE
Remove f-string, since it's not supported by Python 3.5

### LINKED ISSUE #5328: Failed to import xgboost in Python3.5
From xgboost 1.0.0, importing xgboost in Python 3.5 causes an error because of f-strings that is not supported in 3.5.

```
/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/xgboost/dask.py:33: in <module>
    from .sklearn import XGBModel, XGBClassifierBase, xgboost_model_doc
E     File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/xgboost/sklearn.py", line 437
E       msg = f'Current model type: {type(self).__name__}, ' + \
E                                                          ^
E   SyntaxError: invalid syntax
```

- xgboost version: 1.0.0 installed from pip
- environment: ubuntu-latest in GitHub CI ([link to my CI result](https://github.com/nyanp/nyaggle/runs/457601501))

Is Python3.5 no longer supported from 1.0.0?

### PR DESCRIPTION
**Pull request by hcho3**
Closes #5328. Also add Python 3.5 to CI so that f-string does not get accidentally added to the codebase again.

I will need to make a patch and create 1.0.1 patch release.

Aside: Dask now requites Python 3.6+, so I do not run Dask integration tests with Python 3.5.

### CODE REVIEW

**Comment by hcho3** [comment]
@trivialfis No, since Dask does not support Python 3.5. What I want is to have almost all parts of XGBoost compatible with Python 3.5 (as promised in setup.py) and only require Python 3.6 for Dask and cuDF integration.

**Comment by hcho3** [comment]
@JohnZed I'd like to hear from you about supporting Python 3.5. Given that Dask requires 3.6+ we have two options:

1. Require Python 3.6+ for XGBoost as well OR
2. Make XGBoost Python 3.5 compatible, except for `xgboost.dask` module.

Currently, this PR chooses option 2.

**Comment by JohnZed** [comment]
I would suggest option 2 for now but adding a deprecation warning to release notes (and possibly to setup.py) to warn that python 3.5 support will be removed in the upcoming version 1.1+. That gives anyone stuck on 3.5 a fair warning but does not saddle XGB with long-term support for Python 3.5.

**Comment by hcho3** [comment]
@JohnZed Got it. Let's stick with Python 3.5 for now. I like the idea of adding deprecation notice, so let me do that. We can open a separate thread to discuss when we should drop Python 3.5.

Note that Python 3.5 is schedule to reach end-of-life on September 13, 2020.

**Comment by mli** [comment]
# [Codecov](https://codecov.io/gh/dmlc/xgboost/pull/5330?src=pr&el=h1) Report
> Merging [#5330](https://codecov.io/gh/dmlc/xgboost/pull/5330?src=pr&el=desc) into [release_1.0.0](https://codecov.io/gh/dmlc/xgboost/commit/d90e7b31170b86f97eafb6b9b64027abb6881a3e&el=desc) will **decrease** coverage by `0.01%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/dmlc/xgboost/pull/5330?src=pr&el=tree)

```diff
@@                Coverage Diff                @@
##           release_1.0.0    #5330      +/-   ##
=================================================
- Coverage          83.83%   83.82%   -0.02%     
=================================================
  Files                 11       11              
  Lines               2413     2417       +4     
=================================================
+ Hits                2023     2026       +3     
- Misses               390      391       +1     
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/dmlc/xgboost/pull/5330?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/dmlc/xgboost/pull/5330?src=pr&el=footer). Last update [d90e7b3...ed19e0e](https://codecov.io/gh/dmlc/xgboost/pull/5330?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by hcho3** [comment]
Merged. I will push out 1.0.1 release now. It's essentially same as 1.0.0 plus this patch.

**Pull request merged**
