### PR TITLE
Added ntree_limit and output_margin to sklearn predict functions #2 (fixed pylint issue)

### PR DESCRIPTION
**Pull request by Far0n**
This is the same as https://github.com/dmlc/xgboost/pull/428 + fixed pylint issue

### CODE REVIEW

**Comment by terrytangyuan** [comment]
This looks good. Can you squash?

**Comment by Far0n** [comment]
mhh, did I mess it up?

**Comment by terrytangyuan** [comment]
Yeah...you squashed all recent commits on master. Do you mind start a new PR since the change is not that big? Please add your name to contributors if it's not there yet.

**Comment by Far0n** [comment]
My git noobiness just hit. I will redo it.

**Pull request closed without merging**
