### PR TITLE
Remove xgboost's thread_local and switch to dmlc::ThreadLocalStore

### PR DESCRIPTION
**Pull request by Huffers**
See comments on issue #2109.

### CODE REVIEW

**Comment by Huffers** [comment]
Seems "#message" hasn't been defined anywhere.

Should we just use "#pragma message" ?

**Comment by tqchen** [comment]
yes that will do

**Comment by tqchen** [comment]
I have updated dmlc-core to use pragma message, can you do a pull?

**Comment by Huffers** [comment]
Sure, I've pulled the latest dmlc-core now.

Seems Travis has found the "test_basic_models" Python lightweight test now gets a greater error than expected though. That's odd, as I don't see how this pull request could affect that.

**Comment by tqchen** [comment]
can you do a rebase against latest master to bring https://github.com/dmlc/xgboost/pull/2147 in?

**Comment by Huffers** [comment]
Done!

**Pull request merged**
