### PR TITLE
Minor changes to code style

### PR DESCRIPTION
**Pull request by LevineHuang**
Some minor changes to code style in file 'boost_from_prediction.py'.

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Could you put your style changes PRs together?

**Comment by sethah** [comment]
I don't know why we'd separate these PRs. Easier to review as a single PR, IMO.

**Comment by LevineHuang** [comment]
@terrytangyuan 
MY PR  follows the proposal of PEP8.

**Comment by terrytangyuan** [comment]
Please close all your other PRs and combine them into this one. Thanks.

**Pull request merged**
