### PR TITLE
Use bst_float consistently throughout

### PR DESCRIPTION
**Pull request by AbdealiJK**
Using bst_float/float/double causes confusion for contributors and also makes it complicated by using static_cast in multiple places.
By using bst_float consistently, this is avoided.

### CODE REVIEW

**Comment by khotilov** [comment]
Using doubles is necessary to prevent possible large losses of significance or catastrophic cancellations in sums/differences. Please don't change them mindlessly to float.

**Comment by AbdealiJK** [comment]
Personally, I think all cases should  use doubles by default.
Even things like sum_hess and feature values will have a loss of precision.
Which is why I'd rather have everything unified by bst_float so that it can
be set to double.

**Comment by khotilov** [comment]
Setting everything to double would affect memory and speed performance.

**Comment by AbdealiJK** [comment]
@khotilov That makes sense ... it would double all the IO in the distributed setting which would indeed impact things.

I'll modify this to only convert float types to bst_float so that:
 - The places where double are required (due to large computation) don't get impacted
 - the memory/speed performance doesn't get affected

**Comment by AbdealiJK** [comment]
Ok, pushed a new version.
This only changes places where `float` has been hardcoded into bst_float.
There were cases where things are hardcoded to float like:

```
bst_float loss_chg = <get loss chg from somewhere ...>;
best->Update(static_cast<float>(loss_chg), ...)
```

**Comment by AbdealiJK** [comment]
No idea why travis is stuck on this PR, but the builds do pass at my branch in https://travis-ci.org/AbdealiJK/xgboost/builds/179839749

**Comment by AbdealiJK** [comment]
@tqchen Thanks for merging this :+1:

**Comment by davidADSP** [comment]
I think Cover is still being rounded in xgb.model.dt.tree due to loss of precision?

Could it be that either of these aren't using bst_float?

image

image

**Pull request merged**
