### PR TITLE
Take advantage of C++17 features

### PR DESCRIPTION
**Pull request by rongou**
Using `std::as_const` and `std::exclusive_scan`.

### CODE REVIEW

**Comment by rongou** [comment]
@hcho3

**Comment by rongou** [comment]
Hmm looks like the R windows pipeline is still dong `gnu++14`?

**Comment by trivialfis** [comment]
let me fix it.

**Comment by trivialfis** [comment]
https://github.com/dmlc/xgboost/pull/8860

**Comment by rongou** [comment]
@hcho3 looks like the gcc version is too old for `std::exclusive_scan`?

**Comment by hcho3** [comment]
Using GCC 9 for now, since some R packages don't build with GCC 10. See https://github.com/kr-colab/discoal/issues/21#issue-665436177

**Comment by hcho3** [comment]
Disabling sanitizer test due to #8863

**Comment by trivialfis** [comment]
please don't disable the sanitizer test for the use of `exclusive_scan`.

**Comment by trivialfis** [comment]
As mentioned in previous offline chats, we should expect some compiler issues with c++17 considering we support multiple bindings with different specifications of compilers (especially for R mingw). We won't be fully utilizing c++-17 for a period of time depending on the choice of compilers.

**Review by trivialfis — APPROVED** [review]

**Pull request merged**
