### PR TITLE
[jvm-packages] Add new parameter singlePrecisionHistogram to xgboost4j-spark

### PR DESCRIPTION
**Pull request by zhangzhang10**
Expose the existing 'singlePrecisionHistogram' param to the Spark layer.

### CODE REVIEW

**Comment by SmirnovEgorRu** [comment]
Overall LGTM, thank you for adding the parameter to Spark API,
@trivialfis, I suppose the issues in CI are not related to the PR. Can we restart this?

**Comment by trivialfis** [comment]
Yes.  We are working to resolve the issues on CI.

**Comment by hcho3** [comment]
CI is fixed in #5814

**Comment by zhangzhang10** [comment]
@hcho3 Some checks for this PR failed because of "Docker build failure: dial tcp: lookup auth.docker.io: Temporary failure in name resolution". Looks lie a temporary issue. How do I rerun these tests? Thanks.

**Comment by hcho3** [comment]
I restarted the failing test.

**Pull request merged**
