### PR TITLE
[CI] CI cost saving

### PR DESCRIPTION
**Pull request by hcho3**
* Drop CUDA 10.x and use CUDA 11.0 in CI
* Drop JDK 11 and JDK 12 tests

### CODE REVIEW

**Comment by hcho3** [comment]
I'll need to rebuild the machine image for the Windows worker to use CUDA 11.0.

**Comment by hcho3** [comment]
I'll keep #7366 open, since clang-tidy fails when using CUDA 11.0

**Comment by trivialfis** [comment]
Is it caused by `def dockerArgs = "--build-arg CUDA_VERSION_ARG=10.1"` in the ClangTidy groovy function?

**Comment by hcho3** [comment]
When I changed 10.1 to 11.0, clang-tidy fails to pass.

**Comment by trivialfis** [comment]
Got it.  I will take a look into the error later.

**Comment by trivialfis** [comment]
Hi, the errored CI tests for clang-tidy seems to be cmake failing to find appropriate CTK:

```
[2021-11-16T09:29:31.963Z] -- Detecting CUDA compiler ABI info
[2021-11-16T09:29:32.615Z] -- Detecting CUDA compiler ABI info - done
[2021-11-16T09:29:32.615Z] CMake Error at CMakeLists.txt:134 (message):
[2021-11-16T09:29:32.615Z]   CUDA version must be at least 11.0!
[2021-11-16T09:29:32.615Z] 
[2021-11-16T09:29:32.615Z] 
[2021-11-16T09:29:32.615Z] -- Configuring incomplete, errors occurred!
[2021-11-16T09:29:32.615Z] See also "/workspace/cdb/CMakeFiles/CMakeOutput.log".
```

**Comment by trivialfis** [comment]
Other than clang-tidy, is there anything else we need to do for this PR?

**Comment by hcho3** [comment]
@trivialfis We can merge this PR once the Windows test completes running. I had to re-build the Windows machine's image from scratch.

**Comment by hcho3** [comment]
@trivialfis Urr... One of the gtest is now failing:
```
[2021-11-17T21:16:17.829Z] [ RUN      ] MultiClassesSerializationTest.GpuHist
[2021-11-17T21:16:17.829Z] C:/Users/Administrator/workspace/xgboost-win64_PR-7407/tests/cpp/test_serialization.cc(49): error: Expected equality of these values:
[2021-11-17T21:16:17.829Z]   l
[2021-11-17T21:16:17.829Z]     Which is: false
[2021-11-17T21:16:17.829Z]   r
[2021-11-17T21:16:17.829Z]     Which is: true
```

**Comment by hcho3** [comment]
@trivialfis Are you okay with disabling `MultiClassesSerializationTest.GpuHist` for now? Reducing CI cost is a higher priority.

**Comment by trivialfis** [comment]
> Are you okay with disabling MultiClassesSerializationTest.GpuHist for now?

Go ahead.  I will try to reproduce it later.

**Pull request merged**
