### PR TITLE
Added an option to use weights for individual samples

### PR DESCRIPTION
**Pull request by AlexisMignon**
Completed the sklearn API so that sample weights can be used

### CODE REVIEW

**Comment by tqchen** [comment]
I would like to know how did scikit-learn handle sample weights in their API, so we can be as consistent as possible.

**Comment by terrytangyuan** [comment]
@AlexisMignon @tqchen Reference [here](https://github.com/scikit-learn/scikit-learn/blob/06bf797c0deabe2a2f166d19abbd0c305da4d123/sklearn/ensemble/weight_boosting.py). Looks like more handling is needed.

**Comment by AlexisMignon** [comment]
@tqchen  The sample_weight argument usually comes in third place in the fit method for models that can handle them. Actually, the signature of the XGBClassifier already does it this way, however, I've put it in last place in order to be backward compatible since it would have changed the signature for the regressor. If this is not a concern, we can have the same signature for both the classifier and the regressor.

@terrytangyuan I'm not sure that more handling is needed since the XGBoost scikit learn API is nothing but a wrapper. As I understand it, the management of the sample weights is already done by the booster object.

**Comment by terrytangyuan** [comment]
Sure, could you also add a test case?

**Comment by tqchen** [comment]
I think it is reasonable to make things consistent, and put a notice on the change list

**Comment by AlexisMignon** [comment]
I've has some troubles while resyncing my repository. This is why there is a commit regarding "rabit" which is most probably not necessary.

I also noticed that the output values obtained using sample weights even if they are all set to 1.0 are different from those obtained without this option. Which justifies the use of different threshold values in the test.

**Comment by terrytangyuan** [comment]
Closing due to inactive status. Feel free to reopen if you pick it up again.

**Pull request closed without merging**
