### PR TITLE
Upgrading to NCCL2

### PR DESCRIPTION
**Pull request by teju85**
Note that as part of this process, the nccl submodule has now been removed.

### CODE REVIEW

**Comment by hcho3** [comment]
@teju85 @RAMitchell filed #3377 earlier to upgrade NCCL2. He closed it because NCCL2 was behind a membership wall. Has this problem been addressed?

**Comment by teju85** [comment]
@hcho3 
There's also OS-agnostic package that's not behind membership wall.
And they have been used in CI workflows in other projects like pytorch.
Eg: https://github.com/pytorch/builder/search?q=developer.download.nvidia.com&unscoped_q=developer.download.nvidia.com
This is what I've used to resolve this issue to upgrade to nccl2.

There's apparently no v9.1 release for the nccl2 version in the link I used. So, will have to retry this by upgrading to cuda v9.2. Submitting an update soon...

**Comment by hcho3** [comment]
@teju85 I see. Let's fix the CI tests, and we should be able to merge it.

**Comment by teju85** [comment]
@hcho3 Yes, there still seem to be a few LD_LIBRARY_PATH related errors present.
However, there's a couple of urgent items I need to tackle at work.
Hence, will get back to fixing these errors in another couple of days or so.

**Comment by teju85** [comment]
@RAMitchell  Even after I upgraded the version to 9.2 in the Jenkinsfile, it still seems to run on v9.1.
Ref: https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-3404/21/pipeline/40

Would you know how to force the CI workflow to pick up my updates to the Jenkinsfile?

**Comment by hcho3** [comment]
@teju85 I think Jenkins is caching some of the packages that are being installed. Let me go ahead and clean the cache and reboot Jenkins.

**Comment by teju85** [comment]
Thanks @hcho3 ! That should help. So, after you clean the cache, should I just resubmit?

There's also another problem, @hcho3 and @RAMitchell 
In the Jenkinsfile at Line 106, it tries to perform a 'release' container build/run.
With the nccl2 upgrade, it will now require nccl2 to be downloaded as part of the Dockerfile.release.
Is that ok of a change?

**Comment by hcho3** [comment]
@teju85 I'm still getting 404 in the new test: https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-3404/23/pipeline/40/
```
--2018-07-02 07:14:27--  https://developer.download.nvidia.com/compute/redist/nccl/v2.2/nccl_2.2.13-1%2Bcuda9.1_x86_64.txz

Resolving developer.download.nvidia.com... 192.229.211.70, 2606:2800:21f:3aa:dcf:37b:1ed6:1fb

Connecting to developer.download.nvidia.com|192.229.211.70|:443... connected.

HTTP request sent, awaiting response... 404 Not Found

2018-07-02 07:14:27 ERROR 404: Not Found.
```
What's going on here?

**Comment by hcho3** [comment]
Ah, so there is no NCCL 2.2 for CUDA 9.1? Is it correct?

**Comment by teju85** [comment]
yup... it should be v9.2

**Comment by teju85** [comment]
there's no nccl 2.2 for v9.1.
That was the reason we decided to update Jenkinsfile to use v9.2 cuda.

**Comment by hcho3** [comment]
Found this article: https://support.cloudbees.com/hc/en-us/articles/227246367-Why-Jenkinsfile-changes-Are-Not-Reflected-in-PR-Build

I think Jenkins does not trust your modification of Jenkinsfile, since you do not have write access to the XGBoost repo. Unfortunately, I don't have the right to add committers to this repo. Why don't you submit a separate pull request just to modify Jenkinsfile, and we can re-visit this pull request. Thanks!

**Comment by hcho3** [comment]
@teju85 Any follow-up on this?

**Comment by teju85** [comment]
@hcho3 
I have created the changes for the Jenkinsfile. Will submit a PR soon.

Also fixed another nccl2 change needed inside the Dockerfile.release. Once the above PR has been filed, I'll also update this PR with the necessary changes.

**Comment by teju85** [comment]
@hcho3 PR #3460 created for the Jenkinsfile cuda version upgrade. Please help in clearing such a cache and updating the CI workflow to pick up v9.2. Then I'll submit the Dockerfile.release changes (mentioned above) for this PR to kick-off the tests.

**Comment by teju85** [comment]
@hcho3 thanks for merging #3460! Just submitted the next set of changes to fix the previous errors seen. Will keep an eye out on this for any issues and fix, if any, accordingly.

**Comment by hcho3** [comment]
Let me go ahead and upgrade the CI machine to CUDA 9.2.

**Comment by hcho3** [comment]
@teju85 XGBoost is crashing because NCCL2 is being linked dynamically. Is there a way to install static libs for NCCL2?

**Comment by teju85** [comment]
Makes sense. Let me remove dynamic library linking for nccl2 and use static instead. Will update soon...

**Comment by hcho3** [comment]
Done. Thanks a lot!

**Pull request merged**
