### PR TITLE
[R] xgb.plot.tree fixes

### PR DESCRIPTION
**Pull request by khotilov**
- fixed the style of tree graphs for the new DiagrammeR WRT #1934 and cleaned up the code
- now draw branches with missing values in bold
- add an option for `xgb.plot.tree` to return unrendered DiagrammeR graph (if a user wants to modify some things); and an option to display node ID's (for easier debugging)
- deprecated the `n_first_tree` parameter and introduces a tree-index vector selector `trees` (allows to easily select single tree or any combination of trees, e.g., for multiclass models)
- fixes the types for a couple of columns in the output of `xgb.model.dt.tree` (Split to be numeric, and Node to be integer)
- brushed up the docs

### CODE REVIEW

**Comment by jaredlander** [comment]
This does not appear to have made its way to CRAN yet.  Should a submission be expected soon?  I also tried installing from the drat repo (`install.packages("xgboost", repos=c("http://dmlc.ml/drat/", getOption("repos")), type="source")`) and by cloning the repo and following the make instructions.  No matter what I do I get the DiagrammeR error.

```
Error: 'create_node_df' is not an exported object from 'namespace:DiagrammeR'
```

**Comment by khotilov** [comment]
It's not in CRAN yet. However, it's should be very easy, at least under linux or windows, to upgrade the R package once you have the most up-to-date code and right compiler setup: simply go to the 'R-package/' directory and run in R
`install.packages('.', repos = NULL, type="source")`

**Comment by khotilov** [comment]
Actually, I'm looking right now at the "To install the latest version run the following bash script, ..." instructions of https://xgboost.readthedocs.io/en/latest/build.html#r-package-installation and they don't make complete sense for R package installation... I'll fix it.

**Comment by jaredlander** [comment]
Had `xgboost` installed correctly, but had the wrong `diagrammeR`.  It's working now.

Glad it brought attention to the docs though.

**Pull request merged**
