### PR TITLE
Pull CI changes into vertical federated learning branch.

### PR DESCRIPTION
**Pull request by trivialfis**

### CODE REVIEW

**Comment by trivialfis** [comment]
@ZiyueXu77 Please help rebase the federated learning PRs once this is merged.

**Comment by ZiyueXu77** [comment]
> @ZiyueXu77 Please help rebase the federated learning PRs once this is merged.

sure, thanks!

**Comment by trivialfis** [comment]
cc @hcho3 Do you think we should freeze the macos version for Python tests?
- https://github.com/dmlc/xgboost/pull/10124#issuecomment-2075757993
- https://github.com/actions/setup-python/issues/850

**Comment by trivialfis** [comment]
Also, let us ignore the windows CI on the `vertical-federated-learning` feature branch for now. It might resolve itself once we get back to the master branch. It's a lot of effort to work with Windows and we don't support federated learning with windows anyway.

**Comment by ZiyueXu77** [comment]
sounds good! @nvidianz

**Comment by hcho3** [comment]
@trivialfis Let me unblock the CI by freezing the MacOS version.

**Pull request merged**
