### PR TITLE
[CI] Rotate access keys for uploading MacOS artifacts from Travis CI

### PR DESCRIPTION
**Pull request by hcho3**
@trivialfis

### CODE REVIEW

**Review by trivialfis — APPROVED** [review]

**Comment by trivialfis** [comment]
@hcho3 Do we need to change the github action too https://github.com/dmlc/xgboost/runs/3695362969 ?

**Comment by hcho3** [comment]
No.

**Comment by trivialfis** [comment]
This one is also failing https://github.com/dmlc/xgboost/runs/3695362681

**Comment by hcho3** [comment]
@trivialfis Ah, I will need to issue a new cred for GitHub Actions as well. Let me do that now.

**Pull request merged**
