### PR TITLE
restructuring the README with an index

### PR DESCRIPTION
**Pull request by ajkl**

### CODE REVIEW

**Comment by pommedeterresautee** [comment]
Thank you for this cleaning. It looks very good.

2 comments:
- can you please re add `DMLC/` in the title of the file
- can you please make the blog.graphlab link a real link of the word blogpost (so there is no more raw link in the text)

@tqchen @hetong007 now the README file is very clean, it seems to me that it misses visual elements like a logo. 
Most lib have one. It would be useful to include in presentation slides and so on...
Even something simple as the name in Black with a nice Font would be nice.
Or something more fancy if anyone has an idea.
What do you think?

Kind regards,
Michael

**Comment by ajkl** [comment]
those were 3 comments and not 2 ;)
* Is there a reason you want the title to be DMLC/xgboost ? Library titles do not have the org usually. It shows up in the git repo anyway.
* I will add the blog link.
* I did not spend a lot of time rewording things. Lot of them need some fixes. I will try to get to those.

I like the idea of a logo. That will be nice.

**Comment by tqchen** [comment]
Only on the readme title part, we want to place dmlc/xgboost to emphasize it is part of dmlc and we benefit a lot from other dmlc projects and used by other projects. 

This does not necessarily mean the library 's name is dmlc/xgboost, in most part of documentation, it remains as xgboost

**Comment by ajkl** [comment]
Review and merge if things look ok now.
A website for xgboost hosted through github's gh-pages would be nice too.

**Comment by tqchen** [comment]
Thanks for the effort!

**Comment by tqchen** [comment]
We spent some effort to make the documentation and lgo as @ajkl suggested, now we comes with a sphinx built doc along with the logo on head.

**Comment by ajkl** [comment]
The logo looks pretty nice. Thanks for the docs!

**Comment by tqchen** [comment]
I should thank you for making xgboost better:) Please take a look at the docs and see if there is something you like to fix or improve.  Hope we can get more of your wisdom into the project in future

**Pull request merged**
