### PR TITLE
[R] Get CXX flags from R CMD config.

### PR DESCRIPTION
**Pull request by trivialfis**
Close https://github.com/dmlc/xgboost/issues/8663 

Log for configuration:
```
checking Backtrace lib... 
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ -std=gnu++14 accepts -g... yes
checking for g++ -std=gnu++14 option to enable C++11 features... none needed
checking for backtrace in -lexecinfo... no
checking endian... 
configure: creating ./config.status
config.status: creating src/Makevars
** libs
Makevars:16: -DXGBOOST_STRICT_R_MODE=1
Makevars:16: -DDMLC_LOG_BEFORE_THROW=0
Makevars:16: -DDMLC_ENABLE_STD_THREAD=1
Makevars:16: -DDMLC_DISABLE_STDIN=1
Makevars:16: -DDMLC_LOG_CUSTOMIZE=1
Makevars:16: -DXGBOOST_CUSTOMIZE_LOGGER=1
```

All credit to @jameslamb and the work on LightGBM!

### CODE REVIEW

**Review by hcho3 — APPROVED** [review]

**Review by jameslamb — COMMENTED** [review]
Excellent!

This project uses a C compiler (`$CC`) to test for OpenMP, I think you may also need to do one of the following.

```shell
# get C compiler from R's configuration
CC=`"${R_HOME}/bin/R" CMD config CCC`

# ... or switch the OpenMP test to using a C++ compiler, like LightGBM does
# (note the use of CXX instead of CC)

${CXX} -o conftest conftest.c ${CPPFLAGS} ${LDFLAGS} ${OPENMP_LIB} ${OPENMP_CXXFLAGS} 2>/dev/null && ./conftest && ac_pkg_openmp=yes
```

LightGBM reference: https://github.com/microsoft/LightGBM/blob/23403a7c2c4d38961506968291f13c3f344ccb6f/R-package/configure.ac#L140

Otherwise, the detection of OpenMP in `configure` might not match what happens at compilation time. For example, in the situation where someone on a Mac is using `~/.R/Makevars` to force R to use `gcc` instead of `clang`.

I'm not sure which of the two approaches is preferable for XGBoost. In LightGBM we chose the `CXX` approach because we use only C++ source files. But XGBoost has this one `.c` file (https://github.com/dmlc/xgboost/blob/master/R-package/src/init.c) so I'm not sure.

**Comment by trivialfis** [comment]
@jameslamb Thank you for catching that! I updated the c-related flags, currently running tests on rhub with fedora clang and macos cran setup.

**Comment by trivialfis** [comment]
macos test looks good: https://builder.r-hub.io/status/xgboost_2.0.0.1.tar.gz-02f421441fd7716d01e5980d4b4a689d

**Comment by trivialfis** [comment]
Macos compilation seems fine https://builder.r-hub.io/status/xgboost_2.0.0.1.tar.gz-8c4a9c12ea429fc21922b8c6381bffa2

**Pull request merged**
