### PR TITLE
Fix external memory race condition.

### LINKED ISSUE #4619: External memory race condition.
Hi, @RAMitchell @hcho3 @CodingCat 

I encountered an error on master branch a30176907f5628020f8238464c2f58907ee724d1 by running Python test:
``` bash
pytest -s --fulltrace --verbose ./tests/python/test_updaters.py -k colmaker
```

The error is not deterministic, sometimes it's a segfault, while other times it's some failing checks,  I attached a few of them at the end.  Also note that if I limit XGBoost to single thread all tests run smoothly.  So I believe that it's a race error.  I ran tsan but pytest got stuck at collecting tests, asan is not really helpful for debugging producer/consumer thread model.  Could you provide some suggestions? I can't think of a place to start looking...

```
[02:09:12] WARNING: /home/fis/Workspace/xgb/xgboost/src/gbm/gbtree.cc:95: DANGER AHEAD: You have manually specified `updater` parameter. The `tree_method` parameter will be ignored. Incorrect sequence of updaters will produce undefined behavior. For common uses, we recommend using `tree_method` parameter instead.
[02:09:12] WARNING: /home/fis/Workspace/xgb/xgboost/src/gbm/gbtree.cc:95: DANGER AHEAD: You have manually specified `updater` parameter. The `tree_method` parameter will be ignored. Incorrect sequence of updaters will produce undefined behavior. For common uses, we recommend using `tree_method` parameter instead.
[02:09:12] SparsePage::Writer Finished writing to tmptmp_.sorted.col.page
[02:09:12] SparsePageSource: Finished writing to tmptmp_
[02:09:12] SparsePage::Writer Finished writing to tmptmp_.col.page
terminate called after throwing an instance of 'dmlc::Error'
  what():  [02:09:12] /home/fis/Workspace/xgb/xgboost/dmlc-core/include/dmlc/threadediter.h:189: Check failed: !producer_sig_processed_: 
Stack trace:
  [bt] (0) /home/fis/Workspace/xgb/lib/python3.6/site-packages/xgboost-0.90-py3.6.egg/xgboost/./lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x4a) [0x7f9ed8329030]
  [bt] (1) /home/fis/Workspace/xgb/lib/python3.6/site-packages/xgboost-0.90-py3.6.egg/xgboost/./lib/libxgboost.so(dmlc::ThreadedIter<xgboost::SparsePage>::BeforeFirst()+0x126) [0x7f9ed8385830]
  [bt] (2) /home/fis/Workspace/xgb/lib/python3.6/site-packages/xgboost-0.90-py3.6.egg/xgboost/./lib/libxgboost.so(xgboost::data::SparsePageSource::BeforeFirst()+0xa9) [0x7f9ed8381269]
  [bt] (3) /home/fis/Workspace/xgb/lib/python3.6/site-packages/xgboost-0.90-py3.6.egg/xgboost/./lib/libxgboost.so(xgboost::data::SparsePageDMatrix::GetRowBatches()+0x74) [0x7f9ed837b020]
  [bt] (4) /home/fis/Workspace/xgb/lib/python3.6/site-packages/xgboost-0.90-py3.6.egg/xgboost/./lib/libxgboost.so(xgboost::data::SparsePageSource::CreatePageFromDMatrix(xgboost::DMatrix*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)+0x35b) [0x7f9ed8382781]
  [bt] (5) /home/fis/Workspace/xgb/lib/python3.6/site-packages/xgboost-0.90-py3.6.egg/xgboost/./lib/libxgboost.so(xgboost::data::SparsePageSource::CreateColumnPage(xgboost::DMatrix*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)+0x7f) [0x7f9ed8383033]
  [bt] (6) /home/fis/Workspace/xgb/lib/python3.6/site-packages/xgboost-0.90-py3.6.egg/xgboost/./lib/libxgboost.so(xgboost::data::SparsePageDMatrix::GetColumnBatches()+0x5b) [0x7f9ed837b38d]
  [bt] (7) /home/fis/Workspace/xgb/lib/python3.6/site-packages/xgboost-0.90-py3.6.egg/xgboost/./lib/libxgboost.so(xgboost::data::SparsePageDMatrix::GetColDensity(unsigned long)+0xb0) [0x7f9ed837b60e]
  [bt] (8) /home/fis/Workspace/xgb/lib/python3.6/site-packages/xgboost-0.90-py3.6.egg/xgboost/./lib/libxgboost.so(+0x55a835) [0x7f9ed8471835]


Aborted (core dumped)

```

```
[02:08:13] WARNING: /home/fis/Workspace/xgb/xgboost/src/gbm/gbtree.cc:95: DANGER AHEAD: You have manually specified `updater` parameter. The `tree_method` parameter will be ignored. Incorrect sequence of updaters will produce undefined behavior. For common uses, we recommend using `tree_method` parameter instead.
[02:08:13] SparsePage::Writer Finished writing to tmptmp_.sorted.col.page
[02:08:13] SparsePageSource: Finished writing to tmptmp_
[02:08:13] SparsePage::Writer Finished writing to tmptmp_.col.page
[02:08:13] SparsePageSource: Finished writing to tmptmp_
[02:08:13] SparsePage::Writer Finished writing to tmptmp_.col.page
[02:08:13] SparsePage::Writer Finished writing to tmptmp_.col.page
[02:08:13] SparsePageSource: Finished writing to tmptmp_[02:08:13] SparsePageSource: Finished writing to tmptmp_

[02:08:13] SparsePage::Writer Finished writing to tmptmp_.col.page
[02:08:13] SparsePageSource: Finished writing to tmptmp_
Segmentation fault (core dumped)
```

```
[03:47:37] WARNING: /home/fis/Workspace/xgb/xgboost/src/gbm/gbtree.cc:95: DANGER AHEAD: You have manually specified `updater` parameter. The `tree_method` parameter will be ignored. Incorrect sequence of updaters will produce undefined behavior. For common uses, we recommend using `tree_method` parameter instead.
[03:47:37] SparsePage::Writer Finished writing to tmptmp_.sorted.col.page
[03:47:37] SparsePageSource: Finished writing to tmptmp_
[03:47:37] SparsePage::Writer Finished writing to tmptmp_.col.page
terminate called after throwing an instance of 'dmlc::Error'
  what():  [03:47:37] /home/fis/Workspace/xgb/xgboost/dmlc-core/include/dmlc/threadediter.h:419: Check failed: producer_sig_ == kProduce: Make sure you call BeforeFirst not inconcurrent with Next!
Stack trace:
  [bt] (0) /home/fis/Workspace/xgb/lib/python3.6/site-packages/xgboost-0.90-py3.6.egg/xgboost/./lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x4a) [0x7f83af0760e0]
  [bt] (1) /home/fis/Workspace/xgb/lib/python3.6/site-packages/xgboost-0.90-py3.6.egg/xgboost/./lib/libxgboost.so(dmlc::ThreadedIter<xgboost::SparsePage>::Next(xgboost::SparsePage**)+0xe2) [0x7f83af0cda16]
  [bt] (2) /home/fis/Workspace/xgb/lib/python3.6/site-packages/xgboost-0.90-py3.6.egg/xgboost/./lib/libxgboost.so(xgboost::data::SparsePageSource::Next()+0xc8) [0x7f83af0c9798]
  [bt] (3) /home/fis/Workspace/xgb/lib/python3.6/site-packages/xgboost-0.90-py3.6.egg/xgboost/./lib/libxgboost.so(xgboost::data::SparsePageDMatrix::GetRowBatches()+0x8b) [0x7f83af0c36d7]
  [bt] (4) /home/fis/Workspace/xgb/lib/python3.6/site-packages/xgboost-0.90-py3.6.egg/xgboost/./lib/libxgboost.so(xgboost::data::SparsePageSource::CreatePageFromDMatrix(xgboost::DMatrix*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)+0x35b) [0x7f83af0cadf7]
  [bt] (5) /home/fis/Workspace/xgb/lib/python3.6/site-packages/xgboost-0.90-py3.6.egg/xgboost/./lib/libxgboost.so(xgboost::data::SparsePageSource::CreateColumnPage(xgboost::DMatrix*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)+0x7f) [0x7f83af0cb6a9]
  [bt] (6) /home/fis/Workspace/xgb/lib/python3.6/site-packages/xgboost-0.90-py3.6.egg/xgboost/./lib/libxgboost.so(xgboost::data::SparsePageDMatrix::GetColumnBatches()+0x5b) [0x7f83af0c3a2d]
  [bt] (7) /home/fis/Workspace/xgb/lib/python3.6/site-packages/xgboost-0.90-py3.6.egg/xgboost/./lib/libxgboost.so(xgboost::data::SparsePageDMatrix::GetColDensity(unsigned long)+0xb0) [0x7f83af0c3cae]
  [bt] (8) /home/fis/Workspace/xgb/lib/python3.6/site-packages/xgboost-0.90-py3.6.egg/xgboost/./lib/libxgboost.so(+0x76b58b) [0x7f83af19658b]


Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by trivialfis**
Closes #4619 , unblocks #4975 .

~The file lock is not necessary for `colmaker`, only added to be safe.~ Removed, it causes dead lock on Windows.  
Root cause for the fixed issue is, despite its name, `threadedIter` is not thread safe.

### CODE REVIEW

**Comment by trivialfis** [comment]
Em... Seems dead lock on Windows.

**Comment by hcho3** [comment]
@trivialfis Is there a good way to make `threadedIter` actually thread-safe? I thought you and I did some work on it before?

**Comment by trivialfis** [comment]
@hcho3 Probably.  But after many attempts, I have only came to "having an vague intuition what it's and general flow".  For exactly how it works I have no idea.  There might be an easier way to do parallel programming.  But if you understand the implementation in dmlc core well please share some insight.

**Comment by trivialfis** [comment]
@hcho3 Do we want to merge this one for now?  You have more experience with `dmlc-core` I will let you decide. ;-)

**Comment by hcho3** [comment]
@trivialfis Let's merge this for now. I'd like to take another look at ThreadedIter this weekend.

**Comment by trivialfis** [comment]
@hcho3 I will merge this one later unless you think otherwise.  From the look of it, thread iter is not designed to be thread safe.  For a good implementation of thread primitives, I recommend the tbb library, it has many programming patterns that makes parallel programming robust.

**Comment by trivialfis** [comment]
Wait.  Somehow it's failing on the threading PR on Windows..

**Comment by hcho3** [comment]
@trivialfis I see that you removed file locking from this PR. Now this PR only contains a change about GetColDensity(). Does this PR still "fix external memory race condition," as the name of the PR suggests?

**Comment by hcho3** [comment]
> Somehow it's failing on the threading PR on Windows..

where is the failure?

**Comment by trivialfis** [comment]
https://xgboost-ci.net/blue/organizations/jenkins/xgboost-win64/detail/PR-4975/6/pipeline

**Comment by hcho3** [comment]
> From the look of it, thread iter is not designed to be thread safe

@trivialfis Can you elaborate a little bit more? I can use your insight here. I do share your sentiment here; for me it was unsafe concurrent accesses to raw pointers that got me worried the most.

In the end, we may be better off re-writing ThreadedIter entirely.

**Comment by trivialfis** [comment]
Yes.  It fixed the race condition on colmaker.

**Comment by trivialfis** [comment]
@hcho3

> Can you elaborate a little bit more

See the third error message posted on: https://github.com/dmlc/xgboost/issues/4619 it explicitly asked me not to do something concurrently.

> In the end, we may be better off re-writing ThreadedIter entirely.

Agreed.  But that might be as huge as the JSON PR.  So we need some plans and preferably we can share some ideas/algorithms/design patters on how to do it,  otherwise we might build another pile of bugs.

**Comment by hcho3** [comment]
@trivialfis Thanks for the pointer. I agree about the need for planning. My experience is that writing thread-safe code takes lots of care. Let me first consider TBB, and ask whether an in-house implementation of ThreadedIter is called for. I will start a RFC for this.

**Pull request merged**
