### PR TITLE
[jvm-packages] Document incompatibility of CDH Hadoop with XGBoost4J-Spark.

### PR DESCRIPTION
**Pull request by hcho3**
See discussion at #3737.

### CODE REVIEW

**Comment by hcho3** [comment]
@CodingCat What do you think? Is it reasonable to require Apache Hadoop specifically?

**Comment by CodingCat** [comment]
according to the discussions there, they are not using xgboost4j but run on yarn directly, it is more about a problem in https://github.com/dmlc/dmlc-core/blob/649be18a8c55c48517861d67158a45dec54992ee/tracker/dmlc_tracker/yarn.py

**Comment by hcho3** [comment]
@CodingCat Got it. Then it's more accurate to say that YARN doesn't work with CDH Hadoop. Closing it for now

**Comment by CodingCat** [comment]
yeah, dmlc-core is compiled with vanilla version of hadoop https://github.com/dmlc/dmlc-core/blob/master/tracker/yarn/pom.xml

they need to build by their own

**Comment by hcho3** [comment]
@edwardzjl

**Comment by edwardzjl** [comment]
Ok I see, maybe we will give it a try later. Thanks for the information.

**Pull request closed without merging**
