### PR TITLE
Add to documentation how to run tests locally

### PR DESCRIPTION
**Pull request by trams**
A documentation change.
I added a chapter about how to build native unit tests and launch them to the Contributors docs

It was not at all obvious to me when I started on-boarding on this project so my guess someone else could benefit too

Tell me what do you think

### CODE REVIEW

**Comment by hcho3** [comment]
Nice, thanks!

**Comment by hcho3** [comment]
@trams I added instructions for running Python tests and for using Docker containers for convenience. Can you take a look?

**Comment by trams** [comment]
Nice. I didn't yet built python tests so I would try to follow your instructions and I'll you a feedback

**Comment by trams** [comment]
I think running `pytest -v -s --fulltrace tests/python` requires building|installing a python package which is not done for some reason on my machine. I will investigate this tomorrow and come back to you

**Comment by hcho3** [comment]
@trams I think you should set `PYTHONPATH` so that Python can find the XGBoost package.

**Comment by trams** [comment]
I tried running python tests one more time.
One need to install few packager for them to pass but otherwise it works

I tried running unit tests in Docker.
Native one worked like a charm
Python didn't work until I manually create a wheel using setup.py
After I created they mostly worked (5 failed)

**Comment by trams** [comment]
As for the structure.
Given that you recommend to run tests in Docker then I suggest to put the chapter about running them in Docker on top. What do you think?

**Comment by trams** [comment]
Thank you so much for improving dramatically my tiny pull request. Thanks to your addition I was able to start poking around the python part of this project

**Comment by hcho3** [comment]
> I tried running unit tests in Docker.
Native one worked like a charm
Python didn't work until I manually create a wheel using setup.py
After I created they mostly worked (5 failed)

I found a small problem with `test_python.sh` script. After the fix, you should be able to run Python tests without having to build a wheel.

**Comment by hcho3** [comment]
@trams I found out why the 5 tests were failing. I will submit a pull request soon.

**Comment by hcho3** [comment]
> Given that you recommend to run tests in Docker then I suggest to put the chapter about running them in Docker on top. What do you think?

I think it's still good to explain what individual tests do before showing Docker commands.

**Comment by hcho3** [comment]
@trams dmlc/xgboost#4617 should fix the 5 tests that failed.

**Pull request merged**
