### PR TITLE
xgb showcase - delayed feature addition

### PR DESCRIPTION
**Pull request by Far0n**
Top15 private leaderboard xgb-model for kaggle competition "Homesite Quote Conversion" (https://www.kaggle.com/c/homesite-quote-conversion) from winning team "KazAnova | Faron | clobber".
Uses training continuation to add features at later stages of the boosting process.

### CODE REVIEW

**Comment by tqchen** [comment]
we are moving all the links to here https://github.com/dmlc/xgboost/blob/master/demo/README.md

@phunterlau as well

**Comment by Far0n** [comment]
kk

**Comment by phunterlau** [comment]
I will add this and commit the full list.

**Comment by tqchen** [comment]
sounds great

**Pull request closed without merging**
