### PR TITLE
Processor Interface

### PR DESCRIPTION
**Pull request by nvidianz**
Processor interface with the dummy implementation.

### CODE REVIEW

**Comment by ZiyueXu77** [comment]
> Is this related to #9987?

yes, I will update 9987 with the HE interface design and link this PR there

**Comment by trivialfis** [comment]
Hi, is this ready for review?

**Comment by nvidianz** [comment]
> Hi, is this ready for review?

We are still making changes to support Secure XGBoost. I just turned it into draft. Thanks!

**Comment by da-niao-dan** [comment]
hello, I am just checking if I interpret this correctly:
1. The plugin package can only be dynamically linked (by .so file etc) and not statically linked.
2. The plugin package should create a processor class and then provide a .so file. 

right?

**Comment by nvidianz** [comment]
This PR is merged into https://github.com/dmlc/xgboost/pull/10124

**Pull request closed without merging**
