### PR TITLE
Support feature names in Python package 

### PR DESCRIPTION
**Pull request by sinhrks**
Python package can now handle feature names.

- Feature names can be set to ``DMatrix`` via ``feature_names`` kw as below(optional).
  - ``feature_names`` must be a list only consistes form alphanumerics. Because symbols may corrupt ``get_dump`` function.
```
dm = xgb.DMatrix(iris.data, label=iris.target,
                 feature_names=['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth'])
```
- When ``DMatrix`` with ``feature_names`` is passed to ``Booster``, ``Booster`` stores it. Once ``Booster`` has ``feature_names``, it will not accept ``DMatrix`` with different ``feature_names``. Because these are regarded as different data.
- ``get_fscore`` and ``get_dump`` will attach ``Booster``'s feature names if exists.
  - Thus, plotting functions can use it as below.

```
xgb.plot_importance(bst)
```
index

See my gist example for more detail.

https://gist.github.com/sinhrks/cc9a88f74074fc296e12#file-add_featurenames-ipynb

### CODE REVIEW

**Comment by tqchen** [comment]
Sorry for the delayed reply. I was traveling in past few days. 

The mac check seems was due to travis not being able to get graphviz correctly. Although this is not supposed to be your job, can you investigate it a bit?

Thanks for the effort!

**Comment by tqchen** [comment]
Another comment about string encoding and decoding.

It might be interesting to use ```c_str``` and add a function ```py_str``` in core.py to encode and decode strings in various choices.

**Comment by sinhrks** [comment]
@tqchen OK, test failure seems to be caused by scipy installation. I've fixed it to use [``miniconda``](http://conda.pydata.org/miniconda.html) because current test script gets little cluttered.

> Another comment about string encoding and decoding.

I may not understand what you mean, but because Python 3 use the unicode as the default, I don't think many users want to change encoding.

**Comment by tqchen** [comment]
OK, Thanks for the conrtibution :)

What I meant mainly is to have a central place to handle potential encoding and decoding. instead of doing decoding in many parts of code. i.e. always call ```c_str``` to convert python string into ctypes.char_p and always call ```py_str``` to convert things back

**Pull request merged**
