### PR TITLE
[jvm-packages] XGBoost Estimator and Model to work with XGBoostParams

### PR DESCRIPTION
**Pull request by tanwanirahul**

### CODE REVIEW

**Comment by tanwanirahul** [comment]
@CodingCat Please take a look. If there is a change needed for default values on XGBoostParams, please do let me know.

**Comment by CodingCat** [comment]
sure, thanks, I will review it

**Comment by CodingCat** [comment]
any update?

**Comment by CodingCat** [comment]
since this PR contains many conflicts, I have contained the params integration in https://github.com/dmlc/xgboost/pull/1664

@tanwanirahul thanks for your effort

**Pull request closed without merging**
