### PR TITLE
Original version is too slow for large model.

### PR DESCRIPTION
**Pull request by chenwq**

### CODE REVIEW

**Comment by terrytangyuan** [comment]
cc: @hetong007

**Comment by terrytangyuan** [comment]
@hetong007 Could you take a look?

**Comment by hetong007** [comment]
Hi @chenwq , it seems good to me. Can you please update the commit to resolve the conflicts? Thank you. Sorry for the late reply.

**Comment by pommedeterresautee** [comment]
xgb.model.dt.tree has been fully refactored for performance purpose.
Does this PR still make sense @chenwq ?

**Pull request closed without merging**
