### PR TITLE
Only set OpenMP_CXX_FLAGS when OpenMP is found

### PR DESCRIPTION
**Pull request by justinmills**
I found this trying to get the Mac build working without OpenMP. Tips in
issue #2596 helped to point in the right direction.

### CODE REVIEW

**Comment by justinmills** [comment]
Looks like in Cmake 3.9 (which I am using and I suspect is the version in #2596, they have changed the variable to indicate found from `OPENMP_FOUND` to `OpenMP_FOUND`. The travis system builds using cmake 3.2 (on linux at least) so it won't be setting the variable I'm checking for, thus it fails. My only guess as to why this is affecting the mac build on my machine but not on master is that the older version of cmake that the travis osx build is using does not set `OpenMP_CXX_FLAGS` to `NOTFOUND` and instead may just set it to "". Just a guess though. I'll update my check to check for either and see if that restores things.

**Comment by justinmills** [comment]
Not entirely sure I understand the drop in code coverage? Maybe my change causes different code to be compiled by default and thus different code paths?

**Comment by superbobry** [comment]
In my experience this codecov is unreliable. It is able to find "regressions" in the code your PR doesn't even touch.

**Comment by khotilov** [comment]
It looks like the issue in your first commit was fixed in https://gitlab.kitware.com/cmake/cmake/merge_requests/1233 
But travis still seems to be running the one-to-five months old cmake that still has this bug.

In https://gitlab.kitware.com/cmake/cmake/issues/17251 they recommend `if(OpenMP_FOUND OR OpenMP_CXX_FOUND)` as a workaround. But I think `if(OpenMP_CXX_FOUND OR OPENMP_FOUND)` would do as well.

**Comment by justinmills** [comment]
Thanks for merging.

**Pull request merged**
