### PR TITLE
[jvm-packages] Another pack of build/CI improvements

### PR DESCRIPTION
**Pull request by superbobry**
This fixes compilation issues on Windows and enables JVM build for OS X and Windows. The latter only builds the JNI bindings and doesn't run any tests.

### CODE REVIEW

**Comment by superbobry** [comment]
Added a WIP tag, because this breaks compilation on OS X apparrently :(

**Comment by superbobry** [comment]
The latest version builds on both OS X and Windows.

**Comment by CodingCat** [comment]
would you please update travis file in the repo to add OSX build ?

and if possible enable test for windows?

**Comment by superbobry** [comment]
I'm currently working on a test for Windows. I think there already is a test on OS X, but it doesn't include jvm-packages.

**Comment by superbobry** [comment]
Here's a failing build this PR fixes: https://ci.appveyor.com/project/tqchen/xgboost/build/1.0.770/job/bbkcj744k229ufs9.

**Comment by superbobry** [comment]
I've decided to squash this with #2424 and #2425.

**Comment by CodingCat** [comment]
I think #2423 can also be squashed into here?

**Comment by superbobry** [comment]
The build still fails on OS X. I'll have a look tomorrow.

**Comment by CodingCat** [comment]
if you look at OS X build, the job is terminated but reported as `PASS`, the reason for the job's termination is that it produces too long log ....would you mind adjusting the log level to ERROR in our test?

**Comment by superbobry** [comment]
I've added -q flag to Maven to suppress the "Downloading ..." messages. It would still output any failures encountered during the build.

**Comment by CodingCat** [comment]
I think MAVEN_OPTS is only for JVM options, you have to modify run_tests.sh to add -q

**Comment by superbobry** [comment]
Should be OK now.

**Comment by CodingCat** [comment]
yeah, it looks fine now, do you have any other changes to push?

**Comment by superbobry** [comment]
Yep, one more thing: I've removed libawt.so from the list of libraries to link for libxgboost4j.so. Other than that: I'm done.

**Comment by CodingCat** [comment]
Thanks, LGTM

what's the plan for enabling windows test and have a release script?

**Comment by superbobry** [comment]
Thanks!

I think we already can test `xgboost4j` on Windows, but `xgboost4j-spark` requires compiling `libhdfs`. As for the release, setting up something which deploys to GitHub Releases for each tag should be easy.

**Comment by CodingCat** [comment]
I do not have an environment in hand right now...

my question is how the packaged jar looks like right now? We eventually need jars containing native and java/scala code either one per platform (Linux/OSX/Windows(maybe skip Spark for windows)) or a single containing all so/dll files and select based on where it runs

**Comment by superbobry** [comment]
The way [I do it for now](https://github.com/criteo-forks/xgboost-jars/releases/tag/0.7-criteo-20170619115435) is:

1. Compile platform specific JARs for each platform. To be honest, the only platform-specific JAR we need is `xgboost4j`, because it carries the native library. But it's just easier to compile all of them.
2. Merge all JARs by platform. This would effectively create an `xgboost4j` JAR with three version of the native library. `NativeLibraryLoader` would then do the right thing depending on the platform.

**Comment by CodingCat** [comment]
all compilations are with Travis and Appveyor?

**Comment by CodingCat** [comment]
if that's the case, would you mind updating the README.md file to indicate the version of the build tool chain used in there?

**Comment by CodingCat** [comment]
BTW, I didn't find that tests are run in Appveyor? https://ci.appveyor.com/project/tqchen/xgboost/build/1.0.789?

**Comment by superbobry** [comment]
> all compilations are with Travis and Appveyor?

Yep, all but the last merging step. I do it on our internal Jenkins, but this again is just a Python script, so it could be executed on Travis/Appveyor.

> if that's the case, would you mind updating the README.md file to indicate the version of the build tool chain used in there?

You mean the README in dmlc/xgboost or in criteo-forks/xgboost-jars?

> I didn't find that tests are run in Appveyor? 

Nope, at the moment there're no tests. It just makes sure the thing compiles. But I doubt we could get Windows (or any other OS)-specific bugs, so testing on just one OS looks good enough.

**Comment by CodingCat** [comment]
for that python script, what it is doing is trigger test and download generated jar? if yes, is it possible to have a Travis/Appveyor version and add to the code base?

README in dmlc/xgboost 

for test in windows, I would like to avoid things like https://github.com/dmlc/xgboost/issues/2394

**Comment by superbobry** [comment]
> for that python script, what it is doing is trigger test and download generated jar?

There is no automatic trigger at the moment. 

> README in dmlc/xgboost

Sorry, I'm a bit confused. Where should I put the VS version note? It's being tested under both versions from appveyor.yml.

> for test in windows, I would like to avoid things like #2394

The only problem here is the dependency on libhdfs. Maybe I can setup a separate repo building libhdfs and publishing it to GitHub releases. Then in dmlc/xgboost we can fetch the prebuilt version, compile XGBoost with HDFS support and test xgboost4j as well as ont Spark/Flink.

**Comment by CodingCat** [comment]
> for that python script, what it is doing is trigger test and download generated jar?

>>　The build happens on each commit, but only builds triggered by tags are published to GitHub releases.

I see, I guess the only issue with this approach is that we need to expose a github credential with write permission to the repo in public? (I assume that the python script needs to setup github credentials to put jars on a separate branch...)

> README in dmlc/xgboost

>> Sorry, I'm a bit confused. Where should I put the VS version note? It's being tested under both versions from appveyor.yml.

VS is ok, what I am worrying about is GCC and libstdc++ version. The reason I would documented it is that a lot of users are stuck with a wrong gcc/libstdc++ version so that xgboost4j simply crashed....if we have a clear doc here, we can always say that we verified it is working in these versions

> for test in windows, I would like to avoid things like #2394

>> The only problem here is the dependency on libhdfs. Maybe I can setup a separate repo building libhdfs and publishing it to GitHub releases. Then in dmlc/xgboost we can fetch the prebuilt version, compile XGBoost with HDFS support and test xgboost4j as well as on Spark/Flink.

hmmm...it looks like too much comparing to the user group size of Spark under Windows, we can skip Spark/Flink release for windows

**Pull request merged**
