### PR TITLE
[Doc] Add dtreeviz as a showcase example of integration with 3rd-party software

### PR DESCRIPTION
**Pull request by hcho3**
https://github.com/parrt/dtreeviz

### CODE REVIEW

**Comment by hcho3** [comment]
@trivialfis They rely on `tree_to_dataframe()` and `predict()` methods, which we already have tests for.

**Comment by trivialfis** [comment]
Yup, but having a simple demo that can be tested on our side seems really nice and assuring during development.  It's not a heavy dependency anyway.  I can approve this PR and track it in a new issue if that's what you want.

**Comment by hcho3** [comment]
Sure, let's open a new issue for it.

**Comment by trivialfis** [comment]
https://github.com/dmlc/xgboost/issues/6015

**Pull request merged**
