### PR TITLE
[jvm-packages] try setting default profile

### PR DESCRIPTION
**Pull request by geoHeil**
https://github.com/dmlc/xgboost/issues/1858 sbt is not properly interpreting the properties specified in the per profile section of the pom.xml

Be sure to delete the cached variant in ~/.ivy2/caches/ml.dmlc....

### CODE REVIEW

**Comment by tqchen** [comment]
@CodingCat

**Comment by terrytangyuan** [comment]
@CodingCat LGTM. Could you take a look to double check?

**Comment by CodingCat** [comment]
@geoHeil would you mind removing the unrelated changes?

**Comment by geoHeil** [comment]
You mean the fix of maven profiles? Sure. Can look into that
Nan Zhu <notifications@github.com> schrieb am Di. 31. Jan. 2017 um 03:21:

**Comment by CodingCat** [comment]
no, I mean those changes on scala files

**Comment by geoHeil** [comment]
@CodingCat you mean the previous changes? Because this pull request should only have modified the pom.xml, the commit you sent me was my attempt to *remove* these unnecessary edits introduced in 24fcb0729d76e3087c263dce9890411b995ae6ed.

**Comment by CodingCat** [comment]
you can click `Files changed` view, you can see XGBoostModel.scala was unexpectedly modified

**Comment by CodingCat** [comment]
besides that Travis CI seems to be failing?

**Comment by geoHeil** [comment]
Yes, the latest changes were incomplete. I was missing the second file. Now travis should be green again.

**Comment by CodingCat** [comment]
thanks, will approve the PR once Travis passes

**Comment by CodingCat** [comment]
@tqchen , problem on codecov/project checking?

**Comment by tqchen** [comment]
Codecov is not required to get things merged, let me know if you cannot otherwise nexttime

**Pull request merged**
