### PR TITLE
[GPU-Plugin] Support for building to specific GPU architectures

### PR DESCRIPTION
**Pull request by teju85**

### CODE REVIEW

**Comment by RAMitchell** [comment]
I have just PRed code that auto detects the compute capability using the cmake build system. We could try to adapt this code to also work for the makefile or just use what you have here for the makefile only.

**Comment by teju85** [comment]
@RAMitchell  @pseudotensor 
After fetching and merging to the above PR, I'm facing the following build issue while using cmake. Am I missing some setup step here?
```$ make
[  1%] Building NVCC (Device) object CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o
ptxas fatal   : Unresolved extern function 'cudaDeviceSynchronize'
CMake Error at updater_gpu_generated_gpu_hist_builder.cu.o.cmake:266 (message):
  Error generating file
  /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/./updater_gpu_generated_gpu_hist_builder.cu.o


make[2]: *** [CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o] Error 1
make[1]: *** [CMakeFiles/updater_gpu.dir/all] Error 2
make: *** [all] Error 2
```

My env info:
```
$ cmake --version | head -n1
cmake version 3.5.2
$ make --version | head -n1
GNU Make 3.81
$ git log | head -n1
commit 41efe32aa588aad5ab3932b609762730ad07baad
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Mon_Jul_11_17:52:38_CDT_2016
Cuda compilation tools, release 8.0, V8.0.32
```
FWIW, my system has a P100 (sm_60).

**Comment by teju85** [comment]
And here's a more verbose version of the 'make' command.
```
$ make VERBOSE=1
/usr/local/bin/cmake -H/home/snanditale/xgb -B/home/snanditale/xgb/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/bin/cmake -E cmake_progress_start /home/snanditale/xgb/build/CMakeFiles /home/snanditale/xgb/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/snanditale/xgb/build'
make -f CMakeFiles/updater_gpu.dir/build.make CMakeFiles/updater_gpu.dir/depend
make[2]: Entering directory `/home/snanditale/xgb/build'
[  1%] Building NVCC (Device) object CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o
cd /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src && /usr/local/bin/cmake -E make_directory /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/.
cd /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src && /usr/local/bin/cmake -D verbose:BOOL=1 -D build_configuration:STRING= -D generated_file:STRING=/home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/./updater_gpu_generated_gpu_hist_builder.cu.o -D generated_cubin_file:STRING=/home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/./updater_gpu_generated_gpu_hist_builder.cu.o.cubin.txt -P /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o.cmake
-- Removing /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/./updater_gpu_generated_gpu_hist_builder.cu.o
/usr/local/bin/cmake -E remove /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/./updater_gpu_generated_gpu_hist_builder.cu.o
-- Generating dependency file: /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o.NVCC-depend
/usr/local/cuda-8.0/bin/nvcc -M -D__CUDACC__ /home/snanditale/xgb/plugin/updater_gpu/src/gpu_hist_builder.cu -o /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o.NVCC-depend -ccbin /usr/bin/X11/cc -m64 --std c++11 -Xcompiler ,\"-fopenmp\",\"-fPIC\",\"-O3\",\"-funroll-loops\",\"-msse2\",\"-D_MWAITXINTRIN_H_INCLUDED\",\"-D_FORCE_INLINES\",\"-g\" -lineinfo --expt-extended-lambda -gencode arch=compute_60,code=sm_60 -Xcudafe --diag_suppress=cc_clobber_ignored -Xcudafe --diag_suppress=integer_sign_change -Xcudafe --diag_suppress=useless_using_declaration -Xcudafe --diag_suppress=set_but_not_used -Xcompiler -fPIC -G -lineinfo -DNVCC -I/usr/local/cuda-8.0/include -I/home/snanditale/xgb/include -I/home/snanditale/xgb/dmlc-core/include -I/home/snanditale/xgb/rabit/include -I/home/snanditale/xgb/nccl/src -I/home/snanditale/xgb/cub -I/include -I/usr/local/cuda-8.0/include
-- Generating temporary cmake readable file: /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o.depend.tmp
/usr/local/bin/cmake -D input_file:FILEPATH=/home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o.NVCC-depend -D output_file:FILEPATH=/home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o.depend.tmp -P /usr/local/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake
-- Copy if different /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o.depend.tmp to /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o.depend
/usr/local/bin/cmake -E copy_if_different /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o.depend.tmp /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o.depend
-- Removing /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o.depend.tmp and /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o.NVCC-depend
/usr/local/bin/cmake -E remove /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o.depend.tmp /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o.NVCC-depend
-- Generating /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/./updater_gpu_generated_gpu_hist_builder.cu.o
/usr/local/cuda-8.0/bin/nvcc /home/snanditale/xgb/plugin/updater_gpu/src/gpu_hist_builder.cu -c -o /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/./updater_gpu_generated_gpu_hist_builder.cu.o -ccbin /usr/bin/X11/cc -m64 --std c++11 -Xcompiler ,\"-fopenmp\",\"-fPIC\",\"-O3\",\"-funroll-loops\",\"-msse2\",\"-D_MWAITXINTRIN_H_INCLUDED\",\"-D_FORCE_INLINES\",\"-g\" -lineinfo --expt-extended-lambda -gencode arch=compute_60,code=sm_60 -Xcudafe --diag_suppress=cc_clobber_ignored -Xcudafe --diag_suppress=integer_sign_change -Xcudafe --diag_suppress=useless_using_declaration -Xcudafe --diag_suppress=set_but_not_used -Xcompiler -fPIC -G -lineinfo -DNVCC -I/usr/local/cuda-8.0/include -I/home/snanditale/xgb/include -I/home/snanditale/xgb/dmlc-core/include -I/home/snanditale/xgb/rabit/include -I/home/snanditale/xgb/nccl/src -I/home/snanditale/xgb/cub -I/include -I/usr/local/cuda-8.0/include
ptxas fatal   : Unresolved extern function 'cudaDeviceSynchronize'
-- Removing /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/./updater_gpu_generated_gpu_hist_builder.cu.o
/usr/local/bin/cmake -E remove /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/./updater_gpu_generated_gpu_hist_builder.cu.o
CMake Error at updater_gpu_generated_gpu_hist_builder.cu.o.cmake:266 (message):
  Error generating file
  /home/snanditale/xgb/build/CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/./updater_gpu_generated_gpu_hist_builder.cu.o


make[2]: *** [CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o] Error 1
make[2]: Leaving directory `/home/snanditale/xgb/build'
make[1]: *** [CMakeFiles/updater_gpu.dir/all] Error 2
make[1]: Leaving directory `/home/snanditale/xgb/build'
make: *** [all] Error 2
```

**Comment by beniz** [comment]
I was able to go one step further when hitting the same error (though on the master branch, not trying to merge this PR) by adding `--relocatable-device-code true` to the `nvcc` flags. However, another error appears:

```
xgboost/cub/cub/device/dispatch/dispatch_reduce.cuh(468): error: cannot pass an argument with a user-provided copy-constructor to a device-side kernel launch
```

**Comment by teju85** [comment]
Thanks @beniz. -rdc=true helped proceed one step further.
However, now I observe that the compilation time has increased considerably.
And I now do observe the same 'cub' related error as you and it seems to appear from our recently merged grow_gpu plugin.
Investigating...

**Comment by pseudotensor** [comment]
Hi @tuju85  I always observed that the compile time with compute_61 is very much longer than other computes like 52 or 35.  You can try reducing the compute.  I have seen that slowdown in compile on many codes, not just xgboost.  So I assume it's a nvcc/ptxas issue?

As for the "ptxas fatal   : Unresolved extern function 'cudaDeviceSynchronize'" .  I have seen that in windows with compute_61, but I haven't seen it in linux (my boards on various systems are compute_61).  If you google the error,  you see it mentioned alot, e.g https://github.com/thrust/thrust/issues/864

@beniz Interesting you saw that in the master branch, which suggests it's not specific to my PR.  We should probably add that compile option to avoid the error, assuming we understand what is going on.

**Comment by teju85** [comment]
@pseudotensor
I started to see this compile time problem on sm_60 as well, when I pulled in the latest set of changes this morning (IST). For example: I now have a build that's stuck at compiling gpu_hist_builder for ~20 mins now!
```[  1%] Building NVCC (Device) object CMakeFiles/updater_gpu.dir/plugin/updater_gpu/src/updater_gpu_generated_gpu_hist_builder.cu.o```

>Interesting you saw that in the master branch, which suggests it's not specific to my PR.
why do you say its not specific to your PR?

**Comment by pseudotensor** [comment]
@teju85 I was probably confused by what @beniz said.  What happens if you do compute_35?  If the compile still goes and is faster, this shows it's just nvcc/ptxas and not the code in particular.

**Comment by teju85** [comment]
@pseudotensor I tried for sm_35 as well and the same issue persists. :(

In parallel, here's a small experiment I performed:
1. Made '#define NCCL 0' and disabled nccl calls from CMakeLists.txt and ran cmake build flow. The compilation was stuck at gpu_hist_builder.cu for ~20 mins as mentioned above.
2. Now, with the same changes as in previous step, I used the make flow to build xgboost (make PLUGIN_UPDATER_GPU=ON). This, however, completed in ~5 mins!
So, there's something different that happens with the cmake build flow, that's causing the previously mentioned issues.

Let me try to disable the auto detection feature from cmake and see what happens...

**Comment by teju85** [comment]
hmm.. the auto detection indeed seems to cause issues with gpu plugin build. But similar logic works fine in NCCL! Maybe something to do with the use of cub by the gpu plugin? I need to look into the generated nvcc commandline options deeper before confirming the same.

But, by removing the auto-detection logic, and re-introducing my initial changes at the beginning of this PR seem to compile everything properly.

I have updated this PR with those changes as well. Kindly review @pseudotensor

**Comment by teju85** [comment]
@pseudotensor I think that this should also resolve the compute_61 related grow_gpu failures you were seeing previously. Can you check this one too?
Thanks

**Comment by pseudotensor** [comment]
@teju85  Ya, if your version of the autodetect avoids problems, might as well go with it.  I just used dmlc/mshadow and their single line replacement, but maybe there are issues.

**Comment by pseudotensor** [comment]
@teju85 @RAMitchell I see this was accepted.  The code doesn't compile for me even in linux with make -j.  Because the code compiles the same code twice, there is a conflict in files overlapping writing.  I fixed this with some other changes, but that got wiped out.

[ 91%] Building NVCC (Device) object CMakeFiles/cuda_compile.dir/plugin/updater_gpu/src/cuda_compile_generated_updater_gpu.cu.o
[ 93%] Building NVCC (Device) object CMakeFiles/cuda_compile.dir/plugin/updater_gpu/src/cuda_compile_generated_gpu_hist_builder.cu.o
[ 95%] Building NVCC (Device) object CMakeFiles/cuda_compile.dir/plugin/updater_gpu/src/cuda_compile_generated_gpu_hist_builder.cu.o
[ 96%] Building NVCC (Device) object CMakeFiles/cuda_compile.dir/plugin/updater_gpu/src/cuda_compile_generated_updater_gpu.cu.o
Error copying file (if different) from "/data/jon/xgboost.mine/build/CMakeFiles/cuda_compile.dir/plugin/updater_gpu/src/cuda_compile_generated_gpu_hist_builder.cu.o.depend.tmp" to "/data/jon/xgboost.mine/build/CMakeFiles/cuda_compile.dir/plugin/updater_gpu/src/cuda_compile_generated_gpu_hist_builder.cu.o.depend".
CMake Error at cuda_compile_generated_gpu_hist_builder.cu.o.cmake:232 (message):
  Error generating
  /data/jon/xgboost.mine/build/CMakeFiles/cuda_compile.dir/plugin/updater_gpu/src/./cuda_compile_generated_gpu_hist_builder.cu.o


CMakeFiles/xgboost.dir/build.make:70: recipe for target 'CMakeFiles/cuda_compile.dir/plugin/updater_gpu/src/cuda_compile_generated_gpu_hist_builder.cu.o' failed
make[2]: *** [CMakeFiles/cuda_compile.dir/plugin/updater_gpu/src/cuda_compile_generated_gpu_hist_builder.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by pseudotensor** [comment]
@RAMitchell Did you test this on windows already?

**Comment by RAMitchell** [comment]
Yep I test everything on Windows before merging.

FYI @teju85 @pseudotensor  I might have Linux continuous integration working in the next couple of days.

**Comment by pseudotensor** [comment]
On nimbix, Arno can't run with latest PR and gets the below.  If he uses the code prior to this PR then things run fine.

[05:29:24] /data/xgboost/dmlc-core/include/dmlc/././logging.h:300: [05:29:24] /data/xgboost/plugin/updater_gpu/src/updater_gpu.cu:73: GPU plugin exception: function_attributes(): after cudaFuncGetAttributes: invalid device function
Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python3.6/dist-packages/xgboost-0.6-py3.6.egg/xgboost/libxgboost.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x2b470b07144c]
[bt] (1) /usr/local/lib/python3.6/dist-packages/xgboost-0.6-py3.6.egg/xgboost/libxgboost.so(_ZN7xgboost4tree12GPUHistMakerINS0_9GradStatsEE6UpdateERKSt6vectorINS_9bst_gpairESaIS5_EEPNS_7DMatrixERKS4_IPNS_7RegTreeESaISD_EE+0x47d) [0x2b470b1ff43d]
[bt] (2) /usr/local/lib/python3.6/dist-packages/xgboost-0.6-py3.6.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesERKSt6vectorINS_9bst_gpairESaIS3_EEPNS_7DMatrixEiPS2_ISt10unique_ptrINS_7RegTreeESt14default_deleteISB_EESaISE_EE+0x8c3) [0x2b470b105953]
[bt] (3) /usr/local/lib/python3.6/dist-packages/xgboost-0.6-py3.6.egg/xgboost/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPSt6vectorINS_9bst_gpairESaIS5_EEPNS_11ObjFunctionE+0x86d) [0x2b470b106a1d]
[bt] (4) /usr/local/lib/python3.6/dist-packages/xgboost-0.6-py3.6.egg/xgboost/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x22b) [0x2b470b1f7a4b]
[bt] (5) /usr/local/lib/python3.6/dist-packages/xgboost-0.6-py3.6.egg/xgboost/libxgboost.so(XGBoosterUpdateOneIter+0x27) [0x2b470b063467]
[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x2b4675909e40]
[bt] (7) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x2b46759098ab]
[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2cf) [0x2b46756f697f]
[bt] (9) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x8949) [0x2b46756ed949]
Traceback (most recent call last):

**Pull request merged**
