### PR TITLE
Spark example

### PR DESCRIPTION
**Pull request by CodingCat**

### CODE REVIEW

**Comment by tqchen** [comment]
need merge with the lastest master

**Comment by CodingCat** [comment]
@tqchen I merged with master, I still feel that we need to monitor the tracker's return value by calling waitFor, who knows what will happen.....

**Comment by tqchen** [comment]
We can do that via asynchronous thread that wait and throw exception if
something is wrong

**Comment by CodingCat** [comment]
that's what I'm doing currently

**Comment by CodingCat** [comment]
it's done

**Pull request merged**
