### PR TITLE
Save models from xgb.cv

### PR DESCRIPTION
**Pull request by vykhand**
#793 Please note that this change have not been tested. I could not install xgboost from the most recent repository due to some compilation errors - missing logging.h.

### CODE REVIEW

**Comment by pommedeterresautee** [comment]
try this to update your repository
```
git submodule init
git submodule update
```

**Comment by vykhand** [comment]
Hi! Thanks for kind words. I can't figure out what is wrong. I did 
`git submodule init
git submodule update`

before the pull request but after commit. and then again after I got the appveyor error message/. 

How do I fix it now?

**Comment by pommedeterresautee** [comment]
Do you compile on your computer now ?
Have you seen that:
https://github.com/dmlc/xgboost/blob/5d9b80cd8bef05e6f3fd7d4b7624d9a17c255978/doc/build.md#trouble-shooting

**Comment by pommedeterresautee** [comment]
regarding AppVeyor, I don't think it is related to you.

**Comment by vykhand** [comment]
Ah, sorry I thought you were talking about AppVeyor issue, the compilation issue is different - I am getting the exact same message as 

https://github.com/dmlc/xgboost/issues/797

I don't think it could be related to submodules. I am getting it when installing from github from my repo and as well from dmlc.

**Comment by vykhand** [comment]
Hi Guys,

I am fairly new to the process of contributing to XGB, or to any other SW to be honest. 
I fail to re-install xgb from my own git to test my change, due to some problems with compilation.
Is there any other way to test?
Otherwise, may be someone would be so kind and test my change?

With respect, Andrey

**Comment by tqchen** [comment]
@terrytangyuan can you look into this change and see if it can be merged? The Travis tests already passed

**Comment by tqchen** [comment]
@vykhand sorry for the slow action on this. Can you also add an example on how to use this feature, as well as a testcase? 

Thanks

**Comment by vykhand** [comment]
Hi @tqchen,

Something like this should work :

`library(xgboost)
data(agaricus.train, package='xgboost')
dtrain <- xgb.DMatrix(agaricus.train$data, label = agaricus.train$label)
history <- xgb.cv(data = dtrain, nround=3, nthread = 2, nfold = 5, metrics=list("rmse","auc"),
                  max.depth =3, eta = 1, objective = "binary:logistic", prediction = TRUE)

#in structure, there must be a list named "models" with 5 elements, model1 .. model5
str(history)

#test that we can save all 5 models for later reuse
models <-  history$models
for (i in 1:length(models) ) xgb.save(models[[i]],paste0("model",i,".xgb"))
`

**Comment by terrytangyuan** [comment]
@vykhand  Thanks. Maybe let users specify how many top models to save? They probably don't want to save all of them.

**Comment by vykhand** [comment]
Hi @tqchen,

You are right, I was thinking more about the separate parameter called save_models with default to 0, and if is other than 0, the xgb.cv would save x top models based on the metric.

I did it this way because it was the simplest/quickest way. I would probably do it in a more complicated way, but the stopper is that I can't compile from my own git (and from this git also). I get the missing logging.h error above. I just tested it again after fetching new changes - no luck. It appears on 3 machines - my windows laptop, centos VM and ubuntu VM.

**Comment by vykhand** [comment]
Hi @tqchen, I managed to check this change and sadly it is not working. The models list is not a list of xgb.Boosters, but instead is a list of Booster.handles. As I am now able to test this, I will try to figure out a better way.

**Comment by tqchen** [comment]
closing this for now, see https://github.com/dmlc/xgboost/issues/892 for new guideline in enhancing training API

**Pull request closed without merging**
