### PR TITLE
[TREE] Interaction constraints

### PR DESCRIPTION
**Pull request by BlueTea88**
I would like to incorporate interaction constraints functionality in tree building.
It currently only supports the API in R and in the exact greedy algorithm on multi-core.

Please see #3135 for more information.

First time trying to contribute so let me know if there are any issues or you require more information.

### CODE REVIEW

**Comment by BlueTea88** [comment]
Thanks.  I haven't found other papers mentioning interaction constraints.  But I only did a quick search on google as I don't have access to academic archives.

**Comment by hcho3** [comment]
I am hesitant to merge this PR because it adds a lot of new logic to the updater itself that's orthogonal to the tree algorithm. The updater should ideally consist mainly of algorithm.

When you get a chance, can you look at #3335? It creates a nice abstraction called SplitEvaluator. Your use case may be accommodated by creating a SplitEvaluator that assigns infinite penalty on splits that violate feature interaction constraints.

**Comment by BlueTea88** [comment]
Sure. I just had a quick look at #3335 and it does seem more elegant to separate out the constraints.

**Comment by hcho3** [comment]
I'll be working with the author of #3335 to make a room for feature interaction constraints. I'll keep you updated. Thanks!

**Comment by BlueTea88** [comment]
Great, I will subscribe to that PR to as well.  Thank you.

**Pull request closed without merging**
