### PR TITLE
typos in code

### PR DESCRIPTION
**Pull request by Ammar-Azman**
- Change code example typos:
    - `resutls` to `results`

### CODE REVIEW

**Review by trivialfis — APPROVED** [review]
Thank you for the fix!

**Comment by Ammar-Azman** [comment]
Seems that some most of buildkite is not successful. Can I know why?

**Comment by trivialfis** [comment]
It requires manual trigger, I didn't trigger it for typo fix.

**Comment by Ammar-Azman** [comment]
Am I need to trigger it manually?

**Comment by hcho3** [comment]
@Ammar-Azman No, only administrators can do that.

**Pull request merged**
