### PR TITLE
Improve allgather functions

### PR DESCRIPTION
**Pull request by rongou**
- Change the interface to take vectors to make it easier to call
- Implemented `AllgatherV`
- Implemented allgather of strings, needed for syncing column-split feature names/types

### CODE REVIEW

**Comment by rongou** [comment]
@trivialfis

**Review by trivialfis — COMMENTED** [review]
Overall looks good to me.

- Could you please look into the test failure?
- Is there a way to consolidate the interface into something more compact? I'm working on revamping the coll implementation and find it quite difficult to work on at the moment. There are many variants of the interface, some supported by GPU some others are not.

**Comment by rongou** [comment]
Not sure about the test failure. I can't reproduce it on my desktop, even after downgrade gcc from 12 to 9. Any ideas?

Yeah the current interfaces evolved from the original rabit/nccl implementations. Need to invest some additional effort to try to unify them.

**Comment by trivialfis** [comment]
@rongou I think it's a sanitizer error. You can enable it through the cmake flag `USE_SANITIZER=ON` and `ENABLED_SANITIZERS=address;undefined`. For other related flags to get CUDA to work, see `doc/contrib/unit_tests.rst`.

**Comment by rongou** [comment]
@trivialfis Finally got the CI to pass. Please take another look. Thanks!

**Pull request merged**
