### PR TITLE
[Temporary] Multi-GPU predictor

### PR DESCRIPTION
**Pull request by trivialfis**
Please ignore this PR.  I'm attempting to resolve the bug in https://github.com/dmlc/xgboost/pull/3738 . Creating a temporary PR allows me to peek at Jenkins without polluting @canonizer 's branch.

### CODE REVIEW

**Comment by hcho3** [comment]
@trivialfis FYI, now that you are a committer, you have ability to interrupt any CI jobs as well. This may be helpful when you run into executor starvation on Jenkins.

**Comment by trivialfis** [comment]
@hcho3 I looked around the Jenkins interface, only relevant button I saw is "Restart Jenkins: Build & Test".  Which, doens't do anything.

**Comment by hcho3** [comment]
@trivialfis Look for the square stop icon on the top right corner:
screen shot 2018-10-22 at 10 53 21 pm

**Comment by hcho3** [comment]
Also, current setup involves 3 re-tries, so you may have to press the stop button multiple times.

**Comment by trivialfis** [comment]
@hcho3 
screenshot from 2018-10-23 18-55-39

**Comment by hcho3** [comment]
@trivialfis Ugh, I thought all committers had admin rights on Jenkins, but it doesn't seem to be the case. Let me fix this.

**Comment by trivialfis** [comment]
@hcho3  Thanks, that would be a great help!

**Comment by hcho3** [comment]
@trivialfis Looks like I had to manually add you to the admin list. Try it again.

**Comment by hcho3** [comment]
Actually, with a recent Jenkins update, the Stop button now properly works with the retry block. Pressing it once should stop all jobs.

**Comment by trivialfis** [comment]
@hcho3 I tried it again, it's "HTTP ERROR 404" now. 
screenshot from 2018-10-23 20-38-30

**Comment by hcho3** [comment]
Can you access the page https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-3819/4/pipeline/ ?

**Comment by trivialfis** [comment]
@hcho3 Yes, this one works.

**Comment by trivialfis** [comment]
@hcho3 But still no access permission (the stop button isn't there).

**Comment by hcho3** [comment]
Try stopping it and see if it works.

**Comment by trivialfis** [comment]
@hcho3 Oh, after a refresh now I see it.  It works.  Thanks! :)

**Comment by hcho3** [comment]
Good to hear that. You are now able to stop and re-start any CI jobs. Now let's see if we can figure out why multi-GPU test is failing.

**Comment by trivialfis** [comment]
@hcho3 I'm able to stop it, but not restart it.  You can see from the log a java exception "java.lang.NullPointerException: Cannot invoke method getBuildName() on null object
" is thrown after restart.   But I will trigger it by amend commit so it doesn't really matter.

Thanks a lot!  Let me try to figure something out.

**Comment by hcho3** [comment]
@trivialfis That's curious. For now, let's focus on the multi-GPU test. Jenkins setup is relatively new, and it can be improved in the future.

**Comment by hcho3** [comment]
@trivialfis FYI, there are two buttons for restart. Make sure to use the one on the top (without text), not the one at bottom with text.
screen shot 2018-10-23 at 12 54 43 am

**Comment by trivialfis** [comment]
@hcho3 Got it.

**Comment by trivialfis** [comment]
@hcho3 Can appvayor be cancelled?

**Comment by hcho3** [comment]
@trivialfis Yes. Do you see this button on the top right?
screen shot 2018-10-23 at 1 02 31 am
If not, your account is not yet under the `tqchen` group. For this, we'll have to reach out to Tianqi.

**Comment by hcho3** [comment]
In the long run, I'm looking to migrate all Windows tests to Jenkins. You can run many tests in parallel, and each worker can be customized.

**Comment by trivialfis** [comment]
@hcho3 After logging out and log back, I can cancel the appvayor now. :)

That's a good plan,  I am also thinking about if we can reduce or combine some expensive tests.  Will discuss about it later on.

**Comment by trivialfis** [comment]
@hcho3 Last commit in this PR solved the problem.  I will push it to original PR tomorrow.  Thanks for all the help!

**Comment by hcho3** [comment]
@trivialfis No problem. BTW, does your fix work when `n_row = 8`? Otherwise we should raise an error whenever [number of data row] < [number of GPUs]. Alternatively, we can proactively change number of GPUs to fit the number of data rows.

**Comment by trivialfis** [comment]
@hcho3 Good point. Let me keep looking.

**Comment by hcho3** [comment]
@trivialfis I found out that Jenkins was showing 404 for anonymous users. I fixed the configuration to address this.

**Comment by trivialfis** [comment]
@hcho3 Glad to hear that. :)

**Pull request closed without merging**
