### PR TITLE
[dask] Allow empty data matrix in AFT survival

### LINKED ISSUE #6139: Allow empty datasets in `survival:aft` objective and `aft-nloglik` metric
Currently, `survival:aft` objective and `aft-nloglik` metric throws an error when an empty data matrix is passed in. Empty data matrix is a common occurrence when XGBoost is used with Dask, due to quirks in how Dask partitions the data matrix.

The AFT objective and metric should handle empty data matrices like other element-wise objective and metrics, such as `reg:squarederror` and `logloss`.

cc @trivialfis

### PR DESCRIPTION
**Pull request by hcho3**
Closes #6139

### CODE REVIEW

**Review by trivialfis — APPROVED** [review]

**Comment by trivialfis** [comment]
Actually you might need to add a unittest.  The dask interface is no longer using all workers

**Comment by hcho3** [comment]
Any suggestion? Is it sufficient to pass in an empty `DMatrix`?

**Comment by trivialfis** [comment]
Yup.

**Review by trivialfis — APPROVED** [review]
LGTM

**Pull request merged**
