### PR TITLE
Update 0.8 version num

### PR DESCRIPTION
**Pull request by CodingCat**
@hcho3 I think in future, if you want, you can just go to jvm-packages/ and run `dev/change_version.sh 0.72-SNAPSHOT 0.80-SNAPSHOT` when you prepare the release so that we can merge the commit with the formal release one

### CODE REVIEW

**Comment by hcho3** [comment]
@CodingCat Got it. So the latest master should be labeled as `xxx-SNAPSHOT` where `xxx` is the next upcoming release?

**Comment by CodingCat** [comment]
yes, that's right

**Comment by pvillacorta-stratio** [comment]
Excuse me, I've just compiled the jvm package with `mvn -DskipTests=true -Dspark.version=2.2.0 package` but it is not creating the jar-with-dependencies file, only xgboost4j-spark-0.80-SNAPSHOT.jar. I remember to have created it without problems a month ago. Am I missing something? Thanks

**Comment by jzhu-apixio** [comment]
@CodingCat, will 0.8.0 work with spark 2.3?  Thanks so much.

**Pull request merged**
