### PR TITLE
support cuda 10.1

### PR DESCRIPTION
**Pull request by rongou**
Doesn't quite work yet, I'm getting compilations errors:
```bash
/home/rou/src/xgboost/src/common/host_device_vector.cu: In instantiation of ‘void xgboost::HostDeviceVectorImpl<T>::DeviceShard::Init(xgboost::HostDeviceVectorImpl<T>*, int) [with T = long unsigned int]’:
/home/rou/src/xgboost/src/common/host_device_vector.cu:205:1:   required from ‘xgboost::HostDeviceVectorImpl<T>::InitShards()::<lambda(int, xgboost::HostDeviceVectorImpl<T>::DeviceShard&)> [with T = long unsigned int]’
/home/rou/src/xgboost/src/common/host_device_vector.cu:205:13:   required from ‘struct xgboost::HostDeviceVectorImpl<T>::InitShards() [with T = long unsigned int]::<lambda(int, struct xgboost::HostDeviceVectorImpl<long unsigned int>::DeviceShard&)>’
/home/rou/src/xgboost/src/common/host_device_vector.cu:204:23:   required from ‘void xgboost::HostDeviceVectorImpl<T>::InitShards() [with T = long unsigned int]’
/home/rou/src/xgboost/src/common/host_device_vector.cu:171:11:   required from ‘xgboost::HostDeviceVectorImpl<T>::HostDeviceVectorImpl(size_t, T, xgboost::GPUDistribution) [with T = long unsigned int; size_t = long unsigned int]’
/home/rou/src/xgboost/src/common/host_device_vector.cu:430:12:   required from ‘xgboost::HostDeviceVector<T>::HostDeviceVector(size_t, T, xgboost::GPUDistribution) [with T = long unsigned int; size_t = long unsigned int]’
/home/rou/src/xgboost/include/xgboost/data.h:186:14:   required from here
/home/rou/src/xgboost/src/common/host_device_vector.cu:56:16: error: cannot call member function ‘size_t xgboost::HostDeviceVectorImpl<T>::Size() const [with T = long unsigned int; size_t = long unsigned int]’ without object
       LazyResize(vec_->Size());
            ~~~~^~
```

### CODE REVIEW

**Comment by rongou** [comment]
The error is similar to https://github.com/protocolbuffers/protobuf/issues/5805 and https://github.com/tensorflow/tensorflow/issues/26155.

**Comment by RAMitchell** [comment]
Can you please add a new entry to the Jenkinsfile build matrix for cuda 10.1.

I think we can also remove the second entry from the build matrix, we should have sufficient coverage without it and it will speed up CI:
```def buildMatrix = [
    [ "enabled": true,  "os" : "linux", "withGpu": true, "withNccl": true,  "withOmp": true, "pythonVersion": "2.7", "cudaVersion": "9.2", "multiGpu": true],
    [ "enabled": true,  "os" : "linux", "withGpu": true, "withNccl": true,  "withOmp": true, "pythonVersion": "2.7", "cudaVersion": "9.2" ],
    [ "enabled": true,  "os" : "linux", "withGpu": true, "withNccl": true,  "withOmp": true, "pythonVersion": "2.7", "cudaVersion": "8.0" ],
    [ "enabled": true,  "os" : "linux", "withGpu": true, "withNccl": false, "withOmp": true, "pythonVersion": "2.7", "cudaVersion": "8.0" ],
]```

**Comment by rongou** [comment]
Thought this was a compiler bug, I built gcc 8.3 from source, but still getting the same error.

**Comment by rongou** [comment]
Wow, it is a compiler bug. Got everything built under gcc 6.

**Comment by rongou** [comment]
@RAMitchell added 10.1 to the build matrix.

This should work now as long as we stick with gcc 6.

**Comment by trivialfis** [comment]
@rongou That's problematic.  We might need to workaround that.  Is it possible to file an issue at GCC with host code only?

**Comment by rongou** [comment]
Fixes #4220

**Comment by hcho3** [comment]
Wait, is 10.1 container available already?

**Comment by rongou** [comment]
@hcho3 yeah just got pushed to docker hub.

@trivialfis agreed. Maybe we should be less ambitious and stick with cuda 10.0 for now. Let me try to figure out if I can reproduce the bug easily.

**Comment by rongou** [comment]
Hmm, maybe it's actually a cuda sdk bug. In the generated `host_device_vector.cudafe1.cpp`, that line is changed to `LazyResize(Size());`, which is obviously incorrect.

**Comment by trivialfis** [comment]
@rongou Any way I worked around it by de-referencing the pointer first:
```  c++
(*vec_).size();
```

**Comment by rongou** [comment]
@trivialfis cool, that's a good workaround for now. I made the change and added a TODO.

**Pull request merged**
