### PR TITLE
[python-package] Provide a learning_rates parameter to xgb.cv()

### PR DESCRIPTION
**Pull request by JivanRoquet**
_- See issue #1769 -_

Currently the `learning_rates` parameter, which can take either a list of learning rates, or a callback function computing learning rates in a dynamic manner, is available in the `xgb.train()` method.

However, it's not available in the `xgb.cv()` method. Having this parameter could prove handy when doing CV as well as when doing regular training.

Even if the functionality is available by crafting a custom callback, I suggest making `learning_rates` parameter available from `xgb.cv()` for convenience purposes.

### CODE REVIEW

**Comment by JivanRoquet** [comment]
@tqchen any news on this one?

I would gladly accept a feedback or code review when a core team member has some time.

**Comment by tqchen** [comment]
Thanks, the callback function looks good to me.
As discussed in last issue. We would like to gradually deprecate the additional parameters and fully switch to list of callbacks.

So I would like to accept the changes of callback function, possibly we could add an sample on how to achieve this using callback API

**Comment by JivanRoquet** [comment]
@tqchen do you mean that you would provide access to `callbacks` through this:

```python
from xgboost import callbacks
```

In such a case, to achieve the desired result using callback API, an example would be:

```python
from xgboost import callbacks as xgb_callbacks

def my_learning_rates(n, ntot):
    return some_learning_rate

params = {
    'eta': 0.05
}

cv_params = {
    'callbacks': [xgb_callbacks.reset_learning_rate(my_learning_rates)]
}

xgb.cv(params, dmatrix, 500, **cv_params)
```

What do you think about that?

**Comment by tqchen** [comment]
Yes, I mean

```
import xgboost as xgb

xgb.cv(params, dmatrix, 500, callbacks = [ xgb.callback.reset_learning_rate(my_learning_rates, caller='cv')])
```

**Comment by JivanRoquet** [comment]
@tqchen added a `_get_callback_context` method and merged the two callbacks.

Since only the callback can be aware of its context (and not the function returning the callback, since this one is called from the user's module while setting parameters), I merged the two callbacks and made a helper function to get the context.

Context is defined by the following rule:

- if `env.model` is `None` and `env.cvfolds` is not `None` --> context `cv`
- if `env.model` is not `None` and `env.cvfolds` is `None` --> context `train`

**Comment by tqchen** [comment]
I think this is good.  I do think we should remove the learning_rates options from cv, and instead add an example to directly use callback. We would deprecate the other learning_rates options in train and use callbacks.

This makes the interface cleaner in the long term(although it could hurt in short term)

**Comment by JivanRoquet** [comment]
I totally understand the direction towards deprecating parameters.

Where would you want the example of using callbacks to be displayed?

I guess this callback API could have a documentation section on its own? Or do you want to show this examples directly in functions' docstrings (which could be cumbersome)?

**Comment by terrytangyuan** [comment]
Might be better to have a separate example dedicated for callbacks

**Comment by JivanRoquet** [comment]
I just added a quick example on how to use `xgb.callback` module to call predefined callbacks, both in `train()` and in `cv()`.

The actual documentation and examples for each specific callback function is already in `callback.py`.

**Comment by tqchen** [comment]
Cool, Thanks for the effort! This is merged

**Pull request merged**
