### PR TITLE
Initial support for multi-output regression.

### PR DESCRIPTION
**Pull request by trivialfis**
* Implemented as 1 model per target.
* Not available for classification yet.

I will follow up with R and dask implementations if this PR is approved.

Related: https://github.com/dmlc/xgboost/issues/2087 .

Todos:
- [x] Verify data types other than numpy array.
- [ ] Have better specification for return shape.

### CODE REVIEW

**Comment by Craigacp** [comment]
That's exciting. We'd be interested in a XGBoost4J wrapper too, and I might be able to write such a thing once you're happy with the native API. We currently fake this up by training a separate Booster for each output dimension.

**Comment by trivialfis** [comment]
TO-DO for initial support of multi-target model training.  

- [ ] A typed tensor view that can be used in GPU kernels: https://github.com/dmlc/xgboost/pull/7365
- [ ] Typed tensor storage.
- [ ] Type erased tensor for accepting user inputs.  This is available as the array interface class, we just need to extend it to a higher dimension.
- [ ] Convert labels and base margin into matrix/tensor with proper shape attributes.
- [ ] Define the tree index for target, similar to what we currently have as group idx.

**Comment by trivialfis** [comment]
Most of the basic infrastructures are in place now.  Need more thought on classification problem due to different number of classes per target.

**Comment by trivialfis** [comment]
The initial support is merged in https://github.com/dmlc/xgboost/pull/7514 .

**Comment by trivialfis** [comment]
@Craigacp I think for multi-target classification models, xgboost needs a new interface for and potentially lots of refactoring.  I will focus on regression for now.  Thank you for joining the discussion and feel free to test the new feature. ;-)

**Comment by aniruddhghatpande** [comment]
@trivialfis  Is this contain support for all multi output regression ? @Craigacp were you able to write the wrapper for XGBoost4J ?

**Comment by Craigacp** [comment]
I haven't looked into it. I've had less time to work on XGBoost related things for the past couple of years.

**Pull request closed without merging**
