### PR TITLE
Remove extra sync for dense data

### PR DESCRIPTION
**Pull request by ShvetsKS**

### CODE REVIEW

**Review by trivialfis — COMMENTED** [review]
Thanks for the quick fix!  Could you please have some tests?

**Comment by ShvetsKS** [comment]
> Thanks for the quick fix! Could you please have some tests?

done

**Review by trivialfis — APPROVED** [review]
Will merge once the tests have passed.


TODO: Follow up with tests for other tree methods.

**Comment by ShvetsKS** [comment]
> TODO: Follow up with tests for other tree methods.

just added the parameters for `approx` also

**Pull request merged**
