### PR TITLE
Follow Docstring Conventions

### PR DESCRIPTION
**Pull request by TheJacobKim**
## PR Description
I have noticed an inconsistent convention used throughout xgboost's core Python file. So I made some changes that will make the core file to respect docstring conventions according to [PEP 257](https://www.python.org/dev/peps/pep-0257/).

### CODE REVIEW

**Comment by RAMitchell** [comment]
Thanks, is it possible to enforce this via pylint?

**Comment by trivialfis** [comment]
Thanks.

**Comment by TheJacobKim** [comment]
I am not sure if there is a linter for this, but there should be one.

**Comment by trivialfis** [comment]
Em.  Usually I just build the doc myself and if there's no warning then I will submit it.

**Pull request merged**
