### PR TITLE
Fix typo - eval_metric in param should be dictionary

### PR DESCRIPTION
**Pull request by terrytangyuan**

### CODE REVIEW

**Comment by CodingCat** [comment]
see the first test in travis...do you know what happened?

**Comment by terrytangyuan** [comment]
Not sure...seems new to me.

**Comment by terrytangyuan** [comment]
Oh I see what you mean. Python test seems flaky introduced by https://github.com/dmlc/xgboost/pull/1781. Re `cpplint` - I am not sure.  @tqchen Could you help take a look?

**Comment by tqchen** [comment]
@terrytangyuan I fixed the setup issue for cpplint, there will be other issues that need to be fixed

**Comment by terrytangyuan** [comment]
Seems like the other issue is related to this merged PR https://github.com/dmlc/xgboost/pull/1781. I am not sure if it's ok to update the threshold in Python test since the test accuracy threshold change may indicate some problem.

**Comment by tqchen** [comment]
I think it is fine if it is just for poisson regression

**Comment by terrytangyuan** [comment]
Thanks. I will fix it when get a chance.

**Pull request merged**
