### PR TITLE
[BLOCKING][CI] Upgrade to Spark 2.4.3

### LINKED ISSUE #4409: [BLOCKING][jvm-packages] upgrade and test with spark 2.4.3
well....some issues happened in the recent release of Spark, essentially 

2.4.1 has a serious bug

2.4.2 has some issue in scala support (we may not be affected, tho)

2.4.3 is coming

so let's wait for more days to upgrade to 2.4.3 and ensure everything is OK

### PR DESCRIPTION
**Pull request by hcho3**
See #4409. Spark 2.4.1 has a serious bug.

closes #4409.

### CODE REVIEW

**Comment by hcho3** [comment]
@CodingCat The SparkTraining example doesn't seem to be compatible with Spark 2.4.2. Can you take a look?
https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-4414/8/pipeline/204#step-245-log-3381

**Comment by CodingCat** [comment]
it's strange, do we cache some previously built pkg?

**Comment by CodingCat** [comment]
ok, I checked 2.4.2 released tar ball

looks like we are affected due to the release issue in 2.4.2, as 2.4.2 mistakenly released with scala 2.12 in their tar ball....


let's wait for 2.4.3..........

**Comment by hcho3** [comment]
> as 2.4.2 mistakenly released with scala 2.12 in their tar ball....

Was that a mistake? The [download page](https://spark.apache.org/downloads.html) says that "Spark is pre-built with Scala 2.12 since version 2.4.2"

**Comment by CodingCat** [comment]
Yeah, they are not supposed to change scala version in a maintenance release, leading to 2.4.1.tar.gz is for scala 2.11 but 2.4.2.tar.gz is for 2.12

**Comment by CodingCat** [comment]
2.4.3 is ready, when ahead to modify this PR and see how it goes

**Pull request merged**
