### PR TITLE
Add type hints to callback, compat, and config.py

### PR DESCRIPTION
**Pull request by jjwang01**
Adding type hints to callback.py, compat.py, and config.py as part of https://github.com/dmlc/xgboost/issues/6496.

### CODE REVIEW

**Review by trivialfis — COMMENTED** [review]
Thanks for the PR, could you please take a look into the failing tests?

I think adding types to callback might be tricky at the moment as we haven't exposed the packed booster to the public interface yet.

**Comment by jjwang01** [comment]
Yep, looks like all the error traces are complaining about the `_PackedBooster` object. Perhaps I should set the type hints for the respective variables I've added `_PackedBooster` hints to as `Any`? I believe that only `Booster` will cause a compile time error with the `_PackedBooster` object.

**Comment by trivialfis** [comment]
@jjwang01 Can we revert the changes in callback.py and keep the remaining?  I plan to improve the packed booster and expose it to the public in the future.  So right now we might just leave it as it's.

**Comment by trivialfis** [comment]
Closing as these modules are fully typed.

**Pull request closed without merging**
