### PR TITLE
[R] add a demo of multi-class classification R version

### PR DESCRIPTION
**Pull request by BruceZhaoR**
R code

### CODE REVIEW

**Comment by khotilov** [comment]
@BruceZhaoR please do not include the train.md output

**Comment by BruceZhaoR** [comment]
@khotilov ok?

**Comment by hcho3** [comment]
@BruceZhaoR I have restarted the tests. Lately, I see some tests failing without good reason, will need to investigate.

**Comment by BruceZhaoR** [comment]
@hcho3 All checks have passed, can be merged?

**Comment by hcho3** [comment]
Thanks for your contribution.

**Pull request merged**
