### PR TITLE
make DMatrix._init_from_npy2d only copy data when necessary

### PR DESCRIPTION
**Pull request by suntzu86**
When creating DMatrix from a 2d ndarray, it can unnecessarily copy the input data. This can be problematic when the data is already very large--running out of memory. The copy is temporary (going out of scope at the end of this function) but it still adds to peak memory usage.

``numpy.array`` copies its input no matter what by default. By adding ``copy=False``, it will only do so when necessary. Since XGDMatrixCreateFromMat is readonly on the input buffer, this copy is not needed.

Also added comments explaining when a copy can happen (if data ordering/layout is wrong or if type is not 32-bit float).

### CODE REVIEW

**Comment by suntzu86** [comment]
The test failure is happening in master too. Not sure what's up there. Also my change is downstream of the point where ``feature_types`` would get set, so I don't think I would have any effect on that issue.

**Comment by tqchen** [comment]
@suntzu86 can you do a rebase on recent master?

**Comment by suntzu86** [comment]
@tqchen amazed at how much you can do from the web interface, lol. I clicked 'Update branch'; looks like tests are running now.

**Comment by tqchen** [comment]
Thanks, this is merged

**Comment by suntzu86** [comment]
Cool, thank you :)

**Pull request merged**
