### PR TITLE
added unit tests for glm

### PR DESCRIPTION
**Pull request by terrytangyuan**
Hi, 

I added unit tests for glm but for some reason. Git cannot recognize any folders I added and any new files I added. So I deleted the .gitignore file then the push succeeded. 

Thanks,
Yuan

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Actually, can you help me push this .gitignore files back but excluding things that might affect my push or future pushes? I need to push filenames like test_****.R in the future.

**Comment by terrytangyuan** [comment]
Another issue I am having is when I run `devtools::load_all(".")` in `R-package` folder, this error pops up:  
```
Error in find.package(package, lib.loc, verbose = verbose) : 
  there is no package called ‘xgboost'
```

Can you look into this issue? I don't think this is caused by my new testing code. 

Thanks,
Yuan

**Comment by terrytangyuan** [comment]
Addition: `library(xgboost)` or `require(xgboost)` both work. `find.package('xgboost', lib.loc="~/R/win-library/3.2", verbose = verbose)` also works. Could you try to see if you can re-produce this problem?

**Comment by terrytangyuan** [comment]
Okay. I think you guys have just added basic tests on your own. Would you please let people know next time at least?

**Comment by tqchen** [comment]
@terrytangyuan sorry about the not being responsive. I think @hetong007 was busy in the past few month so he might not being able to check the PRs..

**Comment by terrytangyuan** [comment]
Understood. No worries.

**Comment by hetong007** [comment]
Hi @terrytangyuan, thank you for the PR! Do you mind to open a new PR and create the test in a new test file? Your test is something not being covered right now.

**Comment by terrytangyuan** [comment]
@hetong007 No problem. Sounds good.

**Comment by terrytangyuan** [comment]
@hetong007 So I am facing the same problem again. How do you usually run the tests for this package? I tried to create a new .Rproj file and ran R CMD test but didn't work.

**Comment by hetong007** [comment]
@terrytangyuan I run the test by `make Rcheck` at ROOT.

to add the file, you can try `git add -f R-package/tests/testthat/xxx.R`

**Pull request closed without merging**
