### PR TITLE
[jvm-packages] bump flink version number

### PR DESCRIPTION
**Pull request by chenqin**
0.10 was years ago, bump version number

### CODE REVIEW

**Comment by chenqin** [comment]
Thanks @CodingCat will do.

**Comment by chenqin** [comment]
@CodingCat will you be able to help restart pr-merge job?
`[linux_cuda9.2_nccl_omp_py2.7] Still waiting to schedule task
[linux_cuda9.2_nccl_omp_py2.7] Waiting for next available executor
[linux_cuda8.0_nccl_omp_py2.7] Still waiting to schedule task
[linux_cuda8.0_nccl_omp_py2.7] Waiting for next available executor
[linux_cuda8.0_nonccl_omp_py2.7] Still waiting to schedule task
[linux_cuda8.0_nonccl_omp_py2.7] Waiting for next available executor
[Pipeline] [linux_cuda8.0_nonccl_omp_py2.7] // node
[Pipeline] [linux_cuda8.0_nccl_omp_py2.7] // node
[Pipeline] [linux_cuda9.2_nccl_omp_py2.7] // node
Cancelling nested steps due to timeout`

**Comment by CodingCat** [comment]
it's for gpu test, you can ignore it for now....

**Comment by CodingCat** [comment]
LGTM, merged, thanks

**Pull request merged**
