### PR TITLE
[jvm-packages] update spark dependency to 3.0.0

### PR DESCRIPTION
**Pull request by wbo4958**

### CODE REVIEW

**Comment by wbo4958** [comment]
@CodingCat Since Spark 3 has been released on Jun,18,2020. We may need to update XGBoost to the newest Spark to leverage the newest features provided by Spark. Would you help to review it?

**Comment by trivialfis** [comment]
@CodingCat Could you please have a look?

**Comment by CodingCat** [comment]
the committee is voting on the spark version support strategy 

and besides that @wbo4958 , Spark 3.x is a major upgrade, could you list the integration tests you have done for this upgrading?

**Comment by wbo4958** [comment]
Hi @CodingCat, Sorry about that, I didn't realize the committee had been discussing spark 3 supporting strategy.

And this PR just made sure the existing Unit tests can pass in spark 3. I just read the MLlib and Core release note, and I didn't find some special PRs which affect XGBoost things except  `predictRaw` is made public https://issues.apache.org/jira/browse/SPARK-30358. Definitely I have missed something.

Anyway, I can close this PR. Thx

**Comment by wbo4958** [comment]
Hi @CodingCat @hcho3. I've tested this PR in our production env, I've tested classification for Mortgage dataset and regression for Taxi dataset. The test cases can be found in https://github.com/NVIDIA/spark-xgboost-examples

Except that, I have run this PR against spark-2.4.4-scala-2.12 and spark-2.4.3-scala-2.12 and no error found. Seems it can be backwards compatible.

I also read the spark3 release note https://spark.apache.org/docs/3.0.0/ml-migration-guide.html#upgrading-from-mllib-24-to-30 and I didn't found some PR which can break xgboost when running against spark 3.0

Maybe I have missed some, @CodingCat  Could you help to point it out? Thx very much.

**Comment by CodingCat** [comment]
the vote ends on Sunday, so I will come back to this early next week

**Comment by CodingCat** [comment]
merged, thanks!

as the voting result, we will only support Spark 3.0+ and scala 2.12 since xgboost 1.2 release

**Pull request merged**
