### PR TITLE
Add C++ Tests

### PR DESCRIPTION
**Pull request by AbdealiJK**
@tqchen Wanted to check if this approach of using gtest is fine ? (I've adapted it from dmlc-core)
If it's good I'll continue to add more unittests to it to get more coverage of the code.

### CODE REVIEW

**Comment by tqchen** [comment]
LGTM, need to update travis script though to activate gtest

c.f. https://github.com/dmlc/nnvm/blob/master/tests/travis/run_test.sh#L26

also it would be nice to have one file per testcase, again reference https://github.com/dmlc/nnvm/tree/master/tests/cpp would be good guideline

**Comment by AbdealiJK** [comment]
1 test per file seems an over kill, the name of the test is useful for
debugging purposes, and some tests might be pretty small, I think we can do
that on a case by case basis depending on the number of tests. Will try
writing a few and see which seems more intuitive?

I did try the Travis script, but it keeps giving me an error about some
undefined symbols from rabbit and dmlccore. But it works on my Mac
perfectly. Could you take a loot at
https://github.com/AbdealiJK/xgboost/commit/044fe3714f2177b37c98d5db11688d28d38cae86
 ?

**Comment by tqchen** [comment]
it is hard to tell what is going on if you can point me to a travis log, it might be more helpful. The test script will need to link libdmlc.a and librabit.a

**Comment by AbdealiJK** [comment]
@tqchen Sorry, here's more debug info:

Here is the updated commit https://github.com/AbdealiJK/xgboost/commit/ed9f016ad2ecb26158f539cd1e58a6042287cfce
And here is the travis log related to it https://travis-ci.org/AbdealiJK/xgboost/builds/180602642

When compiling it runs
```
g++ -std=c++0x -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -g -O0 -fprofile-arcs -ftest-coverage -fPIC -fopenmp -o tests/cpp/xgboost_test build_tests/cpp/test_data.o build_tests/cpp/test_main.o dmlc-core/libdmlc.a rabit/lib/librabit.a lib/libxgboost.a -pthread -lm  -fopenmp -lrt  -llz4  -lrt -L/home/travis/.cache/usr/lib/ -lgtest
```

which does have the libxgboost, librabit, libdmlc in there, but it still gives `undefined reference to `dmlc::Stream::Create(char const*, char const*, bool)'` and so on.

**Comment by tqchen** [comment]
could have things to do with file order libdmlc.a and librabit might need to come later than libxgboost

**Comment by AbdealiJK** [comment]
Wow. That worked like a charm !
Awesome :) I never knew the order mattered

**Comment by AbdealiJK** [comment]
@tqchen It seems the XGBoost travis queue is stuck and has not been running since the last push to master (11 hrs ago)

**Comment by AbdealiJK** [comment]
@tqchen Can we get this merged ?

I've added a few tests and have also added code coverage which can help us track how much coverage our CPP tests have on the source files. (Currently just ~20%) Will add more when free

You can see the coverage for this PR at https://codecov.io/gh/dmlc/xgboost/pull/1829

PS: You can configure codecov at https://codecov.io/gh/dmlc/xgboost to stop the commit messages

**Comment by AbdealiJK** [comment]
@tqchen Also, preferably please don't quash all the commits into 1 commit like its done in https://github.com/dmlc/xgboost/commit/6f16f0ef5829965ba420ef6937617600d286820a and https://github.com/dmlc/xgboost/commit/2f3958a45597750197de605bfe784763976650c1 .. It loses valuable git history because then a git blame gives a huge diff which is difficult to read.

**Comment by AbdealiJK** [comment]
:+1: thanks for the merge

**Pull request merged**
