### PR TITLE
Booster parameters typing

### PR DESCRIPTION
**Pull request by amotzop**
* Added a `TypedDict` describing the possible Booster parameters, and added it as a type hint.
* Added typing to the `training.py` file.

### CODE REVIEW

**Review by trivialfis — COMMENTED** [review]
Thank you for working on this, but I would like to avoid having another copy of parameter list in Python, which will complicate the maintenence.

**Comment by hcho3** [comment]
I agree with @trivialfis. XGBoost has multiple interfaces (Python, Java, R), and we want to keep the list of parameters in one place.

**Comment by amotzop** [comment]
I understand.
I just wanted to ask what do you think about the following:
1. Commiting just the extra typing information in `training.py`?
2. Adding code to automatically generate the `Parameters` TypedDict from the existing list of parameters (and it will be just an alias to `Dict[str,Any]` before the generation)?

I'm asking because I think that generally such typing information can really help find bugs/mistakes in code and so I'll like to find some way to both have it and keep it easily maintainable.

**Comment by trivialfis** [comment]
Thank you for the suggestion.  There's a list in sklearn API with type information.

**Pull request closed without merging**
