### PR TITLE
[spark] Add validation for param 'early_stopping_rounds' and 'validation_indicator_col'

### PR DESCRIPTION
**Pull request by WeichenXu123**
Signed-off-by: Weichen Xu <weichen.xu@databricks.com>

Add validation for param 'early_stopping_rounds' and 'validation_indicator_col'

### CODE REVIEW

**Comment by WeichenXu123** [comment]
CC @trivialfis @wbo4958 Thanks!

**Review by wbo4958 — APPROVED** [review]

**Comment by WeichenXu123** [comment]
@trivialfis @wbo4958 Ready for merging ! :)

**Comment by WeichenXu123** [comment]
@trivialfis @wbo4958 Ready for merging :)

**Review by trivialfis — APPROVED** [review]

**Comment by trivialfis** [comment]
Will look into the CI and merge it today.

**Comment by wbo4958** [comment]
+1 ed.

**Comment by trivialfis** [comment]
Could you please fix the test?

**Comment by WeichenXu123** [comment]
CC @trivialfis Tests fixed. Failed CIs are not related.

**Review by trivialfis — APPROVED** [review]

**Pull request merged**
