### PR TITLE
[WIP] Add tutorial for Monotonic Constraints.

### PR DESCRIPTION
**Pull request by madrury**
I need to work on the "how it works" section.  In the mean time, I'm submitting this for review.

### CODE REVIEW

**Comment by tqchen** [comment]
made a few comments. In general it looks great, it would also be nice to give an real world example dataset to show when this is useful.

**Comment by tqchen** [comment]
This tutorial looks in general good. We can skip how does it work for now, and provide a few real data examples, so we can merge it in. It would also be nice to propose a blogpost to dmlc.github.io

**Comment by madrury** [comment]
Thanks @tqchen .  I chatted with a friend about ideas for a real word example, and we came up with something to try.  I have some free time tomorrow, so I'll try to get something together there for monday.

**Comment by amontz** [comment]
@madrury For a more "real word" example I added a small [test](https://github.com/amontz/xgboost_monotone_test) in R using the Insurance dataset from MASS; I just required claim frequency to decrease with age.

**Comment by madrury** [comment]
@amontz That's a good idea.  Did adding the constraint improve hold out or cross validation error?

@DexGroves and I had chatted about what dataset to use, and we (he actually) hit upon the diamonds dataset included in ggplot2.  There, for example, you'd expect E[price | X] to be an increasing function of, say, carat.

**Comment by amontz** [comment]
@madrury The data-set only has 64 records. I didn't put any effort into the model, I was just trying to keep it simple with a more realistic problem. Differences between the two seem like noise. Maybe you could get more interesting results with diamonds.

**Comment by tqchen** [comment]
any updates on this? Let us add the realworld example and merge this in

**Comment by tqchen** [comment]
ping ping

**Comment by tqchen** [comment]
@madrury Can you update the realworld example, remove the how it works section for now and let us aim to bring this in

**Comment by madrury** [comment]
Sorry @tqchen , I got a new job and it's been, intense.

I'll get this done this weekend and send you a pull request by monday.

I apologize for my unresponsiveness.

**Comment by tqchen** [comment]
Great, please let me know when it is ready for another round of review

**Comment by tqchen** [comment]
@madrury  ping ping

**Comment by tqchen** [comment]
@madrury any updates on this? We will need to rebase, update and merge this

**Comment by madrury** [comment]
@tqchen Not as much as I would like.  It's been difficult for me to find any time for out of work projects since taking a new job.

I did some work looking for a data set and situation where using the monotonic constraints improved the out of same error (cv error), but did not find any.  My work on this stalled after that.

**Comment by tqchen** [comment]
I see, can you do a bit cleanup on the blogpost(remove TODOs) we could first merge this in for now.

Thanks!

**Comment by XiaoxiaoWang87** [comment]
hey, I added a tutorial here with a real data example, if it helps: https://github.com/XiaoxiaoWang87/xgboost_mono_test/blob/master/tutorial.md

It was modified from my previous tests and intended for a blog post I was writing (so may be slightly long). Let me know what you guys think.

**Comment by tqchen** [comment]
@XiaoxiaoWang87 This looks nice. Please let us know if you would like to contribute back as a tutorial (and a guest blogpost).  Maybe incorporate a bit from this PR about the introduction to the monotonic property.

**Comment by madrury** [comment]
@tqchen I have a few days off for thanksgiving, so I'll make an effort to clean up my work.

**Comment by tqchen** [comment]
great, thanks!

**Comment by XiaoxiaoWang87** [comment]
@tqchen Thanks. Definitely willing to contribute. Let me know when we can wrap this up after all other documentation / cleanup work are done.

**Comment by walterreade** [comment]
@XiaoxiaoWang87 I found the tutorial clear and useful. Thanks very much.

**Comment by tqchen** [comment]
@madrury any updates on this?

**Comment by madrury** [comment]
@tqchen Yup.  Expect a pull request from me tomorrow.

**Comment by tqchen** [comment]
cool, I am going to close this since there are some conflicts to be resolved. Please open a new PR when it is ready for review

**Comment by tqchen** [comment]
@madrury any updates?

**Pull request closed without merging**
