### PR TITLE
small verbose_eval fixes

### PR DESCRIPTION
**Pull request by Far0n**
ensures same behavior for verbose_eval=0 and verbose_eval=False

### CODE REVIEW

**Comment by JohanManders** [comment]
@Far0n There is one small edit I wanted to make to training.py, maybe you could do this so there is only one pull request?

My little edit should fix printing the last eval message if ```early_stopping_rounds``` is set, but XGBoost runs to the end.

Line 209 from training.py should be:
```
if i % verbose_eval_every_line == 0 or i == num_boost_round - 1:
```
instead of:
```
if i % verbose_eval_every_line == 0:
```

**Comment by Far0n** [comment]
@JohanManders I added your changes

**Comment by JohanManders** [comment]
Thanks man!

**Comment by Far0n** [comment]
you are welcome

**Pull request merged**
