### PR TITLE
[CI] Automatically bump Rapids version in containers

### PR DESCRIPTION
**Pull request by hcho3**
TODO:
- [x] set up a workflow to submit an automated pull request, using https://github.com/marketplace/actions/create-pull-request

### CODE REVIEW

**Review by trivialfis — COMMENTED** [review]
Does this affect Python tests? I have been using a conda environment file for development with RMM, maybe it's useful to upstream it here.

**Comment by hcho3** [comment]
> Does this affect Python tests?

Yes.

> I have been using a conda environment file for development with RMM

Currently, we don't use environment files because environment files don't support a parameter. Since we are adopting an automated solution to keep RAPIDS up to date, we can work around this restriction:

* Move all Conda envs into environment files. Make sure to pin Rapids packages to specific versions: `rapids=23.04`, `rmm=23.04` and so forth.
* The automated script should periodically check for the latest RAPIDS release and update the Conda env files appropriately.

What do you think of this idea?

**Comment by trivialfis** [comment]
For some reason, no. It keeps downloading individual components like nsight-system and cudart as 12.1.

**Comment by hcho3** [comment]
Got it. Then let me merge this PR as it is.

**Pull request merged**
