### PR TITLE
stratified cv for python wrapper

### PR DESCRIPTION
**Pull request by Far0n**
- two new parameters for python xgb.cv: *stratified* and *folds*
- stratified = False per default to keep current behavior
- user can pass sklearn KFolds or StratifiedKFolds via *folds* parameter 
- unit test added
- stratified = True depends on sklearn (install check implemented)

### CODE REVIEW

**Comment by Far0n** [comment]
refers to issue: https://github.com/dmlc/xgboost/issues/729

**Comment by terrytangyuan** [comment]
Looks good. Can you finalize the docstring (get rid of question mark) and rebase to resolve conflicts?

**Comment by Far0n** [comment]
done (docstring changes squashed)

**Comment by terrytangyuan** [comment]
Thanks! Will merge when tests pass.

**Comment by Far0n** [comment]
you're welcome

**Comment by haozhenWu** [comment]
@Far0n 
Hi Faron, I try to use stratified = True in python for a binary classification but got the following error : 

/home/haozhen/temp/xgboost/python-package/xgboost/training.pyc in mknfold(dall, nfold, param, seed, evals, fpreproc, stratified, folds)
    237         nfold = len(idset)
    238     else:
--> 239         sfk = XGBStratifiedKFold(n_splits=nfold, shuffle=True, random_state=seed)
    240         idset = [x[1] for x in sfk.split(X=dall.get_label(), y=dall.get_label())]
    241 

TypeError: __init__() got an unexpected keyword argument 'n_splits'

I know I can pre build the stratified folds  and pass them into the folds parameter. I just want to understand why this error happened.

Below is the code I used:
        param = {'objective':'binary:logistic',
                'booster' : 'gbtree',
                'eta' : 0.05,
                'max_depth' : 7,
                'subsample' : 0.83,
                'colsample_bytree' : 0.8,
                'num_parallel_tree' : 1,
                'min_child_weight' : 5,
                'gamma' : 5,
                'max_delta_step':1,
                'scale_pos_weight':sum(dtrain.get_label()==0)/sum(dtrain.get_label()==1),
                'silent':1,
                'seed' : 2016,
                'eval_metric': ['auc'],
                }
        # cross validation
        cv = xgb.cv(param, dtrain, num_boost_round = 500, nfold=5, stratified = True,
                    early_stopping_rounds = 10, maximize = True,
                    callbacks=[xgb.callback.print_evaluation(show_stdv=True)])


Thank you very much!

**Comment by terrytangyuan** [comment]
This should be fixed. Please try the latest version.

**Comment by hellozeyu** [comment]
@terrytangyuan 
Hi Terry,

I just tried some similar code for a Kaggle competition and got the exact same error. I saw the recent latest commit made by you 63829d6 so I re-cloned the repo and built the package. However, it still throws the same error. Maybe I did something wrong when I rebuilt the package. Any suggestions?

**Comment by terrytangyuan** [comment]
What version of sklearn are you using? Could you share the stacktrace of error?

**Comment by hellozeyu** [comment]
I am using sklearn 0.17.1 (I guess it might be the problem.)

And the Trackback error is like this:
```
File "/usr/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/training.py", line 367, in cv
    cvfolds = mknfold(dtrain, nfold, params, seed, metrics, fpreproc, stratified, folds)
File "/usr/local/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/training.py", line 239, in mknfold
    sfk = XGBStratifiedKFold(n_splits=nfold, shuffle=True, random_state=seed)
TypeError: __init__() got an unexpected keyword argument 'n_splits'
```

**Comment by hellozeyu** [comment]
Confirming that I am able to use it after upgrading to the latest version of sklearn(0.18).

**Pull request merged**
