### PR TITLE
Add option to choose booster in scikit intreface (gbtree by default)

### PR DESCRIPTION
**Pull request by jayzed82**

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Could you add a test case so I can visually see this works?

**Comment by jayzed82** [comment]
Test case added.

**Comment by SauceCat** [comment]
Thanks for the work! 
I just found that, for the DART booster, it seems not enough just passing in booster parameter. It also need to set the `sample_type`, `normalize_type `, `rate_drop ` and `skip_drop`.
refer: http://xgboost.readthedocs.io/en/latest/tutorials/dart.html 
Maybe we can add those parameters in for the DART booster?

**Comment by jayzed82** [comment]
Hi, I think this will be possible after pull #2338 is merged.

**Comment by SauceCat** [comment]
@jayzed82 oh, I see. Thank you!

**Pull request merged**
