### PR TITLE
Update dmlc-core and use data iter for GPU sampling tests.

### PR DESCRIPTION
**Pull request by trivialfis**
* Add parquet build.
* Fix unity build.

Close https://github.com/dmlc/xgboost/pull/7139

### CODE REVIEW

**Review by hcho3 — APPROVED** [review]

**Comment by trivialfis** [comment]
Pushed a commit to use the new external memory interface in the gradient sampling test.  It bypasses dmlc threaded iter.

**Comment by hcho3** [comment]
Should this change part of the PR that updates dmlc-core?

**Comment by trivialfis** [comment]
Good point.  I will split it up since more tests need the conversion.

**Comment by trivialfis** [comment]
I still need the updated dmlc-core to confirm that it's working correctly ...

**Review by hcho3 — APPROVED** [review]
LGTM. Please rename this PR to indicate that the external memory test was revised to use the data iterator.

**Pull request merged**
