### PR TITLE
Sklearn convention update

### PR DESCRIPTION
**Pull request by gaw89**
@terrytangyuan, as per #2321, I added n_jobs and random_state parameters along with DeprecationWarnings for seed and nthread.  This brings those two elements of the API up to date with Sklearn standards.  I also have tests showing the functionality and DeprecationWarnings.  I updated the docstring for XGBModel as well.  

I hope this helps!

### CODE REVIEW

**Comment by gaw89** [comment]
Great, thanks for approving!  I added the note.  Should I add myself to contributors.md (recognizing that this is a very small contribution)?

**Comment by terrytangyuan** [comment]
yes please add yourself to contributors

**Comment by gaw89** [comment]
Cool thanks!

I will work on the other skleatn API enhancements next week.

**Comment by terrytangyuan** [comment]
Could you fix the test?

**Comment by gaw89** [comment]
Yes, I will fix those things tomorrow when I am back at my office.  I will
also n_jobs to 1.  Thanks!

**Comment by gaw89** [comment]
I have fixed the tests and updated n_jobs to 1.  Please let me know if you have any other changes.

Thanks!

**Comment by terrytangyuan** [comment]
Merged. Thanks!

**Comment by gaw89** [comment]
Awesome, thanks!  I'll submit a PR in the next couple of days to add GPU support to Sklearn API.

**Pull request merged**
