### PR TITLE
[jvm-packages] fix MLlib CrossValidator issues #1941

### PR DESCRIPTION
**Pull request by mengdong**
Actually, one friend of mine find out the default scalePosWeight is set to 0, which triggered issue #1941

### CODE REVIEW

**Comment by CodingCat** [comment]
While the default value is wrong, it might not be the root cause of cross validation issue...

**Comment by CodingCat** [comment]
if you look at https://github.com/dmlc/xgboost/blob/6f16f0ef5829965ba420ef6937617600d286820a/src/objective/regression_obj.cc#L102, and the detailed description in https://github.com/dmlc/xgboost/issues/1941, this default value issue cannot explain many things

please revise the PR title and the description,   I will merge it

**Comment by mengdong** [comment]
Yeah, when I came across this bug few weeks ago, I was looking at other perspectives as well but those didn't lead to a fix. But this change seems to fix the problem. The line 102 you highlighted explain how scale_pos_weight works, I am also curious why this is only picked up by paramGrid

**Comment by CodingCat** [comment]
I will look at it tmr...

**Comment by CodingCat** [comment]
I have understood the root cause. Will merge it as it fixes the problem, and will submit a patch to have a detailed description of how this happens and the corresponding fix

**Comment by mengdong** [comment]
The patch looks clear, thanks for looking further

**Pull request merged**
