### PR TITLE
Support gamma in GPU_Hist.

### PR DESCRIPTION
**Pull request by trivialfis**
@hcho3 @RAMitchell I just prevent the split when `loss_chg` < `gamma`.  Could you think of a case adding an explicit `pruner` is useful?  One additional thing I found in `pruner` is a syncing operation (broadcasting rank 0 tree), but I don't think it's necessary for `gpu_hist`.

### CODE REVIEW

**Comment by trivialfis** [comment]
I will add tests if the method is reasonable.

**Comment by RAMitchell** [comment]
I can't think of any reason why not, let's do it.

**Comment by trivialfis** [comment]
@RAMitchell Please take a look again.

**Comment by trivialfis** [comment]
@panranyang Fixed. #4707

**Pull request merged**
