### PR TITLE
Remove benchmark code in GPU test.

### PR DESCRIPTION
**Pull request by trivialfis**
We have dedicated benchmark code for it now.

### CODE REVIEW

**Comment by hcho3** [comment]
Before we merge this PR, we should migrate the code to https://github.com/dmlc/xgboost-bench.

**Comment by trivialfis** [comment]
@hcho3 The bench code removed is not really useful.  We have `gbm-bench` for dealing with GPU benchmark.  It's also duplicated with `tests/benchmark` in XGBoost's source tree.

**Comment by trivialfis** [comment]
I will try to upstream some more code to `xgboost-bench` later.  They should be more realistic than the one removed in this PR.

**Comment by trivialfis** [comment]
Although I'm not sure why are we splitting up the benchmark from main repo.

**Comment by hcho3** [comment]
@trivialfis I adopted @RAMitchell's suggestion in https://github.com/dmlc/xgboost/pull/5126#issuecomment-566254927: benchmark should be hosted in a separate repository that is neutrally-hosted.

**Comment by hcho3** [comment]
@trivialfis I opened a new discussion thread: https://github.com/dmlc/xgboost/issues/5142

**Comment by RAMitchell** [comment]
Lets look to phase out `tests/benchmark` as well. These are more like convenience scripts used by a few individuals than a properly documented benchmark.

**Pull request merged**
