### PR TITLE
Updated build instructions for OS X.

### PR DESCRIPTION
**Pull request by lenguyenthedat**
To support OS X El Capitan:

- Clang method doesn't seem to work anymore.
- GCC has been updated to 5.2.0.

Ref: https://github.com/dmlc/xgboost/issues/596, https://github.com/dmlc/xgboost/issues/626

### CODE REVIEW

**Comment by lenguyenthedat** [comment]
Not sure if there is a way to make it work for Clang, but GCC method seems to be much easier with gcc-5.2.0 supported from homebrew - please feel free to update it or let me know here if you want to change anything! :smiley:

**Comment by terrytangyuan** [comment]
@phunterlau Wanna check this?

**Comment by phunterlau** [comment]
@terrytangyuan this update looks good and updated to the current situation with Mac OS X.

**Comment by terrytangyuan** [comment]
Thanks!

**Pull request merged**
