### PR TITLE
re-enable recovery test after rabit allow duplicated allreduce calls with same signature

### PR DESCRIPTION
**Pull request by chenqin**
Reeanble rabit tests after fix 
https://github.com/dmlc/rabit/pull/128 merged

Rabit assume bootstrap allreduce has unique signature, in dmlc/xgboost#5012 we find it failed to satisfy such constraint.

The goal of this pr is to loosen such constraint and allow last write overwrite results with same signature during bootstrap phase. Here is example https://github.com/dmlc/xgboost/pull/4990/files#diff-5fabd019d3f1af7572baa4a6301cf076R36

### CODE REVIEW

**Comment by trivialfis** [comment]
Restarted the aborted tests.

**Comment by chenqin** [comment]
dmlc/xgboost#5033

**Comment by chenqin** [comment]
@trivialfis can we rerun tests, a bit weird.

**Comment by hcho3** [comment]
The error message is
```
undefined symbol: _ZN5rabit6engine9AllgatherEPvmmmm
```
I thought the R package was using mock Rabit?

**Comment by chenqin** [comment]
> The error message in the R tests is
> 
> ```
> undefined symbol: _ZN5rabit6engine9AllgatherEPvmmmm
> ```
> 
> I thought the R package was using mock Rabit? (Distributed training is not supported for XGBoost-R)

I see, that’s probably not related to mock but all gather interface merged in master.

**Comment by chenqin** [comment]
depends on https://github.com/dmlc/rabit/pull/129
@trivialfis

**Comment by trivialfis** [comment]
Will look into this once our Windows worker is back.  Sorry for being slow here.

**Comment by hcho3** [comment]
@trivialfis Sorry for the delay, I was spending time with my family over the Thanksgiving holiday. The blocking issue now is inability to run the compiled C++ tests (`testxgboost.exe`) in Windows workers; the executable simply crashes. I'm investigating now.

**Comment by hcho3** [comment]
@trivialfis I found the reason why `testxgboost.exe` was crashing. I had to install a system lib called [ Microsoft Visual C++ Redistributable for Visual Studio](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads). #5061 will be resolved shortly.

**Comment by trivialfis** [comment]
@hcho3. That's great!

**Comment by trivialfis** [comment]
@chenqin Could you make a rebase onto master branch.  As you used your master branch I can't do that for you.

**Comment by trivialfis** [comment]
@chenqin pls help rebasing, otherwise the Jenkins Windows tests can not pass.

**Comment by chenqin** [comment]
@nateagr
https://github.com/dmlc/rabit/pull/113

`
Error: package or namespace load failed for 'xgboost' in dyn.load(file, DLLpath = DLLpath, ...):

[2019-12-15T01:52:26.359Z]  unable to load shared object '/workspace/xgboost/xgboost.Rcheck/xgboost/libs/xgboost.so':

[2019-12-15T01:52:26.359Z]   /workspace/xgboost/xgboost.Rcheck/xgboost/libs/xgboost.so: undefined symbol: _ZN5rabit6engine9AllgatherEPvmmmmPKciS3_
`

**Comment by chenqin** [comment]
@trivialfis @hcho3 @CodingCat happy new year

**Comment by hcho3** [comment]
@chenqin You too

**Comment by trivialfis** [comment]
@CodingCat Could you please share the rabit bug you discovered?  My next target would be merging PRs.  No more new bug fixes unless critical.

**Comment by CodingCat** [comment]
Why we stop bug fixing but merging new functionalities?

It’s counter-intuitive as the final steps of releasing a new version?

**Comment by trivialfis** [comment]
I mean I won't focus on bug fixes, others can continue the process.  And merging PRs will focus on bug fixes PRs.

**Comment by trivialfis** [comment]
Clarified, sorry for the ambiguity.

**Comment by chenqin** [comment]
thanks @trivialfis helping get enable rabit test pr in. close this pr

**Pull request closed without merging**
