### PR TITLE
Update NVFlare demo to work with the latest release

### PR DESCRIPTION
**Pull request by rongou**
A few small changes to conform to the latest NVFlare release.

### CODE REVIEW

**Comment by rongou** [comment]
@trivialfis @hcho3

**Review by trivialfis — APPROVED** [review]
Thank you for the work! Is this run on the CI? If not, how difficult it's to run it?

**Comment by rongou** [comment]
Probably not too hard, but @hcho3 would be a better judge.

**Comment by trivialfis** [comment]
if we can have all dependencies from conda and pip, that should be quite easy.

**Pull request merged**
