### PR TITLE
Added "group" functionality to DMatrix Slice method

### PR DESCRIPTION
**Pull request by JohnStott**
This will make Cross Validation, sub sampling easier etc (I will extend python cv functionality to support this on acceptance of this pull request).

Note, I have written a test script to prove this method is working as expected.  Please advise where I should post this...if at all?  I assume there are some generic test scripts that get ran on each major release of xgboost?

### CODE REVIEW

**Comment by tqchen** [comment]
Please put the test scripts under tests/python and it will be tested via travis

**Comment by JohnStott** [comment]
Thanks tqchen.  Unfortunately, to test my changes, I needed to be able to access the contents of a DMatrix object and currently, I don't believe this is implemented (nor a ".GetGroups" equivalent) in Python, so I tested in C++.

I will paste here in case it helps with your assessment of code:

```cpp
#include "xgboost\c_api.h"
#include <random>
#include "data/simple_csr_source.h"

static std::random_device _rd; // seed initialiser
//static unsigned int _seed = 0;
static unsigned int _seed = _rd();
static std::mt19937 _rndGen(_seed); // Mersenne-Twister

int main(int argc, char *argv[]) {
 
  const int noOfGroups = 1000;
  const int noOfSliceGroups = 100;
  const int minGrpSize = 1, maxGrpSize = 10;

  //will create 3 structures:
  //1) to pass directly into our initial dmatrix i.e., row & column:
  std::vector< std::vector<int> > rowStructure;
  //2) to make creating slice easier i.e., group, row & column:
  std::vector< std::vector< std::vector<int> > > groupStructure;
  //3) to hold group info
  std::vector<int> groupInfo;

  std::uniform_int_distribution<int> randGrps(minGrpSize, maxGrpSize); 
  int id = 0;
  for (int i = 0; i < noOfGroups; i++) {
    int grpSize = randGrps(_rndGen);
    groupInfo.push_back(grpSize);
    std::vector< std::vector<int> > grp;
    for (int x = 0; x < grpSize; x++) {
      std::vector<int> row;      
      row.push_back(id); //will hold the column id in index 0 to make keeping track easier
      row.push_back(i);  //store group id number in index 1

      grp.push_back(row);
      rowStructure.push_back(row);

      id++;
    }
    groupStructure.push_back(grp);
  }

  //format data suitable for XGDMatrixCreateFromMat: 
  std::vector<float> data;
  for (unsigned i = 0; (i < rowStructure.size()); i++)
  {
    data.push_back(rowStructure[i][0]);
    data.push_back(rowStructure[i][1]);
  }

  DMatrixHandle dmAll;
  XGDMatrixCreateFromMat((float *)&data[0], rowStructure.size(), 2, -1, &dmAll);

  XGDMatrixSetGroup(dmAll, (const unsigned int*)&groupInfo[0], groupInfo.size());

  //get random groups of data:
  std::uniform_int_distribution<int> randG(0, noOfGroups-1);
  std::vector<int> sliceGroups;
  while (sliceGroups.size() < noOfSliceGroups) {
    int randGrpIndex = randG(_rndGen);
    bool existsAlready = false;
    for each (int val in sliceGroups) {
      if (val == randGrpIndex){ 
        existsAlready = true;
        break;
      }
    }
    if (!existsAlready)
      sliceGroups.push_back(randGrpIndex);
  }

  /*comment these out individually to test the Slice method against known issues*/
  ///*1) error: slice index is in wrong group:*/
  //int ix1 = -1;
  //int ix2 = -1;
  //for (int err = 0; err < noOfSliceGroups; err++) {
  //  if (groupStructure[sliceGroups[err]].size() > 1) {
  //    if (ix1 == -1)
  //      ix1 = sliceGroups[err];
  //    else if (ix2 == -1) {
  //      ix2 = sliceGroups[err];
  //      std::vector<int> tmpIx = groupStructure[ix2][0];
  //      groupStructure[ix2][0] = groupStructure[ix1][0];
  //      groupStructure[ix1][0] = tmpIx;
  //      break;
  //    }
  //  }
  //}
  ///*2) error: duplicate index in same group */
  //for (int err = 0; err < noOfSliceGroups; err++) {
  //  if (groupStructure[sliceGroups[err]].size() > 1) {
  //    groupStructure[sliceGroups[err]][0][0] = groupStructure[sliceGroups[err]][1][0];
  //    break;
  //  }
  //}
  ///*3) error: missing index in group */
  //for (int err = 0; err < noOfSliceGroups; err++) {
  //  if (groupStructure[sliceGroups[err]].size() > 1) {
  //    groupStructure[sliceGroups[err]].pop_back();
  //    break;
  //  }
  //}
  ///*4) error: duplicate index in other group */
  //int ix1 = -1;
  //int ix2 = -1;
  //for (int err = 0; err < noOfSliceGroups; err++) {
  //  if (groupStructure[sliceGroups[err]].size() > 1) {
  //    if (ix1 == -1)
  //      ix1 = sliceGroups[err];
  //    else if (ix2 == -1) {
  //      ix2 = sliceGroups[err];
  //      int tmpIx = groupStructure[ix2][0][0];
  //      groupStructure[ix2][0][0] = groupStructure[ix1][0][0];
  //      groupStructure[ix1][0][0] = tmpIx;
  //      break;
  //    }
  //  }
  //}

  //with these random groups, shuffle their rows and use for the slice:
  std::vector<int>ids;
  for each (int grpIndex in sliceGroups){
    std::shuffle(std::begin(groupStructure[grpIndex]), std::end(groupStructure[grpIndex]), _rndGen);
    for (int row = 0; row < groupStructure[grpIndex].size(); row++) {
      ids.push_back(groupStructure[grpIndex][row][0]);
    }
  }
  
  DMatrixHandle dmSlice;
  XGDMatrixSliceDMatrix(dmAll, &ids[0], ids.size(), &dmSlice);

  //if slice is created without error (as expected), do a final check to ensure sliced information is the same 
  //as requested.  This can be done by simply comparing DMatrix column 0 with 'ids' array (as provided to slice method)
  xgboost::data::SimpleCSRSource src;
  src.CopyFrom(static_cast<std::shared_ptr<xgboost::DMatrix>*>(dmSlice)->get());
  bool failed = false;
  int ix = 0;
  for (int i = 0; i < src.row_data_.size(); i+=2) {
    if (static_cast<int>(src.row_data_[i].fvalue != ids[ix])) {
      std::cout << "Error this should never occur!!! Place breakpoint and debug!";
      failed = true;
      break;
    }
    ix++;
  }

  //now, most importantly, check the groups match:
  if (!failed) {
    int cumlSliceGroupAmt = 0;
    for (int grpCumlIndex = 1; grpCumlIndex < src.info.group_ptr.size(); grpCumlIndex++) {
      cumlSliceGroupAmt += groupStructure[sliceGroups[grpCumlIndex - 1]].size();
      if (cumlSliceGroupAmt != src.info.group_ptr[grpCumlIndex]) {
        std::cout << "Error with group sizes! This should never occur!!! Place breakpoint and debug!";
        failed = true;
        break;
      }
      //std::cout << cumlSliceGroupAmt << " " << src.info.group_ptr[grpCumlIndex] << std::endl;
    }
  }

  if (!failed)
    std::cout << "Worked as expected :)";

  std::string str = "";
  std::cin >> str;
}
```

**Comment by JohnStott** [comment]
tqchen - seems to be failing checks due to a non-code related problem.. installation of python....  Is this normal?

**Comment by JohnStott** [comment]
must have been a Travis glitch as I clicked the "Update branch" button, which restarted the travis process and appears okay this time :)

**Comment by JohnStott** [comment]
Added a bug fix above "Fix issue introduced from correction to log2", I was hoping it would have been created as a new pull request.  Once Travis wakes up..., hopefully there will be an option for me to withdraw that change?  Then I can try again from a new branch see if that allows me to add it into its own "pull" request???  Otherwise letting you know here :)

**Comment by tqchen** [comment]
Revisit this issue. There are a few code alignments issues in the c_api. besides that, we will need a testcase to check if it works correctly, please add one under tests/python, and we can merge this in once the testcases passes

Thanks for the contribution!

**Comment by JohnStott** [comment]
I have a couple of hours free later so I'll try and get all this sorted in one go.

The only way I will be able to test this new functionality in Python is if we can see the sliced groups.  So I will need to create and expose a new **get**_groups method.  I assume this is okay?  I will output the groups in the same format as is expected through the current **set**_groups method (as we know, it is stored within c++ in a different format).

**Comment by JohnStott** [comment]
With respect to my Log2 fix, I now know I should have created a new branch in order to submit 2 seperate pull requests. Hopefully I will have this finished today so we can push it all through in one.  But I'll know what to do in future in working with github :)

**Comment by JohnStott** [comment]
Something has failed in Travis.  I don't understand what the issue is?

**Comment by JohnStott** [comment]
tqchen just wanted to ask a question before going ahead with this.  In order to create a test script in Python I will need access to the groups from the DMatrix.  Currently this isn't exposed in the c++ interface i.e., there is no "get_group" or "getUIntInfo" equivalent.  I could write this, however, because the group vector is held in a different structure than that passed in by the user, I would either have to store the group twice (I can't re-arrange the original on the fly and pass to client due to losing local variable pointer scope...I don't like malloc type 'fudges' either).  The other alternative is to transform the group (when getting) in the client i.e., within python/R.  This isn't very nice either but probably preferable?  What do you think?  Is it even worth adding a test script given this?  I also wonder, if it is possible(?), whether having some c++ test scripts, could be used in Travis instead?  I'll await your thoughts before doing anything.

**Comment by JohnStott** [comment]
...having given this a little more thought.  It would probably be better for me to introduce a new method in c_api.cc that is solely for running checks i.e., my script above (my 2nd post).  This could then be called from python. I'll implement something simple, to demonstrate this, and will post tomorrow.

**Comment by JohnStott** [comment]
All my code above is now complete.  The failure above wrt Travis appears to be failing for **everybody's** pull requests, not just mine.

**Comment by JohnStott** [comment]
tqchen please could you advise on what we should do about this travis issue?  #1819

**Comment by JohnStott** [comment]
Closing this as better to use the newly added c++ unittest.  Will resubmit later.

**Pull request closed without merging**
