### PR TITLE
Have to `unname` before comparison

### PR DESCRIPTION
**Pull request by kirillseva**
I've put a browser there and inspected

```r
Called from: finalizer(env)
Browse[1]> best_score
 eval-auc
0.9381443
Browse[1]> attr_best_score
[1] 0.9381443
Browse[1]> all.equal(best_score, attr_best_score)
[1] "names for target but not for current"
Browse[1]> all.equal(unname(best_score), attr_best_score)
[1] TRUE
Browse[1]> unname(best_score)
[1] 0.9381443
Browse[1]> attr_best_score
[1] 0.9381443
Browse[1]> attr_best_score %>% str
 num 0.938
Browse[1]> unname(best_score) %>% str
 num 0.938
```

### CODE REVIEW

**Comment by khotilov** [comment]
I'm sorry, I didn't notice this PR... 

All that was intended here was just to verify that the numerical values were the same, but otherwise it's ok when the objects are not identical. Are there situations where the current check is not sufficient?

**Comment by kirillseva** [comment]
@khotilov I don't care for the check personally. There was a bug upstream that prevented this callback from ever going through (at least in my R version, I think it's 3.2.4). This PR fixes the issue, and this `if` check works as the original author intended

**Comment by kirillseva** [comment]
ping ping ping

**Comment by khotilov** [comment]
I'm afraid I'm still not getting what is the problem that is being fixed here. What errors did you see? What was that upstream bug? Was `==` between named and unnamed scalar values not working properly in some R release? I've just checked and saw no issues in R 3.2.4... Or were you simply getting NA's as best_scores (you check would help to compare two NA's as equal)?

**Comment by khotilov** [comment]
#1617 the root cause is loss of precision, since the attribute is stored as float. And `all.equal` allows for tolerance.

**Comment by kirillseva** [comment]
@khotilov I saw an error while comparing a named and an unnamed vector as stated in the OP.
all.equal allows for tolerance but errors out for different names

**Comment by khotilov** [comment]
There was no `all.equal` in the original line of code that you have changed, thus the error described in the OP could not happen until you changed that line. So I am not sure what was your original failure that you saw, but I'm guessing it was related to the precision loss. Could you please check that #1628 fixes the problem for you? Or, if it does not, please provide some details.

**Comment by kirillseva** [comment]
@khotilov I provided the details in the OP post :) I feel like we have a language barrier problem here 😢 
Here are the steps needed to reproduce:
1) Put a browser in `finalizer.R`, line 351 is fine
2) do this
```r
Browse[1]> best_score
 eval-auc
0.9381443
Browse[1]> attr_best_score
[1] 0.9381443
Browse[1]> all.equal(best_score, attr_best_score)
[1] "names for target but not for current"
```

You will see that `best_score` is a named numeric vector, but `attr_best_score` is an unnamed numeric vector. And at least in R version 3.2.4 this causes `best_score != attr_best_score` to be `TRUE` and for the finalizer to error out despite the booster being trained correctly. Hence, in this pull request I explicitly unname `best_score` and move to `all.equal` in case later you'd want to check for equality with  tolerance.

**Comment by khotilov** [comment]
Let's see if a longer explanation would be more clear...

I've used the `best_score != attr_best_score` comparison in there since I expected them both to be scalars (and to fail for non-scalars) and I cared only about comparing their values. But I admit I didn't know at the time that `as.character` stored only "reliable" digits, so I didn't expect any precision loss. 

AFAIK, the comparison operators like `!=`, `==`, etc work on **values** and they don't take R objects' attributes (such as `.Names`) into account. The `==` is not at all the same as `all.equal` (when using default options). I've checked that value-comparison b/w named and unnamed same-value objects worked as expected in at least four R versions (including the 3.2.4), and I also didn't notice any related bug-fixes in the R release log (such an issue would be a major bug if it existed). Within the browser, when using the pre-#1628 code, you would most likely also see that you had different numerical value between `format(best_score, digits=17)` and `format(attr_best_score, digits=17)`, thus causing `best_score != attr_best_score` to be `TRUE`. Let me know whether #1628 has fixed the issue.

**Comment by kirillseva** [comment]
@khotilov I see, you're right about the precision thing!
I didn't dig far enough, and while R stores a number with the required precision, it looks like it does not print it in a correct way, truncating the output

```r
> a = 0.00010101010101010101010101010101010101010101
> a
[1] 0.0001010101
```

Hence, my change worked because `all.equal` compares within a tolerance!

Let's merge your `as.character` -> `format(...)` change, and I'll close this pull request. Thank you for your patience and for the review!

**Pull request closed without merging**
