### PR TITLE
Fixed shared library loading in the Python package

### PR DESCRIPTION
**Pull request by superbobry**
As discussed in 2cb51f7097df44f7f2993d47865b0090194e2dc4.

I haven't implemented the symlink, because 
* it was previously broken for OS X as well (the shared library had an .so extension) and 
* I'd rather prefer pushing the users to do the right thing. 

If you think I should do otherwise, please comment.

### CODE REVIEW

**Comment by CodingCat** [comment]
it looks like the building under OS X is producing `libxgboost.so`

`
c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -shared -o lib/libxgboost.so build/learner.o build/logging.o build/c_api/c_api.o build/c_api/c_api_error.o build/common/common.o build/common/hist_util.o build/data/data.o build/data/simple_csr_source.o build/data/simple_dmatrix.o build/data/sparse_page_dmatrix.o build/data/sparse_page_raw_format.o build/data/sparse_page_source.o build/data/sparse_page_writer.o build/gbm/gblinear.o build/gbm/gbm.o build/gbm/gbtree.o build/metric/elementwise_metric.o build/metric/metric.o build/metric/multiclass_metric.o build/metric/rank_metric.o build/objective/multiclass_obj.o build/objective/objective.o build/objective/rank_obj.o build/objective/regression_obj.o build/tree/tree_model.o build/tree/tree_updater.o build/tree/updater_colmaker.o build/tree/updater_fast_hist.o build/tree/updater_histmaker.o build/tree/updater_prune.o build/tree/updater_refresh.o build/tree/updater_skmaker.o build/tree/updater_sync.o build_plugin/example/custom_obj.o build_plugin/dense_parser/dense_libsvm.o dmlc-core/libdmlc.a rabit/lib/librabit.a -pthread -lm  
`

**Comment by CodingCat** [comment]
additionally, can we enable the python test in windows?

**Comment by superbobry** [comment]
> it looks like the building under OS X is producing libxgboost.so

I think you're referring to the Makefile-based build. Yes it does produce libxgboost.so, but this is in fact incorrect behaviour, because shared library suffix on OS X is .dylib. There is no libxgboost.so in the CMake build output

```bash
$ grep -R libxgboost\.so build/CMakeFiles/libxgboost.dir
```

**Comment by RAMitchell** [comment]
Can we merge this and look into the tests in a subsequent PR?

**Comment by superbobry** [comment]
Sure!

**Comment by khotilov** [comment]
This breaks python package install for windows build with mingw using either Makefile or `cmake .. -G"Unix Makefiles"`, as those are producing lib/libxgboost.dll

Isn't there a way in cmake to enforce the prefix? Maybe something like `set_target_properties(xgboost PROPERTIES PREFIX "lib")` ? 

Another hacky option:
```diff
-        dll_path = [os.path.join(p, 'xgboost.dll') for p in dll_path]
+        dll_path = [os.path.join(p, 'xgboost.dll') for p in dll_path] + \
+                   [os.path.join(p, 'libxgboost.dll') for p in dll_path]
```

**Comment by superbobry** [comment]
I'm afraid enforcing the prefix (as it was done before) would lead to even more cross-platform compatibility issues. I think CMake is right about using the lib- prefix on MinGW because that's a common convention in the *NIX world, but surely this doesn't make the problem any easier.

**Comment by RAMitchell** [comment]
I suggest (untested):

if(MINGW)
  set_target_properties(xgboost PROPERTIES PREFIX "")
endif()

**Comment by superbobry** [comment]
Nice, I'll try it out.

**Comment by khotilov** [comment]
@RAMitchell yes, that works with a few small changes in Makefile. Continuous integration for the mingw would be useful. It seems to be possible with Appveyor.

@superbobry mingw also works just fine for a fair share of practical needs. We also need it for R.

**Pull request merged**
