### PR TITLE
best_ntree_limit attribute & training continuation bugfix

### PR DESCRIPTION
**Pull request by Far0n**
- new 'Booster' attribute *best_ntree_limit* (see https://github.com/dmlc/xgboost/issues/599)
- unittest for *best_ntree_limit*
- bugfix for wrong *best_iteration* returned after training continuation when using *num_parallel_tree* and/or *num_class* as parameter(s)

### CODE REVIEW

**Comment by Far0n** [comment]
just rebased and squashed

**Comment by Far0n** [comment]
*FileNotFoundError: [Errno 2] No such file or directory: 'dot'* ???

**Comment by terrytangyuan** [comment]
@Far0n Thanks! Perhaps add one more test case for `num_class`?

**Comment by Far0n** [comment]
@terrytangyuan test case added :)

**Pull request merged**
