### PR TITLE
[CI] Upgrade cuDF and RMM to 21.06 nightly

### PR DESCRIPTION
**Pull request by hcho3**
Replaces #6825

Ensure that XGBoost works with the upcoming 21.06 release of RAPIDS software.

### CODE REVIEW

**Comment by hcho3** [comment]
I've removed CUDA 10.1 and 10.2 from the test matrix.

**Review by trivialfis — APPROVED** [review]
Nice work on handling all these complexities!

**Comment by hcho3** [comment]
@trivialfis Do you think it's a big jump if we require CUDA 11.0+ in the next release? (Meaning, users with CUDA 10.x will need to build XGBoost from the source, with no assurance that things will work due to lack of test coverage)

**Comment by trivialfis** [comment]
I'm fine with that.  If needed we can put a warning in C++ code, probably through the use of  `cudaRuntimeGetVersion()`

**Comment by hcho3** [comment]
Do you mean a deprecation warning?

**Comment by trivialfis** [comment]
Yup, if that's needed.

**Comment by hcho3** [comment]
Not sure if it's possible to load a shared lib if the shared lib was built with CUDA 11.0 and the target machine is using CUDA 10.x. It may result in failing to load `libxgboost.so` at all.

**Comment by trivialfis** [comment]
I think it's possible to load. CUDA links a static library into `libxgboost.so`, which handles different versions.

**Pull request merged**
