### PR TITLE
Prevent empty quantiles in fast hist

### LINKED ISSUE #2943: Core dumped: src/common/hist_util.cc:140: Check failed: cbegin != cend
@hcho3 @RAMitchell 
```
import xgboost as xgb
import numpy as np
nan = np.nan
params = {'missing': nan, 'tree_method': 'hist'}
model = xgb.XGBRegressor(**params)

Xuse = [[6.18827160e+05,1.73000000e+02],[  6.37345679e+05     ,         nan], [  6.38888889e+05  ,            nan], [  6.28086420e+05           ,   nan]]
yuse = [ 1000000.,        0.,        0.,   500000.]
wuse = [0, 0, 1, 0]

model.fit(Xuse, yuse, sample_weight = wuse)
```

Fails with hist or gpu_hist.  If I remove the sample_weight, it runs without error.

### LINKED ISSUE #4085: [BLOCKING] xgboost.core.XGBoostError: b'[10:49:41] /root/repo/xgboost/src/common/hist_util.cc:152: Check failed: cut.cut.size() > 0U (0 vs. 0)
[failcut.zip](https://github.com/dmlc/xgboost/files/2804394/failcut.zip)

```
Traceback (most recent call last):
  File "9e6890f4-6d04-4331-b595-8e2b6c9638e9_beforexgbobj.dat.py", line 23, in <module>
    model.fit(X, y, sample_weight=sample_weight, **kwargs)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/sklearn.py", line 738, in fit
    callbacks=callbacks)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/training.py", line 227, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/core.py", line 1065, in update
    dtrain.handle))
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/core.py", line 178, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: b'[10:49:27] /root/repo/xgboost/src/common/hist_util.cc:152: Check failed: cut.cut.size() > 0U (0 vs. 0) \n\nStack trace returned 10 entries:\n[bt] (0) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN4dmlc15LogMessageFatalD2Ev+0x26) [0x7f5c93f04c06]\n[bt] (1) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost6common16GHistIndexMatrix4InitEPNS_7DMatrixEi+0x6a6) [0x7f5c93f299e6]\n[bt] (2) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost4tree17QuantileHistMaker6UpdateEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_7DMatrixERKSt6vectorIPNS_7RegTreeESaISC_EE+0x29e) [0x7f5c9402d1ae]\n[bt] (3) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_7DMatrixEiPSt6vectorISt10unique_ptrINS_7RegTreeESt14default_deleteISC_EESaISF_EE+0x777) [0x7f5c93f7fe17]\n[bt] (4) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_11ObjFunctionE+0x845) [0x7f5c93f810d5]\n[bt] (5) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x400) [0x7f5c93f8f930]\n[bt] (6) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(XGBoosterUpdateOneIter+0x35) [0x7f5c93f13385]\n[bt] (7) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f5d5e47be40]\n[bt] (8) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f5d5e47b8ab]\n[bt] (9) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2cf) [0x7f5d5e6c1d2f]\n'
jon@mr-dl10:/data/jon/h2oai/tmp/seeds/3176099$ emacs -nw 9e6890f4-6d04-4331-b595-8e2b6c9638e9_beforexgbobj.dat.py
jon@mr-dl10:/data/jon/h2oai/tmp/seeds/3176099$ python 9e6890f4-6d04-4331-b595-8e2b6c9638e9_beforexgbobj.dat.py
[10:49:41] /root/repo/xgboost/rabit/include/rabit/./internal/../../dmlc/./logging.h:300: [10:49:41] /root/repo/xgboost/src/common/hist_util.cc:152: Check failed: cut.cut.size() > 0U (0 vs. 0) 

Stack trace returned 10 entries:
[bt] (0) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN4dmlc15LogMessageFatalD2Ev+0x26) [0x7fde59835c06]
[bt] (1) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost6common16GHistIndexMatrix4InitEPNS_7DMatrixEi+0x6a6) [0x7fde5985a9e6]
[bt] (2) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost4tree17QuantileHistMaker6UpdateEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_7DMatrixERKSt6vectorIPNS_7RegTreeESaISC_EE+0x29e) [0x7fde5995e1ae]
[bt] (3) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_7DMatrixEiPSt6vectorISt10unique_ptrINS_7RegTreeESt14default_deleteISC_EESaISF_EE+0x777) [0x7fde598b0e17]
[bt] (4) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_11ObjFunctionE+0x845) [0x7fde598b20d5]
[bt] (5) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x400) [0x7fde598c0930]
[bt] (6) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(XGBoosterUpdateOneIter+0x35) [0x7fde59844385]
[bt] (7) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fdf23dace40]
[bt] (8) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7fdf23dac8ab]
[bt] (9) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2cf) [0x7fdf23ff2d2f]

Traceback (most recent call last):
  File "9e6890f4-6d04-4331-b595-8e2b6c9638e9_beforexgbobj.dat.py", line 23, in <module>
    model.fit(X, y, sample_weight=sample_weight, **kwargs)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/sklearn.py", line 738, in fit
    callbacks=callbacks)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/training.py", line 227, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/core.py", line 1065, in update
    dtrain.handle))
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/core.py", line 178, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: b'[10:49:41] /root/repo/xgboost/src/common/hist_util.cc:152: Check failed: cut.cut.size() > 0U (0 vs. 0) \n\nStack trace returned 10 entries:\n[bt] (0) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN4dmlc15LogMessageFatalD2Ev+0x26) [0x7fde59835c06]\n[bt] (1) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost6common16GHistIndexMatrix4InitEPNS_7DMatrixEi+0x6a6) [0x7fde5985a9e6]\n[bt] (2) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost4tree17QuantileHistMaker6UpdateEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_7DMatrixERKSt6vectorIPNS_7RegTreeESaISC_EE+0x29e) [0x7fde5995e1ae]\n[bt] (3) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost3gbm6GBTree13BoostNewTreesEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_7DMatrixEiPSt6vectorISt10unique_ptrINS_7RegTreeESt14default_deleteISC_EESaISF_EE+0x777) [0x7fde598b0e17]\n[bt] (4) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost3gbm6GBTree7DoBoostEPNS_7DMatrixEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_11ObjFunctionE+0x845) [0x7fde598b20d5]\n[bt] (5) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x400) [0x7fde598c0930]\n[bt] (6) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(XGBoosterUpdateOneIter+0x35) [0x7fde59844385]\n[bt] (7) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fdf23dace40]\n[bt] (8) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7fdf23dac8ab]\n[bt] (9) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2cf) [0x7fdf23ff2d2f]\n'
```

This problem has been in xgboost for a very long time.

Generally xgboost needs to at least go back to base average (for regression) or most frequent (for classification) case as a model.  LightGBM does this with its dummy trees.

### PR DESCRIPTION
**Pull request by hcho3**
In fast histogram algorithm, empty columns (or nearly empty columns) may prevent the quantile sketcher 
from producing any quantile point. Failure cases: #4085 and #2943.

Whenever the quantile sketcher produces no quantile point, insert `2 * [minimum feature value]` into the quantile sketch, so that every feature gets at least one quantile point.

Closes #4085 
Closes #2943

@trivialfis @pseudotensor 

Ps. This PR probably does not address #4083.

### CODE REVIEW

**Comment by hcho3** [comment]
The quantile hist updater test should be revised

**Comment by hcho3** [comment]
@trivialfis I revised the updater unit tests so that they test expected semantics of each operation. Let me know what you think.

**Comment by hcho3** [comment]
And now lint just broke :(
It’s the same error as #4156.

**Comment by trivialfis** [comment]
@hcho3 The linter is fixed.  Rebasing on master should solve the problem. :)

**Comment by hcho3** [comment]
Thanks!

**Comment by hcho3** [comment]
@trivialfis I like your suggestion. Let's come back to it after 0.82 release.

**Comment by trivialfis** [comment]
@hcho3 Could you share some insight for what happens if no quantile is available?  Wouldn't it just be an empty feature that doesn't need evaluation?

**Comment by hcho3** [comment]
@trivialfis For now, I simply insert the minimum value: https://github.com/dmlc/xgboost/pull/4155/files#diff-daec1d0ffe267847ee82f8b885a06dbbR152

**Pull request merged**
