### PR TITLE
[jvm-packages] Add `XGBOOST_RABIT_TRACKER_IP_FOR_TEST` to set rabit tracker IP.

### PR DESCRIPTION
**Pull request by wbo4958**
This fixes the CI failure due to internal IP on github action.

### CODE REVIEW

**Review by hcho3 — APPROVED** [review]

**Review by CodingCat — CHANGES_REQUESTED** [review]
instead of adding another configuration for tracker ip even we already have property file to define that, we should consider use the existing one, e.g. give a parameter specifying external property file, etc.

**Comment by trivialfis** [comment]
@CodingCat Oops, 1 second late.

**Comment by trivialfis** [comment]
Opened a revert PR in https://github.com/dmlc/xgboost/pull/6886

**Comment by trivialfis** [comment]
@wbo4958 Could you please reopen the PR and help look into https://github.com/dmlc/xgboost/pull/6869#pullrequestreview-641381474 ?  Sorry for the mess.

**Pull request merged**
