### PR TITLE
[CI] Improve JVM test in GitHub Actions

### PR DESCRIPTION
**Pull request by hcho3**
* Maven: If HTTP connections get interrupted while downloading packages, re-try up to 3 times. [See documentation](https://maven.apache.org/wagon/wagon-providers/wagon-http/).
* Run tests for XGBoost4J-Spark too. This may prove too heavy for GitHub Actions' agents. We'll see.
* Use `-B` (batch mode) flag to remove download progress from the log, reducing clutter.

### CODE REVIEW

**Comment by trivialfis** [comment]
Thanks for looking into this!  So can we remove the CPU tests on Jenkins?

**Comment by hcho3** [comment]
@trivialfis Let's see how well the Spark tests run here.

**Comment by hcho3** [comment]
@trivialfis

**Review by trivialfis — APPROVED** [review]

**Comment by hcho3** [comment]
I'll prune JVM tests from Jenkins in a future PR.

**Pull request merged**
