### PR TITLE
[pyspark] Re-work _fit function

### PR DESCRIPTION
**Pull request by wbo4958**
The original _fit function has over 200 lines, it's really not easy to read. So I break it up into several functions in this PR.

### CODE REVIEW

**Review by trivialfis — APPROVED** [review]
Looks good to me assuming the CI passes.

**Comment by wbo4958** [comment]
@trivialfis seems the CI env has some issues, could you help to check it? Thx

**Comment by trivialfis** [comment]
Fixed at master branch.

**Comment by wbo4958** [comment]
Thx, updated to latest commit.

**Pull request merged**
