### PR TITLE
added basic CMakeLists.txt files for xgboost.

### PR DESCRIPTION
**Pull request by wnguatem**
My system (win7 x64 running vs2013) was complaining whilst building xgboost. So I had to make the following minor changes.
1. 
Naming convention issue: “math.h” as in (src/common) is a bad idea since this overloads the usual math.h from the development system and Visual Studio keeps looking for exp(), log() e.t.c and can’t find them because of the name collision with the math.h providen by xgboost. I suggest naming this to xgboost_math.h
2.	
Missing Header issues: We need to add the missing header  #include <functional> in sparse_batch_page.h and tree_updater.h for this is required for std::function.
3.	
Collision issue:  I commented out the redefinition of ulong in base.h this seems to be colliding with the defintion in c_api.h
4.	I’ve added some minimal cmake files for both xboost and rabit. This can of course be far more elegant if required

Would be happy for any feedback

### CODE REVIEW

**Comment by tqchen** [comment]
Please make merge the latest version in the master. It would also be great if we can add a CMake build step in travis so the build script is checked.

I agree with your changes (1) and (2)

**Comment by wnguatem** [comment]
Sofar am not familiar with travis, but I'll see that in the course of this week, I'll adjust the cmake build build script accordingly.

**Comment by tqchen** [comment]
Thanks @wnguatem I think we can merge things in once the travis test is passed. You also need to rebase against the most recent masters https://xgboost.readthedocs.org/en/latest/dev-guide/contribute.html#how-to-resolve-conflict-with-master

**Comment by tqchen** [comment]
@wnguatem any update on this?

**Comment by wnguatem** [comment]
Sorry for the delay. I caught a bad cold last week. Will definitely get this running on or before friday this week.

**Comment by tqchen** [comment]
@wnguatem do we have any updates on this?

**Comment by tqchen** [comment]
hi @wnguatem Any chance we can push a bit more and finish this PR? Thanks!

**Comment by wnguatem** [comment]
Absolutely!
I’ll be back from vacation/holiday (Pentecost) on the 30th May.
Should get things up running during that same week.
Cheers

**Pull request closed without merging**
