### PR TITLE
Optimization part applysplit for hist and approx

### PR DESCRIPTION
**Pull request by ShvetsKS**
it's part of #7192

Current implementation of partition allow to read bin matrix data with less random access

full train| airline, ~100m | higgs, ~10m
-- | -- | --
master, s | 403 | 53.7
this PR, s | 170s | 32.5
speedup | 2.37 | 1.65

copy of https://github.com/dmlc/xgboost/pull/7208

### CODE REVIEW

**Comment by hcho3** [comment]
This PR is a duplicate of #7208. Is there some kind of mistake?

**Comment by ShvetsKS** [comment]
> This PR is a duplicate of #7208. Is there some kind of mistake?

Yes. There is a problem with [build-gpu-cuda11.0](https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-7208/43/pipeline/59) step: _Public key for cuda-compat-11-0-450.172.01-1.x86_64.rpm is not installed_

Creating this new PR helped to solve this issue for base PR, but now it doesn't work, sorry. Seems there is a better way to fix it.

**Comment by hcho3** [comment]
@ShvetsKS There is a problem in the CI with repo keys: #7855

**Comment by ShvetsKS** [comment]
> @ShvetsKS There is a problem in the CI with repo keys: #7855

Why there is no such problems for new PR?
Seems it's reproduced only on old ones, like https://github.com/dmlc/xgboost/pull/7208
What's the best way to meetigate it here https://github.com/dmlc/xgboost/pull/7208?

**Comment by hcho3** [comment]
@ShvetsKS This is because Docker containers are cached and reused. I'll try to get to it within next 2 weeks.

**Pull request closed without merging**
