### PR TITLE
Python: add more params in sklearn wrapper.

### PR DESCRIPTION
**Pull request by lihang00**

### CODE REVIEW

**Comment by tqchen** [comment]
thanks, one thing, please keep the original parameter order and add parameters after awards, although it might be less alphabetically ordered, this help keeps things compatible, and originally support parameters are more significant.

**Comment by tqchen** [comment]
@lihang00 it would be great if you can update the PR

**Comment by lihang00** [comment]
Sure, I will update this PR and keep original parameter order later today.

**Comment by tqchen** [comment]
no problem, you can use the order from the xgoost parameter page

**Comment by lihang00** [comment]
add few more params, it should support all "Parameter for Tree Booster" and "Task Parameters".

**Comment by walterreade** [comment]
Should the early_stopping_rounds parameter be included in the params dict also?

**Comment by lihang00** [comment]
early_stopping_rounds parameter is implement in python wrapper. To add it as a parameter, will need some changes in fit fuction. I suggest we open a separate issue (or PR) for adding this parameter.

**Comment by tqchen** [comment]
one thing about eval_metric, this is handled differently in python via a watchlist, consider remove it or try the python way

**Comment by lihang00** [comment]
make sense, I will remove it for now.

**Comment by lihang00** [comment]
ok, I will remove it for now.

**Comment by walterreade** [comment]
I'm happy to do the PR for early_stopping_rounds in the parameter dict, instead of inside the fit method. Just wanted to see if that makes sense (or if not, what the reason is).

**Comment by tqchen** [comment]
I think in the idea of sklearn, seems all the related parameters should go into the init instead of fit, so that makes sense. @lihang00  what was your opinion on this?

**Pull request merged**
