### PR TITLE
[R] Monotonic Constraints in Tree Construction

### PR DESCRIPTION
**Pull request by hetong007**
This is an update as a follow up of https://github.com/dmlc/xgboost/issues/1514

R users now can pass a numerical vector to `monotone_constraints`.

### CODE REVIEW

**Comment by hetong007** [comment]
The errors are in python tests. I will wait for the fix for them and then merge.

**Comment by hetong007** [comment]
@tqchen Can you have a look at the failed checks? They are on python's side, but I didn't touch python.

**Comment by tqchen** [comment]
seems was due to python3 travis issue @terrytangyuan can you look into it?

**Comment by terrytangyuan** [comment]
Checks seem to be passing. Could you rebase and try again?

**Pull request merged**
