### PR TITLE
fix bug: doing rabit call after finalize in spark prediction phase

### PR DESCRIPTION
**Pull request by titicaca**
Issue:
[jvm-packages] Executors fail during prediction (Doing rabit call after Finalize) #1284

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@tqchen @CodingCat Could you take a look?

**Comment by CodingCat** [comment]
I'm not 100% confident about the rabit implementation details, especially about why rabit is involved in prediction, waiting for @tqchen 's answer

**Comment by tqchen** [comment]
LGTM

**Comment by CodingCat** [comment]
@tqchen , why rabit is involved in prediction?

**Comment by tqchen** [comment]
I think it is mainly because the DMatrix construction code asks for the partition id, otherwise there is nothing involved

**Comment by titicaca** [comment]
In c_api.cc, XGBoosterPredict calls bst->LazyInit(),
```
inline void LazyInit() {
    if (!configured_) {
      learner_->Configure(cfg_);
      configured_ = true;
    }
    if (!initialized_) {
      learner_->InitModel();
      initialized_ = true;
    }
  }
```
configured_ in the Booster Constructor is false and will call learner_->Configure(cfg_);
In Configure() in learner.cc, rabit::IsDistributed() calls rabit::getEngine()

**Comment by Earthson** [comment]
Anyone still works on this? @titicaca

**Comment by tqchen** [comment]
need rebase before merge

**Comment by titicaca** [comment]
@tqchen Thanks for  the reminder. I have made rebase and created another pull request:    #1420

**Comment by CodingCat** [comment]
I reproduced this bug today , it seems that this PR does not resolve the problem in a comprehensive way, I'm looking into it

**Comment by nikolay-karpow** [comment]
I'm facing the same problem with spark 2.0.2. 

1. It works fine with embedded spark and with a single executor cluster
2. Executors crash during XGBoostModel.predict(testSet: RDD[MLVector], useExternalCache: Boolean = false) call
3. Execturos crash (less often but still) even with XGBoostModel.booster().predict(data: DMatrix, outPutMargin: Boolean = false, treeLimit: Int = 0)

Is there any progress with this issue? Is there at least any known workaround?

**Comment by tqchen** [comment]
@CodingCat @titicaca Now that I rethinked the problem, I think a cleaner solution is simply do a rabitInit without passing in anything, so it won't even have to wait other rabit workers to start the prediction.

**Comment by CodingCat** [comment]
@nikolay-karpow can you post the complete stack trace? I didn't see how `XGBoostModel.booster().predict` can fail, since it is just a single-machine operation

**Comment by CodingCat** [comment]
@tqchen, do you mean that the Rabit workers will try to sync with each other even we do not start a tracker? because when calling prediction methods, we do not start any tracker....

**Comment by tqchen** [comment]
oh, then that is also fine. As long as the info passed to the worker is empty

**Comment by CodingCat** [comment]
I am curious to see what's the real problem here, since we have initialized a dummy rabit in each Spark task....@nikolay-karpow

**Comment by nikolay-karpow** [comment]
@CodingCat Unfortunately, I cannot give you a stack trace, because there is no one. Executor dies with "Doing rabit call after Finalize", driver just detects executor lost, that's it. And I saw it with `XGBoostModel.booster().predict` just once, during ~30 hours of models training. 

There is one more thing to say though. I experienced those failures when I trained models by 2 in parallel on the same cluster. I'm trying training with just a single model at a time now, it looks stable, there are no dead executors so far (~24 hours). So, maybe multiple models at once is the key?

I'm rather new in XGBoost. But as far as I understand from this discussion and from sources, local predict uses DMatrix, which uses Rabit, right? Just a guess: might it happen, that if there is a training in process, when we do local predict, predict and training can conflict somehow?

**Comment by CodingCat** [comment]
yeah, we do have some problem when we have parallel Rabit trackers/workers, which is something interesting to look into

**Comment by fathersson** [comment]
@CodingCat, since there is some kind of race condition and predict by itself uses rabit, might it happen that for high load of parallel predicts on different models without training for even a single model, there might be failures?

**Comment by CodingCat** [comment]
@fathersson while I forgot most of details about parallel model training issue, I had the impression that the issue is caused by the interaction between worker and tracker, so Spark tasks with dummy rabit worker shall be fine...

but feel free to correct me if you reproduced any issue

**Comment by fathersson** [comment]
@CodingCat do you may be remember if the race condition caused by the rabit itself? I'm trying to narrow it down... Is it may be possible to somehow workaround it by starting different trackers on different ports for different models?

**Pull request closed without merging**
