### PR TITLE
Fix Windows 2016 build.

### PR DESCRIPTION
**Pull request by trivialfis**
Found during setting up github action.  There's still an external test `SparsePage, PushCSCAfterTranspose`  failing on latest Ubuntu and Windows.  I can't fix it right now with the complexity of external memory.  So I just port a small fix here.

### CODE REVIEW

**Comment by hcho3** [comment]
@trivialfis Can you run the exhaustive JSON test with this new code?

**Comment by trivialfis** [comment]
@hcho3 I did.

**Comment by trivialfis** [comment]
Let me try running it on Windows later tonight.

**Comment by trivialfis** [comment]
Note to myself: Clean python build dir after retrying vs version.

**Comment by trivialfis** [comment]
@hcho3 Ran the test on Windows.

**Pull request merged**
