### PR TITLE
TST: Added R unit test for glm

### PR DESCRIPTION
**Pull request by terrytangyuan**

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@hetong007  This passed tests on my local PC though...

**Comment by hetong007** [comment]
1. It cannot pass my check on a Ubuntu 14.04 machine via `make Rcheck`. 
2. `expect_that` is described as "An old style of testing that's no longer encouraged." in its document. Please don't use it. It should pass the test without it.

**Comment by terrytangyuan** [comment]
Got it. Thanks it's passing now.

**Comment by hetong007** [comment]
Merged. Thanks!

**Pull request merged**
