### PR TITLE
Sklearn API support for histogram optimized tree grower.

### PR DESCRIPTION
**Pull request by mortido**
Added `tree_method`, `grow_policy`, `max_leaves` and `max_bin` parameters to Sklearn wrapper with default values and documentation. It allows to use new histogram optimized tree grower (#1950).

### CODE REVIEW

**Comment by gaw89** [comment]
@mortido, I believe these additions are covered by #2338.  This update added the **kwargs argument to the constructor which allows a user to provide a parameter dictionary to XGBClassifier (or XGBRegressor) similar to one which would be provided to xgboost.train().  Full documentation of available parameters is available [here](https://github.com/dmlc/xgboost/blob/master/doc/parameter.md).  

Example:
`from xgboost import XGBClassifier
params = {'tree_method':'auto','grow_policy':'depthwise', 'max_bin':256, 'max_leaves':0}
clf = XGBClassifier(**params)`

Hope this helps!

**Comment by mortido** [comment]
@gaw89, yeah, it looks like with **kwargs now user can handle almost all new parameters. Does it mean that no new arguments should be added to init method of Sklearn wrapper or there is some criteria by which some args should be added and some shouldn't (though it's good to have docstrings)?

**Comment by mortido** [comment]
Just found PR #2336 where discussed that adding every param individually isn't way to go. So I'm closing this PR.

**Comment by gaw89** [comment]
Oh yeah, I forgot about that one.

**Pull request closed without merging**
