### PR TITLE
[R] update `predict` docs (fixes #8869)

### LINKED ISSUE #8869: [R] How to specify the number of threads in `predict.xgb.Booster()`?
I see that we can specify the number of threads in [train()](https://cran.r-project.org/web/packages/xgboost/xgboost.pdf#Rfn.xgb.train.1) using `nthread` parameter, but can it be done in [predict()](https://cran.r-project.org/web/packages/xgboost/xgboost.pdf#Rfn.predict.xgb.Booster.1)? Currently all threads are used by default.

### PR DESCRIPTION
**Pull request by kadyb**
I wanted to rebuild Rd documentation in RStudio, but I got this error:

```
xgboost_R.cc:4:10: fatal error: dmlc/common.h: No such file or directory
    4 | #include <dmlc/common.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
```

But in general this PR should work.

### CODE REVIEW

**Comment by trivialfis** [comment]
Thank you for the PR!

> I wanted to rebuild Rd documentation in RStudio, but I got this error:

Did you fetch the repository using `git clone --recursive https://github.com/dmlc/xgboost.git`?

**Comment by kadyb** [comment]
> Did you fetch the repository using git clone --recursive https://github.com/dmlc/xgboost.git?

It was the problem. I downloaded the repo directly from the GitHub website and it skipped `/dmlc/dmlc-core`. Now it should be fine.

**Review by trivialfis — APPROVED** [review]
Thank you for enhancing the document!

**Comment by kadyb** [comment]
Thanks!

**Pull request merged**
