### PR TITLE
hardcoding akka version https://github.com/dmlc/xgboost/issues/1858

### PR DESCRIPTION
**Pull request by geoHeil**
https://github.com/dmlc/xgboost/issues/1858

### CODE REVIEW

**Comment by CodingCat** [comment]
Is it a problem with maven?

**Comment by geoHeil** [comment]
For maven it is only a warning:

Expected all dependencies to require Scala version: 2.11.8
[WARNING]  com.typesafe.akka:akka-actor_2.11:2.3.11 requires scala
version: 2.11.5
[WARNING] Multiple versions of scala libraries detected!

But for sbt, later on using xgboost4j-spark

it turns out to be fatal

warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.akka#akka-actor_${scala.binary.version};2.3.11:
not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::


Nan Zhu <notifications@github.com> schrieb am Do., 15. Dez. 2016 um
21:37 Uhr:

**Comment by CodingCat** [comment]
then why it is a problem of xgboost? for me it is a problem of sbt....I didn't see how multiple versioned scala libraries would make a build tool not be able to resolve a variable

**Comment by CodingCat** [comment]
I will close this one, since it is just a problem of sbt

**Pull request closed without merging**
