### PR TITLE
[CI] Update machine images

### PR DESCRIPTION
**Pull request by hcho3**
* Use R 4.3 in the Windows machine
* Rebuild machine images using latest base OS images
* Update the launch parameter according to the latest Elastic AWS Stack of BuildKite.
* Enable `BUILDKIT_INLINE_CACHE` option to enable caching layers from pulled containers. This is needed for latest Docker, which uses BuildKit (https://github.com/moby/moby/issues/39003).
* `dlltool.exe` was failing due to long file names. 1) Error out early if `dlltool` fails. 2) Use a short file name for the temporary file.
* Speed up RPM by setting `ulimit` option. See https://github.com/docker/buildx/issues/379
* Use latest NVIDIA Container Toolkit. As a side effect, the legacy command `nvidia-docker` is no longer available. Now we should use `docker run --gpus all` instead.

### CODE REVIEW

**Comment by trivialfis** [comment]
Could you please help take a look into https://github.com/dmlc/xgboost/issues/9618 , it would be great if we can restore the Windows tests.

**Comment by hcho3** [comment]
> Could you please help take a look into https://github.com/dmlc/xgboost/issues/9618

I will take a look at it once we unblock the rest of the CI.

**Comment by hcho3** [comment]
@trivialfis Sorry this is taking a bit longer than I expected. Please refrain from running CI jobs until the CI is straightened out.

**Comment by trivialfis** [comment]
Please disable the allocator test, it doesn't always work.

**Comment by hcho3** [comment]
Merging this to unblock the CI

**Pull request merged**
