### PR TITLE
[CI] Stop Windows pipeline upon a failing pytest

### LINKED ISSUE #9618: [CI] Failing tests are not reported accordingly on Windows.
https://buildkite.com/xgboost/xgboost-ci-windows/builds/3566#018adc46-b6b7-423a-937c-4f35bbb67575

### PR DESCRIPTION
**Pull request by hcho3**
Closes #9618

Currently, the Windows CI pipeline continues to execute even when a pytest fails. Example: https://buildkite.com/xgboost/xgboost-ci-windows/builds/4475#018d34ec-1805-4b3a-8206-e4addbae123f/2297-23796
This is because a PowerShell script doesn't stop automatically when a child process returns a non-zero exit code. See https://stackoverflow.com/a/9949909.

Fix: Explicitly check the exit code from the pytest suites and terminate the script as needed. Example: https://buildkite.com/xgboost/xgboost-ci-windows/builds/4477#018d3862-44d6-4219-8f40-7db901f8653a/4179-25710

### CODE REVIEW

**Comment by hcho3** [comment]
@trivialfis Can you help debug the failing pytest `test_device_quantile_dmatrix.py::TestQuantileDMatrix::test_check_inf` ?

**Comment by trivialfis** [comment]
Will look into it.

**Comment by trivialfis** [comment]
There's a bug in MSVC + NVCC, it somehow enters a condition even though it's false (explicitly printed and verified to be false). Trying to come up with a workaround.

**Review by trivialfis — APPROVED** [review]

**Comment by hcho3** [comment]
Thank you for the fix!

**Pull request merged**
