### PR TITLE
stylistic fix

### PR DESCRIPTION
**Pull request by CodingCat**

### CODE REVIEW

**Comment by CodingCat** [comment]
@tqchen , I think the real problem is the setting of CI, the required tag shall be on `continuous-integration/appveyor/pr`?

**Comment by tqchen** [comment]
see https://travis-ci.org/dmlc/xgboost/jobs/177081720 it seems to be problem in maven?

**Comment by CodingCat** [comment]
eh...the current problem is in maven...before it...when I passed ` continuous-integration/travis-ci/pr ` and `continuous-integration/appveyor/pr` I am stil not be able to merge it....

**Comment by CodingCat** [comment]
from the description https://www.appveyor.com/updates/2015/11/06/, `continuous-integration/appveyor/pr ` is the right thing for PR

**Comment by tqchen** [comment]
I see, I removed the appveyor/branch, and make appveyor/pr as required, thanks for the catch

**Pull request merged**
