### PR TITLE
xgb.cv( printEveryN ) parameter to print every n-th progress message

### PR DESCRIPTION
**Pull request by by321**

### CODE REVIEW

**Comment by hetong007** [comment]
Thank you for this PR :)

**Comment by khotilov** [comment]
An observation concerning the style of function parameters: there was already lowercasenospace, underscore separators, dot separators (with some unusual redundancy between dots and underscores), and now camelCase. It might be a good idea to enforce some consistency.

**Comment by tqchen** [comment]
I agree with @khotilov  on this issue, @hetong007 can you make a fix on this?

**Comment by hetong007** [comment]
@tqchen You mentioned the compatibility with underscore, is it concerning python users?

**Comment by tqchen** [comment]
@hetong007  I think we can do dot cases only.

**Comment by hetong007** [comment]
@tqchen OK, I agree. I will do a pass over name of function arguments.

**Comment by hetong007** [comment]
It is done with the latest commit.

**Pull request merged**
