### PR TITLE
Introducing DPC++-based plugin (updater, predictor, objective function) supporting oneAPI programming model

### PR DESCRIPTION
**Pull request by vepifanov**
Introducing DPC++-based plugin (updater, predictor, objective function) supporting oneAPI programming model.

Updater target is grow_quantile_histmaker.

Following process intended:
1. Start with existing implementation of grow_quantile_histmaker and continuously replace OpenMP parts into DPC++ kernels.
2. As soon as we get whole flow transformed into DPC++ kernels, start analyzing potential optimizations.

Current partial stoppers:
1. DPC++ compiler is required to build plugin sources and final linkage of the library, so additional compiler/linker flags should be added to building process (beyond the plugin itself).
2. Data passing between updater/prediction/getGradient calls is wrapped into HostDeviceVector which now supports only CPU/CUDA memory, so additional host-device transfers are required on each iteration.

### CODE REVIEW

**Comment by trivialfis** [comment]
Just out of personal curiosity, oneapi seems pretty similar to sycl, is it going to be complete different frameworks in the future or it's more about branding?  A follow up question, if there's another vendor supports sycl as khronos sycl like Codeplay or Xilinx do we need to go over this again?

Also now that we have 3 backends, we need to come up with a way to manage them.

**Comment by napetrov** [comment]
@trivialfis - thanks for questions
oneAPI - is a programming model, Intel is initial contributor but this is open initiative that welcome other contributors
sycl - this is both sycl language and corresponding khronos standard
DPC++ - this is language extension on top of sycl that used by oneAPI. It have conformance to certain sycl spec  but primarily this is covered by oneAPI specification in same way as other componets such as oneDAL(Classical ML)
OneAPI spec - https://spec.oneapi.com/versions/latest/index.html 

As for other vendors support - the overall idea that this should allow simple integration for other vendors.  
there was a discussion on this with more details on overall plan
https://github.com/dmlc/xgboost/issues/5442

For backend management - yes. Should we assume this as requirement a this point? or at this is something that make sense to define then this will be moved out of plugin stage?

**Comment by RAMitchell** [comment]
In the plug in stage I don't think it's a requirement, but to integrate into the main code base we will need a clear plan for multiple backends in a maintainable way. It's something to start thinking about.

**Comment by trivialfis** [comment]
You don't have to write a complete implementation at one drop right?  You can start from small but critical like histogram building, and expand to some other places in the future ...

**Pull request closed without merging**
