### PR TITLE
Integration of a faster version of grow_gpu plugin into mainstream

### PR DESCRIPTION
**Pull request by teju85**
Hi,
Please note that this was a one-or-nothing change. Most of these things were needed in order for our grow_gpu version to be made part of this main branch. Things done in this PR:
1. Removed the older files to reduce duplication
2. Moved all of the grow_gpu files under 'exact' folder
3. All of them are inside 'exact' namespace to avoid any conflicts
4. Fixed a bug in benchmark.py while running only 'grow_gpu' plugin
5. Added cub and googletest submodules to ease integration and unit-testing
6. Updates to CMakeLists.txt to directly build cuda objects into libxgboost
7. Added support for building gpu plugins through make flow
8. updated makefile and config.mk to add right targets
9. added unit-tests for grow_gpu plugin
10. Added support for building gpu plugin using 'make' flow as well
11. Updated instructions for building and testing gpu plugin in the README

Things TODO: (and will be in the forthcoming PR's, which I'll make sure are small enough to be reviewed easily)
1. sm_arch updates (currently they are hard-coded in cmake as well as in make)
2. there were some compiler warning messages introduced due to this integration. Those will be removed
3. some more optimizations to the grow_gpu (lower priority, right now)

Regards,
Thejaswi

### CODE REVIEW

**Comment by RAMitchell** [comment]
Awesome work.
@pseudotensor if you have time can you do a code review/test. I will be away a few days.

@tqchen is the addition of submodules ok?

**Comment by teju85** [comment]
@RAMitchell and @tqchen 
I had to remove the googletest submodule in the next commit, since it was conflicting with travis builds. Hence, currently only 'cub' is needed as as submodule.

**Comment by tqchen** [comment]
I think it is fine to include cub as submodule, for gtest, we should not add it, since the gtest is a thirdparty library that is rather stable and we already have it for testing purposes

**Comment by RAMitchell** [comment]
Can you generate the test data in python instead of committing a libsvm file.

Does nvidia require you to have the copyright message? A lot of this code contains my work and will be edited by various other contributors.

**Comment by teju85** [comment]
@RAMitchell 

>>Can you generate the test data in python instead of committing a libsvm file.
These are not randomly generated, but a static dataset that I use to check the correctness of the GPUBuilder. (that way, I know beforehand what the best split is and what each nodes contain). Does it still need to be generated by a script?

>>Does nvidia require you to have the copyright message?
Yes

>> A lot of this code contains my work and will be edited by various other contributors.
That was my mistake. The files which contain code from both of us, I had missed your copyright message during integration. Thanks for catching it. I have fixed this issue in the latest commit.

**Comment by RAMitchell** [comment]
I prefer to generate the data if possible so the tests are self contained and the git repo is cleaner. There are so many parts to xgboost with people actively working on them that the growth of the repo could be a problem.

Would be nice if you could combine the copyright messages into one although I'm sure we can live with it if you can't.

E.g. 
/*
  * Copyright (c) 2017, NVIDIA CORPORATION, Xgboost contributors.  All rights reserved.
  *

**Comment by RAMitchell** [comment]
Tested everything today. Looks really good. 

A few comments:
- Can you print out the memory usage when silent=0, consistent with the other GPU algorithms
- There is a /test and /tests folder. Maybe this could be changed to test/python and test/cpp
- Google test is required to build. This could be annoying as it needs to be manually installed when building on a new machine (e.g. aws). Can we make this optional?
- The linter doesn't look at .cuh files. You may have to change the dmlc-core lint script to manually make it do this, just to check the code style is consistent. I will PR a fix for this at some point.

**Comment by teju85** [comment]
1. Resolved conflicts with the latest changes to CMakeLists.txt
2. Fixed copyright text as per previous comment
3. added a simplistic shell script to generate the data for unit-tests

Let me look into your immediately previous comments, Rory.

**Comment by teju85** [comment]
For generalizing the unit-tests, I have filed an issue here: https://github.com/dmlc/xgboost/issues/2382.

**Comment by teju85** [comment]
@RAMitchell Latest commit fixes your comments. Please check.

**Pull request merged**
