### PR TITLE
updater_quantile_hist.cc annotation adjustment

### PR DESCRIPTION
**Pull request by gklab**

### CODE REVIEW

**Comment by trivialfis** [comment]
Many of the annotations are generated by include-what-you-use. It turns out it's challenging to keep up-to-date as a naive application of iwyu doesn't always give the correct output and requires manual adjustment. It would be great if we could adopt a complete solution based on iwyu with header mapping.

**Comment by gklab** [comment]
> 

Well, automatic plus manual adjustment is really not a long-term solution.
I try to research it.

**Comment by gklab** [comment]
> Many of the annotations are generated by include-what-you-use. It turns out it's challenging to keep up-to-date as a naive application of iwyu doesn't always give the correct output and requires manual adjustment. It would be great if we could adopt a complete solution based on iwyu with header mapping.

Well, automatic plus manual adjustment is really not a long-term solution.
I try to research it.

**Comment by trivialfis** [comment]
Closing now as the changes are out-dated.

**Pull request closed without merging**
