### PR TITLE
Use feature interaction constraints to narrow search space for split candidates

### LINKED ISSUE #4217: Use feature interaction constraints to narrow search space for split candidates.
See https://github.com/dmlc/xgboost/issues/4075#issuecomment-469751693. In the split finding step, we currently enumerate all features:
https://github.com/dmlc/xgboost/blob/5f34078fba1b489009ed80899961c50229070732/src/tree/updater_quantile_hist.cc#L542-L554
The feature interaction constraints kick in only after we evaluate all split candidates.

We should take advantage of feature interaction constraints (if given) and preemptively narrow the search space in feature dimension. TODO: evaluate possible speedup.

### PR DESCRIPTION
**Pull request by sperlingxx**
Fixes #4217 

Use feature interaction constraints to narrow search space for split candidates.

### CODE REVIEW

**Comment by hcho3** [comment]
Nice! Will review soon

**Comment by hcho3** [comment]
Re-basing against the latest master to fix failing tests

**Comment by hcho3** [comment]
I can't figure out why this breaks distributed training.

**Comment by hcho3** [comment]
Actually, the issue is not with distributed training but single-node training too.

**Comment by hcho3** [comment]
@sperlingxx I figured out the problem. I'll merge this after all tests pass.

**Comment by hcho3** [comment]
Thanks!

**Comment by sperlingxx** [comment]
@hcho3 
Thank you very much for debugging this problem, since I'm a noob of OPEN_MP :)

**Pull request merged**
