### PR TITLE
[jvm-pacakges] the first parameter in getModelDump should be featuremap path not model path

### PR DESCRIPTION
**Pull request by fromradio**
The current `XGBoost.getModelDump` method is a wrapper of cpp version. The first parameter should be the featuremap file path and the modelInfo (an array of String) is returned. Thus if we want to get the dump model, we have to write the infos into the model file.

So the code

```java
booster.getModelDump("./model/dump.raw.txt", false);
```

cannot dump the model into the desired path. The change I made can successfully dump the infos into local file with the same format as the python version.

### CODE REVIEW

**Comment by fromradio** [comment]
Hello everyone, It is my first time to use this. I found out that I just modify the java part but python-lightweight-test cannot path. I go to the tests/travis/run_tests.sh and found out that when Task=python-lightweight-test the java part is not compiled? Can anyone help me on this?

**Comment by CodingCat** [comment]
don't worry, there is some problem in the python part or travis CI...just wait for the fix @tqchen

**Comment by CodingCat** [comment]
for this PR, would you fix scala example as well?

**Comment by fromradio** [comment]
Sure, but I have to wait until next Monday to access my working computer. Is it OK?

**Comment by CodingCat** [comment]
that's OK

**Comment by fromradio** [comment]
Hi, I have modified the scala version.

**Pull request merged**
