### PR TITLE
SO_DOMAIN do not support on AIX, using getsockname instead

### PR DESCRIPTION
**Pull request by zheddie**
getsockopt do not support SO_DOMAIN on AIX/IBM i . Using the getsockname() instead to get the domain info. thanks.

### CODE REVIEW

**Review by trivialfis — COMMENTED** [review]
Thank you for the fix, does it work if the socket is not yet binded?

**Comment by trivialfis** [comment]
You can check the result based on cpp unittest `testxgboost --gtest_filter=Socket.Basic`.

**Comment by zheddie** [comment]
@trivialfis  thanks. Can you help me how to build out the testxgboost utility?

**Comment by zheddie** [comment]
> Thank you for the fix, does it work if the socket is not yet binded?

Yes. the domain could be retrieved just after the socket been created by socket() routine.

**Comment by trivialfis** [comment]
XGBoost requires googletest to build its c++ tests.

```
cmake path/to/xgboost -DGOOGLE_TEST=ON
make
./testxgboost

**Review by trivialfis — APPROVED** [review]

**Comment by zheddie** [comment]
BTW, how can we make sure this fix tobe integrated in next release/fixpack ? @trivialfis  thanks.

**Comment by trivialfis** [comment]
@zheddie We will.

**Pull request merged**
