### PR TITLE
Fixes #9332. xgboost4j-gpu_2.12-2.0.0: added libxgboost4j.so back.

### LINKED ISSUE #9332: Not contains `libxgboost4j.so` in the xgboost4j-gpu_2.12-2.0.0-SNAPSHOT.jar
Not contains `libxgboost4j.so` in the xgboost4j-gpu_2.12-2.0.0-SNAPSHOT.jar 
- `libxgboost4j.so` was in the GPU version of xgboost4j-`gpu`_2.12 jar weeks ago, (since 20230606 or so)
-  `libxgboost4j.so` exists in the `CPU` version of xgboost4j_2.12 jar

Download xgboost4j-gpu_2.12-2.0.0-SNAPSHOT.jar jar from [SNAPSHOT repo]
(https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/snapshot) as below

```
mvn -B dependency:get -DremoteRepositories=https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/snapshot  -Dtransitive=false -Dartifact=ml.dmlc:xgboost4j-gpu_2.12:2.0.0-SNAPSHOT:jar

ls

-rw-rw-r--  1    306M Jun  3 21:36 xgboost4j-gpu_2.12-2.0.0-20230603.213634-496.jar
-rw-rw-r--  1    101K Jun  6 03:06 xgboost4j-gpu_2.12-2.0.0-20230606.030622-501.jar
-rw-rw-r--  1    101K Jun 26 03:21 xgboost4j-gpu_2.12-2.0.0-SNAPSHOT.jar
```

XGBoost train on `GPU` will fail as below:

```
java.io.FileNotFoundException: File /lib/linux/x86_64/libxgboost4j.so was not found inside JAR.
at ml.dmlc.xgboost4j.java.NativeLibLoader.createTempFileFromResource(NativeLibLoader.java:285)
at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:228)
at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:168)
at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:34)
```

### PR DESCRIPTION
**Pull request by dotbg**
Fixes #9332

### CODE REVIEW

**Comment by trivialfis** [comment]
cc @hcho3 @wbo4958

**Comment by dotbg** [comment]
Not sure whether I can do anything about the 
```
Could not transfer artifact org.apache.maven.shared:maven-filtering:pom:3.3.1 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-filtering/3.3.1/maven-filtering-3.3.1.pom: Connection reset -> 
``` on windows build machine :(

**Comment by hcho3** [comment]
It was an transient error. I restarted the test.

**Review by hcho3 — APPROVED** [review]

**Review by wbo4958 — APPROVED** [review]

**Comment by dotbg** [comment]
@trivialfis do I need to do anything else to get this merged ?

**Review by trivialfis — APPROVED** [review]
Apologies for the slow reply.

**Comment by dotbg** [comment]
No worries. Could you, please, merge these changes?

**Comment by trivialfis** [comment]
Yup, just waited a little bit for the CI on master branch to pass.

**Comment by dotbg** [comment]
Thanks a lot!

**Pull request merged**
