### PR TITLE
Memory consumption fix for row-major adapters

### PR DESCRIPTION
**Pull request by ShvetsKS**

### CODE REVIEW

**Comment by ShvetsKS** [comment]
related issue: https://github.com/dmlc/xgboost/issues/6552

**Comment by ShvetsKS** [comment]
Step "XGBoost-R-Tests/..." is failed due to connection problems:
"The remote server returned an error: (502) Bad Gateway. Bad Gateway"

**Comment by ShvetsKS** [comment]
@trivialfis thank for removing unused variable :)

**Comment by RAMitchell** [comment]
Is there any solution that does not specialise for row major only?

**Comment by trivialfis** [comment]
I spent some time on reading papers about matrix transpose, see comments in linked issue.

**Comment by ShvetsKS** [comment]
> Is there any solution that does not specialise for row major only?

Yes, as we have to do transpose for columnar-major case there is no common effective solution in my opinion. If it is possible to have resulting columnar-major DMatrix we can some kind of generalize the code effectively.

**Comment by ShvetsKS** [comment]
not sure that [this failure](https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-6779/9/pipeline#step-339-log-278) related to current changes
[2021-03-25T08:11:20.565Z] terminate called after throwing an instance of 'thrust::system::system_error'

[2021-03-25T08:11:20.565Z]   what():  for_each: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered

**Review by trivialfis — APPROVED** [review]
Looks good to me.  Thanks for the quick fix!


@RAMitchell @hcho3 I don't have a better solution for this as it requires a general matrix transpose procedure.  I would like to get it into 1.4.  WDYT?

**Comment by RAMitchell** [comment]
I'm happy to proceed.

**Pull request merged**
