### PR TITLE
[dask] Add shap tests.

### PR DESCRIPTION
**Pull request by trivialfis**
* Add tests for contribution and interaction.
~* Add test for IO.~ Moved to https://github.com/dmlc/xgboost/pull/6582
* Move mypy from github action file to makefile for easier local testing.

Related: https://github.com/dmlc/xgboost/issues/6568 .

I haven't been able to reproduce the particular error on referenced issue with cleanly trained model.  Will keep it open for now.

### CODE REVIEW

**Comment by hcho3** [comment]
I'm assuming that Dask sklearn doesn't support pred_contribs?

**Comment by trivialfis** [comment]
The skl API doesn't support contrib.  Dask interface is just aligning with it.

**Comment by pseudotensor** [comment]
> The skl API doesn't support contrib. Dask interface is just aligning with it.

Ya, but it's super trivial to add support, it's a bug in my view that it's not supported.  It's literally just an option added to predict or predict_proba and passing that along with other options.

**Comment by trivialfis** [comment]
> Ya, but it's super trivial to add support, it's a bug in my view that it's not supported. It's literally just about adding arguments to predict and predict_proba and just passing that along in the existing lean wrapper.

We are making good progress I think.

**Review by RAMitchell — APPROVED** [review]

**Review by hcho3 — APPROVED** [review]

**Pull request merged**
