### PR TITLE
xgb.cv improvements

### PR DESCRIPTION
**Pull request by khotilov**
Implemented an option for the creation of CV folds in xgb.cv to be stratified by the outcome label. Caret's createFolds was used as a prototype. The option is turned on by default since it is rather important for imbalanced datasets.

Added a possibility to directly pass a pre-made list of CV folds' indices to xgb.cv. That makes it more flexible and facilitates its use within workflows. 

Changed xgb.cv to return its performance statistics in numerical format.

### CODE REVIEW

**Comment by tqchen** [comment]
@hetong007  can you review this PR when you have time?

**Comment by hetong007** [comment]
@khotilov Thanks for this commit. It is good.

Regarding the decision of when to do stratification, @tqchen Is `rank:pairwise` taking numerical labels or not?

**Comment by tqchen** [comment]
rand:pairwise takes numerical labels. However, we should deal with rank type task with care, i.e. trying to split the data by groups instead by instance, and have each group of data get into a complete group.

I do not think current cv in python or R implement this case correctly

**Comment by khotilov** [comment]
My understanding was that the existing CV methods implementation was not
designed for use with ranking, so I didn't consider it.
It should be fairly straightforward to add this functionality for the
non-stratified case though. But I don't really see at the moment how to
do generic stratified CV for ranking.

**Comment by tqchen** [comment]
Yes, I am just mentioning that the rank case was not yet supported, and it was not in the history version. I am opening a new issue on this at #270 

So I think current version is totally fine not to considering ranking

**Comment by tqchen** [comment]
@hetong007  Do you have any future comments? I think we can merge it in if it is good before 0.4

**Pull request merged**
