### PR TITLE
ENH: Pickle xgbooster enhancments.

### PR DESCRIPTION
**Pull request by jseabold**
I added an example of the pickling and some notes about using OpenMP after fork. I also refactored your bytearray changes to avoid the copy in memmove. The example will only run on Python 3.4 now. Can you try it out on python 2.x? I don't have a 2.x dev environment handy on this machine. I think you may just need to do a 

```python
try:
    select_start_method("forkserver")
except:
    select_start_method("spawn")
```

Forkserver is only available on 3.4 and spawn has a lot more overhead.

### CODE REVIEW

**Comment by tqchen** [comment]
Let us keep the memmove. The reason was the pointer returned by save_raw is only valid before next call of save_raw. So it is safer to copy the data out

**Comment by tqchen** [comment]
Several comments:
* It seems to be it is better to create an independent guide script sklearn_fork_server.py
    - The fork server seems to be related to use multiple process for parameter tunning? I think we want to be more clear on that(so that user will not be confused with the omp in xgboost)
* What was the exact problem of openmp? Was it because of the threading or because xgb will each up all resources? Would setting nthread=1 help?
* Put the deepcopy back due to the reason mentioned above

Thanks!

**Comment by jseabold** [comment]
Ok, I'll put back the copy. I guess I don't understand this well enough. Incidentally, how did you debug that segfault? I'd like to get better at that.

For the fork + threading bug (maybe not really a bug), see this issue https://github.com/xianyi/OpenBLAS/issues/294. There are a few related discussions I can link later, if you want. I think it's mentioned in Julia issue tracker too, but the openblas thread should get you up to speed.

Setting `OMP_NUM_THREADS=1` does not help. Only using forkserver and compiling without openmp support will work.

I'll fix the example too.

**Comment by tqchen** [comment]
OK, I get your point. I will merge the things in when the PR is updated.

For debug, I traced into the functions where the segfault happens (I used very primal ways by printing the information i need, but I assume gdb will also do the job). Normally segfault is easy to debug, because you normally can trace to the location where it happens, and reason about what happened

**Comment by jseabold** [comment]
Removed the memmove change. Separated off the fork + threading issue to a separate example. Just important to note. I imagine you'll get issues filed about this at some point...

**Pull request merged**
