### PR TITLE
Try avoiding test fixtures.

### PR DESCRIPTION
**Pull request by trivialfis**
Testing for Travis.  Please ignore until WIP label is removed.

### CODE REVIEW

**Comment by trivialfis** [comment]
@hcho3 The error on travis seems gone.

**Comment by hcho3** [comment]
@trivialfis Nice! Should this be also included in 1.0.0 release?

**Comment by trivialfis** [comment]
Not needed.  Just the fixture used in test.

**Comment by trivialfis** [comment]
@hcho3 Actually please cherry pick it, as it helps having successful tests on that branch.

**Pull request merged**
