### PR TITLE
Group cli demo into subdirectory.

### PR DESCRIPTION
**Pull request by trivialfis**
CLI is not most developed interface.  Putting them into correct directory can help new users to avoid it as most of the use cases are from a language binding.

* Add tests
* Some minor fixes.

Fix: https://github.com/dmlc/xgboost/issues/5790

### CODE REVIEW

**Review by hcho3 — APPROVED** [review]

**Comment by hcho3** [comment]
https://xgboost-ci.net/blue/organizations/jenkins/xgboost-win64/detail/PR-6258/4/pipeline/
The pytest appears to hang at the end.

**Comment by hcho3** [comment]
And now two Linux tests are hanging...

**Comment by trivialfis** [comment]
Before you kill the command, is it possible to gdb into the process?

**Comment by hcho3** [comment]
I was not able to gain access to the machine, so I shut down the workers manually.

**Comment by hcho3** [comment]
@trivialfis Did the tests run successfully on your local machine?

**Comment by trivialfis** [comment]
Just finished running all GPU tests and demo tests.  It works fine on my machine.

**Comment by hcho3** [comment]
@trivialfis Thanks. Let me try to reproduce the hanging tests. For now, please refrain from pushing to this pull request.

**Comment by trivialfis** [comment]
> For now, please refrain from pushing to this pull request.

Sure.

**Comment by trivialfis** [comment]
@hcho3 Should I kill the long running workers?

**Comment by hcho3** [comment]
I already killed them. For some reason Jenkins still shows the jobs as running

**Comment by hcho3** [comment]
The tests did not hang this time. It appears that the specific EC2 workers were unhealthy.

**Pull request merged**
