### PR TITLE
[jvm-packages] Disable fast histo for spark

### PR DESCRIPTION
**Pull request by CodingCat**
being confirmed by @tqchen , we need to disable fast histogram for spark before we add allreduce in histogram builder

### CODE REVIEW

**Comment by tqchen** [comment]
actually @CodingCat do you mind try add the allreduce call that that point and see how it goes, it is likely going to be just one line

**Comment by CodingCat** [comment]
sure, let me try that

**Comment by CodingCat** [comment]
before I get a chance to add that let's merge this....

**Comment by CodingCat** [comment]
it looks like we need to sync on this structure https://github.com/dmlc/xgboost/blob/14fba01b5ac42506741e702d3fde68344a82f9f0/src/common/hist_util.h#L134 

Need to prepare Spark Summit talks this week, will work on it after I submit the slides

**Comment by ebernhardson** [comment]
fast histogram was disabled temporarily, 7 months ago, any plans to bring it back? I tested this with a recent master branch and the results are a bit mysterious. I trained 35M observations across 3 executors for 100 rounds with rank:ndcg. Whereas with tree_method -> approx every node reports the same per-round stats (nodes added, pruned, etc), each node reports something different with tree_method -> hist. The final model from hist had 16k nodes, the final model from approx had 20k nodes. ndcg@10 eval metric though was very similar, within .0005.

So there is still something to be done before bringing this back, but i'm not 100% sure what that is.

**Comment by CodingCat** [comment]
Fasthisto does not support distributed training yet...so, it is what was left

**Comment by troszok** [comment]
@CodingCat I assume distributed refers to multiserver training but does it support training on single multicore machine?

**Pull request merged**
