### PR TITLE
Implement parallel logical algorithms.

### PR DESCRIPTION
**Pull request by trivialfis**
Extracted from https://github.com/dmlc/xgboost/pull/8822 .

### CODE REVIEW

**Review by RAMitchell — COMMENTED** [review]
Is this faster at all?

**Comment by trivialfis** [comment]
@RAMitchell Good point.

For simple conditions like `v > 0.0f`, the difference is negligible. For more complicated checks like whether the input is an integer and larger than 0 (NDCG label), the difference is somewhat visible but still not an issue.

```
std::vector<float> data(100000000);

parallel none_of:      0.059212s
std::none_of:  0.140824s
```

I simply implemented it as these two functions when used for data validation, it has to walk through the entire dataset. Seems not necessary.

**Comment by RAMitchell** [comment]
Feel free to merge if you want. My experience in the past is that simple operations on data don't benefit much. Multithreading then adds a bit of complexity and makes debugging harder.

**Comment by trivialfis** [comment]
Make sense, thank you for the review. Will remove the code from the LTR branch.

**Pull request closed without merging**
