### PR TITLE
[python package] include dmlc-tracker into xgb python pkg

### PR DESCRIPTION
**Pull request by sperlingxx**
This PR is a response to issue #4653 .

I made a specialized copy of `dmlc_tracker/tracker.py` in xgboost, because:
1.  symbolic link doesn't work well under  _Windows_
2.  original version of `dmlc_tracker/tracker.py` has a lot of linter problem
3.  Future modifications can be applied on this copy without considering compatibility.

### CODE REVIEW

**Comment by sperlingxx** [comment]
It seems that something irrelevant with this PR make tests failed, how can I rerun it?

**Comment by trivialfis** [comment]
Restarted, seems to be a network issue?

**Comment by trivialfis** [comment]
@sperlingxx The socket seems pointing only to local host port?

**Comment by sperlingxx** [comment]
@trivialfis I made some silly mistakes while fixing linter problem of RabitTracker.

**Pull request merged**
