### PR TITLE
Add Random Forest parameter (num_parallel_tree) in function doc + exampl...

### PR DESCRIPTION
**Pull request by pommedeterresautee**
...e in Vignette.

I have read that the num par tree parameter may be unstable. I don t know if it s still the case.
Feel free to cancel the pull request.

If it can be used, it is interesting for people to be able to compare both algorithms from the same package with one API.

Discovered the parameter from here https://www.kaggle.com/c/otto-group-product-classification-challenge/forums/t/12947/achieve-0-50776-on-the-leaderboard-in-a-minute-with-xgboost?page=4

### CODE REVIEW

**Comment by pommedeterresautee** [comment]
It seems that some users have some interest in this parameter (https://groups.google.com/forum/#!topic/xgboost-user/7aHJn9JapY0).

@tqchen do you want me to add to the description of the parameter in the documentation that it is still experimental?

Kind regards,
Michael

**Comment by tqchen** [comment]
Yes, I think we can add it to the doc, by marking it was still experimental

**Comment by pommedeterresautee** [comment]
@tqchen updated with experimental information.

**Comment by tqchen** [comment]
it seems that there are some divergence from the master branch. @pommedeterresautee can you try to add those changes from a new fork? I will close this one for now

**Comment by pommedeterresautee** [comment]
You mean I need to sync my fork with this deposit then do a new pull request, right?

**Comment by tqchen** [comment]
Yes

**Pull request closed without merging**
