### PR TITLE
[py] fix label encoding of eval sets in sklearn API

### PR DESCRIPTION
**Pull request by tlorieul**
Label encoding in `XGBClassifier` is done after putting the eval sets into DMatrix format, thus the labels of these sets aren't encoded which can trigger an error (most of the cases, it happens not to be useful to encode the labels).

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@tlorieul Thanks! Could you rebase with master? The lint errors can be reproduced by `make pylint`. It would also be good to add a test to cover that particular case.

**Comment by tlorieul** [comment]
Sorry for the delay, I didn't have time to deal with it before. I'm not used to GitHub so I've been struggling a bit to do a clean rebase but it seems to be all in order now, no? :)
I didn't make a test because I'm not sure how to reproduce that bug, I found it while playing around with a dataset from kaggle.

**Comment by terrytangyuan** [comment]
@tlorieul Sorry for late reply. It looks like the conflicts are still out there. Could you try rebase again?

**Comment by tlorieul** [comment]
@terrytangyuan No worries. I rebased it and everything seems ok now.

**Pull request merged**
