### PR TITLE
[airlearner] first commit for airlearner

### PR DESCRIPTION
**Pull request by jq**
@jieyingc
once this merge, we will add more docs for how to use it

### CODE REVIEW

**Comment by CodingCat** [comment]
would you please add docs in this PR?

**Comment by tqchen** [comment]
i would recommend namespace contrib instead of contribution, which is more common

**Comment by jq** [comment]
@CodingCat @tqchen thanks for review, adding docs and renaming, will resubmit it soon

**Comment by CodingCat** [comment]
you do not need to close....the new commits would be reflected here

**Comment by CodingCat** [comment]
is it ready to review?

**Comment by CodingCat** [comment]
is it ready?

**Comment by terrytangyuan** [comment]
@jq Could you add some short description in README? This will be helpful to other people who want to chime in and participate the review.

**Comment by CodingCat** [comment]
@jq are you still working on this?

**Comment by CodingCat** [comment]
discussed with @jq offline, close this one and will make it as a production case linking to airbnb's repo

**Pull request closed without merging**
