### PR TITLE
[R] Fix warning about mismatched names when joining

### PR DESCRIPTION
**Pull request by david-cortes**
fixes https://github.com/dmlc/xgboost/issues/10742
ref https://github.com/dmlc/xgboost/issues/9810

This PR fixes a warning (which actually turn out to come from data.table, not from DiagrammeR) about mismatched column names when concatenating inputs.

I'm not 100% if this is doing what the function is meant to do though, so would be ideal if someone could take a deeper look.

### CODE REVIEW

**Comment by trivialfis** [comment]
@mayer79 Could you please help review this PR when you are available? I'm not familiar with the DiagrammeR package.

**Review by mayer79 — APPROVED** [review]
The original code tried to rbind two data.frames with different column names. This is fixed.

**Comment by david-cortes** [comment]
> The original code tried to rbind two data.frames with different column names. This is fixed.

But is that what it was supposed to be doing?

**Comment by mayer79** [comment]
> > The original code tried to rbind two data.frames with different column names. This is fixed.
> 
> But is that what it was supposed to be doing?

I think yes, but I have never actively used this function.

**Pull request merged**
