### PR TITLE
[py] split value histograms

### PR DESCRIPTION
**Pull request by Far0n**
get split value histogram of a feature:

`gbdt.get_split_value_histogram('f29', bins=5)`

```
f29  SplitValue  Count
0           7.2     39
1          13.9      9
2          20.6      3
3          27.3      1
4          34.0      2
```

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Sorry I've been quite busy and didn't get a chance to review. Could you utilize compat.py and make sure xgboost doesn't rely on pandas. Also consider adding a test. Thanks.

**Comment by Far0n** [comment]
Is it fine to use the same as for "cv" with "as_pandas" for optional pandas usage?

**Comment by terrytangyuan** [comment]
Yeah

**Comment by terrytangyuan** [comment]
Any update on this?

**Comment by Far0n** [comment]
+ unitest
+ using combat
+ does not rely on pands any longer

ok this way?

**Comment by terrytangyuan** [comment]
Thanks. Maybe a short docstring on what's being returned and move unit test to test_with_sklearn.py if you need sklearn to test it.

**Comment by Far0n** [comment]
ok, sec :)

**Comment by Far0n** [comment]
anything else?

**Comment by terrytangyuan** [comment]
Looks good. Missing a docstring for `as_pandas` and probably should give a warning if it's not installed. Will merge after the changes and when travis is happy.  :-)

**Comment by Far0n** [comment]
is it fine to use "sys.stderr.write" for the warning here?

**Comment by terrytangyuan** [comment]
Yeah it's fine for now.

**Pull request merged**
