### PR TITLE
[R] Fix number of threads used in examples.

### PR DESCRIPTION
**Pull request by trivialfis**
- Set threads for data.table
- Disable parallel model IO in XGBoost for R.
- Some helper scripts.

### CODE REVIEW

**Comment by trivialfis** [comment]
tests also have a limit for 2 threads.

**Comment by trivialfis** [comment]
```
Running R code in ‘testthat.R’ had CPU time 3.6 times elapsed time
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking re-building of vignette outputs ... [32s/11s] NOTE
Re-building vignettes had CPU time 3 times elapsed time
```

**Comment by trivialfis** [comment]
@jameslamb @hcho3 Would be great if you could help review the PR when you are available, I think we are close to passing the pre-test now.

**Review by jameslamb — APPROVED** [review]
Changes look good to me!

I agree that the benefit of getting `{xgboost}` v2.0.0 onto CRAN are large enough that it's worth hard-coding in this 2-thread limit for model I/O.

**Comment by trivialfis** [comment]
We still need to go through the reverse dependency check and talk to downstream projects. So, it might take a long time.

**Comment by trivialfis** [comment]
Thank you for all the helpful information! @jameslamb .

**Comment by trivialfis** [comment]
Changed base to master from 2.0.

**Pull request merged**
