### PR TITLE
[jvm-packages] update version number for 1.2 branch

### PR DESCRIPTION
**Pull request by CodingCat**

### CODE REVIEW

**Comment by CodingCat** [comment]
made a staging jar at https://oss.sonatype.org/service/local/repositories/mldmlc-1068/content/ml/dmlc/xgboost4j_2.12/1.2.1/xgboost4j_2.12-1.2.1.jar

checked version
image

**Comment by hcho3** [comment]
@CodingCat Thanks! Where did you obtain libxgboost4j.so this time?

**Review by hcho3 — APPROVED** [review]

**Comment by CodingCat** [comment]
> @CodingCat Thanks! Where did you obtain libxgboost4j.so this time?

I downloaded from s3 for linux and compiled by myself in mac

**Comment by trivialfis** [comment]
Can we close the related issues?

**Pull request merged**
