### PR TITLE
[breaking][CI] Use CTK 12.4

### LINKED ISSUE #10370: Update the default CTK to 12.4.
It should be able to work on all CTK 12.x versions. However, do know that once the default CTK is upgraded to 12, xgboost won't work on CTK 11.x.

### PR DESCRIPTION
**Pull request by hcho3**
Closes #10696
Closes #10370

Marking as breaking, as we are dropping support for CUDA 11.8.

* Apply https://github.com/abseil/abseil-cpp/commit/cfde5f74e276049727f9556f13473a59fe77d9eb to patch Abseil C++ to be compatible with latest CUDA compiler.
* Work around false positive `unix.BlockInCriticalSection` from clang-tidy. See https://github.com/llvm/llvm-project/issues/104241

### CODE REVIEW

**Comment by trivialfis** [comment]
Thank you for working on this! Using 12.4 is going to help with the external memory work significantly. Out of curiosity, what's the kernel driver version of the AMI? Is it using kernel-open? Ubuntu package:
```
$ apt search nvidia-driver
...
nvidia-headless-555-open/jammy 555.58.02-0ubuntu0~gpu22.04.1 amd64
  NVIDIA headless metapackage (open kernel module)
...
```

As for the GRPC, I use:
``` python
>>> import grpc
>>> grpc.__version__
'1.62.2'
```
from conda-forge, seems to work well with CUDA 12.4/5, if it helps.

**Comment by hcho3** [comment]
@trivialfis Here is the kernel driver version:

```
$ nvidia-smi
Tue Aug 13 19:57:56 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       On  |   00000000:00:1E.0 Off |                    0 |
| N/A   32C    P8             14W /   70W |       1MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

The AMI is based on Amazon Linux 2, so it probably doesn't use kernel-open.

**Review by terrytangyuan — COMMENTED** [review]
What release is this targeting?

**Comment by hcho3** [comment]
The next release, which is going to be 3.0.0 (due to the rewrite for the JVM packages).

**Comment by hcho3** [comment]
@terrytangyuan BTW, we would love to get your input on https://github.com/dmlc/xgboost/pull/10639

**Comment by terrytangyuan** [comment]
Sounds great!

**Comment by trivialfis** [comment]
Hmm, RMM is bringing in a different CCCL. Might have to patch it by back porting the one liner fix.

**Review by trivialfis — APPROVED** [review]

**Pull request merged**
