### PR TITLE
[jvm-packages] Move to SBT

### PR DESCRIPTION
**Pull request by trams**
I took an abandoned pull request https://github.com/dmlc/xgboost/pull/2767 and adapted to current master (cc @superbobry)

Checklist:
1. JNI compilation
2. Tests
3. Scalastyle and Checkstyle
4. Cross-compilation wrt Scala version
5. Uber JAR

I welcome your suggestions.

One side effect of this pull request I am very interested in is an ability to build against Scala 2.11
I think it would be nice to support Scala 2.11 as long as our dependencies support it

What do you think?

### CODE REVIEW

**Comment by trams** [comment]
@CodingCat , I just noticed your comment https://github.com/dmlc/xgboost/pull/2767#issuecomment-363299788 on the previous attempt to move to SBT

I will address it

**Comment by CodingCat** [comment]
if the major benefit is to enable building with 2.11, I am not sure if I am a fan of this

1. one of the major future updates for xgboost is to coordinate with spark 3.0.0 release to enable significant features like "GPU-aware scheduler". Furthermore, Spark 3.0.0 has removed the support of scala 2.11 (https://issues.apache.org/jira/browse/SPARK-26132)...

2. at this moment, XGBoost community is to reduce the maintaining overhead and focus more on development and stablize stuffs like APIs, etc., sticking with 2.11 is not along with direction (cc: @hcho3 @RAMitchell @trivialfis for further comments)

**Comment by trams** [comment]
I understand the desire to decrease maintenance burden

I see that Spark 3.0 does not support 2.11 but I think it would be nice for us to support 2.11 until xgboost moves to Spark 3.0. (Is it planned to drop Spark 2.4 support after 1.0 release?)

But regardless of scala 2.11 it would be nice to build xgboost for scala version X and X+1 so everybody could have some time to migrate.I see that Spark mostly build two version of artifacts (https://mvnrepository.com/artifact/org.apache.spark/spark-core) and  I see that Spark 3.0 will likely be build for 2.12 and 2.13 (https://jira.apache.org/jira/browse/SPARK-25075)

SBT would enable this feature easily.
SBT is not the only way to archive this feature so let me know whether the 2.11 is a problem or SBT itself (which I am sure has its drawbacks)

We (me and my colleagues) are interested in supporting ability to build xgboost for 2.11 for at least a little while (I think till the end of the year) so we would provide all the help needed

**Comment by trams** [comment]
Regardless of move to SBT this pull request also contains:
1. fix of DTD headers https://github.com/dmlc/xgboost/pull/4687/commits/6b505541e07c93cdfbf5c57905d1df7da575ebda
2. Remove of hardcoded paths in tests https://github.com/dmlc/xgboost/pull/4687/commits/3a90de0a59eb5610400ce4d93693dc13b56e7d91

I can extract them in a separate commit. Would you be potentially interested in merging them separately?

**Comment by trivialfis** [comment]
@trams 

> I can extract them in a separate commit. Would you be potentially interested in merging them separately?

Yes, please.

**Comment by trams** [comment]
I'll close this pull request for now. Further actions:
1. Reassess SBT and cross compilation issue once Spark will be cross compiled with scala 2.12 and 2.13
2. Extract test fixes as a separate pull request

**Pull request closed without merging**
