### PR TITLE
Enable running objectives with 0 GPU.

### PR DESCRIPTION
**Pull request by trivialfis**
* Enable 0 GPU for objectives.
* Add doc for GPU objectives.
* Fix some objectives defaulted to running on all GPUs.

Brought up by #3874 .

### CODE REVIEW

**Comment by trivialfis** [comment]
@hcho3  I have some difficulties dealing with the parameters.  I want to organize the parameters a little bit so that I can gain more confidence I'm not breaking anything,  but the first thing I encountered is how to save and load these parameters.  So I spent some time on learning how XGBoost saves its model in C++ level and found out that current binary dumping is not exactly formatted. In #3886, you talked about:

> We may want to consider a next generation model format

 Combined with `dump_model` in Python, I want to know what's your idea about next generation model format.  Thanks. :)

**Comment by hcho3** [comment]
@trivialfis The current binary format saves LearnerModelParam, Objective, Metrics, and the decision trees (RegTrees). Extra attributes (string key-value pairs) are also saved. Other parameters are not saved, with the exception of predictor parameters I added in #3856. In general, parameters that are specific to training, such as LearnerTrainParam and TrainParam, are not saved.
The issue is backward compatibility. We are free to change any unsaved parameters but we are not free to change any saved parameters (exception: you can add extra Booster attributes). This is why we cannot change type of num_feature nor add instance count to tree nodes (#3452)

I'd love to adopt a new model format where we can add new fields easily without breaking backward compatibility. Protobuf, XML, JSON would qualify. But the transition is not going to be easy. We'll need to release 1.0 and provide converters for old model files.

**Comment by hcho3** [comment]
A hacky way is to simply append all extra new fields to the end of the legacy format, but it doesn't handle per-tree or per-node information well. But for parameters, this hack may work.

**Comment by trivialfis** [comment]
@hcho3 Thanks for the explanation.  Since we just released the 0.81,  we can consider organizing things a little bit before the next release hit.  I will try to learn more and think about it.  If you have some interesting ideas, feel free to open an issue so more voice can join. :)

**Pull request merged**
