### PR TITLE
use submodule instead of repo copy

### PR DESCRIPTION
**Pull request by xunzhang**
use git submodule to catch upstream bugfix and update

### CODE REVIEW

**Comment by xunzhang** [comment]
You use relative include in xgboost, so the project can not be built successfully rght now. I will fix the relative include with dcml/rabit project soon.

**Comment by tqchen** [comment]
dmlc/rabit was included in the project via git subtree, which is an alternative to git submodule and is able to catch upstream changes. To the user, this appears to be like a copy

**Comment by tqchen** [comment]
I choose to use git subtree instead of git submodule mainly because git sub module requires user to have additional command to clone the repo, and some of non-expert users like R users may not be able to do that. So git subtree allows the repo to be cloned in normal way.

Thanks for doing this @xunzhang :)

**Comment by xunzhang** [comment]
@tqchen 这个pr的submodule路径没写对就close了。本来想改下submodule路径和`build.sh`一起提到next pr，不过git subtree也work就ok了。subtree folder里的code和upstream看起来不一致，所以会有些tricky。

**Comment by tqchen** [comment]
subtree is update based on user command, so it is not auto synced to head, but need to be synced periodically.

**Pull request closed without merging**
