### PR TITLE
Muting the remaining messages when show_progress=False

### PR DESCRIPTION
**Pull request by ivallesp**
I was using the library and I found that when doing a cross validation, even when I chose the parameter show_progress to False, it showed some messages:

"Will train until cv error hasn't decreased in X rounds", in case of having early_stopping

"Stopping. Best iteration:\n[X] cv-mean:[...]\n"

I wrote some conditions for muting it when show_progress=Fase because if you run a bunch of models with a grid of parameters, the high number of messages can bother :D.

### CODE REVIEW

**Comment by ivallesp** [comment]
is everything ok?

**Comment by tqchen** [comment]
Sorry for the delayed reply. Let us reuse the verbose_eval parameter

**Comment by ivallesp** [comment]
Ok I see,  I changed it! is it ok now?

**Comment by ivallesp** [comment]
can we merge it? what are the next steps? the tests are failing because it is a refactoring

**Comment by tqchen** [comment]
please do a rebase to merge your commits, and it will be merged.http://xgboost.readthedocs.org/en/latest/dev-guide/contribute.html#how-to-combine-multiple-commits-into-one

**Comment by ivallesp** [comment]
done :D!

**Comment by tqchen** [comment]
@ivallesp It seems that I merged the change too hastely and now the travis test break due to the change introduced by this PR, https://travis-ci.org/dmlc/xgboost/builds/110415766

Please make a PR to fix this issue, so the other changes can be savely merged in.

**Comment by tqchen** [comment]
https://travis-ci.org/dmlc/xgboost/jobs/110415768#L974

**Comment by ivallesp** [comment]
@tqchen I just did it! Sorry but I made something wrong during the squash and the changes in the training file were not applied. I think it is solved now. Let's wait until tests done. Thank you for reporting it.

**Comment by ivallesp** [comment]
@tqchen yep! Now the tests passed and it is working correctly. Sorry for the inconvenience.

**Pull request merged**
