### PR TITLE
[R-package] xgb.model.dt.tree up to x100 faster

### PR DESCRIPTION
**Pull request by khotilov**
All these:
* unrolling the tree-by-tree loop
* more efficient regexp parsing
* removing unused "Yes.\*" and "No.\*" columns (I can add a simple example for how to get those later if some users would want those)

result in speeding up the xgb.model.dt.tree function (and those that depend on it) by from a few dozen to 100 times. The largest gain is for multi-K decision stumps, which were previously often taking more time in feature importance calculations than in training.

I've also brushed up the docs and wrapped the long lines to make them more GitHub-friendly.

### CODE REVIEW

**Comment by tqchen** [comment]
@pommedeterresautee can you review this?

**Comment by khotilov** [comment]
Some more regex streamlining in the recent commit saves extra 10-20% in time on the top of previous savings. And I've added a simple example for how to following branch pointers.

**Comment by pommedeterresautee** [comment]
This is an awesome work. 
Will check quality code this week (sorry very busy at work right now).
Tks a lot @khotilov !

**Comment by tqchen** [comment]
@pommedeterresautee do you have any updates on this?

**Comment by pommedeterresautee** [comment]
Sorry i have been super busy at work. If everything is ok I should be able
to test on Wednesday.

Kind regards,
Michael

Le vendredi 6 mai 2016, Tianqi Chen <notifications@github.com> a écrit :

> @pommedeterresautee <https://github.com/pommedeterresautee> do you have
> any updates on this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/xgboost/pull/1118#issuecomment-217489072>
>


-- 
________________
Michaël BENESTY
michael@benesty.fr
Please do not print this e-mail unless you really need to.

**Comment by khotilov** [comment]
@pommedeterresautee : what can I do to make it easier for you?

**Comment by terrytangyuan** [comment]
@khotilov Perhaps could you share reproducible benchmark comparisons? Look forward to it.

**Comment by khotilov** [comment]
I can surely do that.

Train a decision stubs model and a deeper tree model:
```R
library(xgboost)
set.seed(123)
n <- 20000
p <- 100
x <- matrix(runif(n*p), n)
f <- sample(p, 10)
b <- rnorm(10, 0, 1)
y <- x[, f] %*% b
y <- y - mean(y)
y = rbinom(n, 1, plogis(y))

itr <- sample(n, floor(0.7*n))
dtr <- xgb.DMatrix(x[itr,], label=y[itr])
dts <- xgb.DMatrix(x[-itr,], label=y[-itr])
watch <- list(train=dtr, test=dts)

x.stubs <- xgb.train(data=dtr, nrounds=5000, watchlist=watch, objective = "binary:logistic", eval_metric="auc", eta=0.01, nthread = 4, max_depth=1, verbose=0)
x.depth6 <- xgb.train(data=dtr, nrounds=1000, watchlist=watch, objective = "binary:logistic", eval_metric="auc", eta=0.01, gamma=1, lambda=0.1, nthread = 4, max_depth=6, verbose=0)

xgb.save(x.stubs, "x.stubs.model")
xgb.save(x.depth6, "x.depth6.model")
```
Benchmark the new code:
```R
library(xgboost)
library(microbenchmark)
x.stubs <- xgb.load("x.stubs.model")
x.depth6 <- xgb.load("x.depth6.model")
microbenchmark( xgb.model.dt.tree(model=x.stubs), xgb.model.dt.tree(model=x.depth6), times=10)
saveRDS(xgb.model.dt.tree(model=x.stubs), "x.stubs.new.tree")
saveRDS(xgb.model.dt.tree(model=x.depth6), "x.depth6.new.tree")

# results:
#Unit: milliseconds
#                                expr      min        lq      mean   median        uq       max neval cld
#  xgb.model.dt.tree(model = x.stubs)  391.682  396.0725  431.9707  403.881  449.2225  554.3204    10  a 
# xgb.model.dt.tree(model = x.depth6) 2152.903 2192.0366 2260.8268 2246.517 2359.4016 2383.2210    10   b
```
Benchmark the old code (current master):
```R
library(xgboost)
library(microbenchmark)
x.stubs <- xgb.load("x.stubs.model")
x.depth6 <- xgb.load("x.depth6.model")
microbenchmark( xgb.model.dt.tree(model=x.stubs), xgb.model.dt.tree(model=x.depth6), times=10)
saveRDS(xgb.model.dt.tree(model=x.stubs), "x.stubs.old.tree")
saveRDS(xgb.model.dt.tree(model=x.depth6), "x.depth6.old.tree")

# results:
#Unit: seconds
#                                expr      min       lq     mean   median       uq      max neval cld
#  xgb.model.dt.tree(model = x.stubs) 42.97661 43.19116 43.52272 43.54251 43.82654 44.05092    10  a 
# xgb.model.dt.tree(model = x.depth6) 45.30768 45.45221 45.62824 45.54923 45.87543 46.17453    10   b
```
Compare the output:
```R
library(data.table)
x.stubs.new <- readRDS("x.stubs.new.tree")
x.depth6.new <- readRDS("x.depth6.new.tree")
x.stubs.old <- readRDS("x.stubs.old.tree")
x.depth6.old <- readRDS("x.depth6.old.tree")

str(x.stubs.new)
str(x.stubs.old)

# to make the "old" compatible:
#   add the Node column
#   order by Tree, Node
#   exclude the Yes.* and No.* columns 
x.stubs.old[, Node := as.numeric(str_match(ID, "-(\\d+)$")[,2])]
x.depth6.old[, Node := as.numeric(str_match(ID, "-(\\d+)$")[,2])]
x.stubs.old <- x.stubs.old[order(Tree, Node), colnames(x.stubs.new), with=F]
x.depth6.old <- x.depth6.old[order(Tree, Node), colnames(x.stubs.new), with=F]

# all are the same now
all.equal( x.stubs.new, x.stubs.old)
all.equal( x.depth6.new, x.depth6.old)
```

**Comment by tqchen** [comment]
I propose to merge as @khotilov indicates that the results are compatible, will merge in 24 hours if  there is no objection

**Comment by terrytangyuan** [comment]
Yeah seems reasonable to merge. @khotilov Could you rebase to resolve any conflicts and then we'll merge?

**Comment by khotilov** [comment]
FYI: commits' dates were reset by the rebase. I guess that shouldn't really matter here.

**Comment by pommedeterresautee** [comment]
No I don t think so. I am compiling right now. Will let you know if I find an issue.

**Comment by pommedeterresautee** [comment]
Seems everything is working and replacing for loop by data.table operation is obviously a good idea. Thanks for the good work @khotilov

**Pull request merged**
