### PR TITLE
Support unity build.

### PR DESCRIPTION
**Pull request by trivialfis**
See https://github.com/dmlc/xgboost/issues/6293 for details.  The speedup may help some build machines for distribution, but I don't think it's useful for daily development.  XGBoost's CPU compilation time on my machine is usually within a minute so not much room for improvement.

Update: Will be enabled on Windows CI.

Close https://github.com/dmlc/xgboost/issues/6293 .

### CODE REVIEW

**Comment by trivialfis** [comment]
@hcho3 I tried enabling it on Windows, see if it helps.  ;-)

**Comment by hcho3** [comment]
@trivialfis Thanks. We should also try to get Ninja build working (#5832) to bring the build time under 10 min.

**Comment by trivialfis** [comment]
@hcho3 It's under 10 minutes now.

**Comment by hcho3** [comment]
Interesting. So unity build does help quite a bit on the Windows platform. Let me approve this PR.

**Review by hcho3 — APPROVED** [review]

**Comment by trivialfis** [comment]
Close https://github.com/dmlc/xgboost/issues/6293 .

**Comment by trivialfis** [comment]
Em, it breaks external memory on Windows somehow.

**Comment by hcho3** [comment]
@trivialfis Another reason to extinguish race condition and other undefined behaviors from the external memory. This is the same issue as the Ninja PR (#5832)

**Comment by hcho3** [comment]
Or can we drop support for external memory on the Windows platform?

**Comment by trivialfis** [comment]
It's not that easy with external memory.  On the on hand I want to remove all use of threads for loading data, on the other hand the performance will be miserable without pre-fetching.

> drop support for external memory on the Windows platform

Dropping it won't solve the root cause, just hiding the issue.

**Comment by hcho3** [comment]
> Dropping it won't solve the root cause, just hiding the issue.

I agree. I just wanted to unblock this PR and #5832 so that we can start enjoying faster turn-around time.

**Comment by trivialfis** [comment]
@hcho3 Can I merge it by reverting the CI change?

**Comment by hcho3** [comment]
Sure

**Comment by trivialfis** [comment]
@hcho3 Do you think it's suitable to merge without passing power test?  It seems travis is having difficulty on allocating power node. https://travis-ci.org/github/dmlc/xgboost/pull_requests

**Pull request merged**
