### PR TITLE
Improve warning when using np.ndarray subsets

### PR DESCRIPTION
**Pull request by JoseLlorensRipolles**
The UserWarning prompted when using numpy subsets was a bit difficult to understand. I also added a suggestion on how to fix the warning.

### CODE REVIEW

**Review by trivialfis — APPROVED** [review]
Thanks for the PR!

**Comment by JoseLlorensRipolles** [comment]
Thank **you** for your awesome work at XGBoost 😄!

**Comment by rteuwens** [comment]
Context: https://github.com/dmlc/xgboost/issues/6908#issuecomment-834658652

Given your suggestion, would this break xgboost?

```py
        if not data.flags.c_contiguous:
            data = np.ascontiguousarray(data)
        data = np.array(data, copy=False, dtype=dtype)
```

Currently, any interaction with sklearn CV split objects results in terminal UserWarning spam.

**Comment by JoseLlorensRipolles** [comment]
> Context: [#6908 (comment)](https://github.com/dmlc/xgboost/issues/6908#issuecomment-834658652)
> 
> Given your suggestion, would this break xgboost?
> 
> ```python
>         if not data.flags.c_contiguous:
>             data = np.ascontiguousarray(data)
>         data = np.array(data, copy=False, dtype=dtype)
> ```
> 
> Currently, any interaction with sklearn CV split objects results in terminal UserWarning spam.

No, it would not break XGBoost, but it would change the structure of the user array without their intent and without giving notice, which could be problematic. In my opinion the copy approach is safer. However, it is true that this warning raises quite a bit when using some sklean methods (Like a gridsearch), so maybe the warning could be dropped altogether.

**Comment by rteuwens** [comment]
> No, it would not break XGBoost, but it would change the structure of the user array without their intent and without giving notice, which could be problematic. In my opinion the copy approach is safer. However, it is true that this warning raises quite a bit when using some sklean methods (Like a gridsearch), so maybe the warning could be dropped altogether.

The error is super annoying and hard to suppress. Limiting the notification to once or dropping it altogether sounds like a welcome change, tbh...

**Comment by hcho3** [comment]
@rteuwens I filed #6997 to remove the warning.

**Comment by rteuwens** [comment]
> @rteuwens I filed #6997 to remove the warning.

Much love! Thank you

**Pull request merged**
