### PR TITLE
Added arm64 job in Travis-CI

### PR DESCRIPTION
**Pull request by odidev**
Added Arm64 job in Travis-CI, modified run_test.sh and setup.sh to add checks for arm64 platform.

### CODE REVIEW

**Comment by RAMitchell** [comment]
Awesome work. @hcho3 should we run any tests? Maybe just `tests/python/test_basic.py`?

**Review by trivialfis — APPROVED** [review]
@odidev  Thanks for the nice work!

> should we run any tests? Maybe just tests/python/test_basic.py?

@RAMitchell We can enable it step by step.  I would start with cpp tests.

**Review by hcho3 — APPROVED** [review]
LGTM. Let me submit a follow-up pull request to enable wheel building with ARM64. We should have Travis CI upload a binary ARM64 wheel to the [S3 bucket](https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/list.html).

**Comment by odidev** [comment]
Thanks for accepting the PR! Could you please let me know when the arm64 wheel will be uploaded on PyPI.

**Comment by trivialfis** [comment]
Tracked in #6243

**Pull request merged**
