### PR TITLE
[FOLLOW-UP] Support for building DMatrix from Apache Arrow data format

### PR DESCRIPTION
**Pull request by xwu99**
Continue work for #7283 #5667

### CODE REVIEW

**Comment by xwu99** [comment]
@trivialfis This is a follow-up work for #7283, Could you help to kick off CI?  It looks it is still using Jenkins there but my fork is using github actions? There is a type check error in github actions but not relavent to this PR. 

image

**Comment by trivialfis** [comment]
Could you rebase to master?

**Comment by xwu99** [comment]
rebased. I didn't change xgboost/dask.py. Could you approve ci again?

**Comment by trivialfis** [comment]
Submitted a fix https://github.com/dmlc/xgboost/pull/7513 .

**Comment by trivialfis** [comment]
I saw some compiler warnings with gcc 9.3 and nvcc 11.4, some of them like `pointless comparison` are quite useful.  Please review and address them.

[log.txt](https://github.com/dmlc/xgboost/files/7732211/log.txt)

**Comment by xwu99** [comment]
@trivialfis I have enabled test_with_arrow for CI.
Github Actions: "macos-10.15" passed. But "windows-2016" just skipped the test.
Jenkins: "Win64 Test" failed. 
It seems they have very different packages installed for different OSes. I need more time to debug this.

**Comment by trivialfis** [comment]
Thanks for the update.  Will review the PR later.   I don't mind disabling Windows support for now.

**Comment by xwu99** [comment]
> Thanks for the update. Will review the PR later. I don't mind disabling Windows support for now.
I have fixed for win64_cpu_test.yml (added cffi) but looks there is some other packages missing in win64_test.yml in order to run with arrow. The test case error silently without useful messages.

**Comment by trivialfis** [comment]
It seems to be hanging on both Linux and Windows.

https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-7512/18/pipeline/180

**Comment by xwu99** [comment]
> It seems to be hanging on both Linux and Windows.
> 
> https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-7512/18/pipeline/180

Thanks, you are right, I will look into details.

**Comment by xwu99** [comment]
> It seems to be hanging on both Linux and Windows.
> 
> https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-7512/18/pipeline/180

@trivialfis Hi, my Jenkinsfile-win64 has changed for debugging, I have added -DUSE_ARROW=ON to cmake and also changed pytest line.

But the change is not effective, Jenkins still execute the old Jenkinsfile-win64 file.  I am not familiar with Jenkins, anything missing?

https://xgboost-ci.net/blue/organizations/jenkins/xgboost-win64/detail/PR-7512/22/pipeline/39

**Comment by trivialfis** [comment]
@hcho3 Could you please help take a look if time allows?

**Comment by hcho3** [comment]
The test server should now use the updated Jenkinsfile.

**Comment by xwu99** [comment]
> The test server should now use the updated Jenkinsfile.

Thanks a lot, I will rebase to master next time. Seems Jenkins only pull in rebased one.

**Comment by trivialfis** [comment]
I have interrupted the win64 CI as it was approaching 3 hours.

**Comment by xwu99** [comment]
> > It seems to be hanging on both Linux and Windows.
> > https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-7512/18/pipeline/180
> 
> Thanks, you are right, I will look into details.

The Linux one is fixed by adding -DUSE_ARROW=ON, for Win64 it passed yesterday by adding -DUSE_ARROW=ON https://xgboost-ci.net/blue/organizations/jenkins/xgboost-win64/detail/PR-7512/24/pipeline. but the same setting hang today.

**Comment by trivialfis** [comment]
> Thanks a lot, I will rebase to master next time. Seems Jenkins only pull in rebased one.

Please let me know when you have rebased the branch.  I will make some more changes based on your current PR.

**Comment by xwu99** [comment]
@trivialfis I have rebased now. When I only test tests\python\test_with_arrow.py, it passed. I am not sure why it doesn't proceed as a whole (tests\python).

**Comment by trivialfis** [comment]
> I am not sure why it doesn't proceed as a whole (tests\python).

I don't know either.  Could you reproduce it locally?

I opened a PR for cmake script: https://github.com/xwu99/xgboost/pull/1 will open some other PRs later.

**Comment by xwu99** [comment]
> > I am not sure why it doesn't proceed as a whole (tests\python).
> 
> I don't know either. Could you reproduce it locally?
> 
> I opened a PR for cmake script: [xwu99#1](https://github.com/xwu99/xgboost/pull/1) will open some other PRs later.

I will check Windows locally.

**Comment by xwu99** [comment]
> > > I am not sure why it doesn't proceed as a whole (tests\python).
> > 
> > 
> > I don't know either. Could you reproduce it locally?
> > I opened a PR for cmake script: [xwu99#1](https://github.com/xwu99/xgboost/pull/1) will open some other PRs later.
> 
> I will check Windows locally. Could you cancel the checks? it seems to hang.

It's a hard to find bug. Digging out code locally finally I found improrting modin.pandas mess up with pyarrow iterator on Windows. Attach the reproducer. Environment: 

OS: Windows 10
modin                     0.11.3          py38haa95532_0
pyarrow                   6.0.1           py38h0b4a547_7_cpu    conda-forge

[test_modin_arrow_hang.zip](https://github.com/dmlc/xgboost/files/7834522/test_modin_arrow_hang.zip)

For XGboost , the previous running of test_dmatrix.py: test_unknown_data (imported modin.pandas) impact the following test_with_arrow. 

I have not found a workaround for modin and pyarrow to co-exist yet.  If user import modin.pandas first, and then load arrow, it will hang.

**Comment by xwu99** [comment]
@trivialfis I have specified arrow to use 4.0 version in the CI instead of latest version due to importing modin resulting in hang for arrow 6.0.  May need to file an issue for modin.

**Comment by trivialfis** [comment]
@xwu99 Thanks for the hard work on this.  Do you know of any plan on supporting latest arrow and modin?

**Comment by xwu99** [comment]
I will contact Modin to see if there is a fix.

**Comment by trivialfis** [comment]
@xwu99 Do you mind if I rebase your commits?

**Comment by xwu99** [comment]
> @xwu99 Do you mind if I rebase your commits?

Pls go ahead to do whatever you need. Btw. Modin team is looking into the hang issue.

**Comment by xwu99** [comment]
@trivialfis I think I have fixed arrow hang issue from workaround https://issues.apache.org/jira/browse/ARROW-15362. the CI error seems irrelavant, you can rebase as you wish.

**Comment by trivialfis** [comment]
Now the arrow is built by default, clang tidy will check the code.

**Comment by xwu99** [comment]
> Now the arrow is built by default, clang tidy will check the code.

ok, I will run clang tidy locally to check.

**Comment by trivialfis** [comment]
I will follow up on this PR.  Apologies for being slow here.

**Comment by xwu99** [comment]
> I will follow up on this PR. Apologies for being slow here.

Thanks. for clang-tidy some renames will do. pls let me know when you need me.

**Comment by trivialfis** [comment]
I made some cleanups to the PR by removing unused code.  From my perspective, it's best to have everything in an adapter instead of DMatrix, but I don't think I will try to implement that in this release.

@hcho3 @RAMitchell Could you please take a look?

**Review by RAMitchell — COMMENTED** [review]
It's a shame we can't use any existing data iterator structure to do this. After all the attempted refactoring of xgboost's data import mechanisms and DMatrix it seems to get more and more confusing and we are just adding API functions for each new format.

**Comment by trivialfis** [comment]
The arrow format can chunk the data arbitrarily for both rows and columns, which makes iterating it really difficult.  We can move some of the code into adapter at the cost of some inefficiency.  Will follow up tomorrow and rebase.

**Comment by trivialfis** [comment]
Thank you for the great work and apologies for the slow response.

**Comment by pseudotensor** [comment]
> It's a shame we can't use any existing data iterator structure to do this. After all the attempted refactoring of xgboost's data import mechanisms and DMatrix it seems to get more and more confusing and we are just adding API functions for each new format.

And the datatable ingest became broken and slow after the refactor.

**Comment by hcho3** [comment]
@pseudotensor Thanks for letting us know. Please file a new GitHub issue so that we can track it. Or is it related to #7642?

**Pull request merged**
