### PR TITLE
Drop Python 3.5; Require Python 3.6+; Replace old-school string formatting with f-strings

### PR DESCRIPTION
**Pull request by Iqrar99**
Based on #5338 , I just replaced some old-school string formatting with f-strings because f-strings are readable, more concise, and less prone to error than other ways of formatting, and also faster.
It's still in progress.

- [x] demo
- [x] jvm-packages
- [x] python-package
- [x] tests

### CODE REVIEW

**Comment by hcho3** [comment]
Note that there’s still discussion ongoing about when to drop Python 3.5. This pull request will have to wait until the discussion concludes.

**Comment by Iqrar99** [comment]
okay, no problem. :)

**Comment by hcho3** [comment]
@Iqrar99 We are moving forward with this PR.

**Comment by hcho3** [comment]
Pylint throws warning for using f-strings in loggers. I removed f-strings from loggers to pass lint check.

**Comment by hcho3** [comment]
I understand that this PR is intrusive, changing a large part of the codebase. I'd like to get approval from 2-3 committers before we merge this PR. An alternative is to merely allow f-strings in the future and keep old string formatting code as is.

**Comment by hcho3** [comment]
I changed my mind now. This PR ended up being quite intrusive, touching all Python files. Whole-sale change like this may introduce unintended breakage.

**Comment by hcho3** [comment]
I opened #5715 to replace this PR.

**Pull request closed without merging**
