### PR TITLE
Revert #5755

### PR DESCRIPTION
**Pull request by hcho3**
Temporarily revert #5755 to prevent OOM error in the [e2e mortgage notebook](https://github.com/rapidsai-community/notebooks-contrib/blob/branch-0.14/intermediate_notebooks/E2E/mortgage/mortgage_e2e.ipynb).

### CODE REVIEW

**Comment by trivialfis** [comment]
I'm still looking into it.  Expect some results today.  Reverting it might break quantile dmatrix completely.

**Comment by hcho3** [comment]
@trivialfis At least it does not break the gtest. Let's see whether the Python tests would pass too.

**Comment by RAMitchell** [comment]
The relevant PR removes the specialised copy for column wise data and instead uses this:
```
// Here the data is already correctly ordered and simply needs to be compacted
// to remove missing data
template <typename AdapterT>
void CopyDataToDMatrix(AdapterT* adapter, common::Span<Entry> data,
                       int device_idx, float missing,
                       common::Span<size_t> row_ptr) {
  auto& batch = adapter->Value();
  auto transform_f = [=] __device__(size_t idx) {
    const auto& e = batch.GetElement(idx);
    return Entry(e.column_idx, e.value);
  };  // NOLINT
  auto counting = thrust::make_counting_iterator(0llu);
  thrust::transform_iterator<decltype(transform_f), decltype(counting), Entry>
      transform_iter(counting, transform_f);
  dh::XGBCachingDeviceAllocator<char> alloc;
  thrust::copy_if(
      thrust::cuda::par(alloc), transform_iter, transform_iter + batch.Size(),
      thrust::device_pointer_cast(data.data()), IsValidFunctor(missing));
}
```

I wonder if the copy_if is responsible for the extra memory allocation.

**Comment by RAMitchell** [comment]
Thrust is using n words to store predicates for the output location of copy_if: https://github.com/thrust/thrust/blob/94e0b1c63fadd5c574c45f05267e45ac136e78ef/thrust/system/detail/generic/copy_if.inl#L64

We can write this more efficiently by redirecting the output of an exclusive scan purely with iterators.

Does someone want to try this? Otherwise I can implement myself.

**Comment by trivialfis** [comment]
Let me give a try.

**Comment by trivialfis** [comment]
I don't think this is necessary anymore.  @hcho3 Thanks for bisecting the code.

**Pull request closed without merging**
