### PR TITLE
Remove duplicated matplotlib installation

### PR DESCRIPTION
**Pull request by Wei-1**
In `Dockerfile.cpu` `matplotlib` was installed twice.
Removing the duplication for cleanness

### CODE REVIEW

**Comment by Wei-1** [comment]
Error log shows that `Client: not connected` while testing `xgboost.dask`
Is this an occasional failure?

**Comment by trivialfis** [comment]
No.  Let me take a look, there is a fix by removing use of test fixture in master branch, I'm not sure if your branch has that commit.

**Comment by Wei-1** [comment]
I can see the latest commit is: Display Sponsor button, link to OpenCollective (#5325)
l will rebase this PR to that.

**Comment by trivialfis** [comment]
That's weird ...  Only this PR is having trouble.  @hcho3 Have you seen similar issue in other build?

**Comment by Wei-1** [comment]
Will the order of the `matplotlib` installation make a difference?
Maybe caused by version dependency or something?

**Comment by Wei-1** [comment]
Close because fixed by #5336

**Pull request closed without merging**
