### PR TITLE
Support column split in gpu hist updater

### PR DESCRIPTION
**Pull request by rongou**

### CODE REVIEW

**Comment by rongou** [comment]
@trivialfis I'm working on enabling column-split with the gpu hist tree method. Only added some tests here, but they seem to hang on some cuda calls. Any idea on how to debug this? Do you see anything obviously wrong?

**Comment by trivialfis** [comment]
@rongou GPU doesn't support multi-target yet.

**Comment by rongou** [comment]
@trivialfis I think this is finally working. Please take a look. Thanks!

**Review by trivialfis — APPROVED** [review]
Looks good to me!

Would you like to produce a document that briefly introduces how everything works with column split in the future?

**Comment by rongou** [comment]
> Would you like to produce a document that briefly introduces how everything works with column split in the future?

Yes probably should create a tutorial.

**Review by trivialfis — APPROVED** [review]

**Comment by trivialfis** [comment]
For some reason, this PR has optimized the GPU hist with the Higgs dataset for about 20 percent of improvement, tested with both RTX8000 and 4070 ti super.

**Comment by trivialfis** [comment]
NVM, git bisect is incorrect.

**Pull request merged**
