### PR TITLE
Small optimization for block hist matrix.

### PR DESCRIPTION
**Pull request by trivialfis**
This is an early WIP.  Please ignore copied and pasted code.  Initial benchmark with HIGGS:

* Platform : Ubuntu 18.10
* CPU : AMD Ryzen 7 2700 Eight-Core Processor

Results:

- Time spent in `GHistIndexBlockMatrix::Init`

| Before | Now |
|----------|-------|
| 7.56465 s | 4.09427 s  (-45.87%) |

- High water marked (peak) memory usage with `GHistIndexBlockMatrix::Init`:

|  | Before | Now |
|--|----------|-------|
| Child high-water RSS                                     |   12138724 KiB | 8359052 KiB (-31.13%) |
| Recursive and acc. high-water RSS+CACHE |   19922500 KiB | 8371424 KiB (-57.98%) |

This is mostly for addressing memory usage issue.  The benchmark is carried out by `tests/benchmark/block_hist_init.cc`.  Hopefully with more effort we can bring back feature grouping, which might be beneficial to GPU Hist too.

One particular thing worth noting is that, I tried injecting OMP into many places, it ends up single thread version is the fastest one.

### CODE REVIEW

**Comment by trivialfis** [comment]
Sadly this is not even close to fixing #2326 .

**Comment by trivialfis** [comment]
@hcho3 The benchmarking code is not necessary, but very useful for  #4503 .  You can decide whether we should keep it here.

**Comment by hcho3** [comment]
@trivialfis I'll review this PR later in detail. I think we should keep the benchmark code. Later, we can expand it as part of a regular performance benchmark.

**Comment by trivialfis** [comment]
@hcho3 Take your time.  This is part of memory optimization for hist and is not the most critical one.

**Pull request closed without merging**
