### PR TITLE
Support different types of filesystems

### PR DESCRIPTION
**Pull request by shaform**
As noted here: http://stackoverflow.com/a/16278054/3455159, we need to change the code a little bit to support different filesystems such as S3FileSystem.

### CODE REVIEW

**Comment by CodingCat** [comment]
@shaform thanks for the PR, have you meet the problem when working with S3 ?

I think in sparkContext.hadoopConfiguration, it shall return the `S3FileSystem` correctly?

**Comment by shaform** [comment]
I tried saving the model to S3 and failed. Since the FileSystem actually depends on the path (one might mix S3 and other paths), sparkContext.hadoopConfiguration is not enough.
Another way is to use `FileSystem.get(uri, context.getConfiguration())` as noted in the same stackoverflow.

**Comment by CodingCat** [comment]
OK, so your source/destination are just two different file systems? 

BTW, would you please update the branch, once the travis says OK, I will merge it

**Comment by CodingCat** [comment]
Thanks, @shaform , merged in

**Comment by shaform** [comment]
Thanks!

**Pull request merged**
