### PR TITLE
[jvm-packages] add Spark and XGBoost tutorial

### PR DESCRIPTION
**Pull request by CodingCat**

### CODE REVIEW

**Comment by CodingCat** [comment]
Hi, @terrytangyuan , I just noticed that something is broken in python-relevant tests, any idea on what happened?

**Comment by terrytangyuan** [comment]
Upstream deps change. We might need to revert this PR as well (I need to double check). https://github.com/dmlc/xgboost/pull/1636
I haven't got a chance to look yet. Been sick recently.

**Comment by CodingCat** [comment]
@terrytangyuan , oh, thanks, 

take care and hope you recover soon

**Comment by CodingCat** [comment]
@tqchen would you mind merging this one?

**Pull request merged**
