### PR TITLE
Use dh::CUDAStream in NCCL communicator

### PR DESCRIPTION
**Pull request by rongou**
@trivialfis

### CODE REVIEW

**Comment by trivialfis** [comment]
No need to rush into it. We merged the NCCL changes. ;-)

I think it will take some time for XGBoost use replace the default CUDA stream and use async streams everywhere.

**Comment by rongou** [comment]
You think the test failures are legit?

**Comment by trivialfis** [comment]
Not sure if it's the CUDA driver warning or the nccl change. The NCCL change seems more likely considering the driver warning was present in previous builds as well

**Comment by trivialfis** [comment]
It's fine to not use that stream for now. I think we will pass the booster context into allreduce in the future. The context contains a CUDA stream (legacy stream for now)

**Comment by rongou** [comment]
Yeah probably need some effort to get everything to use the async stream. Closing this for now.

**Pull request closed without merging**
