### PR TITLE
[CI] Refactor Jenkins CI pipeline + migrate tests to Jenkins

### PR DESCRIPTION
**Pull request by hcho3**
See #4234 for details.

Overview of Jenkins CI pipeline:
Screen Shot 2019-04-16 at 8 17 43 PM

### CODE REVIEW

**Comment by hcho3** [comment]
Will re-open after filling in all blanks

**Comment by hcho3** [comment]
@CodingCat I'm seeing this error with the latest master:
```
19/04/17 12:19:38 ERROR XGBoostSpark: when specifying eval sets as dataframes, you have to ensure that the number of elements in each dataframe is larger than the number of workers
```
https://xgboost-ci.net/blue/organizations/jenkins/hcho3-xgboost-ci-test/detail/refactor_jenkins/71/pipeline/33#step-68-log-2079

How serious is this error? Also, do we want to build a XGBoost JAR with one version of Spark and test it with another version of Spark?

**Comment by hcho3** [comment]
For the time being, I took out all changes related to pylint.

**Comment by CodingCat** [comment]
Oh, I didn’t notice the question here, I think it’s because we have too many cores in jenkins?

How many cores we have there?

**Comment by hcho3** [comment]
@CodingCat 8 cores

**Comment by CodingCat** [comment]
it’s strange...is the issue still there?

**Comment by hcho3** [comment]
@CodingCat For now, I am skipping JVM tests from the Build stage. Trying to export a test JAR so that I can run JVM tests in the Test stage. See https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-4380/18/pipeline/173

**Comment by hcho3** [comment]
@CodingCat What's the meaning of this error?
```
- repartitionForTrainingGroup with group data which has empty partition
Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=172.17.0.2, DMLC_TRACKER_PORT=9091, DMLC_NUM_WORKER=16}
19/04/24 02:52:58 ERROR Executor: Exception in task 10.0 in stage 2.0 (TID 17)
java.util.NoSuchElementException: key not found: train
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at scala.collection.AbstractMap.apply(Map.scala:59)
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$buildDistributedBooster(XGBoost.scala:148)
        ...
9/04/24 02:52:58 ERROR Executor: Exception in task 9.0 in stage 2.0 (TID 16)
java.util.NoSuchElementException: key not found: train
```

**Comment by hcho3** [comment]
Will re-open when things are ready. There's a long way to go

**Comment by hcho3** [comment]
@CodingCat FYI, reducing the number of cores did the trick. Thanks for the suggestion

**Comment by CodingCat** [comment]
@hcho3, yeah, it should work, but 8 cores should not make the failure happen, I met it in a 40-cores machine...

Partitioner of spark may have some secretes that I don’t know...I will check

**Pull request closed without merging**
