### PR TITLE
Redirect to GitHub releases in NEWS.md

### PR DESCRIPTION
**Pull request by terrytangyuan**

### CODE REVIEW

**Review by hcho3 — COMMENTED** [review]
The current practice is that a maintainer writes up a release note draft in `NEWS.md` and others review the pull request. How should the review occur if `NEWS.md` is deprecated?

**Comment by terrytangyuan** [comment]
Okay I didn't realize that we relied  on this for reviewing releases. It looks like we didn't update this file for the past couple of releases. 

Regarding the release review process, perhaps we can do release discussion (with community) and voting (among committers/PMCs) on a GitHub issue or email similar to other Apache projects?

**Comment by hcho3** [comment]
> It looks like we didn't update this file for the past couple of releases.

We only updated it for major releases. The patch releases didn't make it there.

> Regarding the release review process, perhaps we can do release discussion (with community) and voting (among committers/PMCs) on a GitHub issue or email similar to other Apache projects?

We already offer 2-week period for users to try out the release candidate, e.g. https://github.com/dmlc/xgboost/issues/6793. (This issue is pinned in the Issues page.)

We use `NEWS.md` for reviewing the content of the release note, not the release itself. That's done in the RC issue instead.

**Comment by terrytangyuan** [comment]
Sounds good. We should probably document the release process somewhere. I'll close this PR for now as it's no longer needed.

**Pull request closed without merging**
