### PR TITLE
Scikit-Learn Wrapper For XGBoost

### PR DESCRIPTION
**Pull request by nerdcha**
# To Do
 - [x] Basic SKL wrapper
 - [ ] Add support for categorical variables
 - [ ] Test it out on a bunch of different ML scenarios

### CODE REVIEW

**Comment by tqchen** [comment]
great PR! Thanks for making this. two comments:

* Seems the new README.md was deleted and replaced by old one in otto demo, start from a clean fork might resolve that problem
* It would be great to optionally depends on sklearn. if user do not have it, the library can still run smoothed if not using the sklearn related module, i think we can do it like

```python
try:
    from sklearn.base import BaseEstimator
    SKLEARN_INSTALLED = True
except ImportError:
    SKLEARN_INSTALLED = False

XGBModelBase = object
if SKLEARN_INSTALLED:
    XGBModelBase = BaseEstimator

class XGBModel(XGBModelBase):
    def __init__(self):  
        if not SKLEARN_INSTALLED:
            raise Exception('sklearn needs to be installed in order to use this module')

test = XGBModel()
```

**Comment by nerdcha** [comment]
Optionally loading sklearn is a great idea, thanks!
Sorry about the otto readme; I think it changed from "README" to "readme" recently, which confused git. I'll fix it.

**Comment by tqchen** [comment]
Thanks. I am closing this PR since I guess it might be easier to start form a clean fork.
I am looking forward to the new PR

**Comment by tqchen** [comment]
@nerdcha how was the status of the updates? It would really be great if have these changes into xgb soon

**Comment by nerdcha** [comment]
Haven't finished it yet, sorry, but should be in the next week or so.

**Comment by tqchen** [comment]
great! looking forward to it

**Pull request closed without merging**
