### PR TITLE
Fix python setup: avoid import numpy in setup.py

### PR DESCRIPTION
**Pull request by irachex**
Currently `pip install xgboost` will raise traceback like this

```
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "/tmp/pip-build-IAdqYE/xgboost/setup.py", line 20, in <module>
    import xgboost
  File "./xgboost/__init__.py", line 8, in <module>
    from .core import DMatrix, Booster
  File "./xgboost/core.py", line 12, in <module>
    import numpy as np
ImportError: No module named numpy
```

We should avoid importing numpy in setup.py and let pip install numpy and scipy automatically.
That's what `install_requires` for.

### CODE REVIEW

**Comment by tqchen** [comment]
@phunterlau  who is in charge of the pip package

**Comment by tqchen** [comment]
@irachex Can you open another PR to put your name to the list of congributors? Thanks!

**Comment by phunterlau** [comment]
it is because core.py needs numpy and setup.py calls core.py before installing numpy. I will update the pip installation. Thanks.

**Comment by tqchen** [comment]
Thanks @benhamner  for pointing this out. Will push  a fix to this problem

**Pull request merged**
