### PR TITLE
[jvm-packages]fix XGBoost-on-Spark SparseVector missing value problem

### PR DESCRIPTION
**Pull request by adobay**
treat SparseVector as DenseVector

### CODE REVIEW

**Comment by adobay** [comment]
the problem
https://github.com/dmlc/xgboost/pull/4315
https://github.com/dmlc/xgboost/issues/3742
https://github.com/dmlc/xgboost/issues/3634
https://github.com/dmlc/xgboost/issues/4227

**Comment by CodingCat** [comment]
treating everything as dense vector brings significant amount of waste on the memory space, and the problem has been fixed in https://github.com/dmlc/xgboost/pull/4349 , are you still observing something out of order?

**Comment by hcho3** [comment]
@CodingCat I'll defer to you on whether this pull request should make it to 0.90 release. However, I'm concerned that this PR increases memory consumption significantly and caused some tests to fail.

**Comment by shishaochen** [comment]
Memory issue is extemely important in distributed training on large datasets.
In my cases, thousands of slots are 
defined while only small set of them are used per training job. To not change feature index, sparse 
vectors are needed or a must.

**Comment by CodingCat** [comment]
I will close this PR soon as the problem has been fixed by other PRs,

**Pull request closed without merging**
