### PR TITLE
[jvm-packages] Fix early stopping bug

### PR DESCRIPTION
**Pull request by sammynammari**
Addresses https://github.com/dmlc/xgboost/issues/6657

### CODE REVIEW

**Comment by sammynammari** [comment]
so the only failing check is a Python/C++ code linter...which shouldn't be applicable here, yes? Is there any additional action that needs to be taken?

**Comment by trivialfis** [comment]
The linter can be ignored  I will fix it.

@CodingCat Please help to review the PR.

**Comment by trivialfis** [comment]
@wbo4958 Could you please help taking a look?

**Comment by wbo4958** [comment]
LGTM

**Review by wbo4958 — APPROVED** [review]

**Comment by CodingCat** [comment]
could we change the checking instead? setting default would make it consistent with other params

**Comment by wbo4958** [comment]
@sammynammari , I didn't see your response, so I made another PR for this issue https://github.com/dmlc/xgboost/pull/6738.

**Comment by CodingCat** [comment]
closing this in favor of #6738.

**Pull request closed without merging**
