### PR TITLE
[placeholder] r test failure debugging

### PR DESCRIPTION
**Pull request by chenqin**
After upgrade dmlc-core and rabit to latest version, we observed r_test failed due to early stop metrics issue.

cc
@CodingCat @hcho3

### CODE REVIEW

**Comment by CodingCat** [comment]
where is the failure?

**Comment by chenqin** [comment]
https://travis-ci.org/chenqin/xgboost/jobs/525125837

**Comment by CodingCat** [comment]
is this test even related to rabit?

**Comment by CodingCat** [comment]
too many times some test just failed in the next day without changes, we can move attentions to the new CI which is supposed to be more stable now

**Comment by chenqin** [comment]
> is this test even related to rabit?

To my best knowledge, not at all. That's what I am trying to figure out.
I saw most of travis task moved to jenkins, so this may no longer relevant. so F.Y.I.

**Comment by hcho3** [comment]
@chenqin BTW, let me know if you'd like to use our Jenkins server for Rabit integration testing.

**Pull request closed without merging**
