### PR TITLE
Fix data loading

### PR DESCRIPTION
**Pull request by trivialfis**
* Fix config regex.
* Try to explain the error better in exception. (not really useful since dmlc csv parser can parse libsvm file without generating any error.)
* Update doc.

### CODE REVIEW

**Comment by trivialfis** [comment]
Somehow the libsvm parser can parse a csv without generating any error ...

**Comment by trivialfis** [comment]
@hcho3 Do you know the use case of optional value field in libsvm?  In the following code, it's possible for a libsvm `<feature>:<value>` pair to have only feature but no value. https://github.com/dmlc/dmlc-core/blob/808f485387f9a03f78fa9f1159f387d0d91b7a28/src/data/libsvm_parser.h#L146

Could you think of a case I might break compatibility if I enforce having a complete pair?

> Thanks for correcting my mistake :)

Just don't get mad when I create new ones ..

**Comment by thvasilo** [comment]
@trivialfis AFAIK there's no formal format for libsvm files, however there is a program that checks for dataset validity [checkdata.py](https://github.com/cjlin1/libsvm/blob/master/tools/checkdata.py).

I tried a simple dataset with that

```
1 2:1 3:4
1 3
1 4:
```

where the second line does not a value, and the third has the colon but no value, and both were marked as errors.
So for "pure" libsvm files this would be wrong. 

But taking a look at the [blame](https://github.com/dmlc/dmlc-core/blame/808f485387f9a03f78fa9f1159f387d0d91b7a28/src/data/libsvm_parser.h#L146) these were added explicitly, [one](https://github.com/dmlc/dmlc-core/commit/e8824983113e809546cebdcb844db1e8db4cafb9) to support the [ranklib format](https://sourceforge.net/p/lemur/wiki/RankLib%20File%20Format/) and one to add the [weight support](https://github.com/dmlc/dmlc-core/commit/fbf75b7f410b389df20573e6bef205d1b69fed75).

So i'd be hesitant to remove until we are sure why they were added in the first place.

**Comment by trivialfis** [comment]
@thvasilo Thanks for the reply.  From the links you provided, neither ranklib nor [having weights](https://xgboost.readthedocs.io/en/latest/tutorials/input_format.html#instance-weights) would allow missing value with an non-missing index.  I would like to take the risk ...

**Comment by trivialfis** [comment]
Leave a note for the extended libsvm format here:
```
<line> -> <label> <QID> <feature>: <value> ... <feature>: <value> <Comment>
<label> -> <positive integer>: <float> | <positive integer>
<QID> -> qid: <positive integer> | e
<Comment> -> # <String> | e
```

**Comment by trivialfis** [comment]
@hcho3 I can't iterate enough time to rewrite the parser right now.  Can I just fix this config path issue then open an issue for better documentation around our uri format?

**Comment by hcho3** [comment]
@trivialfis Yes, let’s reduce the scope of this PR, to fixing path parsing in config files. Let’s return to data parsing later.

**Comment by trivialfis** [comment]
@hcho3 Would you like to take another if the tests pass?

**Comment by sriramch** [comment]
@trivialfis - this commit broke the build in my environment. more specifically, the assertion on ofstream added in dmatrix uri test. i have gtest 1.7 environment, which does not have this - https://github.com/google/googletest/blob/master/googletest/include/gtest/gtest.h#L293

is there a minimal gtest-dev requirement? if so, we either need to enforce this, or revert the assertion on ofstream explicitly and check explicitly if good bits are set on the stream.

**Comment by hcho3** [comment]
@sriramch We require gtest 1.8.1 and higher. See https://github.com/dmlc/dmlc-core/pull/542

**Comment by sriramch** [comment]
@hcho3 thanks for the clarification and the doc. pr.

**Pull request merged**
