### PR TITLE
[PySpark] change the returning model type to string from binary

### PR DESCRIPTION
**Pull request by wbo4958**
[RAPIDS Accelerator](https://nvidia.github.io/spark-rapids/) is a Spark plugin that leverages the GPUs to accelerate the spark SQL and dataframe API.  But not all types can be supported by RAPIDS Accelerator. For example, It has not supported the `BINARY type` when doing mapInPandas.

``` console
22/07/17 09:06:41 WARN GpuOverrides: 
!Exec <MapInPandasExec> cannot run even partially on the GPU because unsupported data types in output: BinaryType [booster_bytes#31]; not all expressions can be replaced
  !Expression <AttributeReference> booster_bytes#31 cannot run on GPU because expression AttributeReference booster_bytes#31 produces an unsupported type BinaryType
  !Expression <PythonUDF> _train_booster(values#15, label#14) blocks running on GPU because expression PythonUDF _train_booster(values#15, label#14) produces an unsupported type StructType(StructField(booster_bytes,BinaryType,true))
    @Expression <AttributeReference> values#15 could run on GPU
    @Expression <AttributeReference> label#14 could run on GPU
  *Exec <ShuffleExchangeExec> will run on GPU
    *Partitioning <SinglePartition$> will run on GPU
    *Exec <ProjectExec> will run on GPU
      *Expression <Alias> cast(array(sepal_length#0, sepal_width#1, petal_length#2, petal_width#3) as array<float>) AS values#15 will run on GPU
        *Expression <Cast> cast(array(sepal_length#0, sepal_width#1, petal_length#2, petal_width#3) as array<float>) will run on GPU
          *Expression <CreateArray> array(sepal_length#0, sepal_width#1, petal_length#2, petal_width#3) will run on GPU
      *Expression <Alias> cast(class#4 as float) AS label#14 will run on GPU
        *Expression <Cast> cast(class#4 as float) will run on GPU
      *Exec <FileSourceScanExec> will run on GPU
```

So this PR changes returning model from "bytes" to "string", which can make RAPIDS Accelerator speed up XGBoost PySpark seamlessly. And there is no side effect for the XGBoost PySpark itself.

``` console
*Exec <MapInPandasExec> will partially run on GPU
  *Expression <PythonUDF> _train_booster(values#15, label#14) will not block GPU acceleration
  *Exec <ShuffleExchangeExec> will run on GPU
    *Partitioning <SinglePartition$> will run on GPU
    *Exec <ProjectExec> will run on GPU
      *Expression <Alias> cast(array(sepal_length#0, sepal_width#1, petal_length#2, petal_width#3) as array<float>) AS values#15 will run on GPU
        *Expression <Cast> cast(array(sepal_length#0, sepal_width#1, petal_length#2, petal_width#3) as array<float>) will run on GPU
          *Expression <CreateArray> array(sepal_length#0, sepal_width#1, petal_length#2, petal_width#3) will run on GPU
      *Expression <Alias> cast(class#4 as float) AS label#14 will run on GPU
        *Expression <Cast> cast(class#4 as float) will run on GPU
      *Exec <FileSourceScanExec> will run on GPU
```

I have a rough performance test, XGBoost PySpark can have ~35% improvement when using RAPIDS Accelerator.

### CODE REVIEW

**Comment by wbo4958** [comment]
@trivialfis, Looks like `booster.save_raw("json").decode("utf-8")` didn't save the configuration?

**Comment by trivialfis** [comment]
No, it doesn't save the configuration. Is it required? Because the configuration is not stable across versions.

**Comment by wbo4958** [comment]
> No, it doesn't save the configuration. Is it required? Because the configuration is not stable across versions.

I just find another way to handle the configurations.

**Comment by wbo4958** [comment]
@WeichenXu123 @trivialfis Could you help to review this PR?

**Review by trivialfis — APPROVED** [review]

**Pull request merged**
