### PR TITLE
Perform clang-tidy on both cpp and cuda source.

### PR DESCRIPTION
**Pull request by trivialfis**
* Add `GENERATE_COMPILATION_DATABASE' to CMake.
* Rearrange CMakeLists.txt.
* Add basic Python clang-tidy script.

Proposed in #4032 .

@hcho3 Could you please help automating this on Jenkins after sorting out other priorities?  I added a simple documentation and a Python script for the new linting,  but I don't know what's happening with Jenkins or Docker.  Thanks! :)

# Dependencies:
- clang-tidy >= 7
- cmake >= 3.8

### CODE REVIEW

**Comment by trivialfis** [comment]
I removed `modernize-use-auto` from clang-tidy.  The "use auto everywhere" is based on the assumption that we have a perfect IDE which can display correct hints about variable type.  Such an assumption doesn't hold on CUDA programming. :)  If others can argue the merit can overweight the pitfall then I will add it back.

**Comment by trivialfis** [comment]
Actually this might be doable just on Jenkins.  Let me take a closer look. :)

**Comment by hcho3** [comment]
@trivialfis In the longer term, I'd like to migrate some CPU tests to Jenkins, to allow for greater customization (such as higher memory limit).

**Comment by trivialfis** [comment]
@hcho3 Actually somehow I oddly like the memory limitation.  Those error keeps reminding me that I need to optimize it since all tests use relatively small datasets.

**Comment by hcho3** [comment]
@trivialfis We still need to deal with intermittently failing Travis tests though.

**Comment by trivialfis** [comment]
@hcho3 Nope.  At the very least cuda headers are required.  So it seems Jenkins is the right way to go.  Could you please help drafting the Jenkins script after sorting out other priorities?

**Comment by trivialfis** [comment]
@hcho3 I have a branch for completely rewritten cmake: https://github.com/trivialfis/xgboost/tree/cmake

Got some difficulties making a PR, including:

https://github.com/dmlc/dmlc-core/pull/495
https://github.com/dmlc/rabit/pull/77

and after refining linking NCCL all reduce hangs...

**Comment by hcho3** [comment]
@trivialfis Can you post a RFC in the issue track to explain the rationale for upgrading the CMake? I think many people will appreciate the benefits of Modern CMake. In the meanwhile, I'll be looking into clang-tidy, to unblock #4086.

**Comment by trivialfis** [comment]
I can try to finish the first one.  For second one (rabit) I might need some help for setting testing farm on Windows.
For the third, using group calls from NCCL instead of multi-threads can resolve the problem but with slight performance cost.  I believe the bug came from NCCL instead of XGBoost.

> explain the rationale for upgrading the CMake

I **didn't** upgrade CMake, it's still on 3.2 for building XGBoost.  You only need higher version of CMake (3.5) for using GPU and (3.8) for linting.

**Comment by hcho3** [comment]
> I didn't upgrade CMake, it's still on 3.2 for building XGBoost.

I meant to say upgrading the style of the CMake script. Sorry for the confusion.

**Comment by hcho3** [comment]
@trivialfis It doesn't have to be long. If your primary motivation is to follow Modern CMake conventions, then you can just cite some tutorials. Do you have other things you wanted to achieve with your re-organization, other than Modern CMake compliance?

**Comment by trivialfis** [comment]
> other than Modern CMake compliance

One. Make the C APIs usable.

**Comment by trivialfis** [comment]
Well.  Forgotten.  Obsolete the makefiles.

**Comment by hcho3** [comment]
@trivialfis Got it. Let's just create an issue titled "Roadmap: re-organize CMake build." (We won't call it RFC.) You can list the reasons for reorganizing the CMake build. For the first reason (Modern CMake), just cite a few links; for the other two (C API, Makefile deprecation), you should give a brief explanation. How does it sound?

**Comment by trivialfis** [comment]
@hcho3  Cool,  I will make that issue within these two days. :)

**Comment by hcho3** [comment]
@trivialfis Yeah, thanks for the effort. Modern CMake seems really be a thing. I'd take it just for target-based logic.

**Comment by trivialfis** [comment]
@hcho3  Well, it comes with its cost.  After CMake 3.8 CUDA is a formally supported language so these "modern cmake" can be applied to CUDA too.  But many linux distributions doesn't have CMake 3.8 while the currently applied CUDA wrapper is nothing modern.  So for compatibility I got a "half modern" build system.  It gave me a lots of headaches.

**Comment by hcho3** [comment]
Okay, I managed to run the full clang-tidy for both C++ and CUDA sources. I've made a few minor changes to get the clang-tidy work on Jenkins. I'll upload the change soon.

**Comment by hcho3** [comment]
Will upgrade the worker images in Jenkins soon, since we need CMake 3.8.

**Comment by hcho3** [comment]
Clang-tidy will be added as one of the parallel test jobs.

screen shot 2019-01-29 at 10 40 26 pm

**Comment by trivialfis** [comment]
@hcho3 We might want to let it fail for a while.  I will make a huge PR that reformats current code base.

**Comment by hcho3** [comment]
@trivialfis Sorry for the noise. I finally got clang-tidy working on Jenkins: https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/PR-4034/12/pipeline/55

**Comment by trivialfis** [comment]
@hcho3 Can you check out what's the error from clang-tidy?  I generated the log in previous proposal linked above, there are only warnings but no errors.  If the errors came from dmlc-core logging then I know how to resolve it.  Otherwise I need to investigate it a bit more.

**Comment by hcho3** [comment]
I’ll poke around to see how to get the log for the clang-tidy on Jenkins. For now, I’ll fix #4086 by removing clang-tidy there.

**Comment by trivialfis** [comment]
Thanks

**Comment by trivialfis** [comment]
@hcho3 Sorry but can we postpone the CMake refactoring?  I think there are many other priorities currently.

**Comment by hcho3** [comment]
@trivialfis Clang-tidy error messages now should be visible. Let us merge this after tests pass.

**Comment by trivialfis** [comment]
@hcho3 Could you lower down the CUDA version used for clang-tidy to CUDA-9?  10 is not supported by clang-tidy-7

**Comment by hcho3** [comment]
@trivialfis Done. I created a Docker container with CUDA 9.2 and Clang-Tidy 7. Let me know if this is satisfactory.

**Comment by trivialfis** [comment]
@hcho3 Thanks for lots of hard work.  This is really helpful.  I will try to correct the remaining errors in later PRs.

**Comment by hcho3** [comment]
@trivialfis I'll go ahead and review #3825 within a day or two, so that you don't get blocked for later re-factoring. Thanks for your effort towards a consistent coding style for GPU code.

**Pull request merged**
