### PR TITLE
add support for tweedie regression

### PR DESCRIPTION
**Pull request by tonydifranco**
in reference to #1392 and #681

### CODE REVIEW

**Comment by yangs16** [comment]
@tonydifranco  I think you should rebase your work branch against the master branch, instead of merge the master into your work branch. Besides, it would be nice if you could provide an example on some toy dataset.

**Comment by tonydifranco** [comment]
@yangs16 thanks... I will rebase and add an example.  Will try to get to it by the end of the week.

**Comment by tonydifranco** [comment]
@yangs16 or @tqchen can you either merge this PR or provide feedback so that I can make the necessary changes or close it if you don't think it should be added?  I have been using this tweedie objective in practice on large data sets for the past few weeks and can validate it's performance against tweedie glm's and the other implementation of tweedie gbm.  Thanks!

**Comment by tonydifranco** [comment]
closing and re-submitting after rebase

**Pull request closed without merging**
