### PR TITLE
[breaking] Bump Python requirement to 3.10.

### PR DESCRIPTION
**Pull request by trivialfis**
- Bump the Python requirement.
- Fix type hints.
- Use loky to avoid deadlock.
- Workaround cupy-numpy compatibility issue on Windows caused by the `safe` casting rule.
- Simplify the repartitioning logic to avoid dask errors.

Close https://github.com/dmlc/xgboost/issues/10371

### CODE REVIEW

**Review by hcho3 — APPROVED** [review]

**Comment by trivialfis** [comment]
all modin tests are broken due to updated numpy.

**Comment by trivialfis** [comment]
cupy is running into error as well.

**Comment by trivialfis** [comment]
dask-expr appears to be running into trouble with the latest pandas.

**Comment by trivialfis** [comment]
- Moved the make sparse function into `data.py` to fix pylint error, also the definition is more consistent.
- Removed the deterministic partitioning function in dask test due to dask internal error. This might make the test flaky, we will see.

**Comment by trivialfis** [comment]
Err, immediately fail after removing the partitioning function.

**Comment by trivialfis** [comment]
Couldn't reproduce the hang, will try it on aws later.

**Comment by trivialfis** [comment]
@hcho3 Could you please help take another look?

**Review by hcho3 — APPROVED** [review]

**Pull request merged**
