### PR TITLE
Add GPU accelerated tree construction plugin

### PR DESCRIPTION
**Pull request by RAMitchell**
First version of GPU accelerated tree construction.

Tested to work on both linux and windows via Cmake build.

Results in around 4x speed increase with GTX970 vs 4 core i5 on large higgs dataset.

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks Seems this PR contains thirdparty library https://github.com/NVlabs/cub. Please consider modify build script such that the thirdparty library is put under thirdparty cub, checked and automatically downloaded if not exist, instead of putting that in the plugin folder.

**Comment by tqchen** [comment]
Please do a squash after removing the cub related files, and I will do a code review.

**Comment by BlindApe** [comment]
Nice news, @RAMitchell.

Is the restriction to depth 6 a problem with GPU RAM or with the data structure you used? 
Could this limit to be greater in a future? In real problem 10 - 15 is a range that frequently is optimal.

But this first step is very important. Thank again.

**Comment by tqchen** [comment]
@RAMitchell Any updates?

**Comment by RAMitchell** [comment]
@tqchen Sorry for the slow response, have been away from my computer. I have changed it to rely on a version of CUB distributed with the CUDA toolkit.

@BlindApe Thanks for your comments. The restriction is with the algorithm itself. 

I have tried two different types of algorithms, the one shown here which is optimised for trees of depth 4-7 but slows down exponentially at higher depths and another which performs evenly across all depths but is up to twice as slow for small trees.

My understanding was that a depth of 4-8 is the most common in tree boosting, with little to no gains being expected at higher depths. As such I have chosen the algorithm optimised for smaller trees.  

I welcome feedback on users experience with tree depth and whether these assumptions are wrong.

**Comment by tqchen** [comment]
Please fix the code style a bit, to match the Google C style that is used by most of the project.

**Comment by BlindApe** [comment]
@RAMitchell for old gbm R package (gradient boosting with only first order derivatives) 4-8 was the range more frequently has the optimum, but with xgboost, as I said, this range moves to 10-15. Perhapas the several regularization parameters xgboost has is the explain of this different behavior.
If I would need to do a blind bet for a unknown dataset with xgboost I try depth in (10, 12, 8, 15) sequence. But I found a few datasets where (4-7) outperforms higher values. 
Precisely in my company, we are researching in predict optimal parameters based only in meta features of dataset as a way to reduce parameter tuning step.
Would be nice to hear other opinions about depth parameters.

**Comment by gugatr0n1c** [comment]
Hi, just my experience on depth of trees.. I am using from 7 to 11, usually 9 is optimum choice.. and accuracy difference from 6 is significant...

**Comment by RAMitchell** [comment]
I will take a few days to integrate my other code to remove the tree depth restriction, as well as making code style changes and then will reopen the pull request.

**Pull request closed without merging**
