### PR TITLE
Fixed a few typos in README

### PR DESCRIPTION
**Pull request by wgstanton**

### CODE REVIEW

**Comment by pommedeterresautee** [comment]
You split one checkout in two words and you kept other checkout in one word. 

Is there a reason?

 (My English is really bad, just wondering ).

**Comment by wgstanton** [comment]
We can also change "checkout" to two words in the other location. Not a big issue, but that was my mistake.

**Comment by pommedeterresautee** [comment]
Up to you if it is consistent in the whole file :-)

**Comment by pommedeterresautee** [comment]
Or just merge the two words. It s not a big deal I think. Checkout makes me think to Git.

**Comment by wgstanton** [comment]
Yeah, I just made it consistent, because it is a little confusing. I think of "checkout" as in a "git checkout" and "check out" as in "You should check this cool new thing out" (ie. not necessarily just Git related).

**Comment by pommedeterresautee** [comment]
Thanks for the contribution @wgstanton  !

**Pull request merged**
