### PR TITLE
Fix dask predict

### PR DESCRIPTION
**Pull request by trivialfis**
Close https://github.com/dmlc/xgboost/issues/6407 .

### CODE REVIEW

**Comment by hcho3** [comment]
Do you have some performance numbers?

**Comment by trivialfis** [comment]
Yes.  But please let me finish testing on GKE first.  It's a bit cumbersome.

**Comment by trivialfis** [comment]
Simple test, using HIGGS:

```
Train::Duration 5.479685544967651
0.5290751
Predict::Duration 0.9758050441741943
```
``` python
def dmain():
    with LocalCUDACluster() as cluster:
        print('Dashboard link:', cluster.dashboard_link)
        with Client(cluster) as client:
            dask_df = dask_cudf.read_csv(fname, header=None, names=colnames)
            y = dask_df['label']
            X = dask_df[dask_df.columns.difference(['label'])]
            dtrain = dxgb.DaskDMatrix(client, X, y)
            start = time()
            output = dxgb.train(client, {'tree_method': 'gpu_hist'}, dtrain,
                                num_boost_round=10)
            end = time()
            print('Train::Duration', end - start)

            start = time()
            predictions = dxgb.predict(client, output, dtrain)
            predictions = client.persist(predictions)
            wait(predictions)
            predictions.mean().compute()
            end = time()

            print('Predict::Duration', end - start)
            return output['booster'], predictions


if __name__ == '__main__':
    dmain()
```

**Comment by hcho3** [comment]
@trivialfis Can you post the perf number before and after this patch? I want to know if this patch improves performance.

**Comment by trivialfis** [comment]
Before:

```
Train::Duration 5.479079008102417
Predict::Duration 1.6077783107757568
```

The diff should be more significant on platforms with more workers.  Right now I'm just using 2 GPUs.

**Comment by trivialfis** [comment]
Could you please review?

**Review by RAMitchell — APPROVED** [review]

**Pull request merged**
