### PR TITLE
Fix for CRAN Submission

### PR DESCRIPTION
**Pull request by hetong007**
This PR has some fix for the CRAN submission. The current version has an error from the `R CMD check` result on [win-builder](https://win-builder.r-project.org/):

```
* using log directory 'd:/RCompile/CRANguest/R-release/xgboost.Rcheck'
* using R version 3.3.2 (2016-10-31)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* checking for file 'xgboost/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'xgboost' version '0.6-0'
* checking CRAN incoming feasibility ... NOTE
Maintainer: 'Tong He <hetong007@gmail.com>'

Found the following (possibly) invalid URLs:
  URL: https://www.kaggle.com/wiki/MultiClassLogLoss
    From: man/xgb.train.Rd
    Status: 404
    Message: Not Found
* checking package namespace information ... OK

.......

* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
** running tests for arch 'i386' ... ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  [96]	train-rmse:0.998892 
  [97]	train-rmse:0.998892 
  [98]	train-rmse:0.998892 
  [99]	train-rmse:0.998892 
  [100]	train-rmse:0.998892 
  testthat results ================================================================
  OK: 325 SKIPPED: 1 FAILED: 3
  1. Failure: training continuation works (@test_basic.R#151) 
  2. Failure: training continuation works (@test_basic.R#157) 
  3. Failure: training continuation works (@test_basic.R#162) 
  
  Error: testthat unit tests failed
  Execution halted
** running tests for arch 'x64' ... [29s] OK
  Running 'testthat.R' [28s]
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking re-building of vignette outputs ... [24s] OK
* checking PDF version of manual ... OK
* DONE
Status: 1 ERROR, 1 NOTE
```

1. The most important issue is the error from the test_basic.R, on a 32-bit machine. All the failures are related to a call `expect_equal(bst$raw, bst2$raw)`. However I don't have a 32-bit machine by hand for now. If someone could help with the test, please let me know the details.
2. I can visit the reported URL (https://www.kaggle.com/wiki/MultiClassLogLoss) from my web browser. Would be great if someone knows what is happening.

### CODE REVIEW

**Comment by khotilov** [comment]
I will try to reanimate my old WinXP laptop tomorrow... But somehow I was assuming that 32 bit platforms were not actually supported by xgboost - were they?

And I don't see anything wrong with that url either.

**Comment by hetong007** [comment]
I think the check for different archs always exists on CRAN. We might tweak the code a bit to fulfill CRAN's requirement, if necessary.

To reproduce the bug on a 64bit machine, can we somehow flag something in Makevars/Makevars.win, so that it simulate the 32bit environment? I am not sure how to do it. Besides, the environment for this check result is on Windows.

**Comment by tqchen** [comment]
windows machine allows compilation in 32 bit when specified. XGBoost is supposed to be compatible in 32 mode. In case we need to run prediction on mobiles

**Comment by thirdwing** [comment]
I think I have met `expect_equal` problem on 32-bit machine before.

Not a big problem.

**Comment by yixuan** [comment]
This seems to be related to the 32-bit compiler. I tried to compile `xgboost` using different optimization flags. No error occurred if the `-O0` flag was used, but the check failed if `-O1`, `-O2` etc. were used.

**Comment by hetong007** [comment]
I compiled and tested with the 32bit R.exe on Windows, and compared with the `bst$raw` and `bst2$raw` generated by 64bit R.exe. Here are the results:

```
> # The mismatch from 32bit
> expect_equal(bst$raw,bst2$raw)
Error: bst$raw not equal to bst2$raw.
1 element mismatch

> # The normal result from 64bit
> expect_equal(bst3$raw,bst4$raw)

> # Comparing result from 64bit to 32bit
> expect_equal(bst3$raw,bst$raw)
Error: bst3$raw not equal to bst$raw.
72 element mismatches

> # Comparing result from 64bit to 32bit
> expect_equal(bst3$raw,bst2$raw)
Error: bst3$raw not equal to bst2$raw.
72 element mismatches
```
Note: 
1. `bst$raw` and `bst2$raw` are generated from 32bit.
2. `bst3$raw` and `bst3$raw` are generated from 64bit.

Does anyone have any insight on this issue? I have no clue on the difference between the archs.

**Comment by tqchen** [comment]
Could have something to do with filling of the padded elements in aligned structure, can you post a code? Which won't hurt loading but makes raw bits different.

**Comment by tqchen** [comment]
It might be helpful to dump the model in text format, to see if it is problem of model format, or problem of tree construction difference, under 32 bit

**Comment by khotilov** [comment]
I took a quick look at this test in 32 bits win too. I was also changing
the eta, depth and nrounds. A strange thing is that raw models were
identical for some configurations, but for some they were different, and
the number of different bytes usually grows with depth and nrounds in
continuation. The results didn't seem to depend on the seed value.

I also did some comparison of tree dumps (setting 17 digits stringstream
precision) for a few cases of not-same-raw models: sometimes the dumps were
identical (which means that something that not in the dump was different),
and when the differences were visible, those were tiny changes in either
gain or cover values.

**Comment by hetong007** [comment]
I have dumped the models. From the text format, the 32 bit and 64 bit have slight difference in the splitting value:  `-9.53674e-007` against `-1e-006`. I believe this is what causes the 72 mismatches in the above result. 

However, within each arch, the text files are exactly the same. I have attached the raw models (two R objects) generated by the i386 R.exe from the following code:
```r
require(xgboost)
require(testthat)

data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')
train <- agaricus.train
test <- agaricus.test
set.seed(1994)

dtrain <- xgb.DMatrix(train$data, label = train$label)
watchlist = list(train=dtrain)
param <- list(objective = "binary:logistic", max_depth = 2, eta = 1, nthread = 2)

# for the reference, use 4 iterations at once:
set.seed(11)
bst <- xgb.train(param, dtrain, nrounds = 4, watchlist)
# first two iterations:
set.seed(11)
bst1 <- xgb.train(param, dtrain, nrounds = 2, watchlist)
# continue for two more:
bst2 <- xgb.train(param, dtrain, nrounds = 2, watchlist, xgb_model = bst1)
expect_equal(bst$raw, bst2$raw)
```

With i386 R.exe + latest xgboost version, the last line `expect_equal` is likely to trigger an error:
```
Error: bst$raw not equal to bst2$raw.
1 element mismatch
```
The difference lies at the 1718-th position. `ce` against `bd`. Since there's no difference in the model file, I am not sure if it is caused by floating error as well.

[raw.zip](https://github.com/dmlc/xgboost/files/623948/raw.zip)

**Comment by tqchen** [comment]
I will merge these changes for now, we can have another PR to fix the raw test issue

**Pull request merged**
